#include <algorithm>
#include <atomic>
#include <execution>
#include <ranges>
#include <memory>
#include "CUDACore/cudaCheck.h"

#include "gpuClusterTracksByDensity.h"
#include "gpuClusterTracksDBSCAN.h"
#include "gpuClusterTracksIterative.h"
#include "gpuFitVertices.h"
#include "gpuSortByPt2.h"
#include "gpuSplitVertices.h"

namespace gpuVertexFinder {

/**
 * Brief description of the function that loads tracks into a SoA structure.
 *
 * Loads tracks from a pointer to TkSoA object into a ZVertexSoA object,
 * utilizing a WorkSpace object and applying filters such as minimum pt.
 *
 * @param ptracks Pointer to TkSoA object containing track data.
 * @param soa Pointer to ZVertexSoA object where loaded tracks will be stored.
 * @param pws Pointer to WorkSpace object used during loading process.
 * @param ptMin Minimum pt value for filtering tracks.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  void loadTracks(TkSoA const* ptracks, ZVertexSoA* soa, WorkSpace* pws, float ptMin) {
    assert(ptracks);
    assert(soa);

    auto iter{std::views::iota(0, TkSoA::stride())};
    std::for_each(std::execution::par, std::ranges::cbegin(iter), std::ranges::cend(iter), [=](const auto idx) {
      auto const& tracks = *ptracks;
      auto const& fit = tracks.stateAtBS;
      auto const* quality = tracks.qualityData();
      auto nHits = tracks.nHits(idx);
      if (nHits == 0)
        return;  // this is a guard: maybe we need to move to nTracks...

      // initialize soa...
      soa->idv[idx] = -1;

      if (nHits < 4)
        return;  // no triplets
      if (quality[idx] != trackQuality::loose)
        return;

      auto pt = tracks.pt(idx);

      if (pt < ptMin)
        return;

      auto& data = *pws;
      std::atomic_ref<uint32_t> inc{data.ntrks};
      auto it = inc++;
      data.itrk[it] = idx;
      data.zt[it] = tracks.zip(idx);
      data.ezt2[it] = fit.covariance(idx)(14);
      data.ptt2[it] = pt * pt;
    });
  }

/**
 * Produces vertices asynchronously from track information stored in a StructureOfArrays object.
 *
 * @param tksoa pointer to the input tracks in a StructureOfArrays format
 * @param ptMin minimum transverse momentum required for vertex production
 * @return unique pointer to the produced vertices in a StructureOfArrays format
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  ZVertex Producer::makeAsync(TkSoA const* tksoa, float ptMin) const {
    // std::cout << "producing Vertices on GPU" << std::endl;
    ZVertex vertices{std::make_unique<ZVertexSoA>()};

    assert(tksoa);
    auto* soa = vertices.get();
    assert(soa);
    auto ws = std::make_unique<WorkSpace>();

    init(soa, ws.get());
    loadTracks(tksoa, soa, ws.get(), ptMin);
    if (useDensity_ || oneKernel_) {
      clusterTracksByDensity(soa, ws.get(), minT, eps, errmax, chi2max);
    } else if (useDBSCAN_) {
      clusterTracksDBSCAN(soa, ws.get(), minT, eps, errmax, chi2max);
    } else if (useIterative_) {
      clusterTracksIterative(soa, ws.get(), minT, eps, errmax, chi2max);
    }
    fitVertices(soa, ws.get(), 50.);
    splitVertices(soa, ws.get(), 9.f);
    fitVertices(soa, ws.get(), 5000.);

    sortByPt2(soa, ws.get());

    return vertices;
  }

}  // namespace gpuVertexFinder

#undef FROM
