// C++ headers
#include <algorithm>
#include <numeric>

// CMSSW headers
#include "CUDACore/cudaCompat.h"

#include "plugin-SiPixelClusterizer/SiPixelRawToClusterGPUKernel.h"  // !
#include "plugin-SiPixelClusterizer/gpuClusteringConstants.h"        // !

#include "PixelRecHits.h"
#include "gpuPixelRecHits.h"

namespace {

// The following comment is generated by an LLM. 
/**
 * Sets the starting indices for hits in each layer based on the module start indices and layer geometry parameters.
 *
 * @param[in] hitsModuleStart array of module start indices
 * @param[in] cpeParams pointer to pixelCPEforGPU parameters object
 * @param[out] hitsLayerStart array to store the calculated layer start indices
 */ 
  __global__ void setHitsLayerStart(uint32_t const* __restrict__ hitsModuleStart,
                                    pixelCPEforGPU::ParamsOnGPU const* cpeParams,
                                    uint32_t* hitsLayerStart) {
    assert(0 == hitsModuleStart[0]);

    int begin = blockIdx.x * blockDim.x + threadIdx.x;
    constexpr int end = 11;
    for (int i = begin; i < end; i += blockDim.x * gridDim.x) {
      hitsLayerStart[i] = hitsModuleStart[cpeParams->layerGeometry().layerStart[i]];
#ifdef GPU_DEBUG
      printf("LayerStart %d %d: %d\n", i, cpeParams->layerGeometry().layerStart[i], hitsLayerStart[i]);
#endif
    }
  }
}  // namespace

namespace pixelgpudetails {


// The following comment is generated by an LLM. 
/**
 * Creates tracking rec hits in 2D for CPU and pixel rec hits for GPU kernel
 * @param digis_d input digitization data
 * @param clusters_d input cluster data
 * @param bs_d beam spot data
 * @param cpeParams parameters for pixel CP algorithm on GPU
 * @return tracking rec hits in 2D
 */ 
  TrackingRecHit2DCPU PixelRecHitGPUKernel::makeHits(SiPixelDigisSoA const& digis_d,
                                                     SiPixelClustersSoA const& clusters_d,
                                                     BeamSpotPOD const& bs_d,
                                                     pixelCPEforGPU::ParamsOnGPU const* cpeParams) const {
    auto nHits = clusters_d.nClusters();
    TrackingRecHit2DCPU hits_d(nHits, cpeParams, clusters_d.clusModuleStart(), nullptr);

    if (digis_d.nModules())  // protect from empty events
      gpuPixelRecHits::getHits(cpeParams, &bs_d, digis_d.view(), digis_d.nDigis(), clusters_d.view(), hits_d.view());
    cudaCheck(cudaGetLastError());

    // assuming full warp of threads is better than a smaller number...
    if (nHits) {
      setHitsLayerStart(clusters_d.clusModuleStart(), cpeParams, hits_d.hitsLayerStart());
    }

    if (nHits) {
      cms::cuda::fillManyFromVector(hits_d.phiBinner(), 10, hits_d.iphi(), hits_d.hitsLayerStart(), nHits, 256);
    }

    return hits_d;
  }

}  // namespace pixelgpudetails
