#ifndef HeterogenousCore_CUDAUtilities_deviceCount_h
#define HeterogenousCore_CUDAUtilities_deviceCount_h

#include "CUDACore/cudaCheck.h"

#include <cuda_runtime.h>

namespace cms {
  namespace cuda {
/**
 * Returns the number of available CUDA devices
 *
 * @return The number of CUDA devices
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    inline int deviceCount() {
      int ndevices;
      cudaCheck(cudaGetDeviceCount(&ndevices));
      return ndevices;
    }
  }  // namespace cuda
}  // namespace cms

#endif
