#ifndef RecoPixelVertexing_PixelVertexFinding_src_gpuSortByPt2_h
#define RecoPixelVertexing_PixelVertexFinding_src_gpuSortByPt2_h

#include "KokkosCore/hintLightWeight.h"

#include "gpuVertexFinder.h"

namespace KOKKOS_NAMESPACE {
  namespace gpuVertexFinder {

/**
 * Brief description of the function sortByPt2
 *
 * Detailed description of the function sortByPt2
 * Sorts particles by their Pt2 values within a Kokkos parallel environment
 *
 * @param vdata input particle data
 * @param vws workspace data
 * @param team_member team policy member type
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    KOKKOS_FORCEINLINE_FUNCTION void sortByPt2(
        const Kokkos::View<ZVertices, KokkosDeviceMemSpace, RestrictUnmanaged>& vdata,
        const Kokkos::View<WorkSpace, KokkosDeviceMemSpace, RestrictUnmanaged>& vws,
        const Kokkos::TeamPolicy<KokkosExecSpace>::member_type& team_member) {
      auto& __restrict__ data = *vdata.data();
      auto& __restrict__ ws = *vws.data();
      auto nt = ws.ntrks;
      float const* __restrict__ ptt2 = ws.ptt2;
      uint32_t const& nvFinal = data.nvFinal;

      int32_t const* __restrict__ iv = ws.iv;
      float* __restrict__ ptv2 = data.ptv2;
      uint16_t* __restrict__ sortInd = data.sortInd;

      const auto teamRank = team_member.team_rank();
      const auto teamSize = team_member.team_size();

      // if (threadIdx.x == 0)
      //    printf("sorting %d vertices\n",nvFinal);

      if (nvFinal < 1)
        return;

      // fill indexing
      Kokkos::parallel_for(Kokkos::TeamThreadRange(team_member, nt), [&](int i) { data.idv[ws.itrk[i]] = iv[i]; });

      // can be done asynchronoisly at the end of previous event
      Kokkos::parallel_for(Kokkos::TeamThreadRange(team_member, nvFinal), [=](int i) { ptv2[i] = 0; });
      team_member.team_barrier();

      // TODO: no parallel_for + TeamThreadRange because of "continue"
      for (unsigned int i = teamRank; i < nt; i += teamSize) {
        if (iv[i] > 9990)
          continue;
        cms::kokkos::atomic_add(&ptv2[iv[i]], ptt2[i]);
      }

      team_member.team_barrier();

      if (1 == nvFinal) {
        Kokkos::single(Kokkos::PerTeam(team_member), [&]() { sortInd[0] = 0; });
        return;
      }
    }

/**
 * Brief description of the function
 *
 * Detailed description of the function
 *
 * Parameters:
 *   vdata - input view of vertices
 *   vws - input view of workspace
 *   team_member - team policy member type
 *
 * Returns:
 *   None
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    KOKKOS_INLINE_FUNCTION void sortByPt2Kernel(
        const Kokkos::View<ZVertices, KokkosDeviceMemSpace, RestrictUnmanaged>& vdata,
        const Kokkos::View<WorkSpace, KokkosDeviceMemSpace, RestrictUnmanaged>& vws,
        const Kokkos::TeamPolicy<KokkosExecSpace>::member_type& team_member) {
      Kokkos::abort("sortByPt2Kernel: device sort kernel not supported in Kokkos (see sortByPt2Host)");
    }

    // equivalent to CUDA sortByPt2Kernel + deep copy to host
    template <typename MemSpace, typename ExecSpace>
/**
 * Sorts data by Pt2 in ascending order on the host.
 *
 * @param vdata input data to be sorted
 * @param vws workspace for sorting
 * @param hdata output sorted data on the host
 * @param execSpace execution space for parallel operations
 * @param policy team policy for parallel execution
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    void sortByPt2Host(
        const Kokkos::View<ZVertices, MemSpace, RestrictUnmanaged>& vdata,
        const Kokkos::View<WorkSpace, MemSpace, RestrictUnmanaged>& vws,
        const Kokkos::View<ZVertices, typename cms::kokkos::MemSpaceTraits<MemSpace>::HostSpace, RestrictUnmanaged>&
            hdata,
        const ExecSpace& execSpace,
        const Kokkos::TeamPolicy<ExecSpace>& policy) {
      using member_type = typename Kokkos::TeamPolicy<ExecSpace>::member_type;

      Kokkos::parallel_for(
          "sortByPt2", hintLightWeight(policy), KOKKOS_LAMBDA(const member_type& team_member) {
            sortByPt2(vdata, vws, team_member);
          });
      Kokkos::deep_copy(execSpace, hdata, vdata);
      execSpace.fence();

      auto& __restrict__ data = *hdata.data();
      uint32_t const& nvFinal = data.nvFinal;
      float* __restrict__ ptv2 = data.ptv2;
      uint16_t* __restrict__ sortInd = data.sortInd;

      // TODO: Kokkos::sort doesn't supported user-defined comparisons for now. A better
      // solution is to replace BinOp1D (in kokkos/algorithms/src/Kokkos_Sort.hpp) with
      // a custom comparison and create a sort function upon it.
      for (uint16_t i = 0; i < nvFinal; ++i)
        sortInd[i] = i;
      std::sort(sortInd, sortInd + nvFinal, [&](auto i, auto j) { return ptv2[i] < ptv2[j]; });
    }

  }  // namespace gpuVertexFinder
}  // namespace KOKKOS_NAMESPACE

#endif  // RecoPixelVertexing_PixelVertexFinding_src_gpuSortByPt2_h
