#include <limits>

#include "CUDACore/allocate_managed.h"
#include "CUDACore/cudaCheck.h"

#include "getCachingManagedAllocator.h"

namespace {
  const size_t maxAllocationSize =
      notcub::CachingDeviceAllocator::IntPow(cms::cuda::allocator::binGrowth, cms::cuda::allocator::maxBin);
}

namespace cms::cuda {

// The following comment is generated by an LLM. 
/**
 * Allocates managed memory of specified size on the GPU.
 *
 * @param nbytes Size of memory to be allocated in bytes
 * @param stream CUDA stream associated with the allocation
 * @return Pointer to the allocated memory
 */ 
  void *allocate_managed(size_t nbytes, cudaStream_t stream) {
    void *ptr = nullptr;
    if constexpr (allocator::policy == allocator::Policy::Caching) {
      if (nbytes > maxAllocationSize) {
        throw std::runtime_error("Tried to allocate " + std::to_string(nbytes) +
                                 " bytes, but the allocator maximum is " + std::to_string(maxAllocationSize));
      }
      cudaCheck(allocator::getCachingManagedAllocator().ManagedAllocate(&ptr, nbytes, stream));
    } else {
      cudaCheck(cudaMallocManaged(&ptr, nbytes));
    }
    return ptr;
  }


// The following comment is generated by an LLM. 
/**
 * Frees managed memory allocated using the specified allocator policy.
 *
 * @param ptr Pointer to the memory block to be freed
 */ 
  void free_managed(void *ptr) {
    if constexpr (allocator::policy == allocator::Policy::Caching) {
      cudaCheck(allocator::getCachingManagedAllocator().ManagedFree(ptr));
    } else {
      cudaCheck(cudaFree(ptr));
    }
  }

}  // namespace cms::cuda
