#ifndef HeterogeneousCore_CUDAUtilities_ScopedSetDevice_h
#define HeterogeneousCore_CUDAUtilities_ScopedSetDevice_h

#include "CUDACore/cudaCheck.h"

#include <cuda_runtime.h>

namespace cms {
  namespace cuda {
/**
 * @brief Class representing a scoped setting of a CUDA device.
 *
 * This class ensures that the original CUDA device is restored when it goes out of scope,
 * allowing for safe and exception-free device switching.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    class ScopedSetDevice {
    public:
      // Store the original device, without setting a new one
      ScopedSetDevice() {
        // Store the original device
        cudaCheck(cudaGetDevice(&originalDevice_));
      }

      // Store the original device, and set a new current device
      explicit ScopedSetDevice(int device) : ScopedSetDevice() {
        // Change the current device
        set(device);
      }

      // Restore the original device
      ~ScopedSetDevice() {
        // Intentionally don't check the return value to avoid
        // exceptions to be thrown. If this call fails, the process is
        // doomed anyway.
        cudaSetDevice(originalDevice_);
      }

      // Set a new current device, without changing the original device
      // that will be restored when this object is destroyed
      void set(int device) {
        // Change the current device
        cudaCheck(cudaSetDevice(device));
      }

    private:
      int originalDevice_;
    };
  }  // namespace cuda
}  // namespace cms

#endif
