#ifndef EDProducerBase_h
#define EDProducerBase_h

#include "Framework/WaitingTaskWithArenaHolder.h"

namespace edm {
  class Event;
  class EventSetup;

/**
 * Brief description of EDProducer class
 *
 * Detailed description of EDProducer class
 
class EDProducer { * Default constructor for EDProducer
 
EDProducer();
 * Virtual destructor for EDProducer
 
virtual ~EDProducer();
 * Checks if acquire functionality is supported
 * @return true if acquire is supported, false otherwise
 
bool hasAcquire() const;
 * Performs acquisition operation
 * @param event reference to Event object
 * @param eventSetup reference to EventSetup object
 * @param holder reference to WaitingTaskWithArenaHolder object
 
void doAcquire(Event const& event, EventSetup const& eventSetup, WaitingTaskWithArenaHolder holder);
 * Produces data for an event
 * @param event reference to Event object
 * @param eventSetup reference to EventSetup object
 
void doProduce(Event& event, EventSetup const& eventSetup);
 * Pure virtual function to produce data for an event
 * @param event reference to Event object
 * @param eventSetup reference to EventSetup object
 
virtual void produce(Event& event, EventSetup const& eventSetup) = 0;
 * Performs end job operations
 
void doEndJob();
 * Virtual function to perform end job operations
 
virtual void endJob();

private:
};* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  class EDProducer {
  public:
    EDProducer() = default;
    virtual ~EDProducer() = default;

    bool hasAcquire() const { return false; }

    void doAcquire(Event const& event, EventSetup const& eventSetup, WaitingTaskWithArenaHolder holder) {}

    void doProduce(Event& event, EventSetup const& eventSetup) { produce(event, eventSetup); }

    virtual void produce(Event& event, EventSetup const& eventSetup) = 0;

    void doEndJob() { endJob(); }

    virtual void endJob() {}

  private:
  };

/**
 * @brief Interface for external work producers in the event processing framework
 *
 * This abstract base class defines the interface for classes that produce data
 * during event processing It provides methods for acquiring and producing data
 * as well as ending the job
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  class EDProducerExternalWork {
  public:
    EDProducerExternalWork() = default;
    virtual ~EDProducerExternalWork() = default;

    bool hasAcquire() const { return true; }

    void doAcquire(Event const& event, EventSetup const& eventSetup, WaitingTaskWithArenaHolder holder) {
      acquire(event, eventSetup, std::move(holder));
    }

    void doProduce(Event& event, EventSetup const& eventSetup) { produce(event, eventSetup); }

    virtual void acquire(Event const& event, EventSetup const& eventSetup, WaitingTaskWithArenaHolder holder) = 0;
    virtual void produce(Event& event, EventSetup const& eventSetup) = 0;

    void doEndJob() { endJob(); }
    virtual void endJob() {}

  private:
  };
}  // namespace edm

#endif
