#include <algorithm>
#include <cmath>

#include <sycl/sycl.hpp>

#include "SYCLCore/device_unique_ptr.h"
#include "SYCLCore/host_unique_ptr.h"
#include "gpuAlgo1.h"

namespace gpu_algo_1 {
  constexpr int NUM_VALUES = 1000;

  template <typename T>

// The following comment is generated by an LLM. 
/**
 * Performs elementwise addition of two vectors.
 *
 * @param[in] a First input vector.
 * @param[in] b Second input vector.
 * @param[out] c Resulting vector.
 * @param[in] numElements Number of elements in the vectors.
 * @param[in] item SYCL item object.
 */ 
  SYCL_EXTERNAL void vectorAdd(const T *a, const T *b, T *c, int numElements, sycl::nd_item<1> item) {
    int i = item.get_global_id(0);
    if (i < numElements) {
      c[i] = a[i] + b[i];
    }
  }

  template <typename T>

// The following comment is generated by an LLM. 
/**
 * Computes the product of two vectors.
 *
 * @param[in] a First input vector
 * @param[in] b Second input vector
 * @param[out] c Resulting vector
 * @param[in] numElements Number of elements in the vectors
 * @param[in] item SYCL item object providing global IDs
 */ 
  SYCL_EXTERNAL void vectorProd(const T *a, const T *b, T *c, int numElements, sycl::nd_item<3> item) {
    int row = item.get_global_id(1);
    int col = item.get_global_id(2);

    if (row < numElements && col < numElements) {
      c[row * numElements + col] = a[row] * b[col];
    }
  }

  template <typename T>

// The following comment is generated by an LLM. 
/**
 * Performs matrix multiplication operation on input matrices a and b
 * storing result in matrix c utilizing SYCL parallelization
 * @param a First input matrix
 * @param b Second input matrix
 * @param c Resultant matrix
 * @param numElements Number of elements in each dimension of square matrices
 * @param item SYCL item object providing global ids for parallel execution
 */ 
  SYCL_EXTERNAL void matrixMul(const T *a, const T *b, T *c, int numElements, sycl::nd_item<3> item) {
    int row = item.get_global_id(1);
    int col = item.get_global_id(2);

    if (row < numElements && col < numElements) {
      T tmp = 0;
      for (int i = 0; i < numElements; ++i) {
        tmp += a[row * numElements + i] * b[i * numElements + col];
      }
      c[row * numElements + col] = tmp;
    }
  }

  template <typename T>

// The following comment is generated by an LLM. 
/**
 * Performs matrix vector multiplication on a single row of the matrix.
 *
 * @param[in] a Input matrix data
 * @param[in] b Input vector data
 * @param[out] c Resultant vector data
 * @param[in] numElements Number of elements in the input vectors
 * @param[in] item SYCL item object providing global ID
 */ 
  SYCL_EXTERNAL void matrixMulVector(const T *a, const T *b, T *c, int numElements, sycl::nd_item<1> item) {
    int row = item.get_global_id(0);

    if (row < numElements) {
      T tmp = 0;
      for (int i = 0; i < numElements; ++i) {
        tmp += a[row * numElements + i] * b[i];
      }
      c[row] = tmp;
    }
  }
}  // namespace gpu_algo_1

using namespace gpu_algo_1;


// The following comment is generated by an LLM. 
/**
 * Outputs a 1D range object to an output stream.
 *
 * @param out the output stream
 * @param range the 1D range object to output
 * @return a reference to the output stream
 */ 
std::ostream &operator<<(std::ostream &out, sycl::range<1> range) {
  out << '(' << range.get(0) << ')';
  return out;
}


// The following comment is generated by an LLM. 
/**
 * Outputs a 2D range object to an output stream.
 *
 * @param out the output stream
 * @param range the 2D range object to be output
 * @return a reference to the output stream
 */ 
std::ostream &operator<<(std::ostream &out, sycl::range<2> range) {
  out << '(' << range.get(0) << ", " << range.get(1) << ')';
  return out;
}


// The following comment is generated by an LLM. 
/**
 * Outputs a 3D range object to an output stream.
 *
 * @param out the output stream
 * @param range the 3D range object to output
 * @return a reference to the output stream
 */ 
std::ostream &operator<<(std::ostream &out, sycl::range<3> range) {
  out << '(' << range.get(0) << ", " << range.get(1) << ", " << range.get(2) << ')';
  return out;
}

template <int D>

// The following comment is generated by an LLM. 
/**
 * Outputs a string representation of an ndrange object to an output stream
 * 
 * @param out the output stream to write to
 * @param range the ndrange object to output
 * @return a reference to the output stream
 */ 
std::ostream &operator<<(std::ostream &out, sycl::nd_range<D> range) {
  out << '[' << range.get_global_range() << " x " << range.get_local_range() << ']';
  return out;
}


// The following comment is generated by an LLM. 
/**
 * Calculates the integer square root of a given number by iteratively dividing the input value by 4 until it is less than 4, effectively calculating the largest power of 2 that is less than or equal to the square root of the original value.
 *
 * @param value Input number for which the integer square root is calculated
 * @return Largest power of 2 that is less than or equal to the square root of the original value
 */ 
constexpr unsigned int sqrt2(unsigned int value) {
  unsigned int result = 1;
  while (value >= 4) {
    value /= 4;
    result *= 2;
  }
  return result;
}

constexpr unsigned int make_blocks(unsigned int size, unsigned int block_size) {
  return (size + block_size - 1) / block_size;
}


// The following comment is generated by an LLM. 
/**
 * @brief Performs GPU algorithm 1 on the specified stream.
 *
 * This function performs a series of operations on the GPU, including vector addition,
 * vector production, and matrix multiplication. It uses the SYCL library to manage
 * memory and execute kernel functions on the GPU.
 *
 * @param stream The SYCL queue object representing the GPU stream.
 *
 * @return A unique pointer to the resulting array of floats.
 */ 
cms::sycltools::device::unique_ptr<float[]> gpuAlgo1(sycl::queue stream) {
  // FIXME the OpenCL CPU device reports a maximum workgroup size of 8192,
  // but workgroups bigger than 4096 result in a CL_OUT_OF_RESOURCES error
  const unsigned int workgroupSizeLimit = 4096;

  // query the device for the maximum "block size" or workgroup size
  const unsigned int maxWorkgroupSize = std::min<unsigned int>(
      workgroupSizeLimit, stream.get_device().get_info<sycl::info::device::max_work_group_size>());

  // build a rectangular "block" or workgroup
  const unsigned int workgroupRectB = sqrt2(maxWorkgroupSize);
  const unsigned int workgroupRectA = maxWorkgroupSize / workgroupRectB;

  auto h_a = cms::sycltools::make_host_unique<float[]>(NUM_VALUES, stream);
  auto h_b = cms::sycltools::make_host_unique<float[]>(NUM_VALUES, stream);

  for (auto i = 0; i < NUM_VALUES; i++) {
    h_a[i] = i;
    h_b[i] = i * i;
  }

  auto d_a = cms::sycltools::make_device_unique<float[]>(NUM_VALUES, stream);
  auto d_b = cms::sycltools::make_device_unique<float[]>(NUM_VALUES, stream);

  stream.memcpy(d_a.get(), h_a.get(), NUM_VALUES * sizeof(float));
  stream.memcpy(d_b.get(), h_b.get(), NUM_VALUES * sizeof(float));

  unsigned int threadsPerBlock = std::min<unsigned int>(NUM_VALUES, maxWorkgroupSize);
  unsigned int blocksPerGrid = make_blocks(NUM_VALUES, threadsPerBlock);
  unsigned int threadsPerGrid = blocksPerGrid * threadsPerBlock;
  auto grid = sycl::nd_range<1>(threadsPerGrid, threadsPerBlock);

  auto d_c = cms::sycltools::make_device_unique<float[]>(NUM_VALUES, stream);

#ifdef DEBUG
  std::cerr << "block size: " << threadsPerBlock << " / " << maxWorkgroupSize << std::endl;
  std::cerr << "grid size:  " << blocksPerGrid << std::endl;
#endif
  stream.submit([&](sycl::handler &cgh) {
    auto pd_a = d_a.get();
    auto pd_b = d_b.get();
    auto pd_c = d_c.get();

    cgh.parallel_for(grid, [=](sycl::nd_item<1> item) { vectorAdd(pd_a, pd_b, pd_c, NUM_VALUES, item); });
  });

  auto d_ma = cms::sycltools::make_device_unique<float[]>(NUM_VALUES * NUM_VALUES, stream);
  auto d_mb = cms::sycltools::make_device_unique<float[]>(NUM_VALUES * NUM_VALUES, stream);
  auto d_mc = cms::sycltools::make_device_unique<float[]>(NUM_VALUES * NUM_VALUES, stream);

  sycl::range<3> threadsPerBlock3{1, workgroupRectB, workgroupRectA};
  sycl::range<3> blocksPerGrid3{1, make_blocks(NUM_VALUES, workgroupRectB), make_blocks(NUM_VALUES, workgroupRectA)};
  auto threadsPerGrid3 = blocksPerGrid3 * threadsPerBlock3;
  auto grid3 = sycl::nd_range<3>(threadsPerGrid3, threadsPerBlock3);

#ifdef DEBUG
  std::cerr << "block size: " << threadsPerBlock3 << " / " << maxWorkgroupSize << std::endl;
  std::cerr << "grid size:  " << blocksPerGrid3 << std::endl;
#endif
  stream.submit([&](sycl::handler &cgh) {
    auto pd_a = d_a.get();
    auto pd_b = d_b.get();
    auto pd_ma = d_ma.get();

    cgh.parallel_for(grid3, [=](sycl::nd_item<3> item) { vectorProd(pd_a, pd_b, pd_ma, NUM_VALUES, item); });
  });

#ifdef DEBUG
  std::cerr << "block size: " << threadsPerBlock3 << " / " << maxWorkgroupSize << std::endl;
  std::cerr << "grid size:  " << blocksPerGrid3 << std::endl;
#endif
  stream.submit([&](sycl::handler &cgh) {
    auto pd_a = d_a.get();
    auto pd_c = d_c.get();
    auto pd_mb = d_mb.get();

    cgh.parallel_for(grid3, [=](sycl::nd_item<3> item) { vectorProd(pd_a, pd_c, pd_mb, NUM_VALUES, item); });
  });

#ifdef DEBUG
  std::cerr << "block size: " << threadsPerBlock3 << " / " << maxWorkgroupSize << std::endl;
  std::cerr << "grid size:  " << blocksPerGrid3 << std::endl;
#endif
  stream.submit([&](sycl::handler &cgh) {
    auto pd_ma = d_ma.get();
    auto pd_mb = d_mb.get();
    auto pd_mc = d_mc.get();

    cgh.parallel_for(grid3, [=](sycl::nd_item<3> item) { matrixMul(pd_ma, pd_mb, pd_mc, NUM_VALUES, item); });
  });

#ifdef DEBUG
  std::cerr << "block size: " << threadsPerBlock << " / " << maxWorkgroupSize << std::endl;
  std::cerr << "grid size:  " << blocksPerGrid << std::endl;
#endif
  stream.submit([&](sycl::handler &cgh) {
    auto pd_mc = d_mc.get();
    auto pd_b = d_b.get();
    auto pd_c = d_c.get();

    cgh.parallel_for(grid, [=](sycl::nd_item<1> item) { matrixMulVector(pd_mc, pd_b, pd_c, NUM_VALUES, item); });
  });

  // wait for all asynchronous work to complete before destroying the device memory buffers
  stream.wait_and_throw();

  return d_a;
}
