#ifndef HeterogeneousCore_CUDAUtilities_copyAsync_h
#define HeterogeneousCore_CUDAUtilities_copyAsync_h

#include "CUDACore/cudaCheck.h"
#include "CUDACore/device_unique_ptr.h"
#include "CUDACore/host_noncached_unique_ptr.h"
#include "CUDACore/host_unique_ptr.h"

#include <type_traits>

namespace cms {
  namespace hip {

    // Single element

    template <typename T>
/**
 * Copies data asynchronously from host to device.
 *
 * @param dst pointer to unique device memory
 * @param src pointer to unique host memory
 * @param stream hipStream_t object representing the stream
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void copyAsync(device::unique_ptr<T>& dst, const host::unique_ptr<T>& src, hipStream_t stream) {
      // Shouldn't compile for array types because of sizeof(T), but
      // let's add an assert with a more helpful message
      static_assert(std::is_array<T>::value == false,
                    "For array types, use the other overload with the size parameter");
      cudaCheck(hipMemcpyAsync(dst.get(), src.get(), sizeof(T), hipMemcpyHostToDevice, stream));
    }

    template <typename T>
/**
 * Copies data asynchronously from host to device memory.
 *
 * @param dst pointer to unique device memory location
 * @param src pointer to constant non-cached host memory location
 * @param stream HIP stream object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void copyAsync(device::unique_ptr<T>& dst, const host::noncached::unique_ptr<T>& src, hipStream_t stream) {
      // Shouldn't compile for array types because of sizeof(T), but
      // let's add an assert with a more helpful message
      static_assert(std::is_array<T>::value == false,
                    "For array types, use the other overload with the size parameter");
      cudaCheck(hipMemcpyAsync(dst.get(), src.get(), sizeof(T), hipMemcpyHostToDevice, stream));
    }

    template <typename T>
/**
 * Copies data asynchronously from a device pointer to a host pointer.
 *
 * @param dst   destination host pointer
 * @param src   source device pointer
 * @param stream  HIP stream object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void copyAsync(host::unique_ptr<T>& dst, const device::unique_ptr<T>& src, hipStream_t stream) {
      static_assert(std::is_array<T>::value == false,
                    "For array types, use the other overload with the size parameter");
      cudaCheck(hipMemcpyAsync(dst.get(), src.get(), sizeof(T), hipMemcpyDeviceToHost, stream));
    }

    // Multiple elements

    template <typename T>
/**
 * Copies data asynchronously from host to device.
 *
 * @param dst destination array on the device
 * @param src source array on the host
 * @param nelements number of elements to copy
 * @param stream HIP stream to perform the copy operation on
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void copyAsync(device::unique_ptr<T[]>& dst,
                          const host::unique_ptr<T[]>& src,
                          size_t nelements,
                          hipStream_t stream) {
      cudaCheck(hipMemcpyAsync(dst.get(), src.get(), nelements * sizeof(T), hipMemcpyHostToDevice, stream));
    }

    template <typename T>
/**
 * Copies data asynchronously from host to device.
 *
 * @param dst     Destination array on the device.
 * @param src     Source array on the host.
 * @param nelements Number of elements to copy.
 * @param stream  HIP stream handle.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void copyAsync(device::unique_ptr<T[]>& dst,
                          const host::noncached::unique_ptr<T[]>& src,
                          size_t nelements,
                          hipStream_t stream) {
      cudaCheck(hipMemcpyAsync(dst.get(), src.get(), nelements * sizeof(T), hipMemcpyHostToDevice, stream));
    }

    template <typename T>
/**
 * Copies data asynchronously from a device array to a host array.
 *
 * @param dst       Pointer to the destination host array.
 * @param src       Pointer to the source device array.
 * @param nelements Number of elements to copy.
 * @param stream    HIP stream handle.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void copyAsync(host::unique_ptr<T[]>& dst,
                          const device::unique_ptr<T[]>& src,
                          size_t nelements,
                          hipStream_t stream) {
      cudaCheck(hipMemcpyAsync(dst.get(), src.get(), nelements * sizeof(T), hipMemcpyDeviceToHost, stream));
    }
  }  // namespace hip
}  // namespace cms

#endif
