#ifndef HeterogeneousCore_CUDAUtilities_cudastdAlgorithm_h
#define HeterogeneousCore_CUDAUtilities_cudastdAlgorithm_h

#include <utility>

#include <hip/hip_runtime.h>

// reimplementation of std algorithms able to compile with CUDA and run on GPUs,
// mostly by declaringthem constexpr

namespace hip_std {

  template <typename T = void>
  struct less {
    __host__ __device__ constexpr bool operator()(const T &lhs, const T &rhs) const { return lhs < rhs; }
  };

  template <>
  struct less<void> {
    template <typename T, typename U>
    __host__ __device__ constexpr bool operator()(const T &lhs, const U &rhs) const {
      return lhs < rhs;
    }
  };

  template <typename RandomIt, typename T, typename Compare = less<T>>
/**
 * Searches for the lowest index at which an element should be inserted to maintain sorted order.
 *
 * @param first Beginning of the range.
 * @param last End of the range.
 * @param value Value to search for.
 * @param comp Comparison function object.
 * @return Iterator pointing to the insertion point.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  __host__ __device__ constexpr RandomIt lower_bound(RandomIt first, RandomIt last, const T &value, Compare comp = {}) {
    auto count = last - first;

    while (count > 0) {
      auto it = first;
      auto step = count / 2;
      it += step;
      if (comp(*it, value)) {
        first = ++it;
        count -= step + 1;
      } else {
        count = step;
      }
    }
    return first;
  }

  template <typename RandomIt, typename T, typename Compare = less<T>>
/**
 * Searches for the upper bound of a value within a sorted range.
 *
 * @param first Beginning of the search range.
 * @param last End of the search range.
 * @param value Value to search for.
 * @param comp Comparison function object.
 * @return Iterator pointing to the upper bound of the value.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  __host__ __device__ constexpr RandomIt upper_bound(RandomIt first, RandomIt last, const T &value, Compare comp = {}) {
    auto count = last - first;

    while (count > 0) {
      auto it = first;
      auto step = count / 2;
      it += step;
      if (!comp(value, *it)) {
        first = ++it;
        count -= step + 1;
      } else {
        count = step;
      }
    }
    return first;
  }

  template <typename RandomIt, typename T, typename Compare = hip_std::less<T>>
/**
 * Performs a binary search within a range to find an element that matches a specified value.
 * 
 * @param first Iterator pointing to the beginning of the range.
 * @param last Iterator pointing to the end of the range.
 * @param value Value to be searched for within the range.
 * @param comp Comparison function object that defines the sort order.
 * @return An iterator pointing to the found element if it exists, otherwise an iterator equal to last.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  __host__ __device__ constexpr RandomIt binary_find(RandomIt first, RandomIt last, const T &value, Compare comp = {}) {
    first = hip_std::lower_bound(first, last, value, comp);
    return first != last && !comp(value, *first) ? first : last;
  }

}  // namespace hip_std

#endif  // HeterogeneousCore_CUDAUtilities_cudastdAlgorithm_h
