#ifndef HeterogenousCore_CUDAUtilities_deviceCount_h
#define HeterogenousCore_CUDAUtilities_deviceCount_h

#include "CUDACore/cudaCheck.h"

#include <hip/hip_runtime.h>

namespace cms {
  namespace hip {
/**
 * Returns the number of available devices
 *
 * @return The number of devices
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    inline int deviceCount() {
      int ndevices;
      cudaCheck(hipGetDeviceCount(&ndevices));
      return ndevices;
    }
  }  // namespace hip
}  // namespace cms

#endif
