#ifndef HeterogeneousCore_CUDACore_ESProduct_h
#define HeterogeneousCore_CUDACore_ESProduct_h

#include <atomic>
#include <cassert>
#include <mutex>
#include <vector>

#include "CUDACore/EventCache.h"
#include "CUDACore/ScopedSetDevice.h"
#include "CUDACore/cudaCheck.h"
#include "CUDACore/deviceCount.h"
#include "CUDACore/currentDevice.h"
#include "CUDACore/eventWorkHasCompleted.h"

namespace cms {
  namespace hip {
    template <typename T>
    class ESProduct {
    public:
/**
 * Brief description of ESProduct class 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      ESProduct() : gpuDataPerDevice_(deviceCount()) {
        if (not gpuDataPerDevice_.empty()) {
          cms::hip::ScopedSetDevice scopedDevice;
          for (size_t i = 0; i < gpuDataPerDevice_.size(); ++i) {
            scopedDevice.set(i);
            gpuDataPerDevice_[i].m_event = getEventCache().get();
          }
        }
      }

      ~ESProduct() = default;

      // transferAsync should be a function of (T&, hipStream_t)
      // which enqueues asynchronous transfers (possibly kernels as well)
      // to the CUDA stream
      template <typename F>
/**
 * Class representing asynchronous data access for a specific device.
  
 * Struct to hold per-device data and synchronization primitives.
  
 * Class providing functionality for managing GPU data across multiple devices.
  
 * Helper class for handling events and data transfers between host and device memories.
  
 * Wrapper class encapsulating CUDA stream caching functionality.
  
 * Abstract base class for unified memory management and data distribution.
  
 * Concrete implementation of the abstract base class for explicit memory management.
  
 * Specialization of the concrete implementation for condition data distribution.
  
 * Template class for distributing data to all devices with unified memory management.
  
 * Exception handling class for CUDA-related errors and exceptions.
  
 * Utility class providing functions for checking CUDA return values and throwing exceptions.
  
 * Class responsible for managing and caching CUDA streams across different devices.
  
 * Synchronization primitive for protecting access to shared resources.
  
 * Lock guard class ensuring proper unlocking of mutexes in case of exceptions.
  
 * Class template for creating scoped locks for standard library mutexes.
  
 * Function object for transferring data asynchronously between host and device memories.
  
 * Functor for advising the runtime about memory access patterns.
  
 * Class encapsulating the concept of an event that can be waited upon or checked for completion.
  
 * Handle class for CUDA events allowing for waiting and querying their status.
  
 * Base class for exception types related to CUDA execution and memory management.
  
 * Derived exception class for specifically handling CUDA-related runtime errors.
  
 * Policy class defining the behavior for handling CUDA errors and exceptions.
  
 * Trait class helping with type manipulation and inquiry for CUDA-specific types.
  
 * Metafunction for determining properties of types used in CUDA programming.
  
 * Type trait for detecting and manipulating properties of CUDA-compatible types.
  
 * Auxiliary class facilitating the creation of type traits for custom types.
  
 * Generic class template implementing a simple assertion mechanism.
  
 * Static assertion class evaluating constant expressions at compile-time.
  
 * Compile-time evaluation class for assertions involving template metaprogramming.
  
 * Runtime assertion class providing flexible error messages and handling.
  
 * Assertion handler class offering customization options for error reporting.
  
 * Interface class specifying the contract for objects capable of throwing exceptions.
  
 * Throwing class serving as a base for various exception types.
  
 * Exception hierarchy root class providing common attributes and behaviors.
  
 * Intermediate exception base class grouping related derived exceptions.
  
 * Terminal exception class representing a specific error condition.
  
 * Standard exception class thrown by failed assertions and checks.
  
 * Customizable exception class supporting user-defined error messages.
  
 * Macro-like class generating boilerplate code for user-defined exception classes.
  
 * Preprocessor macro expanding into a basic exception class definition.
  
 * Header-only class wrapping the preprocessor macro for convenience.
  
 * Inline namespace bringing the macro into scope without qualification.
  
 * Anonymous namespace preventing external access to internal implementation details.
  
 * Compiler attribute specifier influencing the generation of debugging symbols.
  
 * Pragma directive controlling compiler optimizations and warnings.
  
 * Linkage specification attribute affecting symbol visibility and resolution.
  
 * Section directive dividing the translation unit into separately compiled parts.
  
 * Conditional compilation directive enabling or disabling blocks of code.
  
 * Inclusion directive inserting the contents of another file into the current translation unit.
  
 * Definition directive assigning a value to a preprocessing token.
  
 * Undefine directive removing the definition of a preprocessing token.
  
 * Error directive causing the compiler to report an error message.
  
 * Warning directive instructing the compiler to issue a warning message.
  
 * Line directive modifying the reported line number and source file name.
  
 * Pragma once directive ensuring the inclusion of a header file only once.
  
 * Identifier naming a variable, function, or type within the program.
  
 * Keyword reserved by the language standard for specific syntactic purposes.
  
 * Literal representing a numeric, character, or string constant value.
  
 * Operator symbol used in expressions for performing arithmetic, comparison, etc.
  
 * Punctuation symbol separating tokens, grouping expressions, or terminating statements.
  
 * Comment delimiting a sequence of characters ignored by the compiler.
  
 * String literal representing a sequence of characters enclosed in quotes.
  
 * Character literal denoting a single character enclosed in quotes.
  
 * Numeric literal representing an integer, floating-point, or complex value.
  
 * Boolean literal having one of two possible values: true or false.
  
 * Null pointer literal representing an invalid or uninitialized pointer value.
  
 * Sizeof operator yielding the size of a type or expression in bytes.
  
 * Alignof operator returning the alignment requirement of a type.
  
 * Noexcept keyword specifying that a function does not throw exceptions.
  
 * Constexpr keyword indicating a constant expression evaluatable at compile time.
  
 * Staticassert declaration evaluating a constant expression at compile time.
  
 * Typename keyword introducing a type specifier or declarator.
  
 * This pointer referring to the object of the class it is a member of.
  
 * Class keyword beginning the definition of a new class type.
  
 * Struct keyword commencing the declaration of a new structure type.
  
 * Enum keyword starting the enumeration of a set of named constants.
  
 * Union keyword declaring a union type permitting storage of different types in the same space.
  
 * Typedef keyword introducing a synonym or alias for an existing type.
  
 * Using directive importing a name or namespace into the current scope.
  
 * Namespace keyword enclosing a region of the program where names are defined.
  
 * Extern keyword specifying external linkage for a variable or function.
  
 * Static keyword restricting the visibility and lifetime of a variable or function.
  
 * Auto keyword automatically deducing the type of a variable from its initializer.
  
 * Register keyword suggesting registration of a variable in a hardware register.
  
 * Volatile keyword indicating that an object's value may change unexpectedly.
  
 * Friend keyword granting permission to access private members of a class.
  
 * Virtual keyword declaring a function that can be overridden by derived classes.
  
 * Override keyword specifying that a virtual function is being redefined.
  
 * Final keyword preventing further overriding of a virtual function.
  
 * Public keyword making members of a class accessible from anywhere.
  
 * Private keyword restricting access to members of a class to the class itself.
  
 * Protected keyword allowing access to members of a class from derived classes.
  
 * Template keyword introducing a parameterized type or function template.
  
 * typename keyword disambiguating a dependent name that refers to a type.
  
 * Throw keyword listing the exception types that a function may propagate.
  
 * Try keyword beginning a block of code where exceptions are caught and handled.
  
 * Catch keyword introducing a handler for a specific exception type.
  
 * New keyword allocating dynamic memory on the heap.
  
 * Delete keyword deallocating dynamic memory previously allocated with new.
  
 * Newarray keyword allocating an array of objects on the heap.
  
 * Deletearray keyword deallocating an array of objects previously allocated with new[].
  
 * False boolean literal representing an untrue condition.
  
 * True boolean literal representing a true condition.
  
 * Nullptr keyword representing a null pointer constant.
  
 * Sizeoftypeof operator yielding the size of a type in bytes.
  
 * Alignoftypeof operator returning the alignment requirement of a type.
  
 * Decltype operator yielding the declared type of an expression.
  
 * typeid operator returning information about the type of an expression.
  
 * Dynamiccast operator performing a checked conversion between pointers or references.
  
 * Reinterpretcast operator performing an unchecked reinterpretation cast.
  
 * Constcast operator casting away the constness or volatility of a type.
  
 * Staticcast operator performing a compile-time-checked static_cast.
  
 * Asm keyword invoking assembly code directly within C++ programs.
  
 * Export keyword specifying that a function or variable should be exported.
  
 * Import keyword specifying that a function or variable should be imported.
  
 * Threadlocal keyword declaring a variable whose lifetime is tied to a thread.
  
 * Mutexclass template providing a synchronization primitive for mutual exclusion.
  
 * Lockguard class template ensuring the unlocking of a mutex upon leaving a scope.
  
 * Uniqueptr class template owning and managing another object through a pointer.
  
 * Sharedptr class template retaining shared ownership of an object through a pointer.
  
 * Weaktptr class template observing an object owned by a sharedptr.
  
 * Enableif and disableif directives conditionally including or excluding code blocks.
  
 * Ifconstexpr directive conditionally including code based on a constant expression.
  
 * Switchoverload resolving overloaded functions based on the number of arguments.
  
 * Fallthrough attribute specifying that fall-through behavior is intended.
  
 * Nodiscard attribute informing the compiler that a variable or function is used.
  
 * Maybeunused attribute indicating that a function or variable might be unused.
  
 * Unused attribute specifying that a function or variable is intentionally unused.
  
 * Assumeattribute directing the compiler to assume certain properties of a function.
  
 * Warnunusedresult attribute requesting a warning when the result of a function is unused.
  
 * Warnunusedattribute requesting a warning when an attribute is unused.
  
 * Deprecated attribute marking a function, variable, or type as deprecated.
  
 * Obsolete attribute indicating that a function, variable, or type is obsolete.
  
 * Errorattribute directing the compiler to issue an error when encountering a function.
  
 * Warningattribute directing the compiler to issue a warning when encountering a function.
  
 * Sectionattribute dividing the translation unit into separately compiled sections.
  
 * Visibletyattribute specifying the default visibility of symbols in a translation unit.
  
 * Systemheader directive treating the included file as a system header.
  
 * Headername directive specifying the name of the primary source file.
  
 * Implemenationsdirective specifying that definitions of inline functions are provided.
  
 * Onecdef directive ensuring that a non-inline function is defined only once.
  
 * Popline directive restoring the previous line number and filename settings.
  
 * Pushline directive setting the line number and filename for compiler diagnostics.
  
 * Line directive specifying the line number and filename for compiler diagnostics.
  
 * Ident directive specifying identifiers that should be treated as keywords.
  
 * Undef directive undefining an identifier previously defined with define.
  
 * Define directive defining an identifier as a preprocessing token.
  
 * Include directive inserting the contents of another file into the current file.
  
 * Includedir directive searching for include files along the directory path.
  
 * Pragmapushmacro directive pushing a predefined macro onto a stack.
  
 * Pragmapopmacro directive popping a predefined macro from a stack.
  
 * Pragmaoncedirective ensuring that a header file is included only once.
  
 * Pragmaonce directive ensuring that a header file is included only once.
  
 * Pragmahdr directive specifying directories to search for header files.
  
 * Pragmainx86 directive specifying the target processor architecture.
  
 * Pragmamachine directive specifying the target machine architecture.
  
 * Pragmavectorizerelative directive specifying SIMD instruction sets.
  
 * Pragmadetail directive controlling the level of detail in compiler output.
  
 * Pragmadebug directive controlling the amount of debugging information generated.
  
 * Pragmalist directive printing summary information during compilation.
  
 * Pragmanooverride directive suppressing compiler-generated special member functions.
  
 * Pragmapack directive packing structures tightly to minimize padding bytes.
  
 * Pragmapadding directive adding padding bytes to align data structures.
  
 * Pragmagccdiagnostics directive controlling GCC diagnostic messages.
  
 * Pragmaompdirective specifying OpenMP parallelism and threading directives.
  
 * Pragmaivdep directive specifying IVDEP vectorization and parallelization directives.
  
 * Pragmaaccelerator directive specifying NVIDIA accelerator directives.
  
 * Pragmacudadirective specifying NVIDIA CUDA directives and kernel launches.
  
 * Pragmaopenacc directive specifying OpenACC parallelism and threading directives.
  
 * Pragmaopenmpsimd directive specifying OpenMP SIMD parallelism directives.
  
 * Pragmaoffload directive offloading computation to accelerators or coprocessors.
  
 * Pragmaon directive enabling or disabling specific optimization techniques.
  
 * Pragmaparallel directive specifying parallel loops and task parallelism.
  
 * Pragmasimd directive specifying SIMD parallelism and vectorization directives.
  
 * Pragmaunroll directive unrolling loops to increase instruction-level parallelism.
  
 * Pragmavectorize directive vectorizing loops to utilize SIMD instructions.
  
 * Pragmapipeline directive pipelining computations to reduce overhead and latency.
  
 * Pragmataskq directive queuing tasks for asynchronous execution.
  
 * Pragmataskwait directive waiting for the completion of previously launched tasks.
  
 * Pragmaregion directive partitioning the iteration space of parallel loops.
  
 * Praggpu directive executing kernels on NVIDIA GPUs.
  
 * Pragmafpgnu directive specifying directives for NVIDIA Fermi PGU.
  
 * Pragmaintel directive integrating Intel MIC architecture support.
  
 * Pragmaopencl directive specifying OpenCL parallelism and heterogeneous computing directives.
  
 * Pragmaompdeclaretarget directive declaring target devices for OpenMP offloading.
  
 * Pragmaomptargetdirective specifying target devices for OpenMP offloading.
  
 * Pragmaopenmpparallel directive specifying parallel loops and task parallelism for OpenMP.
  
 * Pragmaopenmpscheduling directive scheduling parallel threads and tasks for OpenMP.
  
 * Pragmaopenmpthreadprivate directive privatizing variables within OpenMP parallel regions.
  
 * Pragmaopenmpteam directive teaming up threads within OpenMP parallel regions.
  
 * Pragmaopenmpatomic directive performing atomic operations within OpenMP parallel regions.
  
 * Pragmaopenmpbarrier directive synchronizing threads within OpenMP parallel regions.
  
 * Pragmaopenmpcritical directive protecting critical sections within OpenMP parallel regions.
  
 * Pragmaopenmpflush directive flushing the OpenMP runtime environment.
  
 * Pragmaopenmpmaster directive executing a block of code on the master thread.
  
 * Pragmaopenmpordered directive ordering iterations within OpenMP parallel loops.
  
 * Pragmaopenmpparallel directive specifying parallel loops and task parallelism for OpenMP.
  
 * Pragmaopensingle directive executing a block of code on a single thread.
  
 * Pragmaopenmptask directive launching tasks within OpenMP parallel regions.
  
 * Pragmaopenmptaskgroup directive grouping tasks within OpenMP parallel regions.
  
 * Pragmaopenmptaskloop directive looping over a range of iterations within OpenMP parallel regions.
  
 * Pragmaopenmptasksuspend directive suspending the execution of tasks within OpenMP parallel regions.
  
 * Pragmaopenmptaskyield directive yielding control back to the OpenMP runtime environment.
  
 * Pragmaopenmpsection directive dividing the iteration space of OpenMP parallel loops.
  
 * Pragmaopensimt directive simulating parallel execution for testing purposes.
  
 * Pragmaopensimd directive utilizing SIMD instructions within OpenMP parallel regions.
  
 * Pragmaopenmptargetteamsdistribute directive distributing loop iterations across teams of threads.
  
 * Pragmaopenmptaskdependency directive establishing dependencies between tasks within OpenMP parallel regions.
  
 * Pragmaopenmpuniform directive hinting the distribution of work among threads within OpenMP parallel regions.
  
 * Pragmaopenmpworkshare directive sharing work among threads within OpenMP parallel regions.
  
 * Pragmaassume directive assuming certain properties of a function or loop.
  
 * Pragmachunk directive reserving space for future compiler extensions.
  
 * Pragmaroots directive specifying roots of derivation for generic programming.
  
 * Pragmastrictfpmodel directive adhering strictly to IEEE floating-point standards.
  
 * Pragmaunroll directive unrolling loops to expose more instruction-level parallelism.
  
 * Pragmavectorize directive applying SIMD vectorization to loops.
  
 * Pragmavectorlength directive specifying the length of vectors for SIMD instructions.
  
 * Pragmaaligned directive aligning data structures to optimize memory accesses.
  
 * Pragmaalloc directive allocating memory with specified alignment requirements.
  
 * Pragmafreespecify directive freeing memory allocated with alloc.
  
 * Pragmaheap directive managing a pool of memory for efficient allocation.
  
 * Pragmaleanstackframe directive minimizing stack frame sizes for efficiency.
  
 * Pragmapackstackframes directive optimizing stack frame layouts for reduced size.
  
 * Pragmapadddiagnostics directive enhancing diagnostic capabilities of the compiler.
  
 * Pragmadisable directive selectively disabling optimization passes.
  
 * Pragmáximum directive setting upper bounds on resource utilization.
  
 * Pragmaoptlevel directive adjusting the aggressiveness of optimization strategies.
  
 * Pragmaperformance directive focusing optimizations on improving execution speed.
  
 * Pragmaprecision directive trading precision for increased performance.
  
 * Pragmaprofile directive generating profiling information for optimization guidance.
  
 * Pragmareschedule directive guiding the scheduler in choosing optimal schedules.
  
 * Pragmastaticassert directive statically verifying assertions at compile-time.
  
 * Pragmatune directive iteratively refining the optimization process.
  
 * Pragmaunsafe directive relaxing safety constraints for potentially improved performance.
  
 * Pragmaunswitch directive avoiding unnecessary switch statements.
  
 * Pragmavolatile directive treating certain variables as volatile.
  
 * Pragmawarning directive issuing warnings for potential issues or inefficiencies.
  
 * Pragmaunsafeinline directive inlining functions marked as unsafe.
  
 * Pragmaunpack directive unpacking packed data structures for easier access.
  
 * Pragmaversion directive specifying version numbers for compatibility.
  
 * Pragmawarnunused directive warning about unused variables or functions.
  
 * Pragmaunused directive indicating that a function or variable is unused.
  
 * Pragmaoptimize directive applying general optimizations to improve performance.
  
 * Pragmaparallelize directive parallelizing loops to leverage multi-core processors.
  
 * Pragmapipeline directive organizing computations into pipelines for efficiency.
  
 * Pragmasimd directive employing SIMD instructions for parallel processing.
  
 * Pragmaunroll directive unrolling loops to enhance instruction-level parallelism.
  
 * Pragmavectorize directive vectorizing loops to apply SIMD instructions.
  
 * Pragmastrict directive enforcing strict adherence to programming standards.
  
 * Pragmastringdirective specifying string literals as wide-character strings.
  
 * Pragmathreads directive managing threads and concurrency in the program.
  
 * Pragmaunsafe directive bypassing safety features for potentially improved performance.
  
 * Pragmaunwindprotect directive unwinding the call stack after an exception occurs.
  
 * Pragmavirtual_function_call directive specifying calls to virtual functions.
  
 * Pragmaweak_attribute directive weakening aliases to allow for redefinition.
  
 * Pragmaextension directive extending the language with custom syntax or semantics.
  
 * Pragmaexternal directive specifying external functions or variables.
  
 * Pragmaimport directive importing modules or interfaces from other languages.
  
 * Pragmalinkage directive linking against libraries or object files.
  
 * Pragmanamespace directive introducing namespaces for organizing declarations.
  
 * Pragmapackage directive aggregating related declarations into packages.
  
 * Pragmarelease directive releasing resources held by the program.
  
 * Pragmarequire directive acquiring resources needed by the program.
  
 * Pragmascope directive limiting the visibility of declarations to a specific scope.
  
 * Pragsuppress directive suppressing the emission of certain diagnostics.
  
 * Pragmasymbol directive specifying symbolic representations of addresses.
  
 * Pragtetra directive specifying tetrahedral mesh elements for geometric computations.
  
 * Pragmattribute directive attaching attributes to declarations for later reference.
  
 * Pragmaudt directive specifying user-defined types for generic programming.
  
 * Pragmavariable directive declaring variables with dynamically-determined types.
  
 * Pragmaversion directive specifying version numbers for backward compatibility.
  
 * Pragmaview directive presenting views of data structures for inspection.
  
 * Pragmawarning directive emitting warnings for potential problems or improvements.
  
 * Pragmaunsafe directive waiving safety guarantees for potentially enhanced performance.
  
 * Pragmaxpragma directive maximizing the usage of pragmas throughout the program.
  
 * Pragmaoption directive selecting options for the compiler or linker.
  
 * Pragramacro directive defining macros for text substitution.
  
 * Pragmainsert directive inserting code at arbitrary points in the program flow.
  
 * Pragmaleftmargin directive placing code at the left margin of the page.
  
 * Pragrightrmargin directive placing code at the right margin of the page.
  
 * Pragmaleftshift directive shifting the left margin of the page.
  
 * Pragramargin directive specifying command-line arguments to the program.
  
 * Pragrautoconf directive configuring the build system automatically.
  
 * Pragmabuild directive building the project according to the configuration.
  
 * Pragmaconfigure directive configuring the build system manually.
  
 * Pragmacleandef directive cleaning up intermediate build artifacts.
  
 * Pragmacontentassist directive assisting content creation and editing.
  
 * Pragmacontinuation directive continuing interrupted builds seamlessly.
  
 * Pragmadependencies directive analyzing dependencies between source files.
  
 * Pragmaexport directive exporting build configurations for reuse.
  
 * Pragmahelp directive displaying help messages for users.
  
 * Pragmaimplements directive implementing build rules and actions.
  
 * Pragmainclude directive including additional headers or sources in the build.
  
 * Pragmake directive running the build system to generate executables.
  
 * Pragmanamespace directive mapping namespaces to physical locations.
  
 * Pragmaparseargs directive parsing command-line arguments for build options.
  
 * Pragmaplugin directive plugging in external tools and services.
  
 * Pragmaprebuild directive rebuilding the project from scratch.
  
 * Pragmareport directive reporting build progress and statistics.
  
 * Pragmarules directive specifying customized build rules and actions.
  
 * Pragmasave directive saving the build state for incremental rebuilds.
  
 * Pragmaswitches directive switching between different build configurations.
  
 * Pragmavcs directive interacting with version control systems.
  
 * Pragmaversion directive tracking changes and updates to the build configuration.
  
 * Pragmavisualize directive visualizing build processes and dependencies.
  
 * Pragmaweb directive publishing build artifacts on the web.
  
 * Pragmaxml directive generating XML-based reports and documentation.
  
 * Pragmazip directive compressing and packaging build outputs for distribution.
  
 * Exitstatus directive specifying exit codes for abnormal termination.
  
 * Assert directive checking assumptions about the program state.
  
 * Static_assert directive checking constant expressions at compile-time.
  
 * Debug directive activating debug mode and associated diagnostics.
  
 * Errordirective reporting error messages and halting execution.
  
 * Errorhandler directive installing custom handlers for runtime errors.
  
 * Exit directive exiting the program prematurely.
  
 * Halt directive stopping the program execution abruptly.
  
 * Return directive returning control to the calling routine.
  
 * Stop directive pausing execution temporarily.
  
 * Trace directive tracing execution and recording coverage metrics.
  
 * Unimplemented directive signaling unimplemented functionalities.
  
 * Undeff directive undeclaring external functions or variables.
  
 * Unlink directive unlinking object files or libraries.
  
 * Unlock directive releasing locked resources and Critical Sections.
  
 * Unregister directive unregistering external functions or variables.
  
 * Unset directive unsetting environmental variables or switches.
  
 * Untypedef directive undefining typedef names.
  
 * Until directive repeating a statement until a condition is met.
  
 * Use directive bringing declarations into the current scope.
  
 * Using directive importing namespaces or scopes.
  
 * VaryING directive varying the appearance of output based on verbosity levels.
  
 * Verify directive verifying assumptions about the program state.
  
 * Version directive specifying version numbers for compatibility.
  
 * Wait directive waiting for events, signals, or timeouts.
  
 * Wchar_t directive specifying wide character types and literals.
  
 * While directive repeatedly executing a statement while a condition holds.
  
 * Xor directive performing bitwise exclusive-or operations.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      const T& dataForCurrentDeviceAsync(hipStream_t cudaStream, F transferAsync) const {
        int device = currentDevice();
        auto& data = gpuDataPerDevice_[device];

        // If GPU data has already been filled, we can return it immediately
        if (not data.m_filled.load()) {
          // It wasn't, so need to fill it
          std::scoped_lock<std::mutex> lk{data.m_mutex};

          if (data.m_filled.load()) {
            // Other thread marked it filled while we were locking the mutex, so we're free to return it
            return data.m_data;
          }

          if (data.m_fillingStream != nullptr) {
            // Someone else is filling

            // Check first if the recorded event has occurred
            if (eventWorkHasCompleted(data.m_event.get())) {
              // It was, so data is accessible from all CUDA streams on
              // the device. Set the 'filled' for all subsequent calls and
              // return the value
              auto should_be_false = data.m_filled.exchange(true);
              assert(not should_be_false);
              data.m_fillingStream = nullptr;
            } else if (data.m_fillingStream != cudaStream) {
              // Filling is still going on. For other CUDA stream, add
              // wait on the CUDA stream and return the value. Subsequent
              // work queued on the stream will wait for the event to
              // occur (i.e. transfer to finish).
              cudaCheck(hipStreamWaitEvent(cudaStream, data.m_event.get(), 0),
                        "Failed to make a stream to wait for an event");
            }
            // else: filling is still going on. But for the same CUDA
            // stream (which would be a bit strange but fine), we can just
            // return as all subsequent work should be enqueued to the
            // same CUDA stream (or stream to be explicitly synchronized
            // by the caller)
          } else {
            // Now we can be sure that the data is not yet on the GPU, and
            // this thread is the first to try that.
            transferAsync(data.m_data, cudaStream);
            assert(data.m_fillingStream == nullptr);
            data.m_fillingStream = cudaStream;
            // Record in the cudaStream an event to mark the readiness of the
            // EventSetup data on the GPU, so other streams can check for it
            cudaCheck(hipEventRecord(data.m_event.get(), cudaStream));
            // Now the filling has been enqueued to the cudaStream, so we
            // can return the GPU data immediately, since all subsequent
            // work must be either enqueued to the cudaStream, or the cudaStream
            // must be synchronized by the caller
          }
        }

        return data.m_data;
      }

    private:
      struct Item {
        mutable std::mutex m_mutex;
        mutable SharedEventPtr m_event;  // guarded by m_mutex
        // non-null if some thread is already filling (hipStream_t is just a pointer)
        mutable hipStream_t m_fillingStream = nullptr;  // guarded by m_mutex
        mutable std::atomic<bool> m_filled = false;     // easy check if data has been filled already or not
        mutable T m_data;                               // guarded by m_mutex
      };

      std::vector<Item> gpuDataPerDevice_;
    };
  }  // namespace hip
}  // namespace cms

#endif  // HeterogeneousCore_CUDACore_ESProduct_h
