#ifndef HeterogeneousCore_CUDAUtilities_interface_host_unique_ptr_h
#define HeterogeneousCore_CUDAUtilities_interface_host_unique_ptr_h

#include <memory>
#include <functional>

#include "CUDACore/allocate_host.h"

namespace cms {
  namespace hip {
    namespace host {
      namespace impl {
        // Additional layer of types to distinguish from host::unique_ptr
        class HostDeleter {
        public:
          void operator()(void *ptr) { cms::hip::free_host(ptr); }
        };
      }  // namespace impl

      template <typename T>
      using unique_ptr = std::unique_ptr<T, impl::HostDeleter>;

      namespace impl {
        template <typename T>
        struct make_host_unique_selector {
          using non_array = cms::hip::host::unique_ptr<T>;
        };
        template <typename T>
        struct make_host_unique_selector<T[]> {
          using unbounded_array = cms::hip::host::unique_ptr<T[]>;
        };
        template <typename T, size_t N>
        struct make_host_unique_selector<T[N]> {
          struct bounded_array {};
        };
      }  // namespace impl
    }    // namespace host

    // Allocate pinned host memory
    template <typename T>
/**
 * @brief Creates a unique selector for a host object of type T on the specified stream.
 *
 * @tparam T Type of the object to be created.
 *
 * @param stream The hipStream_t where the object will be allocated.
 *
 * @return A unique selector for the newly allocated object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    typename host::impl::make_host_unique_selector<T>::non_array make_host_unique(hipStream_t stream) {
      static_assert(std::is_trivially_constructible<T>::value,
                    "Allocating with non-trivial constructor on the pinned host memory is not supported");
      void *mem = allocate_host(sizeof(T), stream);
      return typename host::impl::make_host_unique_selector<T>::non_array{reinterpret_cast<T *>(mem)};
    }

    template <typename T>
/**
 * Brief description: Creates an unbounded array on the host with the specified number of elements and stream.
 *
 * Detailed description: Allocates memory for the array on the host, checks if the element type has a trivial constructor,
 *                  and returns an unbounded array object wrapping the allocated memory.
 *
 * Parameters:
 *   n        - The number of elements in the array.
 *   stream   - The HIP stream associated with the memory allocation.
 *
 * Returns:
 *   An unbounded array object representing the allocated memory on the host.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    typename host::impl::make_host_unique_selector<T>::unbounded_array make_host_unique(size_t n, hipStream_t stream) {
      using element_type = typename std::remove_extent<T>::type;
      static_assert(std::is_trivially_constructible<element_type>::value,
                    "Allocating with non-trivial constructor on the pinned host memory is not supported");
      void *mem = allocate_host(n * sizeof(element_type), stream);
      return typename host::impl::make_host_unique_selector<T>::unbounded_array{reinterpret_cast<element_type *>(mem)};
    }

    template <typename T, typename... Args>
    typename host::impl::make_host_unique_selector<T>::bounded_array make_host_unique(Args &&...) = delete;

    // No check for the trivial constructor, make it clear in the interface
    template <typename T>
/**
 * @brief Creates a unique selector for an uninitialized object of type T on the host.
 *
 * @param stream The HIP stream used for memory allocation.
 * @return A non-array unique selector for the allocated object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    typename host::impl::make_host_unique_selector<T>::non_array make_host_unique_uninitialized(hipStream_t stream) {
      void *mem = allocate_host(sizeof(T), stream);
      return typename host::impl::make_host_unique_selector<T>::non_array{reinterpret_cast<T *>(mem)};
    }

    template <typename T>
/**
 * @brief Creates an unbounded array of uninitialized elements on the host.
 *
 * @tparam T Type of elements in the array.
 * @param n Number of elements in the array.
 * @param stream HIP stream used for memory allocation.
 * @return Unbounded array of uninitialized elements.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    typename host::impl::make_host_unique_selector<T>::unbounded_array make_host_unique_uninitialized(
        size_t n, hipStream_t stream) {
      using element_type = typename std::remove_extent<T>::type;
      void *mem = allocate_host(n * sizeof(element_type), stream);
      return typename host::impl::make_host_unique_selector<T>::unbounded_array{reinterpret_cast<element_type *>(mem)};
    }

    template <typename T, typename... Args>
    typename host::impl::make_host_unique_selector<T>::bounded_array make_host_unique_uninitialized(Args &&...) = delete;
  }  // namespace hip
}  // namespace cms

#endif
