#ifndef SYCLDataFormats_BeamSpot_interface_BeamSpotSYCL_h
#define SYCLDataFormats_BeamSpot_interface_BeamSpotSYCL_h

#include <sycl/sycl.hpp>

#include "DataFormats/BeamSpotPOD.h"
#include "SYCLCore/device_unique_ptr.h"

/**
 * @brief Class representing a beam spot in the SYCL framework
 * 
 * @details This class provides a interface for managing beam spot data on a SYCL device
 *         It includes constructors for creating instances with or without a specified SYCL queue
 *         The class is designed to be movable but non-copiable
 *         It offers methods for accessing the underlying beam spot data and its unique pointer
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
class BeamSpotSYCL {
public:
  // default constructor, required by cms::sycltools::Product<BeamSpotSYCL>
  BeamSpotSYCL() = default;

  // constructor that allocates cached device memory on the given SYCL queue
  BeamSpotSYCL(sycl::queue stream) { data_d_ = cms::sycltools::make_device_unique<BeamSpotPOD>(stream); }

  // movable, non-copiable
  BeamSpotSYCL(BeamSpotSYCL const&) = delete;
  BeamSpotSYCL(BeamSpotSYCL&&) = default;
  BeamSpotSYCL& operator=(BeamSpotSYCL const&) = delete;
  BeamSpotSYCL& operator=(BeamSpotSYCL&&) = default;

  BeamSpotPOD* data() { return data_d_.get(); }
  BeamSpotPOD const* data() const { return data_d_.get(); }

  cms::sycltools::device::unique_ptr<BeamSpotPOD>& ptr() { return data_d_; }
  cms::sycltools::device::unique_ptr<BeamSpotPOD> const& ptr() const { return data_d_; }

private:
  cms::sycltools::device::unique_ptr<BeamSpotPOD> data_d_;
};

#endif  // SYCLDataFormats_BeamSpot_interface_BeamSpotSYCL_h
