#include "SYCLDataFormats/TrackingRecHit2DSYCL.h"
#include "SYCLCore/device_unique_ptr.h"
#include "SYCLCore/host_unique_ptr.h"


// The following comment is generated by an LLM. 
/**
 * Returns a unique pointer to an array of floats representing local coordinates 
 * transferred from device to host asynchronously.
 *
 * @return Unique pointer to float array
 */ 
cms::sycltools::host::unique_ptr<float[]> TrackingRecHit2DSYCL::localCoordToHostAsync(sycl::queue stream) const {
  auto ret = cms::sycltools::make_host_unique<float[]>(4 * nHits(), stream);
  stream.memcpy(ret.get(), m_store32.get(), 4 * nHits() * sizeof(float));
  return ret;
}


// The following comment is generated by an LLM. 
/**
 * Returns a unique pointer to an array of hits module start data transferred from device to host asynchronously.
 *
 * @param stream The sycl queue object used for asynchronous memory transfer.
 * @return A unique pointer to an array of hits module start data on the host.
 */ 
cms::sycltools::host::unique_ptr<uint32_t[]> TrackingRecHit2DSYCL::hitsModuleStartToHostAsync(sycl::queue stream) const {
  auto ret = cms::sycltools::make_host_unique<uint32_t[]>(2001, stream);
  stream.memcpy(ret.get(), m_hitsModuleStart, 4 * 2001 * sizeof(uint32_t));
  return ret;
}


// The following comment is generated by an LLM. 
/**
 * Returns a unique pointer to an array of floats representing global coordinates 
 * asynchronously copied from device to host memory.
 *
 * @return Unique pointer to float array
 */ 
cms::sycltools::host::unique_ptr<float[]> TrackingRecHit2DSYCL::globalCoordToHostAsync(sycl::queue stream) const {
  auto ret = cms::sycltools::make_host_unique<float[]>(4 * nHits(), stream);
  stream.memcpy(ret.get(), m_store32.get() + 4 * nHits(), 4 * nHits() * sizeof(float));
  return ret;
}


// The following comment is generated by an LLM. 
/**
 * Returns a unique pointer to an array of integers representing tracking rec hits 
 * asynchronously copied from device to host memory.
 *
 * @return Unique pointer to an array of integers
 */ 
cms::sycltools::host::unique_ptr<int32_t[]> TrackingRecHit2DSYCL::chargeToHostAsync(sycl::queue stream) const {
  auto ret = cms::sycltools::make_host_unique<int32_t[]>(nHits(), stream);
  stream.memcpy(ret.get(), m_store32.get() + 8 * nHits(), nHits() * sizeof(int32_t));
  return ret;
}


// The following comment is generated by an LLM. 
/**
 * Returns a unique pointer to an array of int16_t values representing tracking rec hits in host memory.
 * The size of the array is determined by the number of hits.
 * The data is copied from device memory to host memory asynchronously using the provided queue.
 *
 * @return A unique pointer to an array of int16_t values
 */ 
cms::sycltools::host::unique_ptr<int16_t[]> TrackingRecHit2DSYCL::sizeToHostAsync(sycl::queue stream) const {
  auto ret = cms::sycltools::make_host_unique<int16_t[]>(2 * nHits(), stream);
  stream.memcpy(ret.get(), m_store16.get() + 2 * nHits(), 2 * nHits() * sizeof(int16_t));
  return ret;
}
