#ifndef HeterogeneousCore_CUDAUtilities_ScopedSetDevice_h
#define HeterogeneousCore_CUDAUtilities_ScopedSetDevice_h

#include "CUDACore/cudaCheck.h"

#include <cuda_runtime.h>

namespace cms {
  namespace cuda {
    class ScopedSetDevice {
    public:
/**
 * Brief description: A helper function to set the CUDA device.
 *
 * Detailed description: This function sets the CUDA device to the specified new device,
 *                      storing the previous device for later restoration.
 *
 * Parameters:
 *   newDevice - The new CUDA device to be set.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      explicit ScopedSetDevice(int newDevice) {
        cudaCheck(cudaGetDevice(&prevDevice_));
        cudaCheck(cudaSetDevice(newDevice));
      }

/**
 * Destructor to restore previous CUDA device setting after scoped set operation * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      ~ScopedSetDevice() {
        // Intentionally don't check the return value to avoid
        // exceptions to be thrown. If this call fails, the process is
        // doomed anyway.
        cudaSetDevice(prevDevice_);
      }

    private:
      int prevDevice_;
    };
  }  // namespace cuda
}  // namespace cms

#endif
