#include "gpuClusterTracksByDensity.h"
#include "gpuClusterTracksDBSCAN.h"
#include "gpuClusterTracksIterative.h"
#include "gpuFitVertices.h"
#include "gpuSortByPt2.h"
#include "gpuSplitVertices.h"

namespace gpuVertexFinder {

/**
 * Brief description of the function loadTracks 
  
 * @brief Loads tracks into the provided vertex SoA and workspace structures.
 * 
 * This function takes in a pointer to an array of tracks, a vertex SoA, 
 * a workspace, and a minimum transverse momentum threshold.
 * It iterates over the tracks, filters out those that do not meet certain criteria,
 * and populates the vertex SoA and workspace with relevant track information.
 * 
 * @param ptracks Pointer to an array of tracks
 * @param soa Vertex SoA to populate
 * @param pws Workspace to populate
 * @param ptMin Minimum transverse momentum threshold
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  void loadTracks(TkSoA const* ptracks, ZVertexSoA* soa, WorkSpace* pws, float ptMin) {
    assert(ptracks);
    assert(soa);
    auto const& tracks = *ptracks;
    auto const& fit = tracks.stateAtBS;
    auto const* quality = tracks.qualityData();

    int nt = TkSoA::stride();
#pragma omp target teams distribute parallel for map(tofrom:soa[:1],pws[:1]) map(to:quality[:pixelTrack::maxNumber()])
    for (int idx = 0; idx < nt; idx++) {
      auto nHits = tracks.nHits(idx);
      if (nHits == 0)
        continue;
        //break;  // this is a guard: maybe we need to move to nTracks...


      // initialize soa...
      soa->idv[idx] = -1;

      if (nHits < 4)
        continue;  // no triplets
      if (quality[idx] != trackQuality::loose)
        continue;

      auto pt = tracks.pt(idx);

      if (pt < ptMin)
        continue;

      auto& data = *pws;
      //auto it = atomicAdd(&data.ntrks, 1);
      uint32_t it;
#pragma omp atomic capture
      it = data.ntrks++;

      data.itrk[it] = idx;
      data.zt[it] = tracks.zip(idx);
      data.ezt2[it] = fit.covariance(idx)(14);
      data.ptt2[it] = pt * pt;
    }
  }

// #define THREE_KERNELS
#ifndef THREE_KERNELS
/**
 * Brief description of the function vertexFinderOneKernel
 *
 * Detailed description of the function vertexFinderOneKernel which finds vertices
 * using one kernel with parameters pdata, pws, minT, eps, errmax and chi2max
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  void vertexFinderOneKernel(gpuVertexFinder::ZVertices* pdata,
                             gpuVertexFinder::WorkSpace* pws,
                             int minT,      // min number of neighbours to be "seed"
                             float eps,     // max absolute distance to cluster
                             float errmax,  // max error to be "seed"
                             float chi2max  // max normalized distance to cluster,
  ) {
    clusterTracksByDensity(pdata, pws, minT, eps, errmax, chi2max);

    fitVertices(pdata, pws, 50.);

    splitVertices(pdata, pws, 9.f);

    fitVertices(pdata, pws, 5000.);

    sortByPt2(pdata, pws);
  }
#else
/**
 * Brief description of the function
 *
 * This function implements the first stage of the vertex finding process
 * It takes in input data and workspace pointers along with several parameters
 * and performs clustering and fitting operations to identify vertices
 *
 * Parameters:
 *   pdata       Pointer to the input vertex data
 *   pws        Pointer to the workspace data
 *   minT       Minimum number of neighbors required to be considered a seed
 *   eps        Maximum absolute distance to consider a point part of a cluster
 *   errmax     Maximum error allowed to consider a point part of a cluster
 *   chi2max    Maximum normalized distance to consider a point part of a cluster
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  void vertexFinderKernel1(gpuVertexFinder::ZVertices* pdata,
                           gpuVertexFinder::WorkSpace* pws,
                           int minT,      // min number of neighbours to be "seed"
                           float eps,     // max absolute distance to cluster
                           float errmax,  // max error to be "seed"
                           float chi2max  // max normalized distance to cluster,
  ) {
    clusterTracksByDensity(pdata, pws, minT, eps, errmax, chi2max);

    fitVertices(pdata, pws, 50.);
  }

/**
 * Brief description of function vertexFinderKernel2 
 * Detailed description of function vertexFinderKernel2 
 * @param pdata pointer to ZVertices data
 * @param pws pointer to WorkSpace data
 * @return none
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  void vertexFinderKernel2(gpuVertexFinder::ZVertices* pdata, gpuVertexFinder::WorkSpace* pws) {
    fitVertices(pdata, pws, 5000.);

    sortByPt2(pdata, pws);
  }
#endif

/**
 * Brief description of the class 
   * Detailed description of the class 
 * This class appears to be responsible for producing heterogeneous vertices 
 * from track information and applying various clustering algorithms 
 * to group tracks into vertices It utilizes different methods such 
 * as density-based clustering DBSCAN and iterative approaches 
 * to achieve this goal The produced vertices are then fitted and sorted 
 * according to their transverse momentum 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  ZVertexHeterogeneous Producer::make(TkSoA const* tksoa, float ptMin) const {
    // std::cout << "producing Vertices on  CPU" <<    std::endl;
    ZVertexHeterogeneous vertices(std::make_unique<ZVertexSoA>());
    assert(tksoa);
    auto* soa = vertices.get();
    assert(soa);

    auto ws_d = std::make_unique<WorkSpace>();

    init(soa, ws_d.get());
    loadTracks(tksoa, soa, ws_d.get(), ptMin);

    if (useDensity_) {
      clusterTracksByDensity(soa, ws_d.get(), minT, eps, errmax, chi2max);
    } else if (useDBSCAN_) {
      clusterTracksDBSCAN(soa, ws_d.get(), minT, eps, errmax, chi2max);
    } else if (useIterative_) {
      clusterTracksIterative(soa, ws_d.get(), minT, eps, errmax, chi2max);
    }
    // std::cout << "found " << (*ws_d).nvIntermediate << " vertices " << std::endl;
    fitVertices(soa, ws_d.get(), 50.);
    // one block per vertex!
    splitVertices(soa, ws_d.get(), 9.f);
    fitVertices(soa, ws_d.get(), 5000.);
    sortByPt2(soa, ws_d.get());

    return vertices;
  }

}  // namespace gpuVertexFinder

#undef FROM
