#ifndef RecoLocalTracker_SiPixelClusterizer_SiPixelROCsStatusAndMappingWrapper_h
#define RecoLocalTracker_SiPixelClusterizer_SiPixelROCsStatusAndMappingWrapper_h

#include "CUDACore/ESProduct.h"
#include "CUDACore/HostAllocator.h"
#include "CUDACore/device_unique_ptr.h"
#include "CondFormats/SiPixelROCsStatusAndMapping.h"

#include <cuda_runtime.h>

#include <set>

/**
 * @brief Class representing a wrapper for ROCs status and mapping data.
 *
 * This class provides functionality for managing ROCs status and mapping data,
 * including handling quality information and accessing GPU memory.
 
class SiPixelROCsStatusAndMappingWrapper {
     * @brief Constructor for initializing the wrapper with ROCs status and mapping data.
   *
   * @param cablingMap The input ROCs status and mapping data.
   * @param modToUnp A vector of module unpacking information.
   
  explicit SiPixelROCsStatusAndMappingWrapper(SiPixelROCsStatusAndMapping const &cablingMap,
                                              std::vector<unsigned char> modToUnp);

     * @brief Destructor for releasing resources held by the wrapper.
   
  ~SiPixelROCsStatusAndMappingWrapper();

     * @brief Checks if quality information is available.
   *
   * @return True if quality information is present, false otherwise.
   
  bool hasQuality() const { return hasQuality_; }

     * @brief Retrieves a pointer to the ROCs status and mapping data on the GPU.
   *
   * @param cudaStream The CUDA stream for asynchronous access.
   * @return A pointer to the ROCs status and mapping data on the GPU.
   
  const SiPixelROCsStatusAndMapping *getGPUProductAsync(cudaStream_t cudaStream) const;

     * @brief Retrieves a pointer to the module unpacking data on the GPU.
   *
   * @param cudaStream The CUDA stream for asynchronous access.
   * @return A pointer to the module unpacking data on the GPU.
   
  const unsigned char *getModToUnpAllAsync(cudaStream_t cudaStream) const;

private:
     * @brief Default module unpacking data stored on the host.
   
  std::vector<unsigned char, cms::cuda::HostAllocator<unsigned char>> modToUnpDefault;

     * @brief Flag indicating presence of quality information.
   
  bool hasQuality_;

     * @brief Pointer to the ROCs status and mapping data structure on the host.
   
  SiPixelROCsStatusAndMapping *cablingMapHost;

     * @brief Structure containing GPU-specific data for the wrapper.
   
  struct GPUData {
         * @brief Destructor for releasing GPU resources.
     
    ~GPUData();

         * @brief Pointer to the ROCs status and mapping data structure on the GPU.
     
    SiPixelROCsStatusAndMapping *cablingMapDevice;
  };

     * @brief Managed product for storing GPUData instances.
   
  cms::cuda::ESProduct<GPUData> gpuData_;

     * @brief Structure containing module unpacking data on the GPU.
   
  struct ModulesToUnpack {
         * @brief Destructor for releasing GPU resources.
     
    ~ModulesToUnpack();

         * @brief Pointer to the module unpacking data on the GPU.
     
    unsigned char *modToUnpDefault;
  };

     * @brief Managed product for storing ModulesToUnpack instances.
   
  cms::cuda::ESProduct<ModulesToUnpack> modToUnp_;
}* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
class SiPixelROCsStatusAndMappingWrapper {
public:
  explicit SiPixelROCsStatusAndMappingWrapper(SiPixelROCsStatusAndMapping const &cablingMap,
                                              std::vector<unsigned char> modToUnp);
  ~SiPixelROCsStatusAndMappingWrapper();

  bool hasQuality() const { return hasQuality_; }

  // returns pointer to GPU memory
  const SiPixelROCsStatusAndMapping *getGPUProductAsync(cudaStream_t cudaStream) const;

  // returns pointer to GPU memory
  const unsigned char *getModToUnpAllAsync(cudaStream_t cudaStream) const;

private:
  std::vector<unsigned char, cms::cuda::HostAllocator<unsigned char>> modToUnpDefault;
  bool hasQuality_;

  SiPixelROCsStatusAndMapping *cablingMapHost = nullptr;  // pointer to struct in CPU

  struct GPUData {
    ~GPUData();
    SiPixelROCsStatusAndMapping *cablingMapDevice = nullptr;  // pointer to struct in GPU
  };
  cms::cuda::ESProduct<GPUData> gpuData_;

  struct ModulesToUnpack {
    ~ModulesToUnpack();
    unsigned char *modToUnpDefault = nullptr;  // pointer to GPU
  };
  cms::cuda::ESProduct<ModulesToUnpack> modToUnp_;
};

#endif
