#ifndef RecoLocalTracker_SiPixelClusterizer_SiPixelROCsStatusAndMappingWrapper_h
#define RecoLocalTracker_SiPixelClusterizer_SiPixelROCsStatusAndMappingWrapper_h

#include "CUDACore/ESProduct.h"
#include "CUDACore/HostAllocator.h"
#include "CUDACore/device_unique_ptr.h"
#include "CondFormats/SiPixelROCsStatusAndMapping.h"

#include <cuda_runtime.h>

#include <set>

/**
 * @brief Wrapper class for managing SiPixelROCsStatusAndMapping data on GPU.
 *
 * This class provides functionality for transferring SiPixelROCsStatusAndMapping data to GPU memory
 * and accessing it asynchronously. It also manages the lifetime of the GPU memory.
 
class SiPixelROCsStatusAndMappingWrapper {
     * @brief Constructor for initializing the wrapper with SiPixelROCsStatusAndMapping data and module unpacking information.
   *
   * @param cablingMap The input SiPixelROCsStatusAndMapping data.
   * @param modToUnp Vector of module unpacking information.
   
  explicit SiPixelROCsStatusAndMappingWrapper(SiPixelROCsStatusAndMapping const &cablingMap, std::vector<unsigned char> modToUnp);
   * @brief Destructor for releasing allocated resources.
   
  ~SiPixelROCsStatusAndMappingWrapper();
   * @brief Checks if quality information is available.
   *
   * @return True if quality information is available, false otherwise.
   
  bool hasQuality() const;
   * @brief Returns a pointer to the SiPixelROCsStatusAndMapping data on the GPU.
   *
   * @param cudaStream The CUDA stream for asynchronous access.
   * @return Pointer to the SiPixelROCsStatusAndMapping data on the GPU.
   
  const SiPixelROCsStatusAndMapping *getGPUProductAsync(cudaStream_t cudaStream) const;
   * @brief Returns a pointer to the module unpacking information on the GPU.
   *
   * @param cudaStream The CUDA stream for asynchronous access.
   * @return Pointer to the module unpacking information on the GPU.
   
  const unsigned char *getModToUnpAllAsync(cudaStream_t cudaStream) const;

 private:   * @brief Default module unpacking information stored on the host.
   
  std::vector<unsigned char, cms::cuda::HostAllocator<unsigned char>> modToUnpDefault;
   * @brief Flag indicating availability of quality information.
   
  bool hasQuality_;
   * @brief Pointer to the SiPixelROCsStatusAndMapping data on the host.
   
  SiPixelROCsStatusAndMapping *cablingMapHost;
   * @brief Struct representing GPU data for SiPixelROcsStatusAndMapping.
   
  struct GPUData {
         * @brief Destructor for releasing GPU resources.
     
    ~GPUData();
     * @brief Pointer to the SiPixelROCsStatusAndMapping data on the GPU.
     
    SiPixelROCsStatusAndMapping *cablingMapDevice;
  };
   * @brief Managed GPU data product for SiPixelROCsStatusAndMapping.
   
  cms::cuda::ESProduct<GPUData> gpuData_;
   * @brief Struct representing module unpacking information on the GPU.
   
  struct ModulesToUnpack {
         * @brief Destructor for releasing GPU resources.
     
    ~ModulesToUnpack();
     * @brief Pointer to the module unpacking information on the GPU.
     
    unsigned char *modToUnpDefault;
  };
   * @brief Managed GPU data product for module unpacking information.
   
  cms::cuda::ESProduct<ModulesToUnpack> modToUnp_;
}* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
class SiPixelROCsStatusAndMappingWrapper {
public:
  explicit SiPixelROCsStatusAndMappingWrapper(SiPixelROCsStatusAndMapping const &cablingMap,
                                              std::vector<unsigned char> modToUnp);
  ~SiPixelROCsStatusAndMappingWrapper();

  bool hasQuality() const { return hasQuality_; }

  // returns pointer to GPU memory
  const SiPixelROCsStatusAndMapping *getGPUProductAsync(cudaStream_t cudaStream) const;

  // returns pointer to GPU memory
  const unsigned char *getModToUnpAllAsync(cudaStream_t cudaStream) const;

private:
  std::vector<unsigned char, cms::cuda::HostAllocator<unsigned char>> modToUnpDefault;
  bool hasQuality_;

  SiPixelROCsStatusAndMapping *cablingMapHost = nullptr;  // pointer to struct in CPU

  struct GPUData {
    ~GPUData();
    SiPixelROCsStatusAndMapping *cablingMapDevice = nullptr;  // pointer to struct in GPU
  };
  cms::cuda::ESProduct<GPUData> gpuData_;

  struct ModulesToUnpack {
    ~ModulesToUnpack();
    unsigned char *modToUnpDefault = nullptr;  // pointer to GPU
  };
  cms::cuda::ESProduct<ModulesToUnpack> modToUnp_;
};

#endif
