#ifndef RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h
#define RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h

#include "SYCLCore/ESProduct.h"
#include "SYCLCore/device_unique_ptr.h"
#include "CondFormats/SiPixelFedCablingMapGPU.h"

#include <sycl/sycl.hpp>

#include <set>

/**
 * @brief Wrapper class for managing SiPixelFedCablingMapGPU data on both host and device.
 *
 * This class provides functionality for handling SiPixelFedCablingMapGPU objects,
 * including asynchronous access to GPU memory and management of associated data.
 
class SiPixelFedCablingMapGPUWrapper {
     * @brief Constructor for initializing the wrapper with a cabling map and module unpacking data.
   *
   * @param cablingMap The input cabling map object.
   * @param modToUnp Vector of module unpacking data.
   
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap,
                                        std::vector<unsigned char> modToUnp);
   * @brief Destructor for releasing resources allocated by the wrapper.
   
  ~SiPixelFedCablingMapGPUWrapper();
   * @brief Checks if quality data is available.
   *
   * @return True if quality data exists, false otherwise.
   
  bool hasQuality() const { return hasQuality_; }
   * @brief Asynchronously retrieves a pointer to the GPU product.
   *
   * @param stream The sycl queue for asynchronous operations.
   * @return Pointer to the GPU product.
   
  const SiPixelFedCablingMapGPU *getGPUProductAsync(sycl::queue stream) const;
   * @brief Asynchronously retrieves a pointer to all module unpacking data on the GPU.
   *
   * @param stream The sycl queue for asynchronous operations.
   * @return Pointer to the module unpacking data on the GPU.
   
  const unsigned char *getModToUnpAllAsync(sycl::queue stream) const;

private:   * @brief Default module unpacking data stored on the host.
   
  std::vector<unsigned char> modToUnpDefault;
   * @brief Flag indicating availability of quality data.
   
  bool hasQuality_;
   * @brief Host-side pointer to the cabling map structure.
   
  SiPixelFedCablingMapGPU *cablingMapHost_ = nullptr;
   * @brief Structure containing device-specific data for the cabling map.
   
  struct GPUData {
         * @brief Default constructor.
     
    GPUData() = default;

         * @brief Destructor.
     
    ~GPUData() {}
     * @brief Unique pointer to the cabling map structure on the device.
     
    cms::sycltools::device::unique_ptr<SiPixelFedCablingMapGPU> cablingMapDevice;
  };
   * @brief ESProduct instance for managing GPUData across devices.
   
  cms::sycltools::ESProduct<GPUData> gpuData_;
   * @brief Structure containing device-specific module unpacking data.
   
  struct ModulesToUnpack {
         * @brief Default constructor.
     
    ModulesToUnpack() = default;

         * @brief Destructor.
     
    ~ModulesToUnpack(){}
     * @brief Unique pointer to the module unpacking data on the device.
     
    cms::sycltools::device::unique_ptr<unsigned char[]> modToUnpDefault;
  };
   * @brief ESProduct instance for managing module unpacking data across devices.
   
  cms::sycltools::ESProduct<ModulesToUnpack> modToUnp_;
}* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
class SiPixelFedCablingMapGPUWrapper {
public:
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap,
                                          std::vector<unsigned char> modToUnp);
  ~SiPixelFedCablingMapGPUWrapper();

  bool hasQuality() const { return hasQuality_; }

  // returns pointer to GPU memory
  const SiPixelFedCablingMapGPU *getGPUProductAsync(sycl::queue stream) const;

  // returns pointer to GPU memory
  const unsigned char *getModToUnpAllAsync(sycl::queue stream) const;

private:
  std::vector<unsigned char> modToUnpDefault;
  bool hasQuality_;

  SiPixelFedCablingMapGPU *cablingMapHost_ = nullptr;  // pointer to struct in CPU

  struct GPUData {
    GPUData() = default;
    ~GPUData() {}

    cms::sycltools::device::unique_ptr<SiPixelFedCablingMapGPU> cablingMapDevice;  // pointer to struct in GPU
  };
  cms::sycltools::ESProduct<GPUData> gpuData_;

  struct ModulesToUnpack {
    ModulesToUnpack() = default;
    ~ModulesToUnpack(){};

    cms::sycltools::device::unique_ptr<unsigned char[]> modToUnpDefault;  // pointer to GPU
  };
  cms::sycltools::ESProduct<ModulesToUnpack> modToUnp_;
};

#endif
