#ifndef RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h
#define RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h

#include "SYCLCore/ESProduct.h"
#include "SYCLCore/device_unique_ptr.h"
#include "CondFormats/SiPixelFedCablingMapGPU.h"

#include <sycl/sycl.hpp>

#include <set>

/**
 * @brief Wrapper class for managing SiPixelFedCablingMapGPU data on GPU
 *
 * This class provides functionality for handling SiPixelFedCablingMapGPU data on the GPU,
 * including asynchronous access to the data and management of related resources.
 
class SiPixelFedCablingMapGPUWrapper {
     * @brief Constructor for initializing the wrapper with cabling map and module unpacking data
   *
   * Initializes the wrapper with the provided cabling map and module unpacking data.
   * @param cablingMap The input cabling map data
   * @param modToUnp Module unpacking data
   
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap, std::vector<unsigned char> modToUnp);
   * @brief Destructor for releasing allocated resources
   
  ~SiPixelFedCablingMapGPUWrapper();
   * @brief Checks if quality data is available
   *
   * Returns true if quality data is present, false otherwise.
   * @return Boolean indicating presence of quality data
   
  bool hasQuality() const;
   * @brief Asynchronously retrieves the GPU product
   *
   * Retrieves the GPU product asynchronously using the provided stream.
   * @param stream The sycl queue stream for asynchronous operation
   * @return Pointer to the GPU product
   
  const SiPixelFedCablingMapGPU *getGPUProductAsync(sycl::queue stream) const;
   * @brief Asynchronously retrieves all module unpacking data
   *
   * Retrieves all module unpacking data asynchronously using the provided stream.
   * @param stream The sycl queue stream for asynchronous operation
   * @return Pointer to the module unpacking data
   
  const unsigned char *getModToUnpAllAsync(sycl::queue stream) const;

private:   * @brief Default module unpacking data
   
  std::vector<unsigned char> modToUnpDefault;
   * @brief Flag indicating presence of quality data
   
  bool hasQuality_;
   * @brief Host-side pointer to the cabling map structure
   
  SiPixelFedCablingMapGPU *cablingMapHost_;
   * @brief Structure representing GPU data
   
  struct GPUData {
         * @brief Default constructor
     
    GPUData() = default;

         * @brief Destructor
     
    ~GPUData() {};
     * @brief Device-unique pointer to the cabling map on the GPU
     
    cms::sycltools::device::unique_ptr<SiPixelFedCablingMapGPU> cablingMapDevice;
  };
   * @brief ESProduct for managing GPUData instances
   
  cms::sycltools::ESProduct<GPUData> gpuData_;
   * @brief Structure representing modules to unpack
   
  struct ModulesToUnpack {
         * @brief Default constructor
     
    ModulesToUnpack() = default;

         * @brief Destructor
     
    ~ModulesToUnpack(){};
     * @brief Device-unique pointer to the module unpacking data on the GPU
     
    cms::sycltools::device::unique_ptr<unsigned char[]> modToUnpDefault;
  };
   * @brief ESProduct for managing ModulesToUnpack instances
   
  cms::sycltools::ESProduct<ModulesToUnpack> modToUnp_;
}* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
class SiPixelFedCablingMapGPUWrapper {
public:
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap,
                                          std::vector<unsigned char> modToUnp);
  ~SiPixelFedCablingMapGPUWrapper();

  bool hasQuality() const { return hasQuality_; }

  // returns pointer to GPU memory
  const SiPixelFedCablingMapGPU *getGPUProductAsync(sycl::queue stream) const;

  // returns pointer to GPU memory
  const unsigned char *getModToUnpAllAsync(sycl::queue stream) const;

private:
  std::vector<unsigned char> modToUnpDefault;
  bool hasQuality_;

  SiPixelFedCablingMapGPU *cablingMapHost_ = nullptr;  // pointer to struct in CPU

  struct GPUData {
    GPUData() = default;
    ~GPUData() {}

    cms::sycltools::device::unique_ptr<SiPixelFedCablingMapGPU> cablingMapDevice;  // pointer to struct in GPU
  };
  cms::sycltools::ESProduct<GPUData> gpuData_;

  struct ModulesToUnpack {
    ModulesToUnpack() = default;
    ~ModulesToUnpack(){};

    cms::sycltools::device::unique_ptr<unsigned char[]> modToUnpDefault;  // pointer to GPU
  };
  cms::sycltools::ESProduct<ModulesToUnpack> modToUnp_;
};

#endif
