// C++ includes
#include <algorithm>
#include <cstring>
#include <iomanip>
#include <iostream>
#include <vector>

// SYCL includes
#include <sycl/sycl.hpp>

// CMSSW includes
#include "SYCLCore/device_unique_ptr.h"
#include "SYCLCore/host_unique_ptr.h"
#include "CondFormats/SiPixelFedCablingMapGPUWrapper.h"


// The following comment is generated by an LLM. 
/**
 * Constructor initializing the object with a given cabling map and module to unmask vector.
 * @param cablingMap The input cabling map.
 * @param modToUnp Vector specifying modules to unmask.
 */ 
SiPixelFedCablingMapGPUWrapper::SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const& cablingMap,
                                                               std::vector<unsigned char> modToUnp)
    : modToUnpDefault(modToUnp.size()), hasQuality_(true) {
  cablingMapHost_ = new SiPixelFedCablingMapGPU();
  std::memcpy(cablingMapHost_, &cablingMap, sizeof(SiPixelFedCablingMapGPU));
  std::copy(modToUnp.begin(), modToUnp.end(), modToUnpDefault.begin());
}

SiPixelFedCablingMapGPUWrapper::~SiPixelFedCablingMapGPUWrapper() { delete cablingMapHost_; }


// The following comment is generated by an LLM. 
/**
 * @brief Retrieves the GPU product asynchronously.
 *
 * This function retrieves the GPU product for the current device,
 * allocating and transferring the necessary data as required.
 *
 * @param stream The SYCL queue used for asynchronous operations.
 *
 * @return A pointer to the GPU product.
 */ 
const SiPixelFedCablingMapGPU* SiPixelFedCablingMapGPUWrapper::getGPUProductAsync(sycl::queue stream) const {
  const auto& data = gpuData_.dataForCurrentDeviceAsync(stream, [this](GPUData& data, sycl::queue& stream) {
    // allocate
    data.cablingMapDevice = cms::sycltools::make_device_unique_uninitialized<SiPixelFedCablingMapGPU>(stream);
    // transfer
    stream.memcpy(data.cablingMapDevice.get(), this->cablingMapHost_, sizeof(SiPixelFedCablingMapGPU));
#ifdef __SYCL_TARGET_INTEL_X86_64__
    // FIXME needed only on CPU ?
    stream.wait();
#endif
  });
  return data.cablingMapDevice.get();
}


// The following comment is generated by an LLM. 
/**
 * @brief Retrieves the module to unpack mapping asynchronously for the current device.
 *
 * @param stream The SYCL queue used for asynchronous operations.
 *
 * @return A constant pointer to the module to unpack mapping data.
 */ 
const unsigned char* SiPixelFedCablingMapGPUWrapper::getModToUnpAllAsync(sycl::queue stream) const {
  const auto& data = modToUnp_.dataForCurrentDeviceAsync(stream, [this](ModulesToUnpack& data, sycl::queue stream) {
    data.modToUnpDefault =
        cms::sycltools::make_device_unique<unsigned char[]>(pixelgpudetails::MAX_SIZE_BYTE_BOOL, stream);
    stream.memcpy(
        data.modToUnpDefault.get(), this->modToUnpDefault.data(), this->modToUnpDefault.size() * sizeof(unsigned char));
#ifdef __SYCL_TARGET_INTEL_X86_64__
    // FIXME needed only on CPU ?
    stream.wait();
#endif
  });
  return data.modToUnpDefault.get();
}
