#ifndef HeterogeneousCore_CUDAUtilities_interface_cudaCompat_h
#define HeterogeneousCore_CUDAUtilities_interface_cudaCompat_h

/*
 * Everything you need to run cuda code in plain sequential c++ code
 */

#ifndef __CUDACC__

#include <algorithm>
#include <cstdint>
#include <cstring>



using cudaStream_t = void*;
constexpr cudaStream_t cudaStreamDefault = nullptr;

namespace cms {
  namespace cudacompat {

    template <typename T1, typename T2>
/**
 * Performs an atomic compare-and-swap operation on the specified address.
 *
 * @param address the memory location to perform the operation on
 * @param compare the value to compare with the current value at address
 * @param val the new value to store at address if comparison succeeds
 * @return the previous value stored at address
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    T1 atomicCAS(T1* address, T1 compare, T2 val) {
      T1 old = *address;
      *address = old == compare ? val : old;
      return old;
    }

    template <typename T1, typename T2>
/**
 * Increments the value of a variable atomically if it is less than a specified threshold.
 *
 * @param a pointer to the variable to be incremented
 * @param b the threshold value
 * @return the original value of the variable
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    T1 atomicInc(T1* a, T2 b) {
      auto ret = *a;
      if ((*a) < T1(b))
        (*a)++;
      return ret;
    }

    template <typename T1, typename T2>
/**
 * Performs an atomic addition operation on a variable.
 *
 * @param a pointer to the variable to be modified
 * @param b value to be added to the variable
 * @return the original value of the variable before modification
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    T1 atomicAdd(T1* a, T2 b) {
      auto ret = *a;
      (*a) += b;
      return ret;
    }

    template <typename T1, typename T2>
/**
 * Subtracts a value from an atomic variable and returns the original value.
 *
 * @param a pointer to the atomic variable
 * @param b value to subtract
 * @return original value of the atomic variable
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    T1 atomicSub(T1* a, T2 b) {
      auto ret = *a;
      (*a) -= b;
      return ret;
    }

    template <typename T1, typename T2>
/**
 * Performs an atomic minimum operation on a variable.
 *
 * @param a pointer to the variable to modify
 * @param b the value to compare with
 * @return the original value of the variable
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    T1 atomicMin(T1* a, T2 b) {
      auto ret = *a;
      *a = std::min(*a, T1(b));
      return ret;
    }
    template <typename T1, typename T2>
/**
 * Performs an atomic maximum operation on a variable.
 *
 * @param a pointer to the variable to update
 * @param b new value to compare with the current value of a
 * @return the previous value of a
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    T1 atomicMax(T1* a, T2 b) {
      auto ret = *a;
      *a = std::max(*a, T1(b));
      return ret;
    }

  }  // namespace cudacompat
}  // namespace cms

// make the cudacompat implementation available in the global namespace
using namespace cms::cudacompat;

#endif  // __CUDACC__

#endif  // HeterogeneousCore_CUDAUtilities_interface_cudaCompat_h
