#ifndef HeterogeneousCore_CUDAUtilities_interface_HistoContainer_h
#define HeterogeneousCore_CUDAUtilities_interface_HistoContainer_h

#include <algorithm>
#include <atomic>
#include <cstddef>
#include <cstdint>
#include <type_traits>

#include "CUDACore/AtomicPairCounter.h"
#include "CUDACore/cuda_assert.h"
#include "CUDACore/cudastdAlgorithm.h"
#include "CUDACore/prefixScan.h"

namespace cms {
  namespace cuda {

    template <typename Histo, typename T>
/**
 * Counts elements from a vector and updates the histogram accordingly.
 *
 * @param h         Pointer to the histogram object
 * @param nh        Number of histograms
 * @param v         Vector containing elements to count
 * @param offsets   Array of offsets for the vector elements
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    void countFromVector(Histo *__restrict__ h,
                         uint32_t nh,
                         T const *__restrict__ v,
                         uint32_t const *__restrict__ offsets) {
      int first = 0;
      for (int i = first, nt = offsets[nh]; i < nt; i++) {
        auto off = cuda_std::upper_bound(offsets, offsets + nh + 1, i);
        assert((*off) > 0);
        int32_t ih = off - offsets - 1;
        assert(ih >= 0);
        assert(ih < int(nh));
        (*h).count(v[i], ih);
      }
    }

    template <typename Histo, typename T>
/**
 * Fills a histogram object from a vector of values and their corresponding offsets.
 *
 * @param h         Pointer to the histogram object to be filled
 * @param nh        Number of histograms
 * @param v         Vector of values to fill the histogram with
 * @param offsets   Vector of offsets corresponding to the values in v
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    void fillFromVector(Histo *__restrict__ h,
                        uint32_t nh,
                        T const *__restrict__ v,
                        uint32_t const *__restrict__ offsets) {
      int first = 0;
      for (int i = first, nt = offsets[nh]; i < nt; i++) {
        auto off = cuda_std::upper_bound(offsets, offsets + nh + 1, i);
        assert((*off) > 0);
        int32_t ih = off - offsets - 1;
        assert(ih >= 0);
        assert(ih < int(nh));
        (*h).fill(v[i], i, ih);
      }
    }

    template <typename Histo>
/**
 * Launches zero initialization for histogram data structure
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void launchZero(Histo *__restrict__ h) {
      uint32_t *poff = (uint32_t *)((char *)(h) + offsetof(Histo, off));
      int32_t size = offsetof(Histo, bins) - offsetof(Histo, off);
      assert(size >= int(sizeof(uint32_t) * Histo::totbins()));
      ::memset(poff, 0, size);
    }

    template <typename Histo>
    inline void launchFinalize(Histo *__restrict__ h) {
      h->finalize();
    }

    template <typename Histo, typename T>
/**
 * Fill many histograms from a vector of values.
 *
 * @param h         Pointer to histogram object
 * @param nh        Number of histograms
 * @param v         Vector of values
 * @param offsets   Offsets into vector for each histogram
 * @param totSize   Total size of all histograms
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void fillManyFromVector(Histo *__restrict__ h,
                                   uint32_t nh,
                                   T const *__restrict__ v,
                                   uint32_t const *__restrict__ offsets,
                                   uint32_t totSize) {
      launchZero(h);
      countFromVector(h, nh, v, offsets);
      h->finalize();
      fillFromVector(h, nh, v, offsets);
    }

    template <typename Assoc>
    void finalizeBulk(AtomicPairCounter const *apc, Assoc *__restrict__ assoc) {
      assoc->bulkFinalizeFill(*apc);
    }

    // iteratate over N bins left and right of the one containing "v"
    template <typename Hist, typename V, typename Func>
/**
 * Brief description: Iterates over bins in a histogram.
 *
 * Detailed description: This function iterates over a specified range of bins in a histogram,
 * applying a given function to each bin.
 *
 * Parameters:
 *   hist - The input histogram.
 *   value - The central value of the bin range.
 *   n - The number of bins to iterate over on either side of the central bin.
 *   func - The function to apply to each bin.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void forEachInBins(Hist const &hist, V value, int n, Func func) {
      int bs = Hist::bin(value);
      int be = std::min(int(Hist::nbins() - 1), bs + n);
      bs = std::max(0, bs - n);
      assert(be >= bs);
      for (auto pj = hist.begin(bs); pj < hist.end(be); ++pj) {
        func(*pj);
      }
    }

    // iteratate over bins containing all values in window wmin, wmax
    template <typename Hist, typename V, typename Func>
/**
 * Iterates over all elements within a specified window of a histogram and applies a function to each element.
 *
 * @param hist The input histogram.
 * @param wmin The minimum value of the window.
 * @param wmax The maximum value of the window.
 * @param func The function to apply to each element within the window.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void forEachInWindow(Hist const &hist, V wmin, V wmax, Func const &func) {
      auto bs = Hist::bin(wmin);
      auto be = Hist::bin(wmax);
      assert(be >= bs);
      for (auto pj = hist.begin(bs); pj < hist.end(be); ++pj) {
        func(*pj);
      }
    }

    template <typename T,                  // the type of the discretized input values
              uint32_t NBINS,              // number of bins
              uint32_t SIZE,               // max number of element
              uint32_t S = sizeof(T) * 8,  // number of significant bits in T
              typename I = uint32_t,  // type stored in the container (usually an index in a vector of the input values)
              uint32_t NHISTS = 1     // number of histos stored
              >
    class HistoContainer {
    public:
      using Counter = uint32_t;

      using CountersOnly = HistoContainer<T, NBINS, 0, S, I, NHISTS>;

      using index_type = I;
      using UT = typename std::make_unsigned<T>::type;

/**
 * Calculates the integer base 2 logarithm of a given 32 bit unsigned integer.
 *
 * @param v The input value.
 * @return The integer base 2 logarithm of v.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      static constexpr uint32_t ilog2(uint32_t v) {
        constexpr uint32_t b[] = {0x2, 0xC, 0xF0, 0xFF00, 0xFFFF0000};
        constexpr uint32_t s[] = {1, 2, 4, 8, 16};

        uint32_t r = 0;  // result of log2(v) will go here
        for (auto i = 4; i >= 0; i--)
          if (v & b[i]) {
            v >>= s[i];
            r |= s[i];
          }
        return r;
      }

      static constexpr uint32_t sizeT() { return S; }
      static constexpr uint32_t nbins() { return NBINS; }
      static constexpr uint32_t nhists() { return NHISTS; }
      static constexpr uint32_t totbins() { return NHISTS * NBINS + 1; }
      static constexpr uint32_t nbits() { return ilog2(NBINS - 1) + 1; }
      static constexpr uint32_t capacity() { return SIZE; }

      static constexpr auto histOff(uint32_t nh) { return NBINS * nh; }

/**
 * Retrieves the binary representation of a value within a specified bit range.
 *
 * @param t The input value to extract bits from.
 * @return The extracted bits as an unsigned integer.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      static constexpr UT bin(T t) {
        constexpr uint32_t shift = sizeT() - nbits();
        constexpr uint32_t mask = (1 << nbits()) - 1;
        return (t >> shift) & mask;
      }

/**
 * Brief description of the function that sets all elements to zero
 *
 * Detailed description of the function that iterates over a collection and assigns zero to each element
 *
 * @return None
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      void zero() {
        for (auto &i : off)
          i = 0;
      }

/**
 * Adds another CountersOnly object to this object.
 *
 * @param co the CountersOnly object to add
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void add(CountersOnly const &co) {
        for (uint32_t i = 0; i < totbins(); ++i) {
          auto &a = (std::atomic<Counter> &)(off[i]);
          a += co.off[i];
        }
      }

/**
 * Returns the previous value of the counter after incrementing it atomically.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      static inline uint32_t atomicIncrement(Counter &x) {
        auto &a = (std::atomic<Counter> &)(x);
        return a++;
      }

/**
 * Decrements the value of an atomic counter variable.
 *
 * @param x Reference to the Counter object to decrement.
 * @return The decremented value of the Counter object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      static inline uint32_t atomicDecrement(Counter &x) {
        auto &a = (std::atomic<Counter> &)(x);
        return a--;
      }

/**
 * Increments the offset of a specific bin in an atomic manner.
 *
 * @param b the bin number to increment
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void countDirect(T b) {
        assert(b < nbins());
        atomicIncrement(off[b]);
      }

/**
 * Brief description: Decrements the offset of a bin and stores an index.
 *
 * Detailed description: This function takes a bin number b and an index j as input,
 * decrements the offset of the specified bin atomically, and stores the index at the
 * corresponding position in the bins array.
 *
 * Parameters:
 *   b - The bin number.
 *   j - The index to store.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void fillDirect(T b, index_type j) {
        assert(b < nbins());
        auto w = atomicDecrement(off[b]);
        assert(w > 0);
        bins[w - 1] = j;
      }

/**
 * Calculates the bulk fill value for an AtomicPairCounter object.
 *
 * @param apc Reference to the AtomicPairCounter object.
 * @param v Array of indices to be filled.
 * @param n Number of elements in the array.
 *
 * @return Index where the filling starts or negative value if overflow occurs.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline int32_t bulkFill(AtomicPairCounter &apc, index_type const *v, uint32_t n) {
        auto c = apc.add(n);
        if (c.m >= nbins())
          return -int32_t(c.m);
        off[c.m] = c.n;
        for (uint32_t j = 0; j < n; ++j)
          bins[c.n + j] = v[j];
        return c.m;
      }

      inline void bulkFinalize(AtomicPairCounter const &apc) { off[apc.get().m] = apc.get().n; }

/**
 * Finalizes the filling process for the AtomicPairCounter object.
 *
 * This function takes into account potential overflows and updates the offset values accordingly.
 *
 * @param apc the AtomicPairCounter object to finalize
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void bulkFinalizeFill(AtomicPairCounter const &apc) {
        auto m = apc.get().m;
        auto n = apc.get().n;
        if (m >= nbins()) {  // overflow!
          off[nbins()] = uint32_t(off[nbins() - 1]);
          return;
        }
        auto first = m;
        for (auto i = first; i < totbins(); i++) {
          off[i] = n;
        }
      }

/**
 * Increments the offset counter for a given type T in a specific bin.
 *
 * @param t The input value of type T to be counted.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void count(T t) {
        uint32_t b = bin(t);
        assert(b < nbins());
        atomicIncrement(off[b]);
      }

/**
 * Brief description of inline function fill
 *
 * Detailed description of inline function fill which fills data into bins
 * @param t input data of type T
 * @param j index of type index_type
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void fill(T t, index_type j) {
        uint32_t b = bin(t);
        assert(b < nbins());
        auto w = atomicDecrement(off[b]);
        assert(w > 0);
        bins[w - 1] = j;
      }

/**
 * Increment the histogram offset at the specified bin with atomic operation
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void count(T t, uint32_t nh) {
        uint32_t b = bin(t);
        assert(b < nbins());
        b += histOff(nh);
        assert(b < totbins());
        atomicIncrement(off[b]);
      }

/**
 * Fill function to store data in histogram bins
 *
 * @param t input data to be binned
 * @param j index type representing the data
 * @param nh number of histograms
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void fill(T t, index_type j, uint32_t nh) {
        uint32_t b = bin(t);
        assert(b < nbins());
        b += histOff(nh);
        assert(b < totbins());
        auto w = atomicDecrement(off[b]);
        assert(w > 0);
        bins[w - 1] = j;
      }

/**
 * Finalizes the calculation by performing a prefix scan on the offset array.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void finalize() {
        assert(off[totbins() - 1] == 0);
        blockPrefixScan(off, totbins());
        assert(off[totbins() - 1] == off[totbins() - 2]);
      }

      constexpr auto size() const { return uint32_t(off[totbins() - 1]); }
      constexpr auto size(uint32_t b) const { return off[b + 1] - off[b]; }

      constexpr index_type const *begin() const { return bins; }
      constexpr index_type const *end() const { return begin() + size(); }

      constexpr index_type const *begin(uint32_t b) const { return bins + off[b]; }
      constexpr index_type const *end(uint32_t b) const { return bins + off[b + 1]; }

      Counter off[totbins()];
      int32_t psws;  // prefix-scan working space
      index_type bins[capacity()];
    };

    template <typename I,        // type stored in the container (usually an index in a vector of the input values)
              uint32_t MAXONES,  // max number of "ones"
              uint32_t MAXMANYS  // max number of "manys"
              >
    using OneToManyAssoc = HistoContainer<uint32_t, MAXONES, MAXMANYS, sizeof(uint32_t) * 8, I, 1>;

  }  // namespace cuda
}  // namespace cms

#endif  // HeterogeneousCore_CUDAUtilities_interface_HistoContainer_h
