#ifndef HeterogeneousCore_SYCLCore_ContextState_h
#define HeterogeneousCore_SYCLCore_ContextState_h

#include <iostream>
#include <memory>
#include <optional>

#include <sycl/sycl.hpp>

namespace cms {
  namespace sycltools {
    /**
     * The purpose of this class is to deliver the device and queue
     * information from ExternalWork's acquire() to producer() via a
     * member variable.
     */
    class ContextState {
    public:
      ContextState() = default;
      ~ContextState() = default;

      ContextState(const ContextState&) = delete;
      ContextState& operator=(const ContextState&) = delete;
      ContextState(ContextState&&) = delete;
      ContextState& operator=(ContextState&& other) = delete;

    private:
      friend class ScopedContextAcquire;
      friend class ScopedContextProduce;
      friend class ScopedContextTask;

/**
 * Sets the SYCL queue associated with this object
 *
 * @param stream shared pointer to the SYCL queue
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      void set(std::shared_ptr<sycl::queue> stream) {
        throwIfStream();
        stream_ = std::move(stream);
      }

/**
 * Returns the device associated with the current stream.
 *
 * @return The device object representing the hardware device.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      sycl::device device() const {
        throwIfNoStream();
        return stream_->get_device();
      }

/**
 * Returns the underlying SYCL queue object associated with this instance.
 *
 * @return The SYCL queue object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      sycl::queue stream() const {
        throwIfNoStream();
        return *stream_;
      }

/**
 * Returns a constant reference to the SYCL queue pointer.
 *
 * @return A constant reference to the SYCL queue pointer.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      std::shared_ptr<sycl::queue> const& streamPtr() const {
        throwIfNoStream();
        return stream_;
      }

/**
 * Releases the SYCL queue pointer and resets the stream.
 *
 * @return The released SYCL queue pointer.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      std::shared_ptr<sycl::queue> releaseStreamPtr() {
        throwIfNoStream();
        // This function needs to effectively reset stream_ (i.e. stream_
        // must be empty after this function). This behavior ensures that
        // the sycl::queue is not hold for inadvertedly long (i.e. to
        // the next event), and is checked at run time.
        return std::move(stream_);
      }

      void throwIfStream() const;
      void throwIfNoStream() const;

      std::shared_ptr<sycl::queue> stream_;
    };
  }  // namespace sycltools
}  // namespace cms

#endif
