#ifndef SYCLCore_getDeviceIndex_h
#define SYCLCore_getDeviceIndex_h

#include <sycl/sycl.hpp>

#include "SYCLCore/chooseDevice.h"

namespace cms::sycltools {
/**
 * Returns the index of a given SYCL device in the list of enumerated devices.
 *
 * @param device The SYCL device to find the index for.
 * @return The index of the device if found, undefined behavior otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  inline int getDeviceIndex(sycl::device const& device) {
    auto const& devices = enumerateDevices();
    auto position = std::find(devices.begin(), devices.end(), device);
    int index = position - devices.begin();
    return index;
  }
}  // namespace cms::sycltools

#endif  // SYCLCore_getDeviceIndex_h