#ifndef SYCLCore_getPlatformIndex
#define SYCLCore_getPlatformIndex

#include <sycl/sycl.hpp>

#include "SYCLCore/chooseDevice.h"

namespace cms::sycltools {
/**
 * Returns the index of a given SYCL platform in the list of available platforms
 *
 * @param platform the SYCL platform to find the index for
 * @return the index of the platform
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  inline int getPlatformIndex(sycl::platform const& platform) {
    auto const& platforms = enumeratePlatforms();
    auto position = std::find(platforms.begin(), platforms.end(), platform);
    int index = position - platforms.begin();
    return index;
  }
}  // namespace cms::sycltools

#endif  // SYCLCore_getPlatformIndex