#ifndef HeterogeneousCore_SYCLUtilities_interface_host_unique_ptr_h
#define HeterogeneousCore_SYCLUtilities_interface_host_unique_ptr_h

#include <functional>
#include <memory>
#include <optional>

#include <sycl/sycl.hpp>
#include "SYCLCore/getHostCachingAllocator.h"

namespace cms {
  namespace sycltools {
    namespace host {
      namespace impl {
        // Additional layer of types to distinguish from host::unique_ptr
        class HostDeleter {
        public:
          HostDeleter() = default;  // for edm::Wrapper
          HostDeleter(sycl::queue stream) : stream_{stream} {}

/**
 * Destructor to release allocated memory from the host caching allocator associated with the stream. 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
          void operator()(void* ptr) {
            if (stream_) {
              CachingAllocator& allocator = getHostCachingAllocator(*stream_);
              allocator.free(ptr);
            }
          }

        private:
          std::optional<sycl::queue> stream_;
        };
      }  // namespace impl

      template <typename T>
      using unique_ptr = std::unique_ptr<T, impl::HostDeleter>;

      namespace impl {
        template <typename T>
        struct make_host_unique_selector {
          using non_array = cms::sycltools::host::unique_ptr<T>;
        };
        template <typename T>
        struct make_host_unique_selector<T[]> {
          using unbounded_array = cms::sycltools::host::unique_ptr<T[]>;
        };
        template <typename T, size_t N>
        struct make_host_unique_selector<T[N]> {
          struct bounded_array {};
        };
      }  // namespace impl
    }    // namespace host

    // Allocate pinned host memory
    template <typename T>
/**
 * Brief description: A selector for creating unique pointers on the host.
 *
 * Detailed description: This class provides functionality for allocating 
 * memory on the host and creating unique pointers to manage that memory.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    typename host::impl::make_host_unique_selector<T>::non_array make_host_unique(sycl::queue const& stream) {
      static_assert(std::is_trivially_constructible<T>::value,
                    "Allocating with non-trivial constructor on the pinned host memory is not supported");
      CachingAllocator& allocator = getHostCachingAllocator(stream);
      void* mem = allocator.allocate(sizeof(T), stream);
      return typename host::impl::make_host_unique_selector<T>::non_array{reinterpret_cast<T*>(mem),
                                                                          host::impl::HostDeleter{stream}};
    }

    template <typename T>
/**
 * Class representing an unbounded array allocated on the host.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    typename host::impl::make_host_unique_selector<T>::unbounded_array make_host_unique(size_t n,
                                                                                        sycl::queue const& stream) {
      using element_type = typename std::remove_extent<T>::type;
      static_assert(std::is_trivially_constructible<element_type>::value,
                    "Allocating with non-trivial constructor on the pinned host memory is not supported");
      CachingAllocator& allocator = getHostCachingAllocator(stream);
      void* mem = allocator.allocate(n * sizeof(element_type), stream);
      return typename host::impl::make_host_unique_selector<T>::unbounded_array{reinterpret_cast<element_type*>(mem),
                                                                                host::impl::HostDeleter{stream}};
    }

    template <typename T, typename... Args>
    typename host::impl::make_host_unique_selector<T>::bounded_array make_host_unique(Args&&...) = delete;

    // No check for the trivial constructor, make it clear in the interface
    template <typename T>
/**
 * @brief Creates a unique selector for a host object
 *
 * This function generates a non-array unique selector for a host object,
 * allocating memory through a caching allocator associated with a SYCL queue.
 *
 * @param stream The SYCL queue used for memory allocation
 * @return A unique selector managing the allocated host object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    typename host::impl::make_host_unique_selector<T>::non_array make_host_unique_uninitialized(
        sycl::queue const& stream) {
      CachingAllocator& allocator = getHostCachingAllocator(stream);
      void* mem = allocator.allocate(sizeof(T), stream);
      return typename host::impl::make_host_unique_selector<T>::non_array{reinterpret_cast<T*>(mem),
                                                                          host::impl::HostDeleter{stream}};
    }

    template <typename T>
/**
 * @brief Creates an unbounded array of uninitialized elements on the host.
 *
 * @tparam T Type of elements in the array.
 * @param n Number of elements in the array.
 * @param stream SYCL queue associated with the array.
 * @return Unbounded array of uninitialized elements.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    typename host::impl::make_host_unique_selector<T>::unbounded_array make_host_unique_uninitialized(
        size_t n, sycl::queue const& stream) {
      using element_type = typename std::remove_extent<T>::type;
      CachingAllocator& allocator = getHostCachingAllocator(stream);
      void* mem = allocator.allocate(n * sizeof(element_type), stream);
      return typename host::impl::make_host_unique_selector<T>::unbounded_array{reinterpret_cast<element_type*>(mem),
                                                                                host::impl::HostDeleter{stream}};
    }

    template <typename T, typename... Args>
    typename host::impl::make_host_unique_selector<T>::bounded_array make_host_unique_uninitialized(Args&&...) = delete;
  }  // namespace sycltools
}  // namespace cms

#endif