#ifndef SYCLDataFormatsCommonHostProduct_H
#define SYCLDataFormatsCommonHostProduct_H

#include "SYCLCore/host_unique_ptr.h"

// a heterogeneous unique pointer...
template <typename T>
/**
 * Brief description of the class HostProduct
 *
 * Detailed description of the class HostProduct
 * This class provides a way to manage unique pointers 
 * to objects of type T on both the host and device sides
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
class HostProduct {
public:
  HostProduct() = default;  // make root happy
  ~HostProduct() = default;
  HostProduct(HostProduct&&) = default;
  HostProduct& operator=(HostProduct&&) = default;

  explicit HostProduct(cms::sycltools::host::unique_ptr<T>&& p) : hm_ptr(std::move(p)) {}
  explicit HostProduct(std::unique_ptr<T>&& p) : std_ptr(std::move(p)) {}

  auto const* get() const { return hm_ptr ? hm_ptr.get() : std_ptr.get(); }

  auto const& operator*() const { return *get(); }

  auto const* operator->() const { return get(); }

private:
  cms::sycltools::host::unique_ptr<T> hm_ptr;  //!
  std::unique_ptr<T> std_ptr;                  //!
};

#endif
