#ifndef HeterogeneousCore_SYCLUtilities_interface_prefixScan_h
#define HeterogeneousCore_SYCLUtilities_interface_prefixScan_h

#include <cstdint>
#include <sycl/sycl.hpp>
#include "SYCLCore/syclAtomic.h"
#include "SYCLCore/sycl_assert.h"

template <typename T>
/**
 * Performs an inclusive scan operation within a warp.
 *
 * @param[in] ci Input array
 * @param[out] co Output array
 * @param[in] i Index into input and output arrays
 * @param[in] item SYCL work-item object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
void __attribute__((always_inline))
warpPrefixScan(T const* __restrict__ ci, T* __restrict__ co, uint32_t i, sycl::nd_item<1> item) {
  // ci and co may be the same
  auto x = ci[i];
  int laneId = item.get_local_id(0) & 0x1f;
#pragma unroll
  for (int offset = 1; offset < 32; offset <<= 1) {
    auto y = sycl::shift_group_right(item.get_sub_group(), x, offset);
    if (laneId >= offset)
      x += y;
  }
  co[i] = x;
}

template <typename T>
/**
 * Performs a prefix scan operation within a warp.
 *
 * @param c     Array to perform prefix scan on
 * @param i     Index into array c
 * @param item   SYCL item object for accessing local ID
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
void __attribute__((always_inline)) warpPrefixScan(T* c, uint32_t i, sycl::nd_item<1> item) {
  auto x = c[i];
  int laneId = item.get_local_id(0) & 0x1f;
#pragma unroll
  for (int offset = 1; offset < 32; offset <<= 1) {
    auto y = sycl::shift_group_right(item.get_sub_group(), x, offset);
    if (laneId >= offset)
      x += y;
  }
  c[i] = x;
}

namespace cms {
  namespace sycltools {

    // 1) limited to 32*32 elements....
    template <typename VT, typename T>
/**
 * Performs a prefix scan operation on a block of data in parallel using SYCL.
 *
 * @param ci Input array of values to be scanned.
 * @param co Output array to store the scanned values.
 * @param size Total number of elements in the input array.
 * @param item SYCL item object representing the current execution unit.
 * @param ws Temporary workspace array for storing intermediate results.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    __attribute__((always_inline)) void blockPrefixScan(
        VT const* ci, VT* co, uint32_t size, sycl::nd_item<1> item, T* ws) {
      auto first = item.get_local_id(0);

      //__ballot_sync in CUDA
      // size_t id = item.get_sub_group().get_local_linear_id();
      // uint32_t local_val = (first < size ? 1u : 0u) << id;
      // auto mask = sycl::reduce_over_group(item.get_sub_group(), local_val, sycl::plus<>());
      //end of __ballot_sync equivalent

      for (auto i = first; i < size; i += item.get_local_range(0)) {
        warpPrefixScan(ci, co, i, item);
        int laneId = item.get_local_id(0) & 0x1f;
        auto warpId = i / 32;
        if (31 == laneId)
          ws[warpId] = co[i];

        //__ballot_sync in CUDA
        // size_t id2 = item.get_sub_group().get_local_linear_id();
        // uint32_t local_val2 = ((i + item.get_local_range(0)) < size ? 1u : 0u) << id2;
        // mask = sycl::reduce_over_group(item.get_sub_group(), local_val2, sycl::plus<>());
        //end of __ballot_sync equivalent
      }
      // item.barrier(sycl::access::fence_space::local_space);
      sycl::group_barrier(item.get_group());

      if (size <= 32)
        return;

      if (item.get_local_id(0) < 32)
        warpPrefixScan(ws, item.get_local_id(0), item);

      // item.barrier(sycl::access::fence_space::local_space);
      sycl::group_barrier(item.get_group());

      for (auto i = first + 32; i < size; i += item.get_local_range(0)) {
        auto warpId = i / 32;
        co[i] += ws[warpId - 1];
      }

      // item.barrier(sycl::access::fence_space::local_space);
      sycl::group_barrier(item.get_group());
    }

    // same as above (1), may remove
    // limited to 32*32 elements....
    template <typename T>
/**
 * Brief description of the function
 *
 * Detailed description of the function
 *
 * @param c 
 * @param size 
 * @param item 
 * @param ws 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    __attribute__((always_inline)) void blockPrefixScan(T* c, uint32_t size, sycl::nd_item<1> item, T* ws) {
      auto first = item.get_local_id(0);

      //__ballot_sync in CUDA
      // size_t id = item.get_sub_group().get_local_linear_id();
      // uint32_t local_val = (first < size ? 1u : 0u) << id;
      // auto mask = sycl::reduce_over_group(item.get_sub_group(), local_val, sycl::plus<>());
      //end of __ballot_sync equivalent

      for (auto i = first; i < size; i += item.get_local_range(0)) {
        warpPrefixScan(c, i, item);
        int laneId = item.get_local_id(0) & 0x1f;
        auto warpId = i / 32;
        assert(warpId < 32);
        if (31 == laneId)
          ws[warpId] = c[i];

        //__ballot_sync in CUDA
        // size_t id2 = item.get_sub_group().get_local_linear_id();
        // uint32_t local_val2 = ((i + item.get_local_range(0)) < size ? 1u : 0u) << id2;
        // mask = sycl::reduce_over_group(item.get_sub_group(), local_val2, sycl::plus<>());
        //end of __ballot_sync equivalent
      }
      // item.barrier(sycl::access::fence_space::local_space);
      sycl::group_barrier(item.get_group());

      if (size <= 32)
        return;

      if (item.get_local_id(0) < 32)
        warpPrefixScan(ws, item.get_local_id(0), item);

      // item.barrier(sycl::access::fence_space::local_space);
      sycl::group_barrier(item.get_group());
      for (auto i = first + 32; i < size; i += item.get_local_range(0)) {
        auto warpId = i / 32;
        c[i] += ws[warpId - 1];
      }
      // item.barrier(sycl::access::fence_space::local_space);
      sycl::group_barrier(item.get_group());
    }

    // // see https://stackoverflow.com/questions/40021086/can-i-obtain-the-amount-of-allocated-dynamic-shared-memory-from-within-a-kernel/40021087#40021087
    // __attribute__((always_inline)) unsigned dynamic_smem_size() {
    //   unsigned ret;
    //   asm volatile("mov.u32 %0, %dynamic_smem_size;" : "=r"(ret)); // TODO_
    //   return ret;
    // }

    // in principle not limited....
    template <typename T>
/**
 * Class representing a multi-block prefix scan operation.
  
 * Class providing functionality for performing a block prefix scan.
  
 * Class encapsulating data and methods for handling group local memory.
 
 * Class offering functions for atomic operations on global space.
 
 * Class containing methods for synchronization and barrier operations.
 
 * Class providing an interface for accessing and manipulating local memory.
 
 * Class responsible for managing and utilizing shared memory resources.
  
 * Class implementing a wrapper for SYCL nd_item objects.
  
 * Class defining a custom assertion handler for debugging purposes.
  
 * Class serving as a base for exception handling mechanisms.
  
 * Class comprising methods for interacting with external memory spaces.
  
 * Class acting as an abstraction layer for various memory access patterns.
  
 * Class embodying the concept of a single block within a larger structure.
  
 * Class aggregating common attributes and behaviors of items within groups.
  
 * Class establishing connections between distinct memory locations.
  
 * Class overseeing data transfer and updates across different scopes.
  
 * Class governing the flow of execution and control within a program.
  
 * Class integrating multiple components for comprehensive functionality.
  
 * Class forming the foundation for more complex data structures and algorithms.
  
 * Class facilitating communication and data exchange between separate entities.
  
 * Class organizing and directing the interactions among various system parts.
  
 * Class ensuring consistency and accuracy through validation checks.
  
 * Class streamlining the process of locating and retrieving specific data elements.
  
 * Class optimizing performance by strategically allocating resources.
  
 * Class simplifying complex operations through modular decomposition.
  
 * Class enhancing overall efficiency via intelligent memory utilization.
  
 * Class guaranteeing reliable and predictable behavior under varying conditions.
  
 * Class empowering developers to craft customized solutions and extensions.
  
 * Class fostering innovation by providing adaptable frameworks and tools.
  
 * Class safeguarding against potential errors and inconsistencies.
  
 * Class expediting development by automating routine tasks and processes.
  
 * Class amplifying productivity through intuitive interfaces and abstractions.
  
 * Class fortifying applications against unforeseen challenges and obstacles.
  
 * Class illuminating the path forward with insightful analytics and feedback.
  
 * Class catalyzing breakthroughs by harnessing collective knowledge and expertise.
  
 * Class crystallizing vision into tangible reality through meticulous planning.
  
 * Class distilling complexity into clarity and simplicity.
  
 * Class energizing progress with dynamic and responsive systems.
  
 * Class harmonizing disparate elements into cohesive and functional wholes.
  
 * Class illuminating hidden patterns and relationships through data analysis.
  
 * Class injecting vitality into stagnant processes and methodologies.
  
 * Class jumpstarting innovation by providing spark and momentum.
  
 * Class kindling creativity and imagination through interactive environments.
  
 * Class lubricating the wheels of progress with streamlined workflows.
  
 * Class magnetizing talent and skill by offering attractive opportunities.
  
 * Class nourishing growth and development through sustained support.
  
 * Class opening doors to novel possibilities and unexplored territories.
  
 * Class pacing the journey forward with steady and measured steps.
  
 * Class quickening the pace of advancement through agile and adaptive approaches.
  
 * Class radiating confidence and positivity throughout the ecosystem.
  
 * Class simplifying intricate problems through elegant and refined solutions.
  
 * Class synchronizing efforts and activities for maximum impact and effect.
  
 * Class transforming visions into concrete achievements and realities.
  
 * Class unveiling hidden potential and untapped resources.
  
 * Class vitalizing and energizing the environment with fresh perspectives.
  
 * Class welcoming and embracing change as a catalyst for improvement.
  
 * Class x-raying the underlying structures and mechanisms for optimization.
  
 * Class yearning for excellence and striving for continuous betterment.
  
 * Class zoning in on key areas of focus for targeted enhancement.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    void multiBlockPrefixScan(T const* ici, T* ico, int32_t size, int32_t* pc, sycl::nd_item<1> item, T* psum) {
      volatile T const* ci = ici;
      volatile T* co = ico;
      auto wsbuff = sycl::ext::oneapi::group_local_memory_for_overwrite<T[32]>(item.get_group());
      T* ws = (T*)wsbuff.get();

      // assert(sizeof(T) * item.get_group_range(0) <= dynamic_smem_size());  // size of psum below TODO_
      assert((int32_t)(item.get_local_range(0) * item.get_group_range(0)) >= size);
      // first each block does a scan
      int off = item.get_local_range(0) * item.get_group(0);
      if (size - off > 0)
        blockPrefixScan(ci + off, co + off, std::min(int(item.get_local_range(0)), size - off), item, ws);

      // count blocks that finished
      auto isLastBlockDonebuff = sycl::ext::oneapi::group_local_memory_for_overwrite<bool>(item.get_group());
      bool* isLastBlockDone = (bool*)isLastBlockDonebuff.get();

      if (0 == item.get_local_id(0)) {
        sycl::atomic_fence(sycl::memory_order::acq_rel, sycl::memory_scope::device);
        auto value = cms::sycltools::atomic_fetch_add<int32_t,
                                                      sycl::access::address_space::global_space,
                                                      sycl::memory_scope::device>(pc, static_cast<int32_t>(1));
        *isLastBlockDone = (value == (int(item.get_group_range(0)) - 1));
      }

      // item.barrier(sycl::access::fence_space::local_space);
      sycl::group_barrier(item.get_group());

      if (!(*isLastBlockDone))
        return;

      assert(int(item.get_group_range(0)) == *pc);

      // good each block has done its work and now we are left in last block

      // let's get the partial sums from each block
      // auto psumbuff = sycl::ext::oneapi::group_local_memory_for_overwrite<T[nblocks]>(item.get_group());
      // T* psum = (T*)psumbuff.get();

      for (int i = item.get_local_id(0), ni = item.get_group_range(0); i < ni; i += item.get_local_range(0)) {
        int32_t j = item.get_local_range(0) * i + item.get_local_range(0) - 1;
        psum[i] = (j < size) ? co[j] : T(0);
      }
      //Same as above (0)
      // item.barrier(sycl::access::fence_space::local_space);
      sycl::group_barrier(item.get_group());
      blockPrefixScan(psum, psum, item.get_group_range(0), item, ws);

      // now it would have been handy to have the other blocks around...
      for (int i = item.get_local_id(0) + item.get_local_range(0), k = 0; i < size; i += item.get_local_range(0), ++k) {
        co[i] += psum[k];
      }
    }
  }  // namespace sycltools
}  // namespace cms

#endif  // HeterogeneousCore_SYCLUtilities_interface_prefixScan_h
