#ifndef HeterogeneousCore_SYCLUtilities_interface_SimpleVector_h
#define HeterogeneousCore_SYCLUtilities_interface_SimpleVector_h

//  author: Felice Pantaleo, CERN, 2018

#include <sycl/sycl.hpp>

#include <type_traits>
#include <utility>

#include "SYCLCore/syclAtomic.h"

namespace cms {
  namespace sycltools {

    template <class T>
    struct SimpleVector {
      constexpr SimpleVector() = default;

      // ownership of m_data stays within the caller
      constexpr void construct(int capacity, T *data) {
        m_size = 0;
        m_capacity = capacity;
        m_data = data;
      }

/**
 * Pushes an element onto the end of the container without checking for capacity.
 *
 * @param element The element to be added to the container.
 * @return The index of the newly added element if successful, -1 otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      inline constexpr int push_back_unsafe(const T &element) {
        auto previousSize = m_size;
        m_size++;
        if (previousSize < m_capacity) {
          m_data[previousSize] = element;
          return previousSize;
        } else {
          --m_size;
          return -1;
        }
      }

      template <class... Ts>
/**
 * Emplaces an element at the end of the container without checking for capacity.
 *
 * @param args  Variable number of arguments to forward to the constructor of T
 * @return Index of the newly added element if successful, -1 otherwise
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      constexpr int emplace_back_unsafe(Ts &&...args) {
        auto previousSize = m_size;
        m_size++;
        if (previousSize < m_capacity) {
          (new (&m_data[previousSize]) T(std::forward<Ts>(args)...));
          return previousSize;
        } else {
          --m_size;
          return -1;
        }
      }

      inline T &back() { return m_data[m_size - 1]; }

/**
 * Returns a constant reference to the last element in the container.
 *
 * @return A constant reference to the last element if the container is not empty,
 *         otherwise returns an undefined value.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      inline const T &back() const {
        if (m_size > 0) {
          return m_data[m_size - 1];
        } else
          return T();  //undefined behaviour
      }

      // thread-safe version of the vector, when used in a SYCL kernel
      int push_back(const T &element) {
        auto previousSize =
            cms::sycltools::atomic_fetch_add<int, sycl::access::address_space::global_space, sycl::memory_scope::device>(
                &m_size, static_cast<int>(1));
        if (previousSize < m_capacity) {
          m_data[previousSize] = element;
          return previousSize;
        } else {
          cms::sycltools::atomic_fetch_sub<int, sycl::access::address_space::global_space, sycl::memory_scope::device>(
              &m_size, static_cast<int>(1));
          return -1;
        }
      }

      template <class... Ts>
/**
 * @brief Emplaces an element at the end of the container.
 *
 * @param args Forwarded arguments to construct the new element.
 * @return The index of the newly added element if successful, -1 otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      int emplace_back(Ts &&...args) {
        auto previousSize = cms::sycltools::atomic_fetch_add<int>(&m_size, static_cast<int>(1));
        if (previousSize < m_capacity) {
          (new (&m_data[previousSize]) T(std::forward<Ts>(args)...));
          return previousSize;
        } else {
          cms::sycltools::atomic_fetch_sub<int>(&m_size, static_cast<int>(1));
          return -1;
        }
      }

      // thread safe version of resize
      int extend(int size = 1) {
        auto previousSize = cms::sycltools::atomic_fetch_add<int>(&m_size, static_cast<int>(size));
        if (previousSize < m_capacity) {
          return previousSize;
        } else {
          cms::sycltools::atomic_fetch_sub<int>(&m_size, static_cast<int>(1));
          return -1;
        }
      }

/**
 * @brief Decreases the size by a specified amount.
 *
 * This function atomically subtracts the given size from the current size,
 * returning the new size if the operation is successful.
 *
 * @param size The amount to decrease the size by.
 * @return The new size after subtraction, or -1 if the operation fails.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      int shrink(int size = 1) {
        auto previousSize = cms::sycltools::atomic_fetch_sub<int>(&m_size, static_cast<int>(1));
        if (previousSize >= size) {
          return previousSize - size;
        } else {
          cms::sycltools::atomic_fetch_add<int>(&m_size, static_cast<int>(size));
          return -1;
        }
      }

      inline constexpr bool empty() const { return m_size <= 0; }
      inline constexpr bool full() const { return m_size >= m_capacity; }
      inline constexpr T &operator[](int i) { return m_data[i]; }
      inline constexpr const T &operator[](int i) const { return m_data[i]; }
      inline constexpr void reset() { m_size = 0; }
      inline constexpr int size() const { return m_size; }
      inline constexpr int capacity() const { return m_capacity; }
      inline constexpr T const *data() const { return m_data; }
      inline constexpr void resize(int size) { m_size = size; }
      inline constexpr void set_data(T *data) { m_data = data; }

    private:
      int m_size;
      int m_capacity;

      T *m_data;
    };

    // ownership of m_data stays within the caller
    template <class T>
/**
 * Brief description of SimpleVector class 
 * Detailed description of SimpleVector class 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    SimpleVector<T> make_SimpleVector(int capacity, T *data) {
      SimpleVector<T> ret;
      ret.construct(capacity, data);
      return ret;
    }

    // ownership of m_data stays within the caller
    template <class T>
/**
 * Constructs a SimpleVector object at the specified memory location.
 *
 * @param mem     Memory address where the vector will be constructed
 * @param capacity Maximum number of elements the vector can hold
 * @param data    Array of elements to initialize the vector with
 * @return Pointer to the newly constructed SimpleVector object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    SimpleVector<T> *make_SimpleVector(SimpleVector<T> *mem, int capacity, T *data) {
      auto ret = new (mem) SimpleVector<T>();
      ret->construct(capacity, data);
      return ret;
    }

  }  // namespace sycltools
}  // namespace cms

#endif  // HeterogeneousCore_SYCLUtilities_interface_SimpleVector_h
