#ifndef HeterogeneousCore_SYCLUtilities_interface_syclAtomic_h
#define HeterogeneousCore_SYCLUtilities_interface_syclAtomic_h

#include <sycl/sycl.hpp>
#include <cstdint>

// those atomic functions come from dpct translation of CUDA atomics
// apart from AtomicInc, the other as fast as native CUDA

namespace cms {
  namespace sycltools {

    template <typename T,
              sycl::access::address_space addrSpace = sycl::access::address_space::global_space,
              sycl::memory_scope Scope = sycl::memory_scope::device,
              sycl::memory_order memOrder = sycl::memory_order::relaxed>
/**
 * @brief Atomic fetch add operation
 *
 * This function performs an atomic fetch add operation on the specified address.
 *
 * @param addr Pointer to the memory location
 * @param operand Value to be added
 * @return Result of the fetch add operation
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    inline T atomic_fetch_add(T *addr, T operand) {
      auto atm = sycl::atomic_ref<T, memOrder, Scope, addrSpace>(addr[0]);

      return atm.fetch_add(operand);
    }

    template <typename T,
              sycl::access::address_space addrSpace = sycl::access::address_space::global_space,
              sycl::memory_scope Scope = sycl::memory_scope::device,
              sycl::memory_order memOrder = sycl::memory_order::relaxed>
/**
 * @brief Performs an atomic fetch subtract operation on a variable.
 *
 * @tparam T Type of the variable being operated on.
 * @param addr Pointer to the variable being operated on.
 * @param operand Value to be subtracted from the variable.
 * @return The original value of the variable before subtraction.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    inline T atomic_fetch_sub(T *addr, T operand) {
      auto atm = sycl::atomic_ref<T, memOrder, Scope, addrSpace>(addr[0]);

      return atm.fetch_sub(operand);
    }

    template <typename T,
              sycl::access::address_space addrSpace = sycl::access::address_space::global_space,
              sycl::memory_scope Scope = sycl::memory_scope::device,
              sycl::memory_order memOrder = sycl::memory_order::relaxed>
/**
 * Fetches the value at the specified address, increments it atomically, 
 * and returns the original value.
 *
 * @param addr The memory address to fetch from and increment
 * @param operand Not used in this implementation
 * @return The original value at the specified address
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    inline T atomic_fetch_compare_inc(T *addr, T operand) {
      auto atm = sycl::atomic_ref<T, memOrder, Scope, addrSpace>(addr[0]);
      assert(addr[0] < operand);

      // extremely inefficient (time pov)
      // TODO_ implement an efficient version of the atomicInc
      //      T old;
      //      while (true) {
      //        old = atm.load();
      //        if (old >= operand) {
      //          if (atm.compare_exchange_strong(old, 0))
      //            break;
      //        } else if (atm.compare_exchange_strong(old, old + 1))
      //          break;
      //      }
      //      return old;
      return atm.fetch_add(1);
    }

    template <typename T,
              sycl::access::address_space addrSpace = sycl::access::address_space::global_space,
              sycl::memory_scope Scope = sycl::memory_scope::device,
              sycl::memory_order memOrder = sycl::memory_order::relaxed>
/**
 * @brief Atomic fetch minimum operation
 *
 * This function performs an atomic fetch minimum operation on the specified address.
 *
 * @param addr Pointer to the memory location
 * @param operand Value to compare with the current value at the memory location
 * @return The original value at the memory location
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    inline T atomic_fetch_min(T *addr, T operand) {
      auto atm = sycl::atomic_ref<T, memOrder, Scope, addrSpace>(addr[0]);

      return atm.fetch_min(operand);
    }

    template <typename T,
              sycl::access::address_space addrSpace = sycl::access::address_space::global_space,
              sycl::memory_scope Scope = sycl::memory_scope::device,
              sycl::memory_order memOrder = sycl::memory_order::relaxed>
/**
 * @brief Atomic fetch maximum operation
 *
 * This function performs an atomic fetch maximum operation on the specified address.
 *
 * @param addr Pointer to the memory location
 * @param operand Value to compare with the current value at the memory location
 * @return The previous value stored at the memory location
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    inline T atomic_fetch_max(T *addr, T operand) {
      auto atm = sycl::atomic_ref<T, memOrder, Scope, addrSpace>(addr[0]);

      return atm.fetch_max(operand);
    }

    template <typename T,
              sycl::access::address_space addrSpace = sycl::access::address_space::global_space,
              sycl::memory_scope Scope = sycl::memory_scope::device,
              sycl::memory_order memOrder = sycl::memory_order::relaxed>
/**
 * @brief Performs an atomic compare exchange strong operation on a memory location.
 *
 * @param addr Memory address to perform the operation on
 * @param expected Expected value at the memory location
 * @param desired Desired new value at the memory location
 * @return The old value at the memory location
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    inline T atomic_compare_exchange_strong(T *addr, T expected, T desired) {
      auto atm = sycl::atomic_ref<T, memOrder, Scope, addrSpace>(addr[0]);
      atm.compare_exchange_strong(expected, desired, memOrder, memOrder);
      return expected;
    }
  }  // namespace sycltools
}  // namespace cms

#endif  // HeterogeneousCore_SYCLUtilities_interface_syclAtomic_h
