#ifndef HeterogeneousCore_SYCLUtilities_interface_syclAtomic_h
#define HeterogeneousCore_SYCLUtilities_interface_syclAtomic_h

#include <sycl/sycl.hpp>
#include <cstdint>

// those atomic functions come from dpct translation of CUDA atomics
// apart from AtomicInc, the other as fast as native CUDA

namespace cms {
  namespace sycltools {

    template <typename T,
              sycl::access::address_space addrSpace = sycl::access::address_space::global_space,
              sycl::memory_scope Scope = sycl::memory_scope::device,
              sycl::memory_order memOrder = sycl::memory_order::relaxed>
/**
 * Fetches the value at the specified address and adds the given operand to it atomically.
 *
 * @param addr The memory address to fetch from and add to.
 * @param operand The value to add to the fetched value.
 * @return The original value at the address before the addition.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline T atomic_fetch_add(T *addr, T operand) {
      auto atm = sycl::atomic_ref<T, memOrder, Scope, addrSpace>(addr[0]);

      return atm.fetch_add(operand);
    }

    template <typename T,
              sycl::access::address_space addrSpace = sycl::access::address_space::global_space,
              sycl::memory_scope Scope = sycl::memory_scope::device,
              sycl::memory_order memOrder = sycl::memory_order::relaxed>
/**
 * @brief Atomic fetch subtract operation
 *
 * This function performs an atomic fetch subtract operation on the specified address.
 *
 * @param addr Pointer to the memory location
 * @param operand Value to be subtracted
 * @return Result of the subtraction operation
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline T atomic_fetch_sub(T *addr, T operand) {
      auto atm = sycl::atomic_ref<T, memOrder, Scope, addrSpace>(addr[0]);

      return atm.fetch_sub(operand);
    }

    template <typename T,
              sycl::access::address_space addrSpace = sycl::access::address_space::global_space,
              sycl::memory_scope Scope = sycl::memory_scope::device,
              sycl::memory_order memOrder = sycl::memory_order::relaxed>
/**
 * Fetches the value at the specified address, increments it atomically, 
 * and returns the original value.
 *
 * @param addr The memory address to fetch from and increment
 * @param operand Not used in this implementation
 * @return The original value at the specified address
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline T atomic_fetch_compare_inc(T *addr, T operand) {
      auto atm = sycl::atomic_ref<T, memOrder, Scope, addrSpace>(addr[0]);
      assert(addr[0] < operand);

      // extremely inefficient (time pov)
      // TODO_ implement an efficient version of the atomicInc
      //      T old;
      //      while (true) {
      //        old = atm.load();
      //        if (old >= operand) {
      //          if (atm.compare_exchange_strong(old, 0))
      //            break;
      //        } else if (atm.compare_exchange_strong(old, old + 1))
      //          break;
      //      }
      //      return old;
      return atm.fetch_add(1);
    }

    template <typename T,
              sycl::access::address_space addrSpace = sycl::access::address_space::global_space,
              sycl::memory_scope Scope = sycl::memory_scope::device,
              sycl::memory_order memOrder = sycl::memory_order::relaxed>
/**
 * @brief Performs an atomic fetch minimum operation on a variable.
 *
 * This function provides a way to atomically update a variable with the minimum value between its current value and a given operand.
 *
 * @param addr The address of the variable to update.
 * @param operand The value to compare with the current value of the variable.
 * @return The original value of the variable before the update.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline T atomic_fetch_min(T *addr, T operand) {
      auto atm = sycl::atomic_ref<T, memOrder, Scope, addrSpace>(addr[0]);

      return atm.fetch_min(operand);
    }

    template <typename T,
              sycl::access::address_space addrSpace = sycl::access::address_space::global_space,
              sycl::memory_scope Scope = sycl::memory_scope::device,
              sycl::memory_order memOrder = sycl::memory_order::relaxed>
/**
 * Fetches the maximum value from an atomic reference.
 *
 * @param addr The address of the atomic variable.
 * @param operand The new value to compare with the current value.
 * @return The previous value of the atomic variable.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline T atomic_fetch_max(T *addr, T operand) {
      auto atm = sycl::atomic_ref<T, memOrder, Scope, addrSpace>(addr[0]);

      return atm.fetch_max(operand);
    }

    template <typename T,
              sycl::access::address_space addrSpace = sycl::access::address_space::global_space,
              sycl::memory_scope Scope = sycl::memory_scope::device,
              sycl::memory_order memOrder = sycl::memory_order::relaxed>
/**
 * @brief Performs an atomic compare exchange strong operation
 * @param addr pointer to the memory location
 * @param expected expected value
 * @param desired new value to be exchanged
 * @return the old value at the memory location
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline T atomic_compare_exchange_strong(T *addr, T expected, T desired) {
      auto atm = sycl::atomic_ref<T, memOrder, Scope, addrSpace>(addr[0]);
      atm.compare_exchange_strong(expected, desired, memOrder, memOrder);
      return expected;
    }
  }  // namespace sycltools
}  // namespace cms

#endif  // HeterogeneousCore_SYCLUtilities_interface_syclAtomic_h
