#ifndef DataFormats_DigiClusterCount_h
#define DataFormats_DigiClusterCount_h

/**
 * @brief Class representing digitization cluster count data structure
 *
 * This class encapsulates the number of modules, digits, and clusters in a detector system,
 * providing methods to access these counts.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
class DigiClusterCount {
public:
  explicit DigiClusterCount(unsigned int nm, unsigned int nd, unsigned int nc)
      : modules_(nm), digis_(nd), clusters_(nc) {}

  unsigned int nModules() const { return modules_; }
  unsigned int nDigis() const { return digis_; }
  unsigned int nClusters() const { return clusters_; }

private:
  unsigned int modules_, digis_, clusters_;
};

#endif
