#ifndef AlpakaCore_alpakastdAlgorithm_h
#define AlpakaCore_alpakastdAlgorithm_h

#include <algorithm>
#include <functional>
#include <utility>

#include <alpaka/alpaka.hpp>

// reimplementation of std algorithms able to compile with Alpaka,
// mostly by declaring them constexpr

namespace alpaka_std {

  template <typename T = void>
  struct less {
    ALPAKA_FN_HOST_ACC constexpr bool operator()(const T &lhs, const T &rhs) const { return lhs < rhs; }
  };

  template <>
  struct less<void> {
    template <typename T, typename U>
    ALPAKA_FN_HOST_ACC constexpr bool operator()(const T &lhs, const U &rhs) const {
      return lhs < rhs;
    }
  };

  template <typename RandomIt, typename T, typename Compare = less<T>>
/**
 * Searches for the lowest index at which an element should be inserted to maintain sorted order.
 *
 * @param first Beginning of the range to search.
 * @param last End of the range to search.
 * @param value Value to search for.
 * @param comp Comparison function object.
 * @return Iterator pointing to the insertion point.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  ALPAKA_FN_HOST_ACC constexpr RandomIt lower_bound(RandomIt first, RandomIt last, const T &value, Compare comp = {}) {
    auto count = last - first;

    while (count > 0) {
      auto it = first;
      auto step = count / 2;
      it += step;
      if (comp(*it, value)) {
        first = ++it;
        count -= step + 1;
      } else {
        count = step;
      }
    }
    return first;
  }

  template <typename RandomIt, typename T, typename Compare = less<T>>
/**
 * @brief Finds the upper bound of a value within a range using binary search.
 *
 * This function performs a binary search to find the upper bound of a given value
 * within a specified range. It returns an iterator pointing to the first element
 * that is greater than the given value, or the end of the range if no such element exists.
 *
 * @param first Iterator pointing to the beginning of the range.
 * @param last Iterator pointing to the end of the range.
 * @param value The value to search for.
 * @param comp Comparison function object.
 * @return An iterator pointing to the upper bound of the value.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  ALPAKA_FN_HOST_ACC constexpr RandomIt upper_bound(RandomIt first, RandomIt last, const T &value, Compare comp = {}) {
    auto count = last - first;

    while (count > 0) {
      auto it = first;
      auto step = count / 2;
      it += step;
      if (!comp(value, *it)) {
        first = ++it;
        count -= step + 1;
      } else {
        count = step;
      }
    }
    return first;
  }

  template <typename RandomIt, typename T, typename Compare = alpaka_std::less<T>>
/**
 * @brief Performs a binary search within a range to find an element.
 *
 * @param first Beginning of the range to search.
 * @param last End of the range to search.
 * @param value Value to search for.
 * @param comp Comparison function object.
 *
 * @return An iterator pointing to the found element if it exists, otherwise last.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  ALPAKA_FN_HOST_ACC constexpr RandomIt binary_find(RandomIt first, RandomIt last, const T &value, Compare comp = {}) {
    first = alpaka_std::lower_bound(first, last, value, comp);
    return first != last && !comp(value, *first) ? first : last;
  }

}  // namespace alpaka_std

#endif  // AlpakaCore_alpakastdAlgorithm_h
