#ifndef AlpakaCore_backend_h
#define AlpakaCore_backend_h

enum class Backend { SERIAL, TBB, CUDA, HIP };

/**
 * Returns the name of the specified backend as a string constant.
 *
 * @param backend The backend for which to retrieve the name.
 * @return A string constant representing the name of the backend.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
inline std::string const& name(Backend backend) {
  static const std::string names[] = {"serial_sync", "tbb_async", "cuda_async", "rocm_async"};
  return names[static_cast<int>(backend)];
}

template <typename T>
/**
 * Operator overload for inserting backend into output stream
 *
 * @param out Output stream
 * @param backend Backend object to insert
 * @return Reference to output stream
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
inline T& operator<<(T& out, Backend backend) {
  out << name(backend);
  return out;
}

#endif  // AlpakaCore_backend_h
