#ifndef AlpakaCore_getHostCachingAllocator_h
#define AlpakaCore_getHostCachingAllocator_h

#include "AlpakaCore/AllocatorConfig.h"
#include "AlpakaCore/CachingAllocator.h"
#include "AlpakaCore/alpaka/devices.h"
#include "AlpakaCore/host.h"

namespace cms::alpakatools {

  template <typename TQueue>
/**
 * Returns a reference to the host caching allocator instance.
 *
 * This function provides thread-safe access to the allocator, ensuring that it is initialized only once.
 *
 * @return A reference to the host caching allocator instance.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  inline CachingAllocator<alpaka_common::DevHost, TQueue>& getHostCachingAllocator() {
    // thread safe initialisation of the host allocator
    static CachingAllocator<alpaka_common::DevHost, TQueue> allocator(host(),
                                                                      config::binGrowth,
                                                                      config::minBin,
                                                                      config::maxBin,
                                                                      config::maxCachedBytes,
                                                                      config::maxCachedFraction,
                                                                      false,   // reuseSameQueueAllocations
                                                                      false);  // debug

    // the public interface is thread safe
    return allocator;
  }

}  // namespace cms::alpakatools

#endif  // AlpakaCore_getHostCachingAllocator_h
