#ifndef AlpakaCore_Product_h
#define AlpakaCore_Product_h

#include <memory>
#include <utility>

#include "AlpakaCore/config.h"
#include "AlpakaCore/ProductBase.h"

namespace edm {
  template <typename T>
  class Wrapper;
}

namespace cms::alpakatools {

  namespace impl {
    template <typename TQueue>
    class ScopedContextGetterBase;
  }

  /**
     * The purpose of this class is to wrap CUDA data to edm::Event in a
     * way which forces correct use of various utilities.
     *
     * The non-default construction has to be done with ScopedContext
     * (in order to properly register the CUDA event).
     *
     * The default constructor is needed only for the ROOT dictionary generation.
     *
     * The CUDA event is in practice needed only for stream-stream
     * synchronization, but someone with long-enough lifetime has to own
     * it. Here is a somewhat natural place. If overhead is too much, we
     * can use them only where synchronization between streams is needed.
     */
  template <typename TQueue, typename T>
/**
 * Brief description of the class.
 *
 * Detailed description of the class.
 
class Product 
{
     * Public member typedef for Queue type.
   
  using Queue = TQueue;

     * Public member typedef for Event type.
   
  using Event = alpaka::Event<Queue>;

     * Default constructor.
   
  Product();

     * Deleted copy constructor.
   
  Product(const Product&) = delete;

     * Deleted copy assignment operator.
   
  Product& operator=(const Product&) = delete;

     * Move constructor.
   
  Product(Product&&);

     * Move assignment operator.
   
  Product& operator=(Product&&);

private:
     * Friend class declaration for impl::ScopedContextGetterBase.
   
  friend class impl::ScopedContextGetterBase<Queue>;

     * Friend class declaration for ScopedContextProduce.
   
  friend class ScopedContextProduce<Queue>;

     * Friend class declaration for edm::Wrapper.
   
  friend class edm::Wrapper<Product<Queue, T>>;

     * Explicit constructor with stream, event, and data parameters.
   *
   * @param stream Shared pointer to the queue.
   * @param event Shared pointer to the event.
   * @param data Data object to be stored.
   
  explicit Product(std::shared_ptr<Queue> stream, std::shared_ptr<Event> event, T data);

     * Templated explicit constructor with variable arguments.
   *
   * @param stream Shared pointer to the queue.
   * @param event Shared pointer to the event.
   * @param args Variable number of arguments.
   
  template <typename... Args>
  explicit Product(std::shared_ptr<Queue> stream, std::shared_ptr<Event> event, Args&&... args);

     * Data member variable.
   
  T data_;
}* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  class Product : public ProductBase<TQueue> {
  public:
    using Queue = TQueue;
    using Event = alpaka::Event<Queue>;

    Product() = default;  // Needed only for ROOT dictionary generation

    Product(const Product&) = delete;
    Product& operator=(const Product&) = delete;
    Product(Product&&) = default;
    Product& operator=(Product&&) = default;

  private:
    friend class impl::ScopedContextGetterBase<Queue>;
    friend class ScopedContextProduce<Queue>;
    friend class edm::Wrapper<Product<Queue, T>>;

    explicit Product(std::shared_ptr<Queue> stream, std::shared_ptr<Event> event, T data)
        : ProductBase<Queue>(std::move(stream), std::move(event)), data_(std::move(data)) {}

    template <typename... Args>
    explicit Product(std::shared_ptr<Queue> stream, std::shared_ptr<Event> event, Args&&... args)
        : ProductBase<Queue>(std::move(stream), std::move(event)), data_(std::forward<Args>(args)...) {}

    T data_;  //!
  };

}  // namespace cms::alpakatools

#endif  // AlpakaCore_Product_h
