#ifndef AlpakaCore_SimpleVector_h
#define AlpakaCore_SimpleVector_h

//  author: Felice Pantaleo, CERN, 2018

#include <type_traits>
#include <utility>

#include "AlpakaCore/config.h"

namespace cms::alpakatools {

  template <class T>
  struct SimpleVector {
    constexpr SimpleVector() = default;

    // ownership of m_data stays within the caller
    constexpr void construct(int capacity, T *data) {
      m_size = 0;
      m_capacity = capacity;
      m_data = data;
    }

/**
 * Pushes an element onto the end of the container without checking for capacity.
 *
 * @param element The element to be added to the container.
 * @return The index of the newly added element if successful, -1 otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    inline constexpr int push_back_unsafe(const T &element) {
      auto previousSize = m_size;
      m_size++;
      if (previousSize < m_capacity) {
        m_data[previousSize] = element;
        return previousSize;
      } else {
        --m_size;
        return -1;
      }
    }

    template <class... Ts>
/**
 * Emplaces an element at the end of the container without checking for capacity.
 *
 * @param args  Variable number of arguments to forward to the constructor of T
 * @return Index of the newly added element if successful, -1 otherwise
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    constexpr int emplace_back_unsafe(Ts &&...args) {
      auto previousSize = m_size;
      m_size++;
      if (previousSize < m_capacity) {
        (new (&m_data[previousSize]) T(std::forward<Ts>(args)...));
        return previousSize;
      } else {
        --m_size;
        return -1;
      }
    }

    ALPAKA_FN_ACC inline T &back() { return m_data[m_size - 1]; }

/**
 * Returns a constant reference to the last element in the container.
 *
 * @return Constant reference to the last element if the container is not empty,
 *         otherwise returns a default-constructed object of type T.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    ALPAKA_FN_ACC inline const T &back() const {
      if (m_size > 0) {
        return m_data[m_size - 1];
      } else
        return T();  //undefined behaviour
    }

    // thread-safe version of the vector, when used in a CUDA kernel
    template <typename TAcc>
/**
 * Pushes an element onto the end of the data structure if there is available capacity.
 *
 * @param acc accelerator handle
 * @param element item to add to the data structure
 * @return index of newly added element or negative value if addition failed due to lack of capacity
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    ALPAKA_FN_ACC int push_back(const TAcc &acc, const T &element) {
      auto previousSize = alpaka::atomicAdd(acc, &m_size, 1, alpaka::hierarchy::Blocks{});
      if (previousSize < m_capacity) {
        m_data[previousSize] = element;
        return previousSize;
      } else {
        alpaka::atomicSub(acc, &m_size, 1, alpaka::hierarchy::Blocks{});
        return -1;
      }
    }

    template <typename TAcc, class... Ts>
/**
 * Emplaces an element at the end of the container.
 *
 * @param acc Accelerator object
 * @param args Arguments to forward to the constructor of the element type
 * @return Index of the newly added element if successful, -1 otherwise
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    ALPAKA_FN_ACC int emplace_back(const TAcc &acc, Ts &&...args) {
      auto previousSize = alpaka::atomicAdd(acc, &m_size, 1, alpaka::hierarchy::Blocks{});
      if (previousSize < m_capacity) {
        (new (&m_data[previousSize]) T(std::forward<Ts>(args)...));
        return previousSize;
      } else {
        alpaka::atomicSub(acc, &m_size, 1, alpaka::hierarchy::Blocks{});
        return -1;
      }
    }

    // thread safe version of resize
    template <typename TAcc>
/**
 * @brief Extends the accumulator by a specified size
 * @param acc Accumulator object
 * @param size Size to extend the accumulator by
 * @return Previous size of the accumulator or -1 if extension failed
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    ALPAKA_FN_ACC int extend(const TAcc &acc, int size = 1) {
      auto previousSize = alpaka::atomicAdd(acc, &m_size, size, alpaka::hierarchy::Blocks{});
      if (previousSize < m_capacity) {
        return previousSize;
      } else {
        alpaka::atomicSub(acc, &m_size, size, alpaka::hierarchy::Blocks{});
        return -1;
      }
    }

    template <typename TAcc>
/**
 * @brief Shrinks the accumulator by a specified size.
 *
 * This function atomically subtracts the specified size from the accumulator,
 * returning the previous size if the result is non-negative, otherwise
 * it adds the size back and returns -1.
 *
 * @param acc The accumulator to modify.
 * @param size The amount to shrink the accumulator by.
 * @return The previous size of the accumulator, or -1 on failure.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    ALPAKA_FN_ACC int shrink(const TAcc &acc, int size = 1) {
      auto previousSize = alpaka::atomicSub(acc, &m_size, size, alpaka::hierarchy::Blocks{});
      if (previousSize >= size) {
        return previousSize - size;
      } else {
        alpaka::atomicAdd(acc, &m_size, size, alpaka::hierarchy::Blocks{});
        return -1;
      }
    }

    inline constexpr bool empty() const { return m_size <= 0; }
    inline constexpr bool full() const { return m_size >= m_capacity; }
    inline constexpr T &operator[](int i) { return m_data[i]; }
    inline constexpr const T &operator[](int i) const { return m_data[i]; }
    inline constexpr void reset() { m_size = 0; }
    inline constexpr int size() const { return m_size; }
    inline constexpr int capacity() const { return m_capacity; }
    inline constexpr T const *data() const { return m_data; }
    inline constexpr void resize(int size) { m_size = size; }
    inline constexpr void set_data(T *data) { m_data = data; }

  private:
    int m_size;
    int m_capacity;

    T *m_data;
  };

  // ownership of m_data stays within the caller
  template <class T>
/**
 * Brief description of SimpleVector class 
 * Detailed description of SimpleVector class 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  SimpleVector<T> make_SimpleVector(int capacity, T *data) {
    SimpleVector<T> ret;
    ret.construct(capacity, data);
    return ret;
  }

  // ownership of m_data stays within the caller
  template <class T>
/**
 * Constructs a SimpleVector object at the specified memory location.
 *
 * @param mem     Memory address where the vector will be constructed
 * @param capacity Maximum number of elements the vector can hold
 * @param data    Array of elements to initialize the vector with
 * @return Pointer to the newly constructed SimpleVector object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  SimpleVector<T> *make_SimpleVector(SimpleVector<T> *mem, int capacity, T *data) {
    auto ret = new (mem) SimpleVector<T>();
    ret->construct(capacity, data);
    return ret;
  }

}  // namespace cms::alpakatools

#endif  // AlpakaCore_SimpleVector_h
