#ifndef AlpakaCore_VecArray_h
#define AlpakaCore_VecArray_h

//
// Author: Felice Pantaleo, CERN
//

#include <utility>

#include "AlpakaCore/config.h"

namespace cms::alpakatools {

  template <class T, int maxSize>
  class VecArray {
  public:
    using self = VecArray<T, maxSize>;
    using value_t = T;

/**
 * Class Vector 
 * Brief description A dynamic array like class with unsafe push back operation
 * Detailed description This class provides an interface similar to stdvector but without bounds checking on pushback operation
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    inline constexpr int push_back_unsafe(const T &element) {
      auto previousSize = m_size;
      m_size++;
      if (previousSize < maxSize) {
        m_data[previousSize] = element;
        return previousSize;
      } else {
        --m_size;
        return -1;
      }
    }

    template <class... Ts>
/**
 * Brief description of the function emplace_back_unsafe 
 * Detailed description of the function emplace_back_unsafe 
 * which adds an element at the end of the container
 * @param args variable number of arguments to be forwarded to constructor of type T
 * @return index of newly added element if successful otherwise -1
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    constexpr int emplace_back_unsafe(Ts &&...args) {
      auto previousSize = m_size;
      m_size++;
      if (previousSize < maxSize) {
        (new (&m_data[previousSize]) T(std::forward<Ts>(args)...));
        return previousSize;
      } else {
        --m_size;
        return -1;
      }
    }

/**
 * Returns a reference to the last element in the container.
 *
 * @return A reference to the last element if the container is not empty,
 *         otherwise returns a default constructed T object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    inline constexpr T &back() const {
      if (m_size > 0) {
        return m_data[m_size - 1];
      } else
        return T();  //undefined behaviour
    }

    // thread-safe version of the vector, when used in a CUDA kernel
    template <typename TAcc>
/**
 * @brief Pushes an element onto the end of the data structure.
 *
 * @param acc Accelerator object
 * @param element Element to be added
 * @return Index of the newly added element if successful, -1 otherwise
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    ALPAKA_FN_ACC int push_back(const TAcc &acc, const T &element) {
      auto previousSize = alpaka::atomicAdd(acc, &m_size, 1, alpaka::hierarchy::Blocks{});
      if (previousSize < maxSize) {
        m_data[previousSize] = element;
        return previousSize;
      } else {
        alpaka::atomicSub(acc, &m_size, 1, alpaka::hierarchy::Blocks{});
        return -1;
      }
    }

    template <typename TAcc, class... Ts>
/**
 * Emplaces an element at the end of the container.
 *
 * @param acc Accelerator object
 * @param args Arguments to forward to the constructor of T
 * @return Index of the newly added element if successful, -1 otherwise
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    ALPAKA_FN_ACC int emplace_back(const TAcc &acc, Ts &&...args) {
      auto previousSize = alpaka::atomicAdd(acc, &m_size, 1, alpaka::hierarchy::Blocks{});
      if (previousSize < maxSize) {
        (new (&m_data[previousSize]) T(std::forward<Ts>(args)...));
        return previousSize;
      } else {
        alpaka::atomicSub(acc, &m_size, 1, alpaka::hierarchy::Blocks{});
        return -1;
      }
    }

/**
 * Removes and returns the last element from the container.
 *
 * @return The last element removed from the container.
 * @pre The container must not be empty.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    inline constexpr T pop_back() {
      if (m_size > 0) {
        auto previousSize = m_size--;
        return m_data[previousSize - 1];
      } else
        return T();
    }

    inline constexpr T const *begin() const { return m_data; }
    inline constexpr T const *end() const { return m_data + m_size; }
    inline constexpr T *begin() { return m_data; }
    inline constexpr T *end() { return m_data + m_size; }
    inline constexpr int size() const { return m_size; }
    inline constexpr T &operator[](int i) { return m_data[i]; }
    inline constexpr const T &operator[](int i) const { return m_data[i]; }
    inline constexpr void reset() { m_size = 0; }
    inline static constexpr int capacity() { return maxSize; }
    inline constexpr T const *data() const { return m_data; }
    inline constexpr void resize(int size) { m_size = size; }
    inline constexpr bool empty() const { return 0 == m_size; }
    inline constexpr bool full() const { return maxSize == m_size; }

  private:
    T m_data[maxSize];

    int m_size;
  };

}  // namespace cms::alpakatools

#endif  // AlpakaCore_VecArray_h
