//
// Author: Felice Pantaleo, CERN
//

#include <cstdint>

#include <sycl/sycl.hpp>

#include "SYCLDataFormats/TrackingRecHit2DSYCL.h"
#include "SYCLCore/printf.h"
#include "SYCLCore/sycl_assert.h"
#include "CondFormats/pixelCPEforGPU.h"

#include "RiemannFit.h"
#include "HelixFitOnGPU.h"

using HitsOnGPU = TrackingRecHit2DSOAView;
using Tuples = pixelTrack::HitContainer;
using OutputSoA = pixelTrack::TrackSoA;

template <int N>
/**
 * @brief Function to perform a fast fit on a set of hits
 * 
 * This function takes in several parameters including the found N-tuplets, 
 * tuple multiplicities, number of hits, hits on GPU, and pointers to arrays 
 * for storing the results of the fit. It performs a series of assertions 
 * to ensure that the input parameters are valid, and then iterates over 
 * the local indices, performing the fast fit for each set of hits.
 * 
 * @param foundNtuplets Pointer to the found N-tuplets
 * @param tupleMultiplicity Pointer to the tuple multiplicities
 * @param nHits Number of hits
 * @param hhp Pointer to the hits on the GPU
 * @param phits Pointer to the array for storing the hits
 * @param phits_ge Pointer to the array for storing the geometric errors
 * @param pfast_fit Pointer to the array for storing the results of the fast fit
 * @param offset Offset value
 * @param item SYCL item object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void kernelFastFit(Tuples const *__restrict__ foundNtuplets,
                   CAConstants::TupleMultiplicity const *__restrict__ tupleMultiplicity,
                   uint32_t nHits,
                   HitsOnGPU const *__restrict__ hhp,
                   double *__restrict__ phits,
                   float *__restrict__ phits_ge,
                   double *__restrict__ pfast_fit,
                   uint32_t offset,
                   sycl::nd_item<1> item) {
  constexpr uint32_t hitsInFit = N;

  assert(hitsInFit <= nHits);

  assert(pfast_fit);
  assert(foundNtuplets);
  assert(tupleMultiplicity);

  // look in bin for this hit multiplicity
  auto local_start = item.get_local_id(0) + item.get_group(0) * item.get_local_range().get(0);

#ifdef RIEMANN_DEBUG
  if (0 == local_start)
    printf("%d Ntuple of size %d for %d hits to fit\n", tupleMultiplicity->size(nHits), nHits, hitsInFit);
#endif

  for (int local_idx = local_start, nt = Rfit::maxNumberOfConcurrentFits(); local_idx < nt;
       local_idx += item.get_group_range(0) * item.get_local_range().get(0)) {
    auto tuple_idx = local_idx + offset;
    if (tuple_idx >= tupleMultiplicity->size(nHits))
      break;

    // get it from the ntuple container (one to one to helix)
    auto tkid = *(tupleMultiplicity->begin(nHits) + tuple_idx);
    assert(tkid < foundNtuplets->nbins());

    assert(foundNtuplets->size(tkid) == nHits);

    Rfit::Map3xNd<N> hits(phits + local_idx);
    Rfit::Map4d fast_fit(pfast_fit + local_idx);
    Rfit::Map6xNf<N> hits_ge(phits_ge + local_idx);

    // Prepare data structure
    auto const *hitId = foundNtuplets->begin(tkid);
    for (unsigned int i = 0; i < hitsInFit; ++i) {
      auto hit = hitId[i];
      // printf("Hit global: %f,%f,%f\n", hhp->xg_d[hit],hhp->yg_d[hit],hhp->zg_d[hit]);
      float ge[6];
      hhp->cpeParams()
          .detParams(hhp->detectorIndex(hit))
          .frame.toGlobal(hhp->xerrLocal(hit), 0, hhp->yerrLocal(hit), ge);
      // printf("Error: %d: %f,%f,%f,%f,%f,%f\n",hhp->detInd_d[hit],ge[0],ge[1],ge[2],ge[3],ge[4],ge[5]);

      hits.col(i) << hhp->xGlobal(hit), hhp->yGlobal(hit), hhp->zGlobal(hit);
      hits_ge.col(i) << ge[0], ge[1], ge[2], ge[3], ge[4], ge[5];
    }
    Rfit::Fast_fit(hits, fast_fit);

    // no NaN here....
    assert(fast_fit(0) == fast_fit(0));
    assert(fast_fit(1) == fast_fit(1));
    assert(fast_fit(2) == fast_fit(2));
    assert(fast_fit(3) == fast_fit(3));
  }
}

template <int N>
/**
 * @brief Fits circles to sets of 2D points with associated uncertainties.
 *
 * This function performs a circle fit for multiple sets of 2D points in parallel,
 * utilizing the SYCL programming model. It takes in various parameters such as
 * tuple multiplicities, number of hits, magnetic field strength, pointers to hit data,
 * and an array to store the fitted circle parameters.
 *
 * @param tupleMultiplicity Pointer to tuple multiplicities
 * @param nHits Number of hits
 * @param B Magnetic field strength
 * @param phits Pointer to hit data
 * @param phits_ge Pointer to geometric hit data
 * @param pfast_fit_input Pointer to input data for fast fit
 * @param circle_fit Array to store fitted circle parameters
 * @param offset Offset for indexing
 * @param item SYCL item object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void kernelCircleFit(CAConstants::TupleMultiplicity const *__restrict__ tupleMultiplicity,
                     uint32_t nHits,
                     double B,
                     double *__restrict__ phits,
                     float *__restrict__ phits_ge,
                     double *__restrict__ pfast_fit_input,
                     Rfit::circle_fit *circle_fit,
                     uint32_t offset,
                     sycl::nd_item<1> item) {
  assert(circle_fit);
  assert(N <= nHits);

  // same as above...

  // look in bin for this hit multiplicity
  auto local_start = item.get_group(0) * item.get_local_range().get(0) + item.get_local_id(0);
  for (int local_idx = local_start, nt = Rfit::maxNumberOfConcurrentFits(); local_idx < nt;
       local_idx += item.get_local_range().get(0) * item.get_group_range(0)) {
    auto tuple_idx = local_idx + offset;
    if (tuple_idx >= tupleMultiplicity->size(nHits))
      break;

    Rfit::Map3xNd<N> hits(phits + local_idx);
    Rfit::Map4d fast_fit(pfast_fit_input + local_idx);
    Rfit::Map6xNf<N> hits_ge(phits_ge + local_idx);

    Rfit::VectorNd<N> rad = (hits.block(0, 0, 2, N).colwise().norm());

    Rfit::Matrix2Nd<N> hits_cov = Rfit::Matrix2Nd<N>::Zero();
    Rfit::loadCovariance2D(hits_ge, hits_cov);

    circle_fit[local_idx] = Rfit::Circle_fit(hits.block(0, 0, 2, N), hits_cov, fast_fit, rad, B, true);

#ifdef RIEMANN_DEBUG
    auto tkid = *(tupleMultiplicity->begin(nHits) + tuple_idx);
    printf("kernelCircleFit circle.par(0,1,2): %d %f,%f,%f\n",
           tkid,
           circle_fit[local_idx].par(0),
           circle_fit[local_idx].par(1),
           circle_fit[local_idx].par(2));
#endif
  }
}

template <int N>
/**
 * Brief description of the function kernelLineFit
 *
 * Detailed description of the function kernelLineFit
 * 
 * @param tupleMultiplicity 
 * @param nHits 
 * @param B 
 * @param results 
 * @param phits 
 * @param phits_ge 
 * @param pfast_fit_input 
 * @param circle_fit 
 * @param offset 
 * @param item 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void kernelLineFit(CAConstants::TupleMultiplicity const *__restrict__ tupleMultiplicity,
                   uint32_t nHits,
                   double B,
                   OutputSoA *results,
                   double *__restrict__ phits,
                   float *__restrict__ phits_ge,
                   double *__restrict__ pfast_fit_input,
                   Rfit::circle_fit *__restrict__ circle_fit,
                   uint32_t offset,
                   sycl::nd_item<1> item) {
  assert(results);
  assert(circle_fit);
  assert(N <= nHits);

  // same as above...

  // look in bin for this hit multiplicity
  auto local_start = (item.get_group(0) * item.get_local_range().get(0) + item.get_local_id(0));
  for (int local_idx = local_start, nt = Rfit::maxNumberOfConcurrentFits(); local_idx < nt;
       local_idx += item.get_group_range(0) * item.get_local_range().get(0)) {
    auto tuple_idx = local_idx + offset;
    if (tuple_idx >= tupleMultiplicity->size(nHits))
      break;

    // get it for the ntuple container (one to one to helix)
    auto tkid = *(tupleMultiplicity->begin(nHits) + tuple_idx);

    Rfit::Map3xNd<N> hits(phits + local_idx);
    Rfit::Map4d fast_fit(pfast_fit_input + local_idx);
    Rfit::Map6xNf<N> hits_ge(phits_ge + local_idx);

    auto const &line_fit = Rfit::Line_fit(hits, hits_ge, circle_fit[local_idx], fast_fit, B, true);

    Rfit::fromCircleToPerigee(circle_fit[local_idx]);

    results->stateAtBS.copyFromCircle(
        circle_fit[local_idx].par, circle_fit[local_idx].cov, line_fit.par, line_fit.cov, 1.f / float(B), tkid);
    results->pt(tkid) = B / sycl::fabs(circle_fit[local_idx].par(2));
    //results->eta(tkid) = sycl::asinh(line_fit.par(0));
    results->eta(tkid) = asinhf(line_fit.par(0));
    results->chi2(tkid) = (circle_fit[local_idx].chi2 + line_fit.chi2) / (2 * N - 5);

#ifdef RIEMANN_DEBUG
    printf("kernelLineFit size %d for %d hits circle.par(0,1,2): %d %f,%f,%f\n",
           N,
           nHits,
           tkid,
           circle_fit[local_idx].par(0),
           circle_fit[local_idx].par(1),
           circle_fit[local_idx].par(2));
    printf("kernelLineFit line.par(0,1): %d %f,%f\n", tkid, line_fit.par(0), line_fit.par(1));
    printf("kernelLineFit chi2 cov %f/%f %e,%e,%e,%e,%e\n",
           circle_fit[local_idx].chi2,
           line_fit.chi2,
           circle_fit[local_idx].cov(0, 0),
           circle_fit[local_idx].cov(1, 1),
           circle_fit[local_idx].cov(2, 2),
           line_fit.cov(0, 0),
           line_fit.cov(1, 1));
#endif
  }
}
