#include "CUDACore/cudaCheck.h"
#include "HelixFitOnGPU.h"


// The following comment is generated by an LLM. 
/**
 * Allocates memory on the GPU for helix fit calculation
 * @param[in] tuples input data in form of tuples
 * @param[in] tupleMultiplicity multiplicity of each tuple
 * @param[out] helix_fit_results structure to store results of helix fit
 */ 
void HelixFitOnGPU::allocateOnGPU(Tuples const *tuples,
                                  TupleMultiplicity const *tupleMultiplicity,
                                  OutputSoA *helix_fit_results) {
  tuples_d = tuples;
  tupleMultiplicity_d = tupleMultiplicity;
  outputSoa_d = helix_fit_results;

  assert(tuples_d);
  assert(tupleMultiplicity_d);
  assert(outputSoa_d);
}

void HelixFitOnGPU::deallocateOnGPU() {}
