//
// Author: Felice Pantaleo, CERN
//

#if defined(EIGEN_USE_GPU) && defined(__NVCOMPILER)

#ifndef EIGEN_COMP_NVCC
#define EIGEN_COMP_NVCC 110700
#endif

#ifndef EIGEN_CUDACC
#define EIGEN_CUDACC ON
#endif

#ifndef EIGEN_CUDA_ARCH
#define EIGEN_CUDA_ARCH 860
#endif

#ifndef EIGEN_CUDA_SDK_VER
#define EIGEN_CUDA_SDK_VER 11070
#endif
#endif

#include <algorithm>
#include <cstdint>
#include <execution>
#include <ranges>

#include "CUDADataFormats/TrackingRecHit2D.h"
#include "CondFormats/pixelCPEforGPU.h"

#include "RiemannFit.h"
#include "HelixFitOnGPU.h"

using HitsOnGPU = TrackingRecHit2DSOAView;
using Tuples = pixelTrack::HitContainer;
using OutputSoA = pixelTrack::TrackSoA;

template <int N>
/**
 * @brief Kernel function for fast fitting of tracks
 * 
 * This function performs a fast fit of tracks using the provided hits and 
 * returns the fitted parameters.
 * 
 * @param foundNtuplets Tuples of hits
 * @param tupleMultiplicity Multiplicity of tuples
 * @param nHits Number of hits
 * @param hhp Hits on GPU
 * @param phits Pointer to store hit parameters
 * @param phits_ge Pointer to store error parameters
 * @param pfast_fit Pointer to store fast fit results
 * @param offset Offset for indexing
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernelFastFit(Tuples const *__restrict__ foundNtuplets,
                   CAConstants::TupleMultiplicity const *__restrict__ tupleMultiplicity,
                   uint32_t nHits,
                   HitsOnGPU const *__restrict__ hhp,
                   double *__restrict__ phits,
                   float *__restrict__ phits_ge,
                   double *__restrict__ pfast_fit,
                   uint32_t offset) {
  constexpr uint32_t hitsInFit = N;

  assert(hitsInFit <= nHits);

  assert(pfast_fit);
  assert(foundNtuplets);
  assert(tupleMultiplicity);

#ifdef RIEMANN_DEBUG
  printf("%d Ntuple of size %d for %d hits to fit\n", tupleMultiplicity->size(nHits), nHits, hitsInFit);
#endif
  auto iter{std::views::iota(0U, Rfit::maxNumberOfConcurrentFits())};
  std::for_each(std::execution::par, std::ranges::cbegin(iter), std::ranges::cend(iter), [=](const auto local_idx) {
    auto tuple_idx = local_idx + offset;
    if (tuple_idx >= tupleMultiplicity->size(nHits))
      break;

    // get it from the ntuple container (one to one to helix)
    auto tkid = *(tupleMultiplicity->begin(nHits) + tuple_idx);
    assert(tkid < foundNtuplets->nbins());

    assert(foundNtuplets->size(tkid) == nHits);

    Rfit::Map3xNd<N> hits(phits + local_idx);
    Rfit::Map4d fast_fit(pfast_fit + local_idx);
    Rfit::Map6xNf<N> hits_ge(phits_ge + local_idx);

    // Prepare data structure
    auto const *hitId = foundNtuplets->begin(tkid);
    for (unsigned int i = 0; i < hitsInFit; ++i) {
      auto hit = hitId[i];
      // printf("Hit global: %f,%f,%f\n", hhp->xg_d[hit],hhp->yg_d[hit],hhp->zg_d[hit]);
      float ge[6];
      hhp->cpeParams()
          .detParams(hhp->detectorIndex(hit))
          .frame.toGlobal(hhp->xerrLocal(hit), 0, hhp->yerrLocal(hit), ge);
      // printf("Error: %d: %f,%f,%f,%f,%f,%f\n",hhp->detInd_d[hit],ge[0],ge[1],ge[2],ge[3],ge[4],ge[5]);

      hits.col(i) << hhp->xGlobal(hit), hhp->yGlobal(hit), hhp->zGlobal(hit);
      hits_ge.col(i) << ge[0], ge[1], ge[2], ge[3], ge[4], ge[5];
    }
    Rfit::Fast_fit(hits, fast_fit);

    // no NaN here....
    assert(fast_fit(0) == fast_fit(0));
    assert(fast_fit(1) == fast_fit(1));
    assert(fast_fit(2) == fast_fit(2));
    assert(fast_fit(3) == fast_fit(3));
  });
}

template <int N>
/**
 * @brief Function to perform circle fit on a set of points
 * 
 * @param tupleMultiplicity Tuple multiplicity data structure
 * @param nHits Number of hits
 * @param B Magnetic field strength
 * @param phits Array of hit positions
 * @param phits_ge Array of geometric error estimates
 * @param pfast_fit_input Input data for fast fit algorithm
 * @param circle_fit Output circle fit results
 * @param offset Index offset for parallel processing
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernelCircleFit(CAConstants::TupleMultiplicity const *__restrict__ tupleMultiplicity,
                     uint32_t nHits,
                     double B,
                     double *__restrict__ phits,
                     float *__restrict__ phits_ge,
                     double *__restrict__ pfast_fit_input,
                     Rfit::circle_fit *circle_fit,
                     uint32_t offset) {
  assert(circle_fit);
  assert(N <= nHits);

  // same as above...

  // look in bin for this hit multiplicity
  auto iter{std::views::iota(0U, Rfit::maxNumberOfConcurrentFits())};
  std::for_each(std::execution::par, std::ranges::cbegin(iter), std::ranges::cend(iter), [=](const auto local_idx) {
    auto tuple_idx = local_idx + offset;
    if (tuple_idx >= tupleMultiplicity->size(nHits))
      break;

    Rfit::Map3xNd<N> hits(phits + local_idx);
    Rfit::Map4d fast_fit(pfast_fit_input + local_idx);
    Rfit::Map6xNf<N> hits_ge(phits_ge + local_idx);

    Rfit::VectorNd<N> rad = (hits.block(0, 0, 2, N).colwise().norm());

    Rfit::Matrix2Nd<N> hits_cov = Rfit::Matrix2Nd<N>::Zero();
    Rfit::loadCovariance2D(hits_ge, hits_cov);

    circle_fit[local_idx] = Rfit::Circle_fit(hits.block(0, 0, 2, N), hits_cov, fast_fit, rad, B, true);

#ifdef RIEMANN_DEBUG
//    auto tkid = *(tupleMultiplicity->begin(nHits) + tuple_idx);
//  printf("kernelCircleFit circle.par(0,1,2): %d %f,%f,%f\n", tkid,
//         circle_fit[local_idx].par(0), circle_fit[local_idx].par(1), circle_fit[local_idx].par(2));
#endif
  });
}

template <int N>
/**
 * Brief description of the function kernelLineFit
 *
 * Detailed description of the function kernelLineFit
 * This function performs line fitting on a set of input data points
 * It takes several parameters including tuple multiplicity, number of hits, magnetic field strength, output SoA, and various pointers to arrays
 * The function uses parallel execution and concurrent fits to improve performance
 * It calculates and stores the results in the output SoA, including state at BS, pt, eta, and chi2 values
  
 * Brief description of the struct CAConstants
 *
 * Detailed description of the struct CAConstants
 * This struct contains constants used throughout the application
 * It includes a TupleMultiplicity type which represents a collection of tuple multiplicities
 
 * Brief description of the class Rfit
 *
 * Detailed description of the class Rfit
 * This class provides functionality for performing fits on data points
 * It includes methods for circle fit, line fit, and mapping between different coordinate systems
 * The class also defines several nested classes such as Map3xNd, Map4d, and Map6xNf
 
 * Brief description of the class OutputSoA
 *
 * Detailed description of the class OutputSoA
 * This class represents an output Structure of Arrays
 * It provides methods for accessing and modifying its elements, including copyFromCircle and pt
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernelLineFit(CAConstants::TupleMultiplicity const *__restrict__ tupleMultiplicity,
                   uint32_t nHits,
                   double B,
                   OutputSoA *results,
                   double *__restrict__ phits,
                   float *__restrict__ phits_ge,
                   double *__restrict__ pfast_fit_input,
                   Rfit::circle_fit *__restrict__ circle_fit,
                   uint32_t offset) {
  assert(results);
  assert(circle_fit);
  assert(N <= nHits);

  // same as above...

  auto iter{std::views::iota(0U, Rfit::maxNumberOfConcurrentFits())};
  std::for_each(std::execution::par, std::ranges::cbegin(iter), std::ranges::cend(iter), [=](const auto local_idx) {
    auto tuple_idx = local_idx + offset;
    if (tuple_idx >= tupleMultiplicity->size(nHits))
      break;

    // get it for the ntuple container (one to one to helix)
    auto tkid = *(tupleMultiplicity->begin(nHits) + tuple_idx);

    Rfit::Map3xNd<N> hits(phits + local_idx);
    Rfit::Map4d fast_fit(pfast_fit_input + local_idx);
    Rfit::Map6xNf<N> hits_ge(phits_ge + local_idx);

    auto const &line_fit = Rfit::Line_fit(hits, hits_ge, circle_fit[local_idx], fast_fit, B, true);

    Rfit::fromCircleToPerigee(circle_fit[local_idx]);

    results->stateAtBS.copyFromCircle(
        circle_fit[local_idx].par, circle_fit[local_idx].cov, line_fit.par, line_fit.cov, 1.f / float(B), tkid);
    results->pt(tkid) = B / std::abs(circle_fit[local_idx].par(2));
    results->eta(tkid) = asinhf(line_fit.par(0));
    results->chi2(tkid) = (circle_fit[local_idx].chi2 + line_fit.chi2) / (2 * N - 5);

#ifdef RIEMANN_DEBUG
    printf("kernelLineFit size %d for %d hits circle.par(0,1,2): %d %f,%f,%f\n",
           N,
           nHits,
           tkid,
           circle_fit[local_idx].par(0),
           circle_fit[local_idx].par(1),
           circle_fit[local_idx].par(2));
    printf("kernelLineFit line.par(0,1): %d %f,%f\n", tkid, line_fit.par(0), line_fit.par(1));
    printf("kernelLineFit chi2 cov %f/%f %e,%e,%e,%e,%e\n",
           circle_fit[local_idx].chi2,
           line_fit.chi2,
           circle_fit[local_idx].cov(0, 0),
           circle_fit[local_idx].cov(1, 1),
           circle_fit[local_idx].cov(2, 2),
           line_fit.cov(0, 0),
           line_fit.cov(1, 1));
#endif
  });
}
