#ifndef HeterogeneousCore_CUDAUtilities_interface_cudaCompat_h
#define HeterogeneousCore_CUDAUtilities_interface_cudaCompat_h

/*
 * Everything you need to run cuda code in plain sequential c++ code
 */

#ifndef __CUDACC__

#include <algorithm>
#include <cstdint>
#include <cstring>

#include <cuda_runtime.h>

namespace cms {
  namespace cudacompat {

#ifndef __CUDA_RUNTIME_H__
    struct dim3 {
      uint32_t x, y, z;
    };
#endif
    const dim3 threadIdx = {0, 0, 0};
    const dim3 blockDim = {1, 1, 1};

    extern thread_local dim3 blockIdx;
    extern thread_local dim3 gridDim;

    template <typename T1, typename T2>
/**
 * Performs an atomic compare and swap operation on the specified address.
 * @param address the memory location to perform the operation on
 * @param compare the value to compare with the current value at address
 * @param val the new value to store at address if the comparison succeeds
 * @return the previous value stored at address
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    T1 atomicCAS(T1* address, T1 compare, T2 val) {
      T1 old = *address;
      *address = old == compare ? val : old;
      return old;
    }

    template <typename T1, typename T2>
/**
 * Increments the value of a variable atomically if it is less than a specified threshold.
 *
 * @param a pointer to the variable to increment
 * @param b the threshold value
 * @return the original value of the variable
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    T1 atomicInc(T1* a, T2 b) {
      auto ret = *a;
      if ((*a) < T1(b))
        (*a)++;
      return ret;
    }

    template <typename T1, typename T2>
/**
 * Performs an atomic addition operation on a variable.
 * @param a pointer to the variable to be modified
 * @param b value to be added to the variable
 * @return the original value of the variable before modification
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    T1 atomicAdd(T1* a, T2 b) {
      auto ret = *a;
      (*a) += b;
      return ret;
    }

    template <typename T1, typename T2>
/**
 * Decrements the value of an atomic variable by a specified amount and returns its previous value.
 *
 * @param a pointer to the atomic variable to decrement
 * @param b the amount to subtract from the atomic variable
 * @return the previous value of the atomic variable
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    T1 atomicSub(T1* a, T2 b) {
      auto ret = *a;
      (*a) -= b;
      return ret;
    }

    template <typename T1, typename T2>
/**
 * Performs an atomic minimum operation on a value stored at a memory location.
 * @param a pointer to the memory location containing the value to be updated
 * @param b the new value to compare with the existing value
 * @return the original value stored at the memory location before update
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    T1 atomicMin(T1* a, T2 b) {
      auto ret = *a;
      *a = std::min(*a, T1(b));
      return ret;
    }
    template <typename T1, typename T2>
/**
 * @brief Atomic maximum operation
 * @param a pointer to the variable to update
 * @param b new value to compare with
 * @return previous value of the variable
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    T1 atomicMax(T1* a, T2 b) {
      auto ret = *a;
      *a = std::max(*a, T1(b));
      return ret;
    }

    inline void __syncthreads() {}
    inline void __threadfence() {}
    inline bool __syncthreads_or(bool x) { return x; }
    inline bool __syncthreads_and(bool x) { return x; }
    template <typename T>
    inline T __ldg(T const* x) {
      return *x;
    }

/**
 * Resets the grid dimensions and block indices to their default values.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void resetGrid() {
      blockIdx = {0, 0, 0};
      gridDim = {1, 1, 1};
    }

  }  // namespace cudacompat
}  // namespace cms

// some  not needed as done by cuda runtime...
#ifndef __CUDA_RUNTIME_H__
#define __host__
#define __device__
#define __global__
#define __shared__
#define __forceinline__
#endif

// make sure function are inlined to avoid multiple definition
#ifndef __CUDA_ARCH__
#undef __global__
#define __global__ inline __attribute__((always_inline))
#undef __forceinline__
#define __forceinline__ inline __attribute__((always_inline))
#endif

#ifndef __CUDA_ARCH__
using namespace cms::cudacompat;
#endif

#endif

#endif  // HeterogeneousCore_CUDAUtilities_interface_cudaCompat_h
