#ifndef HeterogenousCore_CUDAUtilities_currentDevice_h
#define HeterogenousCore_CUDAUtilities_currentDevice_h

#include "CUDACore/cudaCheck.h"

#include <cuda_runtime.h>

namespace cms {
  namespace cuda {
/**
 * Returns the index of the current CUDA device
 *
 * @return The index of the current CUDA device
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline int currentDevice() {
      int dev;
      cudaCheck(cudaGetDevice(&dev));
      return dev;
    }
  }  // namespace cuda
}  // namespace cms

#endif
