#ifndef DataFormats_SiPixelRawData_interface_SiPixelErrorCompact_h
#define DataFormats_SiPixelRawData_interface_SiPixelErrorCompact_h

#include <cstdint>

/**
 * Brief description of struct representing pixel error information in compact form
 * Detailed description of struct members including rawId word errorType and fedId
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
struct SiPixelErrorCompact {
  uint32_t rawId;
  uint32_t word;
  uint8_t errorType;
  uint8_t fedId;
};

#endif  // DataFormats_SiPixelRawData_interface_SiPixelErrorCompact_h
