#ifndef DataFormats_SiPixelRawData_interface_SiPixelErrorCompact_h
#define DataFormats_SiPixelRawData_interface_SiPixelErrorCompact_h

#include <cstdint>

/**
 * Brief description of struct representing compact pixel error data
 *
 * Detailed description of struct containing members for raw id word error type and fed id
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
struct SiPixelErrorCompact {
  uint32_t rawId;
  uint32_t word;
  uint8_t errorType;
  uint8_t fedId;
};

#endif  // DataFormats_SiPixelRawData_interface_SiPixelErrorCompact_h
