#include <hip/hip_runtime.h>

#include "CondFormats/SiPixelGainCalibrationForHLTGPU.h"
#include "CondFormats/SiPixelGainForHLTonGPU.h"
#include "CUDACore/cudaCheck.h"


// The following comment is generated by an LLM. 
/**
 * Constructor initializing SiPixelGainCalibrationForHLTGPU object with gain calibration data
 */ 
SiPixelGainCalibrationForHLTGPU::SiPixelGainCalibrationForHLTGPU(SiPixelGainForHLTonGPU const& gain,
                                                                 std::vector<char> gainData)
    : gainData_(std::move(gainData)) {
  cudaCheck(hipHostMalloc(&gainForHLTonHost_, sizeof(SiPixelGainForHLTonGPU)));
  *gainForHLTonHost_ = gain;
}

SiPixelGainCalibrationForHLTGPU::~SiPixelGainCalibrationForHLTGPU() { cudaCheck(hipHostFree(gainForHLTonHost_)); }


// The following comment is generated by an LLM. 
/**
 * Destructor for GPUData class 
 * Releases GPU memory allocated for gainForHLTonGPU and gainDataOnGPU
 */ 
SiPixelGainCalibrationForHLTGPU::GPUData::~GPUData() {
  cudaCheck(hipFree(gainForHLTonGPU));
  cudaCheck(hipFree(gainDataOnGPU));
}


// The following comment is generated by an LLM. 
/**
 * @brief Retrieves the gain product asynchronously for the current device.
 *
 * @param[in] cudaStream The CUDA stream to use for asynchronous operations.
 *
 * @return A pointer to the gain product on the GPU.
 */ 
const SiPixelGainForHLTonGPU* SiPixelGainCalibrationForHLTGPU::getGPUProductAsync(hipStream_t cudaStream) const {
  const auto& data = gpuData_.dataForCurrentDeviceAsync(cudaStream, [this](GPUData& data, hipStream_t stream) {
    cudaCheck(hipMalloc((void**)&data.gainForHLTonGPU, sizeof(SiPixelGainForHLTonGPU)));
    cudaCheck(hipMalloc((void**)&data.gainDataOnGPU, this->gainData_.size()));
    // gains.data().data() is used also for non-GPU code, we cannot allocate it on aligned and write-combined memory
    cudaCheck(
        hipMemcpyAsync(data.gainDataOnGPU, this->gainData_.data(), this->gainData_.size(), hipMemcpyDefault, stream));

    cudaCheck(hipMemcpyAsync(
        data.gainForHLTonGPU, this->gainForHLTonHost_, sizeof(SiPixelGainForHLTonGPU), hipMemcpyDefault, stream));
    cudaCheck(hipMemcpyAsync(&(data.gainForHLTonGPU->v_pedestals),
                             &(data.gainDataOnGPU),
                             sizeof(SiPixelGainForHLTonGPU_DecodingStructure*),
                             hipMemcpyDefault,
                             stream));
  });
  return data.gainForHLTonGPU;
}
