#ifndef RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h
#define RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h

#include "CUDACore/ESProduct.h"
#include "CUDACore/HostAllocator.h"
#include "CUDACore/device_unique_ptr.h"
#include "CondFormats/SiPixelFedCablingMapGPU.h"

#include <hip/hip_runtime.h>

#include <set>

/**
 * @brief Wrapper class for managing SiPixelFedCablingMapGPU data on multiple GPUs.
 *
 * This class provides asynchronous access to SiPixelFedCablingMapGPU data on multiple GPUs,
 * along with associated module-to-unpack data. It handles memory allocation and deallocation
 * on both host and device memories, ensuring efficient data transfer and usage.
 
class SiPixelFedCablingMapGPUWrapper {
     * @brief Constructor for initializing the wrapper with cabling map and module-to-unpack data.
   *
   * @param cablingMap The input cabling map data structure.
   * @param modToUnp Module-to-unpack data.
   
     * @brief Destructor for releasing allocated resources.
   
 * @brief Checks if quality data is available.
 *
 * @return True if quality data exists, false otherwise.
 
    * @brief Retrieves a pointer to the GPU product asynchronously.
 *
 * @param cudaStream The CUDA stream handle for asynchronous operation.
 * @return Pointer to the GPU product.
 
    * @brief Retrieves a pointer to all module-to-unpack data asynchronously.
 *
 * @param cudaStream The CUDA stream handle for asynchronous operation.
 * @return Pointer to the module-to-unpack data.
 

 * @struct GPUData
 * @brief Structure representing GPU data, including a pointer to the cabling map on the device.
 *
 * Manages the lifetime of device memory for the cabling map.
 
    * @struct ModulesToUnpack
 * @brief Structure representing module-to-unpack data on the GPU.
 *
 * Handles the memory for unpacking modules on the device.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
class SiPixelFedCablingMapGPUWrapper {
public:
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap,
                                          std::vector<unsigned char> modToUnp);
  ~SiPixelFedCablingMapGPUWrapper();

  bool hasQuality() const { return hasQuality_; }

  // returns pointer to GPU memory
  const SiPixelFedCablingMapGPU *getGPUProductAsync(hipStream_t cudaStream) const;

  // returns pointer to GPU memory
  const unsigned char *getModToUnpAllAsync(hipStream_t cudaStream) const;

private:
  std::vector<unsigned char, cms::hip::HostAllocator<unsigned char>> modToUnpDefault;
  bool hasQuality_;

  SiPixelFedCablingMapGPU *cablingMapHost = nullptr;  // pointer to struct in CPU

  struct GPUData {
    ~GPUData();
    SiPixelFedCablingMapGPU *cablingMapDevice = nullptr;  // pointer to struct in GPU
  };
  cms::hip::ESProduct<GPUData> gpuData_;

  struct ModulesToUnpack {
    ~ModulesToUnpack();
    unsigned char *modToUnpDefault = nullptr;  // pointer to GPU
  };
  cms::hip::ESProduct<ModulesToUnpack> modToUnp_;
};

#endif
