#ifndef plugin_PixelTriplets_alpaka_CAHitNtupletGeneratorOnGPU_h
#define plugin_PixelTriplets_alpaka_CAHitNtupletGeneratorOnGPU_h

#include "AlpakaCore/SimpleVector.h"
#include "AlpakaCore/config.h"
//#include "AlpakaCore/memory.h"
#include "AlpakaDataFormats/alpaka/PixelTrackAlpaka.h"
#include "AlpakaDataFormats/alpaka/TrackingRecHit2DAlpaka.h"

#include "CAHitNtupletGeneratorKernels.h"
#include "GPUCACell.h"
#include "HelixFitOnGPU.h"

namespace edm {
  class Event;
  class EventSetup;
  class ProductRegistry;
}  // namespace edm

namespace ALPAKA_ACCELERATOR_NAMESPACE {
/**
 * @class CAHitNtupletGeneratorOnGPU
 * @brief Generates hit ntuplets on GPU
 * @details This class is responsible for generating hit ntuplets on the GPU
 *         It provides methods for making tuples asynchronously and launching kernels
 *         It uses various data structures such as HitsOnGPU, HitsOnCPU, and QualityCuts
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  class CAHitNtupletGeneratorOnGPU {
  public:
    using HitsOnGPU = TrackingRecHit2DSoAView;
    using HitsOnCPU = TrackingRecHit2DAlpaka;
    using hindex_type = TrackingRecHit2DSoAView::hindex_type;

    using Quality = pixelTrack::Quality;
    using OutputSoA = pixelTrack::TrackSoA;
    using HitContainer = pixelTrack::HitContainer;
    using Tuple = HitContainer;

    using QualityCuts = cAHitNtupletGenerator::QualityCuts;
    using Params = cAHitNtupletGenerator::Params;
    using Counters = cAHitNtupletGenerator::Counters;

  public:
    CAHitNtupletGeneratorOnGPU(edm::ProductRegistry& reg);
    ~CAHitNtupletGeneratorOnGPU() = default;

    PixelTrackAlpaka makeTuplesAsync(TrackingRecHit2DAlpaka const& hits_d, float bfield, Queue& queue) const;

  private:
#ifdef TODO
    void buildDoublets(HitsOnCPU const& hh, cudaStream_t stream) const;

    void hitNtuplets(HitsOnCPU const& hh, const edm::EventSetup& es, bool useRiemannFit, cudaStream_t cudaStream);

    void launchKernels(HitsOnCPU const& hh, bool useRiemannFit, cudaStream_t cudaStream) const;
#endif

    Params m_params;

    //cms::alpakatools::device_buffer<Device, Counters> m_counters;
  };
}  // namespace ALPAKA_ACCELERATOR_NAMESPACE

#endif  // plugin_PixelTriplets_alpaka_CAHitNtupletGeneratorOnGPU_h
