#ifndef KokkosCore_kokkosConfigCommon_h
#define KokkosCore_kokkosConfigCommon_h

#include <vector>
#include <memory>

// This header needs to be #included in a file that may not be
// compiled with nvcc.
namespace kokkos_common {
/**
 * @brief Manages initialization scope for various backends
 *
 * This class provides a way to initialize different backends such as serial, pthread, CUDA, or HIP
 * within a specific scope. It ensures proper cleanup when going out of scope.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  class InitializeScopeGuard {
  public:
    enum class Backend { SERIAL, PTHREAD, CUDA, HIP };

    explicit InitializeScopeGuard(std::vector<Backend> const& backends, int numberOfInnerThreads = 1);
    ~InitializeScopeGuard();

  private:
    class Impl;
    std::unique_ptr<Impl> pimpl_;
  };
}  // namespace kokkos_common

#endif
