#ifndef HeterogeneousCore_AlpakaCore_chooseDevice_h
#define HeterogeneousCore_AlpakaCore_chooseDevice_h

#include "AlpakaCore/alpakaConfig.h"
#include "AlpakaCore/alpakaDevices.h"
#include "Framework/Event.h"

namespace cms::alpakatools {

  template <typename TPlatform>
/**
 * @brief Returns a reference to the chosen alpaka device based on the EDM stream ID.
 *
 * @param id The EDM stream ID used to select the device.
 * @return A constant reference to the selected alpaka device.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  alpaka::Dev<TPlatform> const& chooseDevice(edm::StreamID id) {
    // For startes we "statically" assign the device based on
    // edm::Stream number. This is suboptimal if the number of
    // edm::Streams is not a multiple of the number of CUDA devices
    // (and even then there is no load balancing).

    // TODO: improve the "assignment" logic
    auto const& devices = cms::alpakatools::devices<TPlatform>;
    return devices[id % devices.size()];
  }

}  // namespace cms::alpakatools

#endif  // HeterogeneousCore_AlpakaCore_chooseDevice_h
