#ifndef HeterogeneousCore_AlpakaCore_ContextState_h
#define HeterogeneousCore_AlpakaCore_ContextState_h

#include <memory>
#include <stdexcept>
#include <utility>

#include <alpaka/alpaka.hpp>

namespace cms::alpakatools {

  template <typename TQueue>
  class ScopedContextAcquire;

  template <typename TQueue>
  class ScopedContextProduce;

  template <typename TQueue>
  class ScopedContextTask;

  /**
     * The purpose of this class is to deliver the device and CUDA stream
     * information from ExternalWork's acquire() to producer() via a
     * member/StreamCache variable.
     */
  template <typename TQueue>
  class ContextState {
  public:
    using Queue = TQueue;
    using Device = alpaka::Dev<Queue>;

    ContextState() = default;
    ~ContextState() = default;

    ContextState(const ContextState&) = delete;
    ContextState& operator=(const ContextState&) = delete;
    ContextState(ContextState&&) = delete;
    ContextState& operator=(ContextState&& other) = delete;

  private:
    friend class ScopedContextAcquire<TQueue>;
    friend class ScopedContextProduce<TQueue>;
    friend class ScopedContextTask<TQueue>;

/**
 * Sets the stream associated with this object.
 *
 * @param stream the new stream to associate with this object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    void set(std::shared_ptr<Queue> stream) {
      throwIfStream();
      stream_ = std::move(stream);
    }

/**
 * Returns the device associated with the current stream.
 *
 * @return The device object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    Device device() const {
      throwIfNoStream();
      return alpaka::getDev(*stream_);
    }

/**
 * Returns the queue stream associated with this object.
 *
 * @return the queue stream
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    Queue stream() const {
      throwIfNoStream();
      return *stream_;
    }

/**
 * Returns a constant reference to the shared pointer of the stream object.
 *
 * @return A constant reference to the shared pointer of the stream object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    std::shared_ptr<Queue> const& streamPtr() const {
      throwIfNoStream();
      return stream_;
    }

/**
 * @brief Releases the stream pointer.
 *
 * This function resets the internal stream state, ensuring it is empty after invocation.
 * The released stream pointer is returned as a shared pointer to facilitate memory management.
 *
 * @return A shared pointer to the released queue.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    std::shared_ptr<Queue> releaseStreamPtr() {
      throwIfNoStream();
      // This function needs to effectively reset stream_ (i.e. stream_
      // must be empty after this function). This behavior ensures that
      // the std::shared_ptr<Queue> is not hold for inadvertedly long (i.e. to
      // the next event), and is checked at run time.
      return std::move(stream_);
    }

/**
 * Throws an exception if a stream is present.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    void throwIfStream() const {
      if (stream_) {
        throw std::runtime_error("Trying to set ContextState, but it already had a valid state");
      }
    }

/**
 * Throws an exception if no stream is associated with this object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    void throwIfNoStream() const {
      if (not stream_) {
        throw std::runtime_error("Trying to get ContextState, but it did not have a valid state");
      }
    }

    std::shared_ptr<Queue> stream_;
  };

}  // namespace cms::alpakatools

#endif  // HeterogeneousCore_AlpakaCore_ContextState_h
