#ifndef FWCore_Concurrency_FunctorTask_h
#define FWCore_Concurrency_FunctorTask_h
// -*- C++ -*-
//
// Package:     Concurrency
// Class  :     FunctorTask
//
/**\class FunctorTask FunctorTask.h FWCore/Concurrency/interface/FunctorTask.h

 Description: Builds a tbb::task from a lambda.

 Usage:
 
*/
//
// Original Author:  Chris Jones
//         Created:  Thu Feb 21 13:46:31 CST 2013
// $Id$
//

// system include files
#include <atomic>
#include <exception>
#include <memory>

// user include files
#include "Framework/TaskBase.h"

// forward declarations

namespace edm {
  template <typename F>
/**
 * @class FunctorTask
 * @brief A task that executes a given functor
 * @details This class wraps a functor and provides a way to execute it as a task
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  class FunctorTask : public TaskBase {
  public:
    explicit FunctorTask(F f) : func_(std::move(f)) {}

    void execute() final { func_(); };

  private:
    F func_;
  };

  template <typename F>
  FunctorTask<F>* make_functor_task(F f) {
    return new FunctorTask<F>(std::move(f));
  }
}  // namespace edm

#endif
