#ifndef AlpakaDataFormats_alpaka_BeamSpotAlpaka_h
#define AlpakaDataFormats_alpaka_BeamSpotAlpaka_h

#include <alpaka/alpaka.hpp>

#include "AlpakaCore/config.h"
#include "AlpakaCore/memory.h"
#include "DataFormats/BeamSpotPOD.h"

namespace ALPAKA_ACCELERATOR_NAMESPACE {

/**
 * Brief description of the class.
 *
 * Detailed description of the class.
 
class BeamSpotAlpaka { * Default constructor deleted because alpaka buffers are not default constructible.
  * Constructor allocating cached device memory on the given queue.
 * @param queue The queue used for allocation.
  * Move constructor.
  * Deleted copy constructor.
  * Move assignment operator.
  * Deleted copy assignment operator.
  * Returns a pointer to the data.
 * @return Pointer to the data.
  * Returns a constant pointer to the data.
 * @return Constant pointer to the data.
  * Returns a reference to the buffer.
 * @return Reference to the buffer.
  * Returns a constant reference to the buffer.
 * @return Constant reference to the buffer.
  * Data member variable storing the device buffer.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  class BeamSpotAlpaka {
  public:
    // default constructor, required by cms::alpakatools::Product<Queue, BeamSpotAlpaka>
    BeamSpotAlpaka() = delete;  // alpaka buffers are not default-constructible

    // constructor that allocates cached device memory on the given queue
    BeamSpotAlpaka(Queue const& queue) : data_d_{cms::alpakatools::make_device_buffer<BeamSpotPOD>(queue)} {}

    // movable, non-copiable
    BeamSpotAlpaka(BeamSpotAlpaka const&) = delete;
    BeamSpotAlpaka(BeamSpotAlpaka&&) = default;
    BeamSpotAlpaka& operator=(BeamSpotAlpaka const&) = delete;
    BeamSpotAlpaka& operator=(BeamSpotAlpaka&&) = default;

    BeamSpotPOD* data() { return data_d_.data(); }
    BeamSpotPOD const* data() const { return data_d_.data(); }

    cms::alpakatools::device_buffer<Device, BeamSpotPOD>& buf() { return data_d_; }
    cms::alpakatools::device_buffer<Device, BeamSpotPOD> const& buf() const { return data_d_; }

  private:
    cms::alpakatools::device_buffer<Device, BeamSpotPOD> data_d_;
  };

}  // namespace ALPAKA_ACCELERATOR_NAMESPACE

#endif  // AlpakaDataFormats_alpaka_BeamSpotAlpaka_h
