#ifndef RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h
#define RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h

#include "CondFormats/SiPixelFedCablingMapGPU.h"

#include <set>

/**
 * @brief Wrapper class for SiPixelFedCablingMapGPU providing additional functionality
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
class SiPixelFedCablingMapGPUWrapper {
public:
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap,
                                          std::vector<unsigned char> modToUnp);
  ~SiPixelFedCablingMapGPUWrapper() = default;

  bool hasQuality() const { return hasQuality_; }

  const SiPixelFedCablingMapGPU *getCPUProduct() const { return &cablingMapHost; }

  const unsigned char *getModToUnpAll() const { return modToUnpDefault.data(); }

private:
  std::vector<unsigned char> modToUnpDefault;
  bool hasQuality_;

  SiPixelFedCablingMapGPU cablingMapHost;
};

#endif
