#ifndef FEDRawData_FEDRawDataCollection_h
#define FEDRawData_FEDRawDataCollection_h

/** \class FEDRawDataCollection
 *  An EDCollection storing the raw data for all  FEDs in a Event.
 *  
 *  Reference: DaqPrototype/DaqPersistentData/interface/DaqFEDOpaqueData.h
 *
 *  \author N. Amapane - S. Argiro'
 */

#include "DataFormats/FEDRawData.h"

#include <vector>

/**
 * @brief Class representing a collection of FED raw data.
 *
 * This class provides methods for retrieving and manipulating FED raw data.
 
class FEDRawDataCollection {
     * @brief Default constructor.
   
  FEDRawDataCollection();

     * @brief Virtual destructor.
   
  virtual ~FEDRawDataCollection();

     * @brief Retrieves constant reference to FED data for specified fedid.
   * @param fedid Identifier of the FED.
   * @return Constant reference to FEDRawData object.
   
  const FEDRawData& FEDData(int fedid) const;

     * @brief Retrieves non-constant reference to FED data for specified fedid.
   * @param fedid Identifier of the FED.
   * @return Non-constant reference to FEDRawData object.
   
  FEDRawData& FEDData(int fedid);

     * @brief Copy constructor.
   * @param other Another instance of FEDRawDataCollection.
   
  FEDRawDataCollection(const FEDRawDataCollection&);

     * @brief Swaps contents with another FEDRawDataCollection instance.
   * @param other Instance to swap with.
   
  void swap(FEDRawDataCollection& other);

private:
     * @brief Vector containing raw FED data.
   
  std::vector<FEDRawData> data_;
}* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
class FEDRawDataCollection {
public:
  FEDRawDataCollection();

  virtual ~FEDRawDataCollection();

  /// retrieve data for fed @param fedid
  const FEDRawData& FEDData(int fedid) const;

  /// retrieve data for fed @param fedid
  FEDRawData& FEDData(int fedid);

  FEDRawDataCollection(const FEDRawDataCollection&);

  void swap(FEDRawDataCollection& other) { data_.swap(other.data_); }

private:
  std::vector<FEDRawData> data_;  ///< the raw data
};

inline void swap(FEDRawDataCollection& a, FEDRawDataCollection& b) { a.swap(b); }

#endif
