#include "KokkosCore/kokkosConfigCommon.h"
#include "KokkosCore/kokkosConfig.h"
#include "KokkosCore/memoryTraits.h"

#include <iostream>

constexpr int ELEMENTS = 10;

template <typename ExecSpace>
KOKKOS_INLINE_FUNCTION void process(const Kokkos::View<int*, ExecSpace, Restrict>& data, int i) {
  data(i) = 2 * i;
}


// The following comment is generated by an LLM. 
/**
 * Tests the functionality of Kokkos views and parallel execution
  
void test() {
     * Creates a device view of integers with the label data_d and size ELEMENTS
   
  Kokkos::View<int*, KokkosExecSpace, Restrict> data_d("data_d", ELEMENTS);
  
     * Creates a host mirror view of the device view data_d
   
  auto data_h = Kokkos::create_mirror_view(data_d);
  
     * Initializes the host view with values from 0 to ELEMENTS-1
   
  for (int i = 0; i < ELEMENTS; ++i) {
    data_h[i] = i;
  }
  
     * Copies the data from the host view to the device view
   
  Kokkos::deep_copy(KokkosExecSpace(), data_d, data_h);
  
     * Executes a parallel loop over the range 0 to ELEMENTS-1 on the device
   * and applies the lambda function to each iteration
   
  Kokkos::parallel_for(
      Kokkos::RangePolicy<KokkosExecSpace>(KokkosExecSpace(), 0, ELEMENTS),
      KOKKOS_LAMBDA(int i) { process(data_d, i); });
  
     * Copies the data from the device view back to the host view
   
  Kokkos::deep_copy(KokkosExecSpace(), data_h, data_d);
  
     * Inserts a fence to ensure all previous operations are complete
   
  Kokkos::fence();
  
     * Prints the values of the host view to the console
   
  for (int i = 0; i < ELEMENTS; ++i) {
    std::cout << i << " " << data_h(i) << std::endl;
  }
}*/ 
void test() {
  Kokkos::View<int*, KokkosExecSpace, Restrict> data_d("data_d", ELEMENTS);
  auto data_h = Kokkos::create_mirror_view(data_d);
  for (int i = 0; i < ELEMENTS; ++i) {
    data_h[i] = i;
  }
  Kokkos::deep_copy(KokkosExecSpace(), data_d, data_h);

  Kokkos::parallel_for(
      Kokkos::RangePolicy<KokkosExecSpace>(KokkosExecSpace(), 0, ELEMENTS),
      KOKKOS_LAMBDA(int i) { process(data_d, i); });
  Kokkos::deep_copy(KokkosExecSpace(), data_h, data_d);
  Kokkos::fence();
  for (int i = 0; i < ELEMENTS; ++i) {
    std::cout << i << " " << data_h(i) << std::endl;
  }
}


// The following comment is generated by an LLM. 
/**
 * Main program entry point initializes Kokkos scope and executes test function
 */ 
int main() {
  kokkos_common::InitializeScopeGuard kokkosGuard({KokkosBackend<KokkosExecSpace>::value});
  test();
  return 0;
}
