#ifndef FWCore_Concurrency_TaskBase_h
#define FWCore_Concurrency_TaskBase_h
// -*- C++ -*-
//
// Package:     Concurrency
// Class  :     TaskBase
//
/**\class TaskBase TaskBase.h FWCore/Concurrency/interface/TaskBase.h

 Description: Base class for tasks.

 Usage:
    Used as a callback to happen after a task has been completed.
*/
//
// Original Author:  Chris Jones
//         Created:  Tue Jan 5 13:46:31 CST 2020
// $Id$
//

// system include files
#include <atomic>
#include <exception>
#include <memory>

// user include files

// forward declarations

namespace edm {
/**
 * @brief Base class for tasks that provides reference counting and execution functionality.
 *
 * This class serves as a foundation for tasks that need to be executed and managed.
 * It includes a reference count to track the number of references to the task,
 * as well as a pure virtual function to execute the task.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  class TaskBase {
  public:
    friend class TaskSentry;

    ///Constructor
    TaskBase() : m_refCount{0} {}
    virtual ~TaskBase() = default;

    virtual void execute() = 0;

    void increment_ref_count() { ++m_refCount; }
    unsigned int decrement_ref_count() { return --m_refCount; }

  private:
    virtual void recycle() { delete this; }

    std::atomic<unsigned int> m_refCount{0};
  };

/**
 * Class representing a sentry for tasks providing automatic task recycling 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  class TaskSentry {
  public:
    TaskSentry(TaskBase* iTask) : m_task{iTask} {}
    ~TaskSentry() { m_task->recycle(); }
    TaskSentry() = delete;
    TaskSentry(TaskSentry const&) = delete;
    TaskSentry(TaskSentry&&) = delete;
    TaskSentry operator=(TaskSentry const&) = delete;
    TaskSentry operator=(TaskSentry&&) = delete;

  private:
    TaskBase* m_task;
  };
}  // namespace edm

#endif
