#ifndef FEDRawData_FEDRawDataCollection_h
#define FEDRawData_FEDRawDataCollection_h

/** \class FEDRawDataCollection
 *  An EDCollection storing the raw data for all  FEDs in a Event.
 *  
 *  Reference: DaqPrototype/DaqPersistentData/interface/DaqFEDOpaqueData.h
 *
 *  \author N. Amapane - S. Argiro'
 */

#include "DataFormats/FEDRawData.h"

#include <vector>

/**
 * @brief Class representing a collection of raw data from Front End Devices (FEDs)
 *
 * Provides methods for retrieving and manipulating raw data from FEDs
 
class FEDRawDataCollection {
     * @brief Default constructor
   
  FEDRawDataCollection();
     * @brief Virtual destructor
   
  virtual ~FEDRawDataCollection();
     * @brief Retrieves constant reference to raw data for specified FED
   * @param fedid Identifier of the FED
   * @return Constant reference to raw data
   
  const FEDRawData& FEDData(int fedid) const;
     * @brief Retrieves non-constant reference to raw data for specified FED
   * @param fedid Identifier of the FED
   * @return Non-constant reference to raw data
   
  FEDRawData& FEDData(int fedid);
     * @brief Copy constructor
   * @param other Instance to copy from
   
  FEDRawDataCollection(const FEDRawDataCollection&);
     * @brief Swaps contents with another instance
   * @param other Instance to swap with
   
  void swap(FEDRawDataCollection& other);
  
private:   * @brief Vector containing raw data from FEDs
   
  std::vector<FEDRawData> data_;
}* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
class FEDRawDataCollection {
public:
  FEDRawDataCollection();

  virtual ~FEDRawDataCollection();

  /// retrieve data for fed @param fedid
  const FEDRawData& FEDData(int fedid) const;

  /// retrieve data for fed @param fedid
  FEDRawData& FEDData(int fedid);

  FEDRawDataCollection(const FEDRawDataCollection&);

  void swap(FEDRawDataCollection& other) { data_.swap(other.data_); }

private:
  std::vector<FEDRawData> data_;  ///< the raw data
};

inline void swap(FEDRawDataCollection& a, FEDRawDataCollection& b) { a.swap(b); }

#endif
