#include <cassert>
#include <iostream>

#include "AlpakaCore/AtomicPairCounter.h"
#include "AlpakaCore/alpaka/devices.h"
#include "AlpakaCore/initialise.h"
#include "AlpakaCore/memory.h"
#include "AlpakaCore/workdivision.h"

using namespace cms::alpakatools;
using namespace ALPAKA_ACCELERATOR_NAMESPACE;

struct update {
  template <typename TAcc>

// The following comment is generated by an LLM. 
/**
 * @brief Performs an operation on a grid of elements with atomic pair counter updates
 * @param acc access object for the grid
 * @param dc pointer to atomic pair counter
 * @param ind array to store indices
 * @param cont array to store content
 * @param n number of elements in the grid
 */ 
  ALPAKA_FN_ACC void operator()(
      const TAcc &acc, AtomicPairCounter *dc, uint32_t *ind, uint32_t *cont, uint32_t n) const {
    for_each_element_in_grid(acc, n, [&](uint32_t i) {
      auto m = i % 11;
      m = m % 6 + 1;  // max 6, no 0
      auto c = dc->add(acc, m);
      assert(c.m < n);
      ind[c.m] = c.n;
      for (uint32_t j = c.n; j < c.n + m; ++j)
        cont[j] = i;
    });
  }
};

struct finalize {
  template <typename TAcc>

// The following comment is generated by an LLM. 
/**
 * @brief Performs operation on accelerator with atomic pair counter
 * @param acc Accelerator object
 * @param dc Pointer to atomic pair counter
 * @param ind Array of indices
 * @param cont Array of counters
 * @param n Size of arrays
 */ 
  ALPAKA_FN_ACC void operator()(
      const TAcc &acc, AtomicPairCounter const *dc, uint32_t *ind, uint32_t *cont, uint32_t n) const {
    assert(dc->get().m == n);
    ind[n] = dc->get().n;
  }
};

struct verify {
  template <typename TAcc>

// The following comment is generated by an LLM. 
/**
 * @brief Checks the consistency of the index and counter data structures.
 *
 * This function iterates over all elements in the grid and verifies that the 
 * indices and counters are correctly aligned and contain the expected values.
 *
 * @param acc The accelerator object used for parallel execution.
 * @param dc A pointer to an atomic pair counter object.
 * @param ind An array of indices.
 * @param cont An array of container indices.
 * @param n The number of elements in the grid.
 */ 
  ALPAKA_FN_ACC void operator()(
      const TAcc &acc, AtomicPairCounter const *dc, uint32_t const *ind, uint32_t const *cont, uint32_t n) const {
    for_each_element_in_grid(acc, n, [&](uint32_t i) {
      assert(0 == ind[0]);
      assert(dc->get().m == n);
      assert(ind[n] == dc->get().n);
      auto ib = ind[i];
      auto ie = ind[i + 1];
#ifndef NDEBUG
      auto k = cont[ib++];
#endif
      assert(k < n);
      for (; ib < ie; ++ib)
        assert(cont[ib] == k);
    });
  }
};


// The following comment is generated by an LLM. 
/**
 * @brief Main program entry point
 *
 * Initializes the application, sets up the device and queue, 
 * performs updates and finalization on the data, and verifies the results.
 */ 
int main() {
  initialise();
  const Device device = devices<Platform>().at(0);
  Queue queue(device);

  auto c_d = make_device_buffer<AtomicPairCounter>(queue);
  alpaka::memset(queue, c_d, 0);

  std::cout << "size " << sizeof(AtomicPairCounter) << std::endl;

  constexpr uint32_t N = 20000;
  constexpr uint32_t M = N * 6;
  auto n_d = make_device_buffer<uint32_t[]>(queue, N);
  auto m_d = make_device_buffer<uint32_t[]>(queue, M);

  constexpr uint32_t NUM_VALUES = 10000;

  // Update
  const auto blocksPerGrid = 2000u;
  const auto threadsPerBlockOrElementsPerThread = 512u;
  const auto workDiv = make_workdiv<Acc1D>(blocksPerGrid, threadsPerBlockOrElementsPerThread);
  alpaka::enqueue(queue,
                  alpaka::createTaskKernel<Acc1D>(workDiv, update(), c_d.data(), n_d.data(), m_d.data(), NUM_VALUES));

  // Finalize
  const auto blocksPerGridFinalize = 1u;
  const auto threadsPerBlockOrElementsPerThreadFinalize = 1u;
  const auto workDivFinalize = make_workdiv<Acc1D>(blocksPerGridFinalize, threadsPerBlockOrElementsPerThreadFinalize);
  alpaka::enqueue(
      queue,
      alpaka::createTaskKernel<Acc1D>(workDivFinalize, finalize(), c_d.data(), n_d.data(), m_d.data(), NUM_VALUES));

  // Verify
  alpaka::enqueue(queue,
                  alpaka::createTaskKernel<Acc1D>(workDiv, verify(), c_d.data(), n_d.data(), m_d.data(), NUM_VALUES));

  auto c_h = make_host_buffer<AtomicPairCounter>(queue);
  alpaka::memcpy(queue, c_h, c_d);
  alpaka::wait(queue);

  std::cout << c_h->get().n << ' ' << c_h->get().m << std::endl;

  return 0;
}
