#include <iostream>

#include "AlpakaCore/alpaka/devices.h"
#include "AlpakaCore/initialise.h"
#include "AlpakaCore/memory.h"
#include "AlpakaCore/prefixScan.h"
#include "AlpakaCore/workdivision.h"

using namespace cms::alpakatools;
using namespace ALPAKA_ACCELERATOR_NAMESPACE;

template <typename T>
struct format_traits {
public:
  static const constexpr char* failed_msg = "failed %d %d %d: %d %d\n";
};

template <>
struct format_traits<float> {
public:
  static const constexpr char* failed_msg = "failed %d %d %d: %f %f\n";
};

template <typename T>
struct testPrefixScan {
  template <typename TAcc>

// The following comment is generated by an LLM. 
/**
 * Performs parallel operations on an array of elements within a block.
 *
 * @param acc accelerator object
 * @param size number of elements in the block
 */  ALPAKA_FN_ACC void operator()(const TAcc& acc, unsigned int size) const {
    auto& ws = alpaka::declareSharedVar<T[32], __COUNTER__>(acc);
    auto& c = alpaka::declareSharedVar<T[1024], __COUNTER__>(acc);
    auto& co = alpaka::declareSharedVar<T[1024], __COUNTER__>(acc);

    for_each_element_in_block_strided(acc, size, [&](uint32_t i) { c[i] = 1; });

    alpaka::syncBlockThreads(acc);

    blockPrefixScan(acc, c, co, size, ws);
    blockPrefixScan(acc, c, size, ws);

    assert(1 == c[0]);
    assert(1 == co[0]);

    for_each_element_in_block_strided(acc, size, 1u, [&](uint32_t i) {
      assert(c[i] == c[i - 1] + 1);
      assert(c[i] == i + 1);
      assert(c[i] == co[i]);
    });
  }
};

/*
 * NB: GPU-only, so do not care about elements here.
 */
template <typename T>
struct testWarpPrefixScan {
  template <typename TAcc>

// The following comment is generated by an LLM. 
/**
 * Performs an operation on the given accelerator with the specified size.
 *
 * @param acc The accelerator to perform the operation on.
 * @param size The size of the operation.
 */  ALPAKA_FN_ACC void operator()(const TAcc& acc, uint32_t size) const {
#if defined(ALPAKA_ACC_GPU_CUDA_ASYNC_BACKEND) && defined(__CUDA_ARCH__) || \
    defined(ALPAKA_ACC_GPU_HIP_ASYNC_BACKEND) && defined(__HIP_DEVICE_COMPILE__)
    assert(size <= 32);
    auto& c = alpaka::declareSharedVar<T[1024], __COUNTER__>(acc);
    auto& co = alpaka::declareSharedVar<T[1024], __COUNTER__>(acc);

    uint32_t const blockDimension = alpaka::getWorkDiv<alpaka::Block, alpaka::Threads>(acc)[0u];
    uint32_t const blockThreadIdx = alpaka::getIdx<alpaka::Block, alpaka::Threads>(acc)[0u];
    auto i = blockThreadIdx;
    c[i] = 1;
    alpaka::syncBlockThreads(acc);
    auto laneId = blockThreadIdx & 0x1f;

    warpPrefixScan(laneId, c, co, i, 0xffffffff);
    warpPrefixScan(laneId, c, i, 0xffffffff);

    alpaka::syncBlockThreads(acc);

    assert(1 == c[0]);
    assert(1 == co[0]);
    if (i != 0) {
      if (c[i] != c[i - 1] + 1)
        printf(format_traits<T>::failed_msg, size, i, blockDimension, c[i], c[i - 1]);
      assert(c[i] == c[i - 1] + 1);
      assert(c[i] == static_cast<T>(i + 1));
      assert(c[i] == co[i]);
    }
#endif
  }
};

struct init {
  template <typename TAcc>

// The following comment is generated by an LLM. 
/**
 * Performs an operation on a grid of elements setting each element to a specified value
 * @param acc accelerator object used for parallelization
 * @param v pointer to the array of values to be modified
 * @param val new value assigned to each element in the array
 * @param n number of elements in the grid
 */  ALPAKA_FN_ACC void operator()(const TAcc& acc, uint32_t* v, uint32_t val, uint32_t n) const {
    for_each_element_in_grid(acc, n, [&](uint32_t index) {
      v[index] = val;

      if (index == 0)
        printf("init\n");
    });
  }
};

struct verify {
  template <typename TAcc>

// The following comment is generated by an LLM. 
/**
 * Performs verification of grid elements against expected values.
 *
 * @param[in] acc Accessor object for grid operations
 * @param[in] v Array of values to verify
 * @param[in] n Number of elements in the array
 */  ALPAKA_FN_ACC void operator()(const TAcc& acc, uint32_t const* v, uint32_t n) const {
    for_each_element_in_grid(acc, n, [&](uint32_t index) {
      assert(v[index] == index + 1);

      if (index == 0)
        printf("verify\n");
    });
  }
};


// The following comment is generated by an LLM. 
/**
 * @brief Main program entry point.
 *
 * This is the primary function where program execution begins.
 
  * @brief Initializes the environment.
 *
 * Performs necessary setup and initialization tasks.
 
  * @brief Retrieves a reference to the default device.
 *
 * Returns a constant reference to the first available device.
 *
 * @return A constant reference to the default device.
 
  * @brief Creates a command queue object.
 *
 * Constructs a new queue instance associated with the specified device.
 *
 * @param device The device to associate the queue with.
 
  * @brief Configures warp-level parallelism parameters.
 *
 * Defines constants for threads per block and blocks per grid.
 
  * @brief Computes work division for warp-level operations.
 *
 * Calculates the work division based on the number of blocks and threads.
 *
 * @tparam Acc1D Accelerator type.
 * @param blocksPerGrid Number of blocks per grid.
 * @param threadsPerBlockOrElementsPerThread Threads per block or elements per thread.
 * @return Work division configuration.
 
  * @brief Enqueues a task kernel for warp prefix scan operation.
 *
 * Submits a kernel launch request for executing the warp prefix scan task.
 *
 * @tparam Acc1D Accelerator type.
 * @param workDivWork Division of work among threads.
 * @param func Task kernel function to execute.
 * @param arg Argument to pass to the kernel function.
 
  * @brief Prints a message indicating block-level processing.
 
  * @brief Iterates over various block sizes for portable block prefix scan.
 *
 * Loops through different block sizes from 32 to 1024.
 
  * @brief Configures block-level parallelism parameters.
 *
 * Defines constants for blocks per grid and threads per block.
 
  * @brief Computes work division for block-level operations.
 *
 * Calculates the work division based on the number of blocks and threads.
 *
 * @tparam Acc1D Accelerator type.
 * @param blocksPerGrid2 Number of blocks per grid.
 * @param bs Threads per block or elements per thread.
 * @return Work division configuration.
 
  * @brief Enqueues a task kernel for portable block prefix scan operation.
 *
 * Submits a kernel launch request for executing the block prefix scan task.
 *
 * @tparam Acc1D Accelerator type.
 * @param workDivSingleBlock Division of work among threads.
 * @param func Task kernel function to execute.
 * @param j Problem size.
 
  * @brief Iterates over multiple block sizes for multiblock prefix scan.
 *
 * Loops through increasing problem sizes.
 
  * @brief Allocates device buffer memory.
 *
 * Creates a new device buffer with the specified capacity.
 *
 * @tparam T Data type stored in the buffer.
 * @param queue Command queue to associate the buffer with.
 * @param numItems Capacity of the buffer.
 * @return Device buffer handle.
 
  * @brief Initializes data in the device buffer.
 *
 * Launches an initialization kernel to set up the buffer contents.
 *
 * @param workDivMultiBlockInit Work division configuration.
 * @param func Initialization kernel function.
 * @param input_d Input buffer handle.
 * @param value Initial value to fill the buffer with.
 * @param numItems Buffer capacity.
 
  * @brief Configures multiblock-level parallelism parameters.
 *
 * Defines constants for threads per block and blocks per grid.
 
  * @brief Computes work division for multiblock-level operations.
 *
 * Calculates the work division based on the number of blocks and threads.
 *
 * @tparam Acc1D Accelerator type.
 * @param nBlocks Number of blocks.
 * @param nThreads Number of threads per block.
 * @return Work division configuration.
 
  * @brief Enqueues a task kernel for multiblock prefix scan operation.
 *
 * Submits a kernel launch request for executing the multiblock prefix scan task.
 *
 * @tparam Acc1D Accelerator type.
 * @param workDivMultiBlock Division of work among threads.
 * @param func Multiblock prefix scan kernel function.
 * @param input_d Input buffer handle.
 * @param output_d Output buffer handle.
 * @param numItems Buffer capacity.
 
  * @brief Verifies results after multiblock prefix scan operation.
 *
 * Launches a verification kernel to check the output buffer contents.
 *
 * @param workDivMultiBlock Division of work among threads.
 * @param func Verification kernel function.
 * @param output_d Output buffer handle.
 * @param numItems Buffer capacity.
 */int main() {
  initialise();
  Device const& device = devices<Platform>().at(0);
  Queue queue(device);

  // WARP PREFIXSCAN (OBVIOUSLY GPU-ONLY)
#if defined(ALPAKA_ACC_GPU_CUDA_ASYNC_BACKEND) || defined(ALPAKA_ACC_GPU_HIP_ASYNC_BACKEND)
  std::cout << "warp level" << std::endl;

  const auto threadsPerBlockOrElementsPerThread = 32;
  const auto blocksPerGrid = 1;
  const auto workDivWarp = make_workdiv<Acc1D>(blocksPerGrid, threadsPerBlockOrElementsPerThread);

  alpaka::enqueue(queue, alpaka::createTaskKernel<Acc1D>(workDivWarp, testWarpPrefixScan<int>(), 32));
  alpaka::enqueue(queue, alpaka::createTaskKernel<Acc1D>(workDivWarp, testWarpPrefixScan<int>(), 16));
  alpaka::enqueue(queue, alpaka::createTaskKernel<Acc1D>(workDivWarp, testWarpPrefixScan<int>(), 5));
#endif

  // PORTABLE BLOCK PREFIXSCAN
  std::cout << "block level" << std::endl;

  // Running kernel with 1 block, and bs threads per block or elements per thread.
  // NB: obviously for tests only, for perf would need to use bs = 1024 in GPU version.
  for (int bs = 32; bs <= 1024; bs += 32) {
    const auto blocksPerGrid2 = 1;
    const auto workDivSingleBlock = make_workdiv<Acc1D>(blocksPerGrid2, bs);

    std::cout << "blocks per grid: " << blocksPerGrid2 << ", threads per block or elements per thread: " << bs
              << std::endl;

    // Problem size
    for (int j = 1; j <= 1024; ++j) {
      alpaka::enqueue(queue, alpaka::createTaskKernel<Acc1D>(workDivSingleBlock, testPrefixScan<uint16_t>(), j));
      alpaka::enqueue(queue, alpaka::createTaskKernel<Acc1D>(workDivSingleBlock, testPrefixScan<float>(), j));
    }
  }

  // PORTABLE MULTI-BLOCK PREFIXSCAN
  int num_items = 200;
  for (int ksize = 1; ksize < 4; ++ksize) {
    std::cout << "multiblock" << std::endl;
    num_items *= 10;

    auto input_d = make_device_buffer<uint32_t[]>(queue, num_items);
    auto output1_d = make_device_buffer<uint32_t[]>(queue, num_items);

    const auto nThreadsInit = 256;  // NB: 1024 would be better
    const auto nBlocksInit = divide_up_by(num_items, nThreadsInit);
    const auto workDivMultiBlockInit = make_workdiv<Acc1D>(nBlocksInit, nThreadsInit);

    alpaka::enqueue(queue,
                    alpaka::createTaskKernel<Acc1D>(workDivMultiBlockInit, init(), input_d.data(), 1, num_items));

    const auto nThreads = 1024;
    const auto nBlocks = divide_up_by(num_items, nThreads);
    const auto workDivMultiBlock = make_workdiv<Acc1D>(nBlocks, nThreads);

    std::cout << "launch multiBlockPrefixScan " << num_items << ' ' << nBlocks << std::endl;
    alpaka::enqueue(
        queue,
        alpaka::createTaskKernel<Acc1D>(
            workDivMultiBlock, multiBlockPrefixScanFirstStep<uint32_t>(), input_d.data(), output1_d.data(), num_items));

    const auto blocksPerGridSecondStep = 1;
    const auto workDivMultiBlockSecondStep = make_workdiv<Acc1D>(blocksPerGridSecondStep, nThreads);
    alpaka::enqueue(queue,
                    alpaka::createTaskKernel<Acc1D>(workDivMultiBlockSecondStep,
                                                    multiBlockPrefixScanSecondStep<uint32_t>(),
                                                    input_d.data(),
                                                    output1_d.data(),
                                                    num_items,
                                                    nBlocks));

    alpaka::enqueue(queue, alpaka::createTaskKernel<Acc1D>(workDivMultiBlock, verify(), output1_d.data(), num_items));

    alpaka::wait(queue);  // input_d and output1_d end of scope
  }                       // ksize

  return 0;
}
