#ifndef RecoPixelVertexing__PixelTrackFitting__test_common_h
#define RecoPixelVertexing__PixelTrackFitting__test_common_h

#include <algorithm>
#include <cassert>
#include <random>

template <class C>
/**
 * @brief Prints the contents of a matrix to the console.
 *
 * @param m The matrix to be printed.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
__host__ __device__ void printIt(C* m) {
#ifdef TEST_DEBUG
  printf("\nMatrix %dx%d\n", (int)m->rows(), (int)m->cols());
  for (u_int r = 0; r < m->rows(); ++r) {
    for (u_int c = 0; c < m->cols(); ++c) {
      printf("Matrix(%d,%d) = %f\n", r, c, (*m)(r, c));
    }
  }
#endif
}

template <class C1, class C2>
/**
 * Checks if two matrices are equal within a fuzzy tolerance.
 *
 * @param a First matrix to compare.
 * @param b Second matrix to compare.
 * @param epsilon Fuzzy tolerance factor.
 * @return True if matrices are equal within tolerance, false otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
bool isEqualFuzzy(C1 a, C2 b, double epsilon = 1e-6) {
  for (unsigned int i = 0; i < a.rows(); ++i) {
    for (unsigned int j = 0; j < a.cols(); ++j) {
      assert(std::abs(a(i, j) - b(i, j)) < std::min(std::abs(a(i, j)), std::abs(b(i, j))) * epsilon);
    }
  }
  return true;
}

bool isEqualFuzzy(double a, double b, double epsilon = 1e-6) {
  return std::abs(a - b) < std::min(std::abs(a), std::abs(b)) * epsilon;
}

template <typename T>
/**
 * Fills a matrix with random values between 0.0 and 2.0.
 *
 * @param t the matrix to be filled
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
void fillMatrix(T& t) {
  std::random_device rd;
  std::mt19937 gen(rd());
  std::uniform_real_distribution<> dis(0.0, 2.0);
  for (int row = 0; row < t.rows(); ++row) {
    for (int col = 0; col < t.cols(); ++col) {
      t(row, col) = dis(gen);
    }
  }
  return;
}

#endif
