#include "CUDACore/cudaCheck.h"

#include "gpuClusterTracksByDensity.h"
#include "gpuClusterTracksDBSCAN.h"
#include "gpuClusterTracksIterative.h"
#include "gpuFitVertices.h"
#include "gpuSortByPt2.h"
#include "gpuSplitVertices.h"

#undef PIXVERTEX_DEBUG_PRODUCE

namespace gpuVertexFinder {

  // reject outlier tracks that contribute more than this to the chi2 of the vertex fit
  constexpr float maxChi2ForFirstFit = 50.f;
  constexpr float maxChi2ForFinalFit = 5000.f;

  // split vertices with a chi2/NDoF greater than this
  constexpr float maxChi2ForSplit = 9.f;


// The following comment is generated by an LLM. 
/**
 * Loads tracks from a TrackSoA object into a workspace.
 * @param[in] ptracks pointer to TrackSoA object containing track data
 * @param[out] soa pointer to ZVertexSoA object to store loaded tracks
 * @param[out] pws pointer to WorkSpace object to store additional track data
 * @param[in] ptMin minimum transverse momentum required for a track to be loaded
 */ 
  __global__ void loadTracks(TkSoA const* ptracks, ZVertexSoA* soa, WorkSpace* pws, float ptMin) {
    assert(ptracks);
    assert(soa);
    auto const& tracks = *ptracks;
    auto const& fit = tracks.stateAtBS;
    auto const* quality = tracks.qualityData();

    auto first = blockIdx.x * blockDim.x + threadIdx.x;
    for (int idx = first, nt = TkSoA::stride(); idx < nt; idx += gridDim.x * blockDim.x) {
      auto nHits = tracks.nHits(idx);
      if (nHits == 0)
        break;  // this is a guard: maybe we need to move to nTracks...

      // initialize soa...
      soa->idv[idx] = -1;

      if (nHits < 4)
        continue;  // no triplets
      if (quality[idx] != pixelTrack::Quality::loose)
        continue;

      auto pt = tracks.pt(idx);

      if (pt < ptMin)
        continue;

      auto& data = *pws;
      auto it = atomicAdd(&data.ntrks, 1);
      data.itrk[it] = idx;
      data.zt[it] = tracks.zip(idx);
      data.ezt2[it] = fit.covariance(idx)(14);
      data.ptt2[it] = pt * pt;
    }
  }

// #define THREE_KERNELS
#ifndef THREE_KERNELS

// The following comment is generated by an LLM. 
/**
 * @brief Finds vertices in a set of data using density-based clustering
 * @param[in] pdata pointer to ZVertices data structure
 * @param[in,out] pws pointer to WorkSpace data structure
 * @param[in] minT minimum number of neighbors required to seed a cluster
 * @param[in] eps maximum absolute distance to consider points part of a cluster
 * @param[in] errmax maximum error allowed for seeding a cluster
 * @param[in] chi2max maximum normalized distance to consider points part of a cluster
 */ 
  __global__ void vertexFinderOneKernel(gpuVertexFinder::ZVertices* pdata,
                                        gpuVertexFinder::WorkSpace* pws,
                                        int minT,      // min number of neighbours to be "seed"
                                        float eps,     // max absolute distance to cluster
                                        float errmax,  // max error to be "seed"
                                        float chi2max  // max normalized distance to cluster,
  ) {
    clusterTracksByDensity(pdata, pws, minT, eps, errmax, chi2max);
    __syncthreads();
    fitVertices(pdata, pws, maxChi2ForFirstFit);
    __syncthreads();
    splitVertices(pdata, pws, maxChi2ForSplit);
    __syncthreads();
    fitVertices(pdata, pws, maxChi2ForFinalFit);
    __syncthreads();
    sortByPt2(pdata, pws);
  }
#else

// The following comment is generated by an LLM. 
/**
 * @brief Finds vertices in a set of data points using density-based clustering
 * @param[in] pdata pointer to ZVertices data structure
 * @param[in,out] pws pointer to WorkSpace data structure
 * @param[in] minT minimum number of neighbors required to seed a cluster
 * @param[in] eps maximum absolute distance to consider two points part of same cluster
 * @param[in] errmax maximum error allowed for seeding a cluster
 * @param[in] chi2max maximum normalized distance to consider two points part of same cluster
 */ 
  __global__ void vertexFinderKernel1(gpuVertexFinder::ZVertices* pdata,
                                      gpuVertexFinder::WorkSpace* pws,
                                      int minT,      // min number of neighbours to be "seed"
                                      float eps,     // max absolute distance to cluster
                                      float errmax,  // max error to be "seed"
                                      float chi2max  // max normalized distance to cluster,
  ) {
    clusterTracksByDensity(pdata, pws, minT, eps, errmax, chi2max);
    __syncthreads();
    fitVertices(pdata, pws, maxChi2ForFirstFit);
  }


// The following comment is generated by an LLM. 
/**
 * @brief Finds vertices in parallel using GPU acceleration
 * @param pdata pointer to ZVertices data structure
 * @param pws pointer to WorkSpace data structure
 */ 
  __global__ void vertexFinderKernel2(gpuVertexFinder::ZVertices* pdata, gpuVertexFinder::WorkSpace* pws) {
    fitVertices(pdata, pws, maxChi2ForFinalFit);
    __syncthreads();
    sortByPt2(pdata, pws);
  }
#endif

#ifdef __CUDACC__

// The following comment is generated by an LLM. 
/**
 * @brief Produces heterogeneous vertices from tracks.
 *
 * This function generates vertices from an array of tracks and returns them as a unique pointer.
 * It uses either the GPU or CPU depending on compilation flags.
 *
 * @param stream CUDA stream object for asynchronous execution on the GPU.
 * @param tksoa Array of tracks used to produce vertices.
 * @param ptMin Minimum transverse momentum required for track consideration.
 *
 * @return Unique pointer to the produced heterogeneous vertices.
  
 * @brief Initializes the workspace for vertex production.
 *
 * This function sets up the necessary data structures for finding vertices.
 *
 * @param soa Structure of arrays containing vertex data.
 * @param ws_d Workspace object containing necessary data for vertex finding.
 
  * @brief Loads tracks into the vertex finder.
 *
 * This function transfers track data into the vertex finder's data structure.
 *
 * @param tksoa Array of tracks to be loaded.
 * @param soa Structure of arrays containing vertex data.
 * @param ws_d Workspace object containing necessary data for vertex finding.
 * @param ptMin Minimum transverse momentum required for track consideration.
 
 * @brief Finds vertices in the loaded tracks.
 *
 * This function implements various clustering algorithms to identify vertices.
 *
 * @param soa Structure of arrays containing vertex data.
 * @param ws_d Workspace object containing necessary data for vertex finding.
 * @param minT Minimum value for some parameter.
 * @param eps Some epsilon value.
 * @param errmax Maximum error allowed.
 * @param chi2max Maximum chi-squared value.
 
 * @brief Fits vertices after clustering.
 *
 * This function performs a fitting procedure on the identified vertices.
 *
 * @param soa Structure of arrays containing vertex data.
 * @param ws_d Workspace object containing necessary data for vertex finding.
 * @param maxChi2ForFirstFit Maximum chi-squared value for first fit.
 
 * @brief Splits vertices based on some criteria.
 *
 * This function takes the fitted vertices and splits them further if needed.
 *
 * @param soa Structure of arrays containing vertex data.
 * @param ws_d Workspace object containing necessary data for vertex finding.
 * @param maxChi2ForSplit Maximum chi-squared value for splitting.
 
 * @brief Sorts vertices by their pT values.
 *
 * This function rearranges the vertices based on their transverse momenta.
 *
 * @param soa Structure of arrays containing vertex data.
 * @param ws_d Workspace object containing necessary data for vertex finding.
 */ 
  ZVertexHeterogeneous Producer::makeAsync(cudaStream_t stream, TkSoA const* tksoa, float ptMin) const {
#ifdef PIXVERTEX_DEBUG_PRODUCE
    std::cout << "producing Vertices on GPU" << std::endl;
#endif  // PIXVERTEX_DEBUG_PRODUCE
    ZVertexHeterogeneous vertices(cms::cuda::make_device_unique<ZVertexSoA>(stream));
#else
  ZVertexHeterogeneous Producer::make(TkSoA const* tksoa, float ptMin) const {
#ifdef PIXVERTEX_DEBUG_PRODUCE
    std::cout << "producing Vertices on  CPU" << std::endl;
#endif  // PIXVERTEX_DEBUG_PRODUCE
    ZVertexHeterogeneous vertices(std::make_unique<ZVertexSoA>());
#endif
    assert(tksoa);
    auto* soa = vertices.get();
    assert(soa);

#ifdef __CUDACC__
    auto ws_d = cms::cuda::make_device_unique<WorkSpace>(stream);
#else
    auto ws_d = std::make_unique<WorkSpace>();
#endif

#ifdef __CUDACC__
    init<<<1, 1, 0, stream>>>(soa, ws_d.get());
    auto blockSize = 128;
    auto numberOfBlocks = (TkSoA::stride() + blockSize - 1) / blockSize;
    loadTracks<<<numberOfBlocks, blockSize, 0, stream>>>(tksoa, soa, ws_d.get(), ptMin);
    cudaCheck(cudaGetLastError());
#else
    init(soa, ws_d.get());
    loadTracks(tksoa, soa, ws_d.get(), ptMin);
#endif

#ifdef __CUDACC__
    // Running too many thread lead to problems when printf is enabled.
    constexpr int maxThreadsForPrint = 1024 - 256;
    constexpr int numBlocks = 1024;
    constexpr int threadsPerBlock = 128;

    if (oneKernel_) {
      // implemented only for density clustesrs
#ifndef THREE_KERNELS
      vertexFinderOneKernel<<<1, maxThreadsForPrint, 0, stream>>>(soa, ws_d.get(), minT, eps, errmax, chi2max);
#else
      vertexFinderKernel1<<<1, maxThreadsForPrint, 0, stream>>>(soa, ws_d.get(), minT, eps, errmax, chi2max);
      cudaCheck(cudaGetLastError());
      // one block per vertex...
      splitVerticesKernel<<<numBlocks, threadsPerBlock, 0, stream>>>(soa, ws_d.get(), maxChi2ForSplit);
      cudaCheck(cudaGetLastError());
      vertexFinderKernel2<<<1, maxThreadsForPrint, 0, stream>>>(soa, ws_d.get());
#endif
    } else {  // five kernels
      if (useDensity_) {
        clusterTracksByDensityKernel<<<1, maxThreadsForPrint, 0, stream>>>(soa, ws_d.get(), minT, eps, errmax, chi2max);
      } else if (useDBSCAN_) {
        clusterTracksDBSCAN<<<1, maxThreadsForPrint, 0, stream>>>(soa, ws_d.get(), minT, eps, errmax, chi2max);
      } else if (useIterative_) {
        clusterTracksIterative<<<1, maxThreadsForPrint, 0, stream>>>(soa, ws_d.get(), minT, eps, errmax, chi2max);
      }
      cudaCheck(cudaGetLastError());
      fitVerticesKernel<<<1, maxThreadsForPrint, 0, stream>>>(soa, ws_d.get(), maxChi2ForFirstFit);
      cudaCheck(cudaGetLastError());
      // one block per vertex...
      splitVerticesKernel<<<numBlocks, threadsPerBlock, 0, stream>>>(soa, ws_d.get(), maxChi2ForSplit);
      cudaCheck(cudaGetLastError());
      fitVerticesKernel<<<1, maxThreadsForPrint, 0, stream>>>(soa, ws_d.get(), maxChi2ForFinalFit);
      cudaCheck(cudaGetLastError());
      sortByPt2Kernel<<<1, maxThreadsForPrint, 0, stream>>>(soa, ws_d.get());
    }
    cudaCheck(cudaGetLastError());
#else  // __CUDACC__
    if (useDensity_) {
      clusterTracksByDensity(soa, ws_d.get(), minT, eps, errmax, chi2max);
    } else if (useDBSCAN_) {
      clusterTracksDBSCAN(soa, ws_d.get(), minT, eps, errmax, chi2max);
    } else if (useIterative_) {
      clusterTracksIterative(soa, ws_d.get(), minT, eps, errmax, chi2max);
    }
#ifdef PIXVERTEX_DEBUG_PRODUCE
    std::cout << "found " << (*ws_d).nvIntermediate << " vertices " << std::endl;
#endif  // PIXVERTEX_DEBUG_PRODUCE
    fitVertices(soa, ws_d.get(), maxChi2ForFirstFit);
    // one block per vertex!
    splitVertices(soa, ws_d.get(), maxChi2ForSplit);
    fitVertices(soa, ws_d.get(), maxChi2ForFinalFit);
    sortByPt2(soa, ws_d.get());
#endif

    return vertices;
  }

}  // namespace gpuVertexFinder
