#ifndef RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h
#define RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h

#include "CUDACore/ESProduct.h"
#include "CUDACore/HostAllocator.h"
#include "CUDACore/device_unique_ptr.h"
#include "CondFormats/SiPixelFedCablingMapGPU.h"

#include <cuda_runtime.h>

#include <set>

/**
 * @brief Wrapper class for managing SiPixelFedCablingMapGPU data on GPU.
 *
 * This class provides functionality for wrapping SiPixelFedCablingMapGPU objects,
 * handling quality flags, and accessing GPU memory asynchronously.
 
class SiPixelFedCablingMapGPUWrapper {
     * @brief Constructor for initializing the wrapper with a cabling map and module data.
   *
   * @param cablingMap The input cabling map to be wrapped.
   * @param modToUnp Module data to be associated with the wrapper.
   
  public:
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap,
                                          std::vector<unsigned char> modToUnp);
     * @brief Destructor for releasing resources held by the wrapper.
   
  ~SiPixelFedCablingMapGPUWrapper();
     * @brief Query method to check if the wrapper has quality data.
   *
   * @return True if the wrapper has quality data, false otherwise.
   
  bool hasQuality() const { return hasQuality_; }
     * @brief Method to retrieve a pointer to the GPU product asynchronously.
   *
   * @param cudaStream The CUDA stream to use for asynchronous access.
   * @return A pointer to the GPU product.
   
  const SiPixelFedCablingMapGPU *getGPUProductAsync(cudaStream_t cudaStream) const;
     * @brief Method to retrieve a pointer to the module unpacking data asynchronously.
   *
   * @param cudaStream The CUDA stream to use for asynchronous access.
   * @return A pointer to the module unpacking data.
   
  const unsigned char *getModToUnpAllAsync(cudaStream_t cudaStream) const;
  
  private:   * @brief Default module data stored in host memory.
   
  std::vector<unsigned char, cms::cuda::HostAllocator<unsigned char>> modToUnpDefault;   * @brief Flag indicating whether the wrapper has quality data.
   
  bool hasQuality_;
     * @brief Pointer to the cabling map structure in host memory.
   
  SiPixelFedCablingMapGPU *cablingMapHost; 
     * @brief Nested structure representing GPU data.
   
  struct GPUData {     * @brief Destructor for releasing GPU resources.
     
    ~GPUData();     * @brief Pointer to the cabling map structure in GPU memory.
     
    SiPixelFedCablingMapGPU *cablingMapDevice; 
  };   * @brief Product storing GPU data across devices.
   
  cms::cuda::ESProduct<GPUData> gpuData_;
     * @brief Nested structure representing modules to unpack.
   
  struct ModulesToUnpack {     * @brief Destructor for releasing GPU resources.
     
    ~ModulesToUnpack();     * @brief Pointer to module unpacking data in GPU memory.
     
    unsigned char *modToUnpDefault; 
  };   * @brief Product storing module unpacking data across devices.
   
  cms::cuda::ESProduct<ModulesToUnpack> modToUnp_;
}* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
class SiPixelFedCablingMapGPUWrapper {
public:
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap,
                                          std::vector<unsigned char> modToUnp);
  ~SiPixelFedCablingMapGPUWrapper();

  bool hasQuality() const { return hasQuality_; }

  // returns pointer to GPU memory
  const SiPixelFedCablingMapGPU *getGPUProductAsync(cudaStream_t cudaStream) const;

  // returns pointer to GPU memory
  const unsigned char *getModToUnpAllAsync(cudaStream_t cudaStream) const;

private:
  std::vector<unsigned char, cms::cuda::HostAllocator<unsigned char>> modToUnpDefault;
  bool hasQuality_;

  SiPixelFedCablingMapGPU *cablingMapHost = nullptr;  // pointer to struct in CPU

  struct GPUData {
    ~GPUData();
    SiPixelFedCablingMapGPU *cablingMapDevice = nullptr;  // pointer to struct in GPU
  };
  cms::cuda::ESProduct<GPUData> gpuData_;

  struct ModulesToUnpack {
    ~ModulesToUnpack();
    unsigned char *modToUnpDefault = nullptr;  // pointer to GPU
  };
  cms::cuda::ESProduct<ModulesToUnpack> modToUnp_;
};

#endif
