#ifndef RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h
#define RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h

#include "CUDACore/ESProduct.h"
#include "CUDACore/HostAllocator.h"
#include "CUDACore/device_unique_ptr.h"
#include "CondFormats/SiPixelFedCablingMapGPU.h"

#include <cuda_runtime.h>

#include <set>

/**
 * @brief Wrapper class for managing SiPixelFedCablingMapGPU data on GPU and CPU.
 *
 * This class provides functionality for handling SiPixelFedCablingMapGPU data,
 * including asynchronous access to GPU memory and quality checks.
 
class SiPixelFedCablingMapGPUWrapper {
     * @brief Constructor for initializing the wrapper with cabling map and module data.
   *
   * @param cablingMap The input cabling map data.
   * @param modToUnp Module data for unpacking.
   
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap,
                                        std::vector<unsigned char> modToUnp);
   * @brief Destructor for releasing allocated resources.
   
  ~SiPixelFedCablingMapGPUWrapper();
   * @brief Checks if the wrapper has quality data.
   *
   * @return True if quality data is available, false otherwise.
   
  bool hasQuality() const { return hasQuality_; }
   * @brief Returns a pointer to the GPU product asynchronously.
   *
   * @param cudaStream The CUDA stream for asynchronous operation.
   * @return Pointer to the GPU product.
   
  const SiPixelFedCablingMapGPU *getGPUProductAsync(cudaStream_t cudaStream) const;
   * @brief Returns a pointer to the module data for unpacking asynchronously.
   *
   * @param cudaStream The CUDA stream for asynchronous operation.
   * @return Pointer to the module data.
   
  const unsigned char *getModToUnpAllAsync(cudaStream_t cudaStream) const;

 private:   * @brief Default module data stored on the host.
   
  std::vector<unsigned char, cms::cuda::HostAllocator<unsigned char>> modToUnpDefault;
   * @brief Flag indicating availability of quality data.
   
  bool hasQuality_;
   * @brief Pointer to the cabling map data on the host.
   
  SiPixelFedCablingMapGPU *cablingMapHost;  
   * @brief Struct representing GPU data.
   
  struct GPUData {
         * @brief Destructor for releasing GPU resources.
     
    ~GPUData();
    
         * @brief Pointer to the cabling map data on the GPU.
     
    SiPixelFedCablingMapGPU *cablingMapDevice;  
  };
   * @brief Product for distributing GPU data across devices.
   
  cms::cuda::ESProduct<GPUData> gpuData_;
   * @brief Struct representing modules to unpack.
   
  struct ModulesToUnpack {
         * @brief Destructor for releasing GPU resources.
     
    ~ModulesToUnpack();
    
         * @brief Pointer to the module data on the GPU.
     
    unsigned char *modToUnpDefault;  
  };
   * @brief Product for distributing module data across devices.
   
  cms::cuda::ESProduct<ModulesToUnpack> modToUnp_;
}* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
class SiPixelFedCablingMapGPUWrapper {
public:
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap,
                                          std::vector<unsigned char> modToUnp);
  ~SiPixelFedCablingMapGPUWrapper();

  bool hasQuality() const { return hasQuality_; }

  // returns pointer to GPU memory
  const SiPixelFedCablingMapGPU *getGPUProductAsync(cudaStream_t cudaStream) const;

  // returns pointer to GPU memory
  const unsigned char *getModToUnpAllAsync(cudaStream_t cudaStream) const;

private:
  std::vector<unsigned char, cms::cuda::HostAllocator<unsigned char>> modToUnpDefault;
  bool hasQuality_;

  SiPixelFedCablingMapGPU *cablingMapHost = nullptr;  // pointer to struct in CPU

  struct GPUData {
    ~GPUData();
    SiPixelFedCablingMapGPU *cablingMapDevice = nullptr;  // pointer to struct in GPU
  };
  cms::cuda::ESProduct<GPUData> gpuData_;

  struct ModulesToUnpack {
    ~ModulesToUnpack();
    unsigned char *modToUnpDefault = nullptr;  // pointer to GPU
  };
  cms::cuda::ESProduct<ModulesToUnpack> modToUnp_;
};

#endif
