#ifndef HeterogeneousCore_SYCLUtilities_interface_device_unique_ptr_h
#define HeterogeneousCore_SYCLUtilities_interface_device_unique_ptr_h

#include <functional>
#include <memory>
#include <optional>

#include <sycl/sycl.hpp>
#include "SYCLCore/getDeviceCachingAllocator.h"

namespace cms {
  namespace sycltools {
    namespace device {
      namespace impl {
        // Additional layer of types to distinguish from host::unique_ptr
        class DeviceDeleter {
        public:
          DeviceDeleter() = default;  // for edm::Wrapper
          DeviceDeleter(sycl::queue stream) : stream_{stream} {}

/**
 * Destructor to release allocated memory back to the caching allocator when associated with a stream. 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
          void operator()(void* ptr) {
            if (stream_) {
              CachingAllocator& allocator = getDeviceCachingAllocator(*stream_);
              allocator.free(ptr);
            }
          }

        private:
          std::optional<sycl::queue> stream_;
        };
      }  // namespace impl

      template <typename T>
      using unique_ptr = std::unique_ptr<T, impl::DeviceDeleter>;

      namespace impl {
        template <typename T>
        struct make_device_unique_selector {
          using non_array = cms::sycltools::device::unique_ptr<T>;
        };
        template <typename T>
        struct make_device_unique_selector<T[]> {
          using unbounded_array = cms::sycltools::device::unique_ptr<T[]>;
        };
        template <typename T, size_t N>
        struct make_device_unique_selector<T[N]> {
          struct bounded_array {};
        };
      }  // namespace impl
    }    // namespace device

    template <typename T>
/**
 * @brief Creates a unique pointer to an object of type T allocated on the device memory.
 *
 * @tparam T The type of the object to be allocated.
 *
 * @param stream The SYCL queue used for allocation.
 *
 * @return A unique pointer to the allocated object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    typename device::impl::make_device_unique_selector<T>::non_array make_device_unique(sycl::queue const& stream) {
      static_assert(std::is_trivially_constructible<T>::value,
                    "Allocating with non-trivial constructor on the device memory is not supported");
      CachingAllocator& allocator = getDeviceCachingAllocator(stream);
      void* mem = allocator.allocate(sizeof(T), stream);
      return typename device::impl::make_device_unique_selector<T>::non_array{reinterpret_cast<T*>(mem),
                                                                              device::impl::DeviceDeleter{stream}};
    }

    template <typename T>
/**
 * @brief Creates an unbounded array of unique pointers to devices.
 *
 * @tparam T The type of elements in the array.
 *
 * @param n The number of elements in the array.
 * @param stream The SYCL queue used for allocation.
 *
 * @return An unbounded array of unique pointers to devices.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    typename device::impl::make_device_unique_selector<T>::unbounded_array make_device_unique(
        size_t n, sycl::queue const& stream) {
      using element_type = typename std::remove_extent<T>::type;
      static_assert(std::is_trivially_constructible<element_type>::value,
                    "Allocating with non-trivial constructor on the device memory is not supported");
      CachingAllocator& allocator = getDeviceCachingAllocator(stream);
      void* mem = allocator.allocate(n * sizeof(element_type), stream);
      return typename device::impl::make_device_unique_selector<T>::unbounded_array{
          reinterpret_cast<element_type*>(mem), device::impl::DeviceDeleter{stream}};
    }

    template <typename T, typename... Args>
    typename device::impl::make_device_unique_selector<T>::bounded_array make_device_unique(Args&&...) = delete;

    // No check for the trivial constructor, make it clear in the interface
    template <typename T>
/**
 * @brief Constructs a unique pointer to an uninitialized object of type T on a device.
 *
 * @param stream The SYCL queue used to manage the device memory allocation.
 *
 * @return A non-array unique pointer to the allocated device memory.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    typename device::impl::make_device_unique_selector<T>::non_array make_device_unique_uninitialized(
        sycl::queue const& stream) {
      CachingAllocator& allocator = getDeviceCachingAllocator(stream);
      void* mem = allocator.allocate(sizeof(T), stream);
      return typename device::impl::make_device_unique_selector<T>::non_array{reinterpret_cast<T*>(mem),
                                                                              device::impl::DeviceDeleter{stream}};
    }

    template <typename T>
/**
 * @brief Creates an unbounded array of uninitialized elements on a device.
 *
 * @tparam T Type of elements in the array.
 * @param n Number of elements in the array.
 * @param stream SYCL queue used for allocation.
 * @return Unbounded array of uninitialized elements.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    typename device::impl::make_device_unique_selector<T>::unbounded_array make_device_unique_uninitialized(
        size_t n, sycl::queue const& stream) {
      using element_type = typename std::remove_extent<T>::type;
      CachingAllocator& allocator = getDeviceCachingAllocator(stream);
      void* mem = allocator.allocate(n * sizeof(element_type), stream);
      return typename device::impl::make_device_unique_selector<T>::unbounded_array{
          reinterpret_cast<element_type*>(mem), device::impl::DeviceDeleter{stream}};
    }

    template <typename T, typename... Args>
    typename device::impl::make_device_unique_selector<T>::bounded_array make_device_unique_uninitialized(Args&&...) =
        delete;
  }  // namespace sycltools
}  // namespace cms

#endif  //HeterogeneousCore_SYCLUtilities_interface_device_unique_ptr_h