#ifndef SYCLCore_getDeviceCachingAllocator_h
#define SYCLCore_getDeviceCachingAllocator_h

#include <optional>
#include <mutex>
#include <vector>

#include <sycl/sycl.hpp>

#include "SYCLCore/getDeviceIndex.h"
#include "SYCLCore/AllocatorConfig.h"
#include "SYCLCore/CachingAllocator.h"

namespace cms::sycltools {

  namespace detail {
/**
 * Allocates an array of device allocators for each available device.
 *
 * @return A unique pointer to an array of device allocators.
 
inline auto allocate_device_allocators() 
 * Custom deleter function to destroy device allocator objects and deallocate memory.
 *
 * @param ptr Pointer to the array of device allocators.
 
auto deleter = [size](Allocator* ptr) 
 * Unique pointer to manage the lifetime of the device allocator array.
 *
 * @tparam T Type of the allocated objects.
 * @tparam Deleter Type of the custom deleter function.
 
std::unique_ptr<Allocator[], decltype(deleter)>* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    inline auto allocate_device_allocators() {
      using Allocator = cms::sycltools::CachingAllocator;
      auto const& devices = enumerateDevices();
      auto const size = devices.size();

      // allocate the storage for the objects
      auto ptr = std::allocator<Allocator>().allocate(size);

      // construct the objects in the storage
      for (size_t index = 0; index < size; ++index) {
        new (ptr + index) Allocator(devices[index],
                                    false,  // isHost
                                    config::binGrowth,
                                    config::minBin,
                                    config::maxBin,
                                    config::maxCachedBytes,
                                    config::maxCachedFraction,
                                    config::allocator_policy,  // reuseSameQueueAllocations
                                    false);                    // debug
      }

      // use a custom deleter to destroy all objects and deallocate the memory
      auto deleter = [size](Allocator* ptr) {
        for (size_t i = size; i > 0; --i) {
          (ptr + i - 1)->~Allocator();
        }
        std::allocator<Allocator>().deallocate(ptr, size);
      };

      return std::unique_ptr<Allocator[], decltype(deleter)>(ptr, deleter);
    }

  }  // namespace detail

  inline CachingAllocator& getDeviceCachingAllocator(sycl::queue const& stream) {
    // initialise all allocators, one per device
    static auto allocators = detail::allocate_device_allocators();

    size_t const index = getDeviceIndex(stream.get_device());
    assert(index < cms::sycltools::enumerateDevices().size());

    // the public interface is thread safe
    return allocators[index];
  }

}  // namespace cms::sycltools

#endif  // SYCLCore_getDeviceCachingAllocator_h