#ifndef HeterogeneousCore_SYCLUtilities_interface_host_unique_ptr_h
#define HeterogeneousCore_SYCLUtilities_interface_host_unique_ptr_h

#include <functional>
#include <memory>
#include <optional>

#include <sycl/sycl.hpp>
#include "SYCLCore/getHostCachingAllocator.h"

namespace cms {
  namespace sycltools {
    namespace host {
      namespace impl {
        // Additional layer of types to distinguish from host::unique_ptr
        class HostDeleter {
        public:
          HostDeleter() = default;  // for edm::Wrapper
          HostDeleter(sycl::queue stream) : stream_{stream} {}

/**
 * Destructor to release allocated memory from the host caching allocator associated with the stream. 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
          void operator()(void* ptr) {
            if (stream_) {
              CachingAllocator& allocator = getHostCachingAllocator(*stream_);
              allocator.free(ptr);
            }
          }

        private:
          std::optional<sycl::queue> stream_;
        };
      }  // namespace impl

      template <typename T>
      using unique_ptr = std::unique_ptr<T, impl::HostDeleter>;

      namespace impl {
        template <typename T>
        struct make_host_unique_selector {
          using non_array = cms::sycltools::host::unique_ptr<T>;
        };
        template <typename T>
        struct make_host_unique_selector<T[]> {
          using unbounded_array = cms::sycltools::host::unique_ptr<T[]>;
        };
        template <typename T, size_t N>
        struct make_host_unique_selector<T[N]> {
          struct bounded_array {};
        };
      }  // namespace impl
    }    // namespace host

    // Allocate pinned host memory
    template <typename T>
/**
 * Brief description: Creates a unique selector for host memory allocation.
 *
 * Detailed description: This function generates a unique selector for allocating
 * memory on the host with trivial constructibility checks. It utilizes a caching
 * allocator to manage memory and provides a custom deleter for proper cleanup.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    typename host::impl::make_host_unique_selector<T>::non_array make_host_unique(sycl::queue const& stream) {
      static_assert(std::is_trivially_constructible<T>::value,
                    "Allocating with non-trivial constructor on the pinned host memory is not supported");
      CachingAllocator& allocator = getHostCachingAllocator(stream);
      void* mem = allocator.allocate(sizeof(T), stream);
      return typename host::impl::make_host_unique_selector<T>::non_array{reinterpret_cast<T*>(mem),
                                                                          host::impl::HostDeleter{stream}};
    }

    template <typename T>
/**
 * Brief description of unbounded_array function
 *
 * Detailed description of unbounded_array function which generates 
 * a unique selector for host memory allocation
 *
 * @param n size of array to allocate
 * @param stream queue object representing the SYCL command queue
 * @return unbounded_array object containing allocated memory pointer and deleter
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    typename host::impl::make_host_unique_selector<T>::unbounded_array make_host_unique(size_t n,
                                                                                        sycl::queue const& stream) {
      using element_type = typename std::remove_extent<T>::type;
      static_assert(std::is_trivially_constructible<element_type>::value,
                    "Allocating with non-trivial constructor on the pinned host memory is not supported");
      CachingAllocator& allocator = getHostCachingAllocator(stream);
      void* mem = allocator.allocate(n * sizeof(element_type), stream);
      return typename host::impl::make_host_unique_selector<T>::unbounded_array{reinterpret_cast<element_type*>(mem),
                                                                                host::impl::HostDeleter{stream}};
    }

    template <typename T, typename... Args>
    typename host::impl::make_host_unique_selector<T>::bounded_array make_host_unique(Args&&...) = delete;

    // No check for the trivial constructor, make it clear in the interface
    template <typename T>
/**
 * @brief Creates a unique selector for uninitialized host memory
 * 
 * @param stream SYCL queue object
 * @return Unique selector for uninitialized host memory
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    typename host::impl::make_host_unique_selector<T>::non_array make_host_unique_uninitialized(
        sycl::queue const& stream) {
      CachingAllocator& allocator = getHostCachingAllocator(stream);
      void* mem = allocator.allocate(sizeof(T), stream);
      return typename host::impl::make_host_unique_selector<T>::non_array{reinterpret_cast<T*>(mem),
                                                                          host::impl::HostDeleter{stream}};
    }

    template <typename T>
/**
 * Creates an unbounded array of uninitialized elements on the host.
 *
 * @param n The number of elements in the array.
 * @param stream The SYCL queue associated with the allocation.
 *
 * @return An unbounded array of uninitialized elements.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    typename host::impl::make_host_unique_selector<T>::unbounded_array make_host_unique_uninitialized(
        size_t n, sycl::queue const& stream) {
      using element_type = typename std::remove_extent<T>::type;
      CachingAllocator& allocator = getHostCachingAllocator(stream);
      void* mem = allocator.allocate(n * sizeof(element_type), stream);
      return typename host::impl::make_host_unique_selector<T>::unbounded_array{reinterpret_cast<element_type*>(mem),
                                                                                host::impl::HostDeleter{stream}};
    }

    template <typename T, typename... Args>
    typename host::impl::make_host_unique_selector<T>::bounded_array make_host_unique_uninitialized(Args&&...) = delete;
  }  // namespace sycltools
}  // namespace cms

#endif