#include <algorithm>
#include <cassert>
#include <iostream>
#include <random>
#include <limits>
#include <array>
#include <memory>

#include <sycl/sycl.hpp>

#include "SYCLCore/AtomicPairCounter.h"
#include "SYCLCore/HistoContainer.h"
#include "SYCLCore/chooseDevice.h"
#include "SYCLCore/device_unique_ptr.h"

constexpr uint32_t MaxElem = 64000;
constexpr uint32_t MaxTk = 8000;
constexpr uint32_t MaxAssocs = 4 * MaxTk;

using Assoc = cms::sycltools::OneToManyAssoc<uint16_t, MaxElem, MaxAssocs>;
using SmallAssoc = cms::sycltools::OneToManyAssoc<uint16_t, 128, MaxAssocs>;
using Multiplicity = cms::sycltools::OneToManyAssoc<uint16_t, 8, MaxTk>;
using TK = std::array<uint16_t, 4>;
using cms::sycltools::AtomicPairCounter;


// The following comment is generated by an LLM. 
/**
 * Counts multiplicity in parallel using SYCL.
 *
 * @param[in] tk Input data
 * @param[out] assoc Output association
 * @param[in] n Number of items to process
 * @param[in] item SYCL item object
 */ 
void countMultiLocal(TK const* __restrict__ tk, Multiplicity* __restrict__ assoc, int32_t n, sycl::nd_item<1> item) {
  int first = item.get_local_range().get(0) * item.get_group(0) + item.get_local_id(0);
  for (int i = first; i < n; i += item.get_group_range(0) * item.get_local_range().get(0)) {
    auto localbuff = sycl::ext::oneapi::group_local_memory_for_overwrite<Multiplicity::CountersOnly>(item.get_group());
    Multiplicity::CountersOnly* local = (Multiplicity::CountersOnly*)localbuff.get();
    if (item.get_local_id(0) == 0)
      local->zero();
    sycl::group_barrier(item.get_group());
    local->countDirect(2 + i % 4);
    sycl::group_barrier(item.get_group());
    if (item.get_local_id(0) == 0)
      assoc->add(*local);
  }
}


// The following comment is generated by an LLM. 
/**
 * Counts multiplicity associations in parallel using SYCL.
 *
 * @param[in] tk Input array of type TK
 * @param[out] assoc Output object to store multiplicity counts
 * @param[in] n Total number of items to process
 * @param[in] item SYCL nd_item object representing the current work item
 */ 
void countMulti(TK const* __restrict__ tk, Multiplicity* __restrict__ assoc, int32_t n, sycl::nd_item<1> item) {
  int first = item.get_local_range().get(0) * item.get_group(0) + item.get_local_id(0);
  for (int i = first; i < n; i += item.get_group_range(0) * item.get_local_range().get(0))
    assoc->countDirect(2 + i % 4);
}


// The following comment is generated by an LLM. 
/**
 * Verifies the equality of two multiplicity objects within a parallel processing context.
 *
 * @param m1 First multiplicity object to compare.
 * @param m2 Second multiplicity object to compare.
 * @param item SYCL item representing the current processing unit.
 */ 
void verifyMulti(Multiplicity* __restrict__ m1, Multiplicity* __restrict__ m2, sycl::nd_item<1> item) {
  auto first = item.get_local_range().get(0) * item.get_group(0) + item.get_local_id(0);
  for (auto i = first; i < Multiplicity::totbins(); i += item.get_group_range(0) * item.get_local_range().get(0))
    assert(m1->off[i] == m2->off[i]);
}


// The following comment is generated by an LLM. 
/**
 * Counts the occurrences of each element in the input array.
 *
 * @param[in] tk Input array of elements to count.
 * @param[out] assoc Association object to store the counts.
 * @param[in] n Size of the input array.
 * @param[in] item SYCL item object representing the current kernel execution.
 */ 
void count(TK const* __restrict__ tk, Assoc* __restrict__ assoc, int32_t n, sycl::nd_item<1> item) {
  int first = item.get_local_range().get(0) * item.get_group(0) + item.get_local_id(0);
  for (int i = first; i < 4 * n; i += item.get_group_range(0) * item.get_local_range().get(0)) {
    auto k = i / 4;
    auto j = i - 4 * k;
    assert(j < 4);
    if (k >= n)
      return;
    if (tk[k][j] < MaxElem)
      assoc->countDirect(tk[k][j]);
  }
}


// The following comment is generated by an LLM. 
/**
 * Fills an association array based on input data from a track kernel.
 *
 * @param[in] tk Input track kernel data
 * @param[out] assoc Association array to be filled
 * @param[in] n Size of the input data
 * @param[in] item SYCL item object providing parallelization information
 */ 
void fill(TK const* __restrict__ tk, Assoc* __restrict__ assoc, int32_t n, sycl::nd_item<1> item) {
  int first = item.get_local_range().get(0) * item.get_group(0) + item.get_local_id(0);
  for (int i = first; i < 4 * n; i += item.get_group_range(0) * item.get_local_range().get(0)) {
    auto k = i / 4;
    auto j = i - 4 * k;
    assert(j < 4);
    if (k >= n)
      return;
    if (tk[k][j] < MaxElem)
      assoc->fillDirect(tk[k][j], k);
  }
}

void verify(Assoc* __restrict__ assoc) { assert(assoc->size() < Assoc::capacity()); }

template <typename Assoc>

// The following comment is generated by an LLM. 
/**
 * Fills bulk data structure using atomic pair counter and thread block information.
 *
 * @param apc         pointer to atomic pair counter object
 * @param tk          array of track data
 * @param assoc       association object for bulk filling
 * @param n           number of tracks to process
 * @param item        SYCL item object containing thread block information
 */ 
void fillBulk(
    AtomicPairCounter* apc, TK const* __restrict__ tk, Assoc* __restrict__ assoc, int32_t n, sycl::nd_item<1> item) {
  int first = item.get_local_range().get(0) * item.get_group(0) + item.get_local_id(0);
  for (int k = first; k < n; k += item.get_group_range(0) * item.get_local_range().get(0)) {
    auto m = tk[k][3] < MaxElem ? 4 : 3;
    assoc->bulkFill(*apc, &tk[k][0], m);
  }
}

template <typename Assoc>

// The following comment is generated by an LLM. 
/**
 * Verifies the bulk data integrity by checking for potential overflows and size constraints.
 *
 * @param assoc   The association object to be verified.
 * @param apc     The atomic pair counter object to check for overflow conditions.
 */ 
void verifyBulk(Assoc const* __restrict__ assoc, AtomicPairCounter const* apc) {
  if (apc->get().m >= Assoc::nbins())
    printf("Overflow %d %d\n", apc->get().m, Assoc::nbins());
  assert(assoc->size() < Assoc::capacity());
}


// The following comment is generated by an LLM. 
/**
 * @brief Main entry point of the program.
 *
 * @param argc Number of command line arguments.
 * @param argv Array of command line arguments.
 * @return Exit status of the program.
 
int main(int argc, char** argv)
 * @brief Function to count associations.
 *
 * @param v_d_get Device pointer to array of associations.
 * @param a_d_get Device pointer to association object.
 * @param N Size of the array.
 * @param item ND item for parallel execution.
 
void count(v_d_get, a_d_get, N, item)
 * @brief Function to verify associations.
 *
 * @param a_d_get Device pointer to association object.
 
void verify(a_d_get)
 * @brief Function to fill associations.
 *
 * @param v_d_get Device pointer to array of associations.
 * @param a_d_get Device pointer to association object.
 * @param N Size of the array.
 * @param item ND item for parallel execution.
 
void fill(v_d_get, a_d_get, N, item)
 * @brief Function to fill bulk associations.
 *
 * @param dc_d Device pointer to atomic pair counter.
 * @param v_d_get Device pointer to array of associations.
 * @param a_d_get Device pointer to association object.
 * @param N Size of the array.
 * @param item ND item for parallel execution.
 
void fillBulk(dc_d, v_d_get, a_d_get, N, item)
 * @brief Function to finalize bulk associations.
 *
 * @param dc_d Device pointer to atomic pair counter.
 * @param a_d_get Device pointer to association object.
 * @param item ND item for parallel execution.
 
void finalizeBulk/dc_d, a_d_get, item)
 * @brief Function to verify bulk associations.
 *
 * @param a_d_get Device pointer to association object.
 * @param dc_d Device pointer to atomic pair counter.
 
void verifyBulk(a_d_get, dc_d)
 * @brief Function to count multiplicities.
 *
 * @param v_d_get Device pointer to array of associations.
 * @param m1_d_get Device pointer to multiplicity object.
 * @param N Size of the array.
 * @param item ND item for parallel execution.
 
void countMulti(v_d_get, m1_d_get, N, item)
 * @brief Function to count local multiplicities.
 *
 * @param v_d_get Device pointer to array of associations.
 * @param m2_d_get Device pointer to multiplicity object.
 * @param N Size of the array.
 * @param item ND item for parallel execution.
 
void countMultiLocal(v_d_get, m2_d_get, N, item)
 * @brief Function to verify multiplicities.
 *
 * @param m1_d_get Device pointer to multiplicity object.
 * @param m2_d_get Device pointer to multiplicity object.
 * @param item ND item for parallel execution.
 
void verifyMulti(m1_d_get, m2_d_get, item)*/ 
int main(int argc, char** argv) {
  std::cout << "OneToManyAssoc " << sizeof(Assoc) << ' ' << Assoc::nbins() << ' ' << Assoc::capacity() << std::endl;
  std::cout << "OneToManyAssoc (small) " << sizeof(SmallAssoc) << ' ' << SmallAssoc::nbins() << ' '
            << SmallAssoc::capacity() << std::endl;

  std::mt19937 eng;
  std::geometric_distribution<int> rdm(0.8);

  constexpr uint32_t N = 4000;
  std::vector<std::array<uint16_t, 4>> tr(N);

  // fill with "index" to element
  long long ave = 0;
  int imax = 0;
  auto n = 0U;
  auto z = 0U;
  auto nz = 0U;
  for (auto i = 0U; i < 4U; ++i) {
    auto j = 0U;
    while (j < N && n < MaxElem) {
      if (z == 11) {
        ++n;
        z = 0;
        ++nz;
        continue;
      }  // a bit of not assoc
      auto x = rdm(eng);
      auto k = std::min(j + x + 1, N);
      if (i == 3 && z == 3) {  // some triplets time to time
        for (; j < k; ++j)
          tr[j][i] = MaxElem + 1;
      } else {
        ave += x + 1;
        imax = std::max(imax, x);
        for (; j < k; ++j)
          tr[j][i] = n;
        ++n;
      }
      ++z;
    }
    assert(n <= MaxElem);
    assert(j <= N);
  }
  std::cout << "filled with " << n << " elements " << double(ave) / n << ' ' << imax << ' ' << nz << std::endl;

  std::string devices(argv[1]);
  setenv("ONEAPI_DEVICE_SELECTOR", devices.c_str(), true);

  cms::sycltools::enumerateDevices(true);
  sycl::device device = cms::sycltools::chooseDevice(0);
  sycl::queue queue = sycl::queue(device, sycl::property::queue::in_order());
  std::cout << "OneToMany offload to " << device.get_info<sycl::info::device::name>() << " on backend "
            << device.get_backend() << std::endl;

  auto v_d = cms::sycltools::make_device_unique<std::array<uint16_t, 4>[]>(N, queue);
  assert(v_d.get());
  auto a_d = cms::sycltools::make_device_unique<Assoc[]>(1, queue);
  auto sa_d = cms::sycltools::make_device_unique<SmallAssoc[]>(1, queue);

  queue.memcpy(v_d.get(), tr.data(), N * sizeof(std::array<uint16_t, 4>)).wait();

  cms::sycltools::launchZero(a_d.get(), queue);

  int max_work_group_size = queue.get_device().get_info<sycl::info::device::max_work_group_size>();
  auto nThreads = std::min(256, max_work_group_size);
  auto nBlocks = (4 * N + nThreads - 1) / nThreads;

  queue.submit([&](sycl::handler& cgh) {
    auto v_d_get = v_d.get();
    auto a_d_get = a_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(nBlocks * nThreads), sycl::range(nThreads)),
                     [=](sycl::nd_item<1> item) { count(v_d_get, a_d_get, N, item); });
  });

  cms::sycltools::launchFinalize(a_d.get(), queue);
  queue.submit([&](sycl::handler& cgh) {
    auto a_d_get = a_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(1), sycl::range(1)), [=](sycl::nd_item<1> item) { verify(a_d_get); });
  });
  queue.submit([&](sycl::handler& cgh) {
    auto v_d_get = v_d.get();
    auto a_d_get = a_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(nBlocks * nThreads), sycl::range(nThreads)),
                     [=](sycl::nd_item<1> item) { fill(v_d_get, a_d_get, N, item); });
  });

  Assoc la;

  queue.memcpy(&la, a_d.get(), sizeof(Assoc)).wait();

  std::cout << la.size() << std::endl;
  imax = 0;
  ave = 0;
  z = 0;
  for (auto i = 0U; i < n; ++i) {
    auto x = la.size(i);
    if (x == 0) {
      z++;
      continue;
    }
    ave += x;
    imax = std::max(imax, int(x));
  }
  assert(0 == la.size(n));
  std::cout << "found with " << n << " elements " << double(ave) / n << ' ' << imax << ' ' << z << std::endl;

  // now the inverse map (actually this is the direct....)
  AtomicPairCounter* dc_d;
  AtomicPairCounter dc(0);

  dc_d = sycl::malloc_device<AtomicPairCounter>(1, queue);
  queue.memset(dc_d, 0, sizeof(AtomicPairCounter)).wait();
  nBlocks = (N + nThreads - 1) / nThreads;
  queue.submit([&](sycl::handler& cgh) {
    auto v_d_get = v_d.get();
    auto a_d_get = a_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(nBlocks * nThreads), sycl::range(nThreads)),
                     [=](sycl::nd_item<1> item) { fillBulk(dc_d, v_d_get, a_d_get, N, item); });
  });
  queue.submit([&](sycl::handler& cgh) {
    auto a_d_get = a_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(nBlocks * nThreads), sycl::range(nThreads)),
                     [=](sycl::nd_item<1> item) { cms::sycltools::finalizeBulk(dc_d, a_d_get, item); });
  });
  queue.submit([&](sycl::handler& cgh) {
    auto a_d_get = a_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(1), sycl::range(1)),
                     [=](sycl::nd_item<1> item) { verifyBulk(a_d_get, dc_d); });
  });

  queue.memcpy(&la, a_d.get(), sizeof(Assoc));
  queue.memcpy(&dc, dc_d, sizeof(AtomicPairCounter));

  queue.memset(dc_d, 0, sizeof(AtomicPairCounter)).wait();
  queue.submit([&](sycl::handler& cgh) {
    auto v_d_get = v_d.get();
    auto sa_d_get = sa_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(nBlocks * nThreads), sycl::range(nThreads)),
                     [=](sycl::nd_item<1> item) { fillBulk(dc_d, v_d_get, sa_d_get, N, item); });
  });
  queue.submit([&](sycl::handler& cgh) {
    auto sa_d_get = sa_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(nBlocks * nThreads), sycl::range(nThreads)),
                     [=](sycl::nd_item<1> item) { cms::sycltools::finalizeBulk(dc_d, sa_d_get, item); });
  });
  queue.submit([&](sycl::handler& cgh) {
    sycl::stream out(64 * 1024, 80, cgh);

    auto sa_d_get = sa_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(1), sycl::range(1)),
                     [=](sycl::nd_item<1> item) { verifyBulk(sa_d_get, dc_d); });
  });

  std::cout << "final counter value " << dc.get().n << ' ' << dc.get().m << std::endl;

  std::cout << la.size() << std::endl;
  imax = 0;
  ave = 0;
  for (auto i = 0U; i < N; ++i) {
    auto x = la.size(i);
    if (!(x == 4 || x == 3))
      std::cout << i << ' ' << x << std::endl;
    assert(x == 4 || x == 3);
    ave += x;
    imax = std::max(imax, int(x));
  }
  assert(0 == la.size(N));
  std::cout << "found with ave occupancy " << double(ave) / N << ' ' << imax << std::endl;

  // here verify use of block local counters
  auto m1_d = cms::sycltools::make_device_unique<Multiplicity[]>(1, queue);
  auto m2_d = cms::sycltools::make_device_unique<Multiplicity[]>(1, queue);
  cms::sycltools::launchZero(m1_d.get(), queue);
  cms::sycltools::launchZero(m2_d.get(), queue);

  nBlocks = (4 * N + nThreads - 1) / nThreads;
  queue.submit([&](sycl::handler& cgh) {
    auto v_d_get = v_d.get();
    auto m1_d_get = m1_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(nBlocks * nThreads), sycl::range(nThreads)),
                     [=](sycl::nd_item<1> item) { countMulti(v_d_get, m1_d_get, N, item); });
  });
  queue.submit([&](sycl::handler& cgh) {
    auto v_d_get = v_d.get();
    auto m2_d_get = m2_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(nBlocks * nThreads), sycl::range(nThreads)),
                     [=](sycl::nd_item<1> item) { countMultiLocal(v_d_get, m2_d_get, N, item); });
  });
  queue.submit([&](sycl::handler& cgh) {
    auto m1_d_get = m1_d.get();
    auto m2_d_get = m2_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(Multiplicity::totbins()), sycl::range(Multiplicity::totbins())),
                     [=](sycl::nd_item<1> item) { verifyMulti(m1_d_get, m2_d_get, item); });
  });

  cms::sycltools::launchFinalize(m1_d.get(), queue);
  cms::sycltools::launchFinalize(m2_d.get(), queue);
  queue.submit([&](sycl::handler& cgh) {
    auto m1_d_get = m1_d.get();
    auto m2_d_get = m2_d.get();

    cgh.parallel_for(sycl::nd_range(sycl::range(Multiplicity::totbins()), sycl::range(Multiplicity::totbins())),
                     [=](sycl::nd_item<1> item) { verifyMulti(m1_d_get, m2_d_get, item); });
  });

  queue.wait_and_throw();

  return 0;
}
