#ifndef plugin_SiPixelClusterizer_alpaka_gpuCalibPixel_h
#define plugin_SiPixelClusterizer_alpaka_gpuCalibPixel_h

#include <algorithm>
#include <cstdint>
#include <cstdio>

#include "AlpakaCore/config.h"
#include "AlpakaDataFormats/gpuClusteringConstants.h"
#include "CondFormats/alpaka/SiPixelGainForHLTonGPU.h"

namespace ALPAKA_ACCELERATOR_NAMESPACE {
  namespace gpuCalibPixel {

    constexpr uint16_t InvId = 9999;  // must be > MaxNumModules

    // valid for run2
    constexpr float VCaltoElectronGain = 47;         // L2-4: 47 +- 4.7
    constexpr float VCaltoElectronGain_L1 = 50;      // L1:   49.6 +- 2.6
    constexpr float VCaltoElectronOffset = -60;      // L2-4: -60 +- 130
    constexpr float VCaltoElectronOffset_L1 = -670;  // L1:   -670 +- 220

    struct calibDigis {
      template <typename TAcc>
/**
 * Brief description of the function object class
 *
 * Detailed description of the function object class
 
class FunctionObjectClass {
     * @brief Constructor for the function object class
   * @param none
   
  FunctionObjectClass();

     * @brief Overloaded function call operator
   * @param acc 
   * @param isRun2 
   * @param id 
   * @param x 
   * @param y 
   * @param adc 
   * @param ped 
   * @param numElements 
   * @param moduleStart 
   * @param nClustersInModule 
   * @param clusModuleStart 
   * @return void
   
  void operator()(
    const TAcc& acc,
    bool isRun2,
    uint16_t* id,
    uint16_t const* __restrict__ x,
    uint16_t const* __restrict__ y,
    uint16_t* adc,
    SiPixelGainForHLTonGPU const* __restrict__ ped,
    int numElements,
    uint32_t* __restrict__ moduleStart,        
    uint32_t* __restrict__ nClustersInModule,  
    uint32_t* __restrict__ clusModuleStart     
  ) const;

};* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      ALPAKA_FN_ACC void operator()(const TAcc& acc,
                                    bool isRun2,
                                    uint16_t* id,
                                    uint16_t const* __restrict__ x,
                                    uint16_t const* __restrict__ y,
                                    uint16_t* adc,
                                    SiPixelGainForHLTonGPU const* __restrict__ ped,
                                    int numElements,
                                    uint32_t* __restrict__ moduleStart,        // just to zero first
                                    uint32_t* __restrict__ nClustersInModule,  // just to zero them
                                    uint32_t* __restrict__ clusModuleStart     // just to zero first
      ) const {
        const uint32_t threadIdxGlobal(alpaka::getIdx<alpaka::Grid, alpaka::Threads>(acc)[0u]);

        // zero for next kernels...
        if (threadIdxGlobal == 0) {
          clusModuleStart[0] = moduleStart[0] = 0;
        }

        cms::alpakatools::for_each_element_in_grid_strided(
            acc, gpuClustering::MaxNumModules, [&](uint32_t i) { nClustersInModule[i] = 0; });

        cms::alpakatools::for_each_element_in_grid_strided(acc, numElements, [&](uint32_t i) {
          if (id[i] != InvId) {
            float conversionFactor = (isRun2) ? (id[i] < 96 ? VCaltoElectronGain_L1 : VCaltoElectronGain) : 1.f;
            float offset = (isRun2) ? (id[i] < 96 ? VCaltoElectronOffset_L1 : VCaltoElectronOffset) : 0;

            bool isDeadColumn = false, isNoisyColumn = false;

            int row = x[i];
            int col = y[i];
            auto ret = ped->getPedAndGain(id[i], col, row, isDeadColumn, isNoisyColumn);
            float pedestal = ret.first;
            float gain = ret.second;
            // float pedestal = 0; float gain = 1.;
            if (isDeadColumn | isNoisyColumn) {
              id[i] = InvId;
              adc[i] = 0;
              printf("bad pixel at %d in %d\n", i, id[i]);
            } else {
              float vcal = adc[i] * gain - pedestal * gain;
              adc[i] = std::max(100, int(vcal * conversionFactor + offset));
            }
          }
        });
      }
    };
  }  // namespace gpuCalibPixel
}  // namespace ALPAKA_ACCELERATOR_NAMESPACE

#endif  // plugin_SiPixelClusterizer_alpaka_gpuCalibPixel_h
