#ifndef HeterogeneousCore_CUDAUtilities_cudaCheck_h
#define HeterogeneousCore_CUDAUtilities_cudaCheck_h

// C++ standard headers
#include <iostream>
#include <sstream>
#include <stdexcept>

// Boost headers
#define BOOST_STACKTRACE_USE_BACKTRACE
#include <boost/stacktrace.hpp>

// CUDA headers
#include <cuda.h>
#include <cuda_runtime.h>

namespace cms {
  namespace cuda {

/**
 * Brief description: Aborts program execution due to a CUDA error.
 *
 * Detailed description: This function generates an error message including
 * the filename, line number, CUDA command, error message, and optional description.
 * It also includes the current stack trace for debugging purposes.
 * The function throws a runtime error with the formatted error message.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    [[noreturn]] inline void abortOnCudaError(const char* file,
                                              int line,
                                              const char* cmd,
                                              const char* error,
                                              const char* message,
                                              const char* description = nullptr) {
      std::ostringstream out;
      out << "\n";
      out << file << ", line " << line << ":\n";
      out << "cudaCheck(" << cmd << ");\n";
      out << error << ": " << message << "\n";
      if (description)
        out << description << "\n";

      out << "\nCurrent stack trace:\n";
      out << boost::stacktrace::stacktrace();
      out << "\n";

      throw std::runtime_error(out.str());
    }

/**
 * Checks the result of a CUDA operation and handles errors accordingly.
 *
 * @param file The file where the check is being performed.
 * @param line The line number where the check is being performed.
 * @param cmd The command that was executed.
 * @param result The result of the CUDA operation.
 * @param description A descriptive message about the error.
 * @return True if the result is successful, false otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline bool cudaCheck_(
        const char* file, int line, const char* cmd, CUresult result, const char* description = nullptr) {
      if (result == CUDA_SUCCESS)
        return true;

      const char* error;
      const char* message;
      cuGetErrorName(result, &error);
      cuGetErrorString(result, &message);
      abortOnCudaError(file, line, cmd, error, message, description);
      return false;
    }

/**
 * Checks the result of a CUDA operation and aborts if an error occurs.
 *
 * @param file The source file where the check is performed.
 * @param line The line number in the source file where the check is performed.
 * @param cmd The CUDA command that was executed.
 * @param result The result of the CUDA operation.
 * @param description An optional description of the error.
 * @return True if the CUDA operation was successful, false otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline bool cudaCheck_(
        const char* file, int line, const char* cmd, cudaError_t result, const char* description = nullptr) {
      if (result == cudaSuccess)
        return true;

      const char* error = cudaGetErrorName(result);
      const char* message = cudaGetErrorString(result);
      abortOnCudaError(file, line, cmd, error, message, description);
      return false;
    }

  }  // namespace cuda
}  // namespace cms

#define cudaCheck(ARG, ...) (cms::cuda::cudaCheck_(__FILE__, __LINE__, #ARG, (ARG), ##__VA_ARGS__))

#endif  // HeterogeneousCore_CUDAUtilities_cudaCheck_h
