#ifndef HeterogeneousCore_CUDACore_src_getCachingDeviceAllocator
#define HeterogeneousCore_CUDACore_src_getCachingDeviceAllocator

#include <iomanip>
#include <iostream>

#include <cuda_runtime.h>

#include "CUDACore/cudaCheck.h"
#include "CUDACore/currentDevice.h"
#include "CUDACore/deviceCount.h"
#include "CUDACore/eventWorkHasCompleted.h"
#include "CUDACore/GenericCachingAllocator.h"

namespace cms::cuda::allocator {
  // Use caching or not
  enum class Policy { Synchronous = 0, Asynchronous = 1, Caching = 2 };
#ifndef CUDADEV_DISABLE_CACHING_ALLOCATOR
  constexpr Policy policy = Policy::Caching;
#elif CUDA_VERSION >= 11020 && !defined CUDADEV_DISABLE_ASYNC_ALLOCATOR
  constexpr Policy policy = Policy::Asynchronous;
#else
  constexpr Policy policy = Policy::Synchronous;
#endif
  // Growth factor (bin_growth in cub::CachingDeviceAllocator
  constexpr unsigned int binGrowth = 2;
  // Smallest bin, corresponds to binGrowth^minBin bytes (min_bin in cub::CacingDeviceAllocator
  constexpr unsigned int minBin = 8;
  // Largest bin, corresponds to binGrowth^maxBin bytes (max_bin in cub::CachingDeviceAllocator). Note that unlike in cub, allocations larger than binGrowth^maxBin are set to fail.
  constexpr unsigned int maxBin = 30;
  // Total storage for the allocator. 0 means no limit.
  constexpr size_t maxCachedBytes = 0;
  // Fraction of total device memory taken for the allocator. In case there are multiple devices with different amounts of memory, the smallest of them is taken. If maxCachedBytes is non-zero, the smallest of them is taken.
  constexpr double maxCachedFraction = 0.8;
  constexpr bool debug = false;

/**
 * Calculates the minimum number of bytes that can be cached across all devices.
 *
 * @return The minimum number of cacheable bytes.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  inline size_t minCachedBytes() {
    size_t ret = std::numeric_limits<size_t>::max();
    int currentDevice;
    cudaCheck(cudaGetDevice(&currentDevice));
    const int numberOfDevices = deviceCount();
    for (int i = 0; i < numberOfDevices; ++i) {
      size_t freeMemory, totalMemory;
      cudaCheck(cudaSetDevice(i));
      cudaCheck(cudaMemGetInfo(&freeMemory, &totalMemory));
      ret = std::min(ret, static_cast<size_t>(maxCachedFraction * freeMemory));
    }
    cudaCheck(cudaSetDevice(currentDevice));
    if (maxCachedBytes > 0) {
      ret = std::min(ret, maxCachedBytes);
    }
    return ret;
  }

  struct DeviceTraits {
    using DeviceType = int;
    using QueueType = cudaStream_t;
    using EventType = cudaEvent_t;

    static constexpr DeviceType kInvalidDevice = -1;

    static DeviceType currentDevice() { return cms::cuda::currentDevice(); }

/**
 * @brief Returns the device type where memory is allocated for an event.
 *
 * This function takes a device event as input and returns the device type 
 * where the memory is allocated, which in this case is the same as the 
 * device where the event is recorded.
 *
 * @param deviceEvent The device event for which memory allocation is done.
 * @return The device type where memory is allocated.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static DeviceType memoryDevice(DeviceType deviceEvent) {
      // For device allocator the device where the memory is allocated
      // on is the same as the device where the event is recorded on.
      return deviceEvent;
    }

    static bool canReuseInDevice(DeviceType a, DeviceType b) { return a == b; }

    static bool canReuseInQueue(QueueType a, QueueType b) { return a == b; }

    template <typename C>
/**
 * @brief Compares two devices based on their type and an additional comparison function.
 *
 * @param a_dev The first device to compare.
 * @param b_dev The second device to compare.
 * @param compare A callable object that provides additional comparison logic.
 * @return True if a_dev is considered less than b_dev, false otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static bool deviceCompare(DeviceType a_dev, DeviceType b_dev, C&& compare) {
      if (a_dev == b_dev) {
        return compare();
      }
      return a_dev < b_dev;
    }

    static bool eventWorkHasCompleted(EventType e) { return cms::cuda::eventWorkHasCompleted(e); }

/**
 * Creates a new event with timing disabled
 *
 * @return A newly created event
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static EventType createEvent() {
      EventType e;
      cudaCheck(cudaEventCreateWithFlags(&e, cudaEventDisableTiming));
      return e;
    }

    static void destroyEvent(EventType e) { cudaCheck(cudaEventDestroy(e)); }

    static EventType recreateEvent(EventType e, DeviceType prev, DeviceType next) {
      throw std::runtime_error("CUDADeviceTraits::recreateEvent() should never be called");
    }

    static void recordEvent(EventType e, QueueType queue) { cudaCheck(cudaEventRecord(e, queue)); }

    struct DevicePrinter {
      DevicePrinter(DeviceType device) : device_(device) {}
      void write(std::ostream& os) const { os << "Device " << device_; }
      DeviceType device_;
    };

    static DevicePrinter printDevice(DeviceType device) { return DevicePrinter(device); }

/**
 * Allocates memory on the device.
 *
 * @param bytes Number of bytes to allocate
 * @return Pointer to allocated memory
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static void* allocate(size_t bytes) {
      void* ptr;
      cudaCheck(cudaMalloc(&ptr, bytes));
      return ptr;
    }

/**
 * Attempts to allocate memory on the GPU.
 *
 * @param bytes The number of bytes to allocate.
 * @return A pointer to the allocated memory or nullptr if allocation failed due to out of memory.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static void* tryAllocate(size_t bytes) {
      void* ptr;
      auto error = cudaMalloc(&ptr, bytes);
      if (error == cudaErrorMemoryAllocation) {
        return nullptr;
      }
      cudaCheck(error);
      return ptr;
    }

    static void free(void* ptr) { cudaCheck(cudaFree(ptr)); }
  };

/**
 * Operator overload for printing DevicePrinter objects to an output stream
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  inline std::ostream& operator<<(std::ostream& os, DeviceTraits::DevicePrinter const& pr) {
    pr.write(os);
    return os;
  }

  using CachingDeviceAllocator = GenericCachingAllocator<DeviceTraits>;

/**
 * Returns a caching device allocator instance.
 *
 * This function provides access to a statically initialized CachingDeviceAllocator object,
 * which manages memory allocation and caching for devices. The allocator's settings,
 * such as bin growth, minimum and maximum bin sizes, and debugging mode, are configured
 * upon initialization. The function returns a reference to the allocator instance,
 * allowing users to utilize its functionality in a thread-safe manner.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  inline CachingDeviceAllocator& getCachingDeviceAllocator() {
    if (debug) {
      std::cout << "cub::CachingDeviceAllocator settings\n"
                << "  bin growth " << binGrowth << "\n"
                << "  min bin    " << minBin << "\n"
                << "  max bin    " << maxBin << "\n"
                << "  resulting bins:\n";
      for (auto bin = minBin; bin <= maxBin; ++bin) {
        auto binSize = ::allocator::intPow(binGrowth, bin);
        if (binSize >= (1 << 30) and binSize % (1 << 30) == 0) {
          std::cout << "    " << std::setw(8) << (binSize >> 30) << " GB\n";
        } else if (binSize >= (1 << 20) and binSize % (1 << 20) == 0) {
          std::cout << "    " << std::setw(8) << (binSize >> 20) << " MB\n";
        } else if (binSize >= (1 << 10) and binSize % (1 << 10) == 0) {
          std::cout << "    " << std::setw(8) << (binSize >> 10) << " kB\n";
        } else {
          std::cout << "    " << std::setw(9) << binSize << " B\n";
        }
      }
      std::cout << "  maximum amount of cached memory: " << (minCachedBytes() >> 20) << " MB\n";
    }

    // the public interface is thread safe
    static CachingDeviceAllocator allocator{binGrowth, minBin, maxBin, minCachedBytes(), debug};
    return allocator;
  }
}  // namespace cms::cuda::allocator

#endif
