#include "CUDADataFormats/SiPixelDigisCUDA.h"

#include "CUDACore/copyAsync.h"
#include "CUDACore/device_unique_ptr.h"
#include "CUDACore/host_unique_ptr.h"


// The following comment is generated by an LLM. 
/**
 * Constructor initializing member variables with unique pointers to device memory
 * allocating space for pixel digis data structures on the GPU
 * @param maxFedWords maximum number of fed words
 * @param stream CUDA stream for asynchronous operations
 */ 
SiPixelDigisCUDA::SiPixelDigisCUDA(size_t maxFedWords, cudaStream_t stream)
    : xx_d(cms::cuda::make_device_unique<uint16_t[]>(maxFedWords, stream)),
      yy_d(cms::cuda::make_device_unique<uint16_t[]>(maxFedWords, stream)),
      adc_d(cms::cuda::make_device_unique<uint16_t[]>(maxFedWords, stream)),
      moduleInd_d(cms::cuda::make_device_unique<uint16_t[]>(maxFedWords, stream)),
      clus_d(cms::cuda::make_device_unique<int32_t[]>(maxFedWords, stream)),
      view_d(cms::cuda::make_device_unique<DeviceConstView>(stream)),
      pdigi_d(cms::cuda::make_device_unique<uint32_t[]>(maxFedWords, stream)),
      rawIdArr_d(cms::cuda::make_device_unique<uint32_t[]>(maxFedWords, stream)) {
  auto view = cms::cuda::make_host_unique<DeviceConstView>(stream);
  view->xx_ = xx_d.get();
  view->yy_ = yy_d.get();
  view->adc_ = adc_d.get();
  view->moduleInd_ = moduleInd_d.get();
  view->clus_ = clus_d.get();

  cms::cuda::copyAsync(view_d, view, stream);
}


// The following comment is generated by an LLM. 
/**
 * Returns a unique pointer to an array of uint16_t values copied asynchronously from device memory to host memory.
 */ 
cms::cuda::host::unique_ptr<uint16_t[]> SiPixelDigisCUDA::adcToHostAsync(cudaStream_t stream) const {
  auto ret = cms::cuda::make_host_unique<uint16_t[]>(nDigis(), stream);
  cms::cuda::copyAsync(ret, adc_d, nDigis(), stream);
  return ret;
}


// The following comment is generated by an LLM. 
/**
 * Returns a unique pointer to an array of integers representing cluster data copied asynchronously from device to host.
 */ 
cms::cuda::host::unique_ptr<int32_t[]> SiPixelDigisCUDA::clusToHostAsync(cudaStream_t stream) const {
  auto ret = cms::cuda::make_host_unique<int32_t[]>(nDigis(), stream);
  cms::cuda::copyAsync(ret, clus_d, nDigis(), stream);
  return ret;
}


// The following comment is generated by an LLM. 
/**
 * Returns a unique pointer to an array of uint32_t on the host 
 * containing digi data transferred asynchronously from the device.
 *
 * @param stream CUDA stream handle
 * @return Unique pointer to host array of uint32_t
 */ 
cms::cuda::host::unique_ptr<uint32_t[]> SiPixelDigisCUDA::pdigiToHostAsync(cudaStream_t stream) const {
  auto ret = cms::cuda::make_host_unique<uint32_t[]>(nDigis(), stream);
  cms::cuda::copyAsync(ret, pdigi_d, nDigis(), stream);
  return ret;
}


// The following comment is generated by an LLM. 
/**
 * @brief Copies raw ID array from device to host asynchronously.
 *
 * @param stream CUDA stream used for asynchronous copy operation.
 * @return Unique pointer to host array containing copied raw IDs.
 */ 
cms::cuda::host::unique_ptr<uint32_t[]> SiPixelDigisCUDA::rawIdArrToHostAsync(cudaStream_t stream) const {
  auto ret = cms::cuda::make_host_unique<uint32_t[]>(nDigis(), stream);
  cms::cuda::copyAsync(ret, rawIdArr_d, nDigis(), stream);
  return ret;
}
