#ifndef EDProducerBase_h
#define EDProducerBase_h

#include "Framework/WaitingTaskWithArenaHolder.h"

namespace edm {
  class Event;
  class EventSetup;

/**
 * Brief description of the EDProducer class.
 *
 * The EDProducer class provides an abstract base class for producers,
 * defining the interface for acquiring and producing data.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  class EDProducer {
  public:
    EDProducer() = default;
    virtual ~EDProducer() = default;

    bool hasAcquire() const { return false; }

    void doAcquire(Event const& event, EventSetup const& eventSetup, WaitingTaskWithArenaHolder holder) {}

    void doProduce(Event& event, EventSetup const& eventSetup) { produce(event, eventSetup); }

    virtual void produce(Event& event, EventSetup const& eventSetup) = 0;

    void doEndJob() { endJob(); }

    virtual void endJob() {}

  private:
  };

/**
 * @brief Interface for producers that perform work externally
 *
 * This class provides an interface for producers that need to perform work outside of the normal production loop.
 * It allows for acquisition and production of events in a way that is decoupled from the main event processing flow.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  class EDProducerExternalWork {
  public:
    EDProducerExternalWork() = default;
    virtual ~EDProducerExternalWork() = default;

    bool hasAcquire() const { return true; }

    void doAcquire(Event const& event, EventSetup const& eventSetup, WaitingTaskWithArenaHolder holder) {
      acquire(event, eventSetup, std::move(holder));
    }

    void doProduce(Event& event, EventSetup const& eventSetup) { produce(event, eventSetup); }

    virtual void acquire(Event const& event, EventSetup const& eventSetup, WaitingTaskWithArenaHolder holder) = 0;
    virtual void produce(Event& event, EventSetup const& eventSetup) = 0;

    void doEndJob() { endJob(); }
    virtual void endJob() {}

  private:
  };
}  // namespace edm

#endif
