#include "CUDADataFormats/TrackingRecHit2DCUDA.h"
#include "CUDACore/copyAsync.h"
#include "CUDACore/cudaCheck.h"
#include "CUDACore/device_unique_ptr.h"
#include "CUDACore/host_unique_ptr.h"

template <>

// The following comment is generated by an LLM. 
/**
 * Returns a unique pointer to an array of floats representing local coordinates 
 * transferred asynchronously from device to host memory.
 *
 * @param stream CUDA stream handle
 * @return Unique pointer to float array
 */ 
cms::cuda::host::unique_ptr<float[]> TrackingRecHit2DCUDA::localCoordToHostAsync(cudaStream_t stream) const {
  auto ret = cms::cuda::make_host_unique<float[]>(4 * nHits(), stream);
  cms::cuda::copyAsync(ret, m_store32, 4 * nHits(), stream);
  return ret;
}

template <>

// The following comment is generated by an LLM. 
/**
 * Returns a unique pointer to an array of hits module start data transferred from device to host asynchronously.
 *
 * @param stream CUDA stream handle
 * @return Unique pointer to array of hits module start data
 */ 
cms::cuda::host::unique_ptr<uint32_t[]> TrackingRecHit2DCUDA::hitsModuleStartToHostAsync(cudaStream_t stream) const {
  auto ret = cms::cuda::make_host_unique<uint32_t[]>(2001, stream);
  cudaCheck(cudaMemcpyAsync(ret.get(), m_hitsModuleStart, 4 * 2001, cudaMemcpyDefault, stream));
  return ret;
}

template <>

// The following comment is generated by an LLM. 
/**
 * @brief Copies global coordinates from device to host asynchronously.
 *
 * @param stream CUDA stream for asynchronous operation
 * @return Unique pointer to array of floats representing global coordinates on host
 */ 
cms::cuda::host::unique_ptr<float[]> TrackingRecHit2DCUDA::globalCoordToHostAsync(cudaStream_t stream) const {
  auto ret = cms::cuda::make_host_unique<float[]>(4 * nHits(), stream);
  cudaCheck(cudaMemcpyAsync(
      ret.get(), m_store32.get() + 4 * nHits(), 4 * nHits() * sizeof(float), cudaMemcpyDefault, stream));
  return ret;
}

template <>

// The following comment is generated by an LLM. 
/**
 * Returns a unique pointer to an array of integers representing tracking rec hits charges 
 * transferred asynchronously from device to host memory.
 *
 * @param stream CUDA stream handle
 * @return Unique pointer to an array of integers
 */ 
cms::cuda::host::unique_ptr<int32_t[]> TrackingRecHit2DCUDA::chargeToHostAsync(cudaStream_t stream) const {
  auto ret = cms::cuda::make_host_unique<int32_t[]>(nHits(), stream);
  cudaCheck(
      cudaMemcpyAsync(ret.get(), m_store32.get() + 8 * nHits(), nHits() * sizeof(int32_t), cudaMemcpyDefault, stream));
  return ret;
}

template <>

// The following comment is generated by an LLM. 
/**
 * @brief Asynchronously copies size data from device to host.
 *
 * @param stream CUDA stream used for asynchronous operation
 * @return Unique pointer to array of int16_t values on host
 */ 
cms::cuda::host::unique_ptr<int16_t[]> TrackingRecHit2DCUDA::sizeToHostAsync(cudaStream_t stream) const {
  auto ret = cms::cuda::make_host_unique<int16_t[]>(2 * nHits(), stream);
  cudaCheck(cudaMemcpyAsync(
      ret.get(), m_store16.get() + 2 * nHits(), 2 * nHits() * sizeof(int16_t), cudaMemcpyDefault, stream));
  return ret;
}
