#ifndef HeterogeneousCore_CUDAUtilities_interface_portableAtomicOp_h
#define HeterogeneousCore_CUDAUtilities_interface_portableAtomicOp_h

#include <algorithm>
#include <atomic>
#include <concepts>
#include <type_traits>

#ifdef __NVCOMPILER
#include <nv/target>
#endif

namespace cms::cuda {

  template <std::totally_ordered T, typename Tp = std::add_pointer_t<T>>
/**
 * @brief Performs an atomic addition operation on a variable.
 *
 * This function adds a value to a variable in a thread-safe manner,
 * ensuring that the operation is executed as a single, uninterruptible unit.
 *
 * @param address The memory address of the variable to modify.
 * @param val The value to add to the variable.
 * @return The result of the atomic addition operation.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  T atomicAdd(Tp address, T val) {
#ifdef __NVCOMPILER
    // We need to check if execution space is device or host, ::atomicAdd is undefined in host execution space
    if target (nv::target::is_device) {
      return ::atomicAdd(address, val);
    } else {
      std::atomic_ref<T> inc{*address};
      return inc.fetch_add(val);
    }
#else
    std::atomic_ref<T> inc{*address};
    return inc.fetch_add(val);
#endif
  }

  template <std::totally_ordered T, typename Tp = std::add_pointer_t<T>>
/**
 * @brief Performs an atomic minimum operation on a variable.
 *
 * This function atomically updates the value at the specified address to be the minimum of its current value and the given value.
 *
 * @param address The memory address of the variable to update.
 * @param val The new value to compare with the current value.
 * @return The previous value of the variable.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  T atomicMin(Tp address, T val) {
#ifdef __NVCOMPILER
    // We need to check if execution space is device or host, ::atomicMin is undefined in host execution space
    if target (nv::target::is_device) {
      return ::atomicMin(address, val);
    } else {
      std::atomic_ref<T> pa{*address};
      T old{pa.load()};
      while (!pa.compare_exchange_weak(old, std::min(old, val)))
        ;
      return old;
    }
#else
    std::atomic_ref<T> pa{*address};
    T old{pa.load()};
    while (!pa.compare_exchange_weak(old, std::min(old, val)))
      ;
    return old;
#endif
  }

  template <std::totally_ordered T, typename Tp = std::add_pointer_t<T>>
/**
 * Performs an atomic maximum operation on a variable at a specified address.
 *
 * @param address The memory address of the variable to operate on.
 * @param val The value to compare and potentially update the variable with.
 * @return The previous value of the variable before the operation was performed.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  T atomicMax(Tp address, T val) {
#ifdef __NVCOMPILER
    // We need to check if execution space is device or host, ::atomicMin is undefined in host execution space
    if target (nv::target::is_device) {
      return ::atomicMax(address, val);
    } else {
      std::atomic_ref<T> pa{*address};
      T old{pa.load()};
      while (!pa.compare_exchange_weak(old, std::max(old, val)))
        ;
      return old;
    }
#else
    std::atomic_ref<T> pa{*address};
    T old{pa.load()};
    while (!pa.compare_exchange_weak(old, std::max(old, val)))
      ;
    return old;
#endif
  }

  template <std::totally_ordered T, typename Tp = std::add_pointer_t<T>>
/**
 * @brief Performs an atomic increment operation on a variable.
 *
 * This function provides a way to atomically increment a variable,
 * ensuring that the operation is thread-safe and visible to all threads.
 *
 * @param address The memory address of the variable to be incremented.
 * @param val The value to be added to the variable.
 * @return The previous value of the variable before the increment operation.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  T atomicInc(Tp address, T val) {
#ifdef __NVCOMPILER
    // We need to check if execution space is device or host, ::atomicInc is undefined in host execution space
    if target (nv::target::is_device) {
      return ::atomicInc(address, val);
    } else {
      std::atomic_ref<T> pa{*address};
      T old{pa.load()};
      while (!pa.compare_exchange_weak(old, ((old >= val) ? 0 : (old + 1))))
        ;
      return old;
    }
#else
    std::atomic_ref<T> pa{*address};
    T old{pa.load()};
    while (!pa.compare_exchange_weak(old, ((old >= val) ? 0 : (old + 1))))
      ;
    return old;
#endif
  }
}  // namespace cms::cuda

#endif