#ifndef HeterogeneousCore_CUDAUtilities_interface_SimpleVector_h
#define HeterogeneousCore_CUDAUtilities_interface_SimpleVector_h

//  author: Felice Pantaleo, CERN, 2018

#include <atomic>
#include <type_traits>
#include <utility>

namespace cms {
  namespace cuda {

    template <class T>
    struct SimpleVector {
      constexpr SimpleVector() = default;

      // ownership of m_data stays within the caller
      constexpr void construct(int32_t capacity, T *data) {
        m_size = 0;
        m_capacity = capacity;
        m_data = data;
      }

/**
 * Pushes an element onto the end of the container without checking for capacity.
 *
 * @param element The element to be added to the container.
 * @return The index of the newly added element if successful, -1 otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline constexpr int push_back_unsafe(const T &element) {
        auto previousSize = size();
        m_size++;
        if (previousSize < m_capacity) {
          m_data[previousSize] = element;
          return previousSize;
        } else {
          --m_size;
          return -1;
        }
      }

      template <class... Ts>
/**
 * Emplaces an element at the end of the container without checking for capacity.
 *
 * @param args  forwarding arguments to pass to the constructor of T
 * @return the index where the new element was inserted, or -1 if reallocation failed
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      constexpr int emplace_back_unsafe(Ts &&...args) {
        auto previousSize = size();
        m_size++;
        if (previousSize < m_capacity) {
          (new (&m_data[previousSize]) T(std::forward<Ts>(args)...));
          return previousSize;
        } else {
          --m_size;
          return -1;
        }
      }

      inline T &back() { return m_data[size() - 1]; }

/**
 * Returns a constant reference to the last element in the container.
 *
 * @return A constant reference to the last element if the container is not empty,
 *         otherwise returns an undefined value.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline const T &back() const {
        if (size() > 0) {
          return m_data[size() - 1];
        } else
          return T();  //undefined behaviour
      }

      // thread-safe version of the vector, when used in a CUDA kernel
      int push_back(const T &element) {
        std::atomic_ref<int32_t> s(m_size);
        auto previousSize = s++;
        if (previousSize < m_capacity) {
          m_data[previousSize] = element;
          return previousSize;
        } else {
          --s;
          return -1;
        }
      }

      template <class... Ts>
/**
 * @brief Emplaces an element at the end of the container.
 *
 * @tparam Ts Types of arguments to forward to the constructor of T.
 * @param args Arguments to forward to the constructor of T.
 * @return The index of the newly constructed element if successful, -1 otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      int emplace_back(Ts &&...args) {
        std::atomic_ref<int32_t> s(m_size);
        auto previousSize = s++;
        if (previousSize < m_capacity) {
          (new (&m_data[previousSize]) T(std::forward<Ts>(args)...));
          return previousSize;
        } else {
          --s;
          return -1;
        }
      }

      // thread safe version of resize
      int extend(int32_t size = 1) {
        std::atomic_ref<int32_t> s(m_size);
        auto previousSize = s.fetch_add(size);
        if (previousSize < m_capacity) {
          return previousSize;
        } else {
          s -= size;
          return -1;
        }
      }

/**
 * Decreases the internal counter by a specified amount if it is sufficient
 * @param size the amount to decrease the counter by
 * @return the new value of the counter if successful otherwise -1
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      int shrink(int32_t size = 1) {
        std::atomic_ref<int32_t> s(m_size);
        auto previousSize = s.fetch_sub(size);
        if (previousSize >= size) {
          return previousSize - size;
        } else {
          s += size;
          return -1;
        }
      }

      inline constexpr bool empty() const { return size() <= 0; }
      inline constexpr bool full() const { return size() >= m_capacity; }
      inline constexpr T &operator[](int i) { return m_data[i]; }
      inline constexpr const T &operator[](int i) const { return m_data[i]; }
      inline constexpr void reset() { resize(0); }
      inline constexpr int32_t size() const { return m_size; }
      inline constexpr int32_t capacity() const { return m_capacity; }
      inline constexpr T const *data() const { return m_data; }
      inline constexpr void resize(int32_t size) { m_size = size; }
      inline constexpr void set_data(T *data) { m_data = data; }

    private:
      int32_t m_capacity;
      int32_t m_size;

      T *m_data;
    };

    // ownership of m_data stays within the caller
    template <class T>
/**
 * Constructs a simple vector with specified capacity and data.
 *
 * @param capacity The initial capacity of the vector.
 * @param data The array of elements to initialize the vector with.
 * @return A newly constructed SimpleVector instance.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    SimpleVector<T> make_SimpleVector(int32_t capacity, T *data) {
      SimpleVector<T> ret;
      ret.construct(capacity, data);
      return ret;
    }

    // ownership of m_data stays within the caller
    template <class T>
/**
 * Creates a new SimpleVector instance at the specified memory location.
 *
 * @param mem Memory location where the vector will be constructed
 * @param capacity Initial capacity of the vector
 * @param data Array of elements to initialize the vector with
 * @return Pointer to the newly created SimpleVector instance
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    SimpleVector<T> *make_SimpleVector(SimpleVector<T> *mem, int32_t capacity, T *data) {
      auto ret = new (mem) SimpleVector<T>();
      ret->construct(capacity, data);
      return ret;
    }

  }  // namespace cuda
}  // namespace cms

#endif  // HeterogeneousCore_CUDAUtilities_interface_SimpleVector_h
