#ifndef HeterogeneousCore_CUDAUtilities_interface_VecArray_h
#define HeterogeneousCore_CUDAUtilities_interface_VecArray_h

//
// Author: Felice Pantaleo, CERN
//

#include <atomic>

namespace cms {
  namespace cuda {

    template <class T, int maxSize>
    class VecArray {
    public:
      using self = VecArray<T, maxSize>;
      using value_t = T;

/**
 * Class Vector 
 * Brief description: Dynamic array class with unsafe push back operation
 * Detailed description: This class represents a dynamic array that allows elements to be added without checking for bounds
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline constexpr int push_back_unsafe(const T &element) {
        auto previousSize = m_size;
        m_size++;
        if (previousSize < maxSize) {
          m_data[previousSize] = element;
          return previousSize;
        } else {
          --m_size;
          return -1;
        }
      }

      template <class... Ts>
/**
 * Brief description of the function emplace_back_unsafe 
 * Detailed description of the function emplace_back_unsafe 
 * @param args variable number of arguments 
 * @return integer value indicating success or failure 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      constexpr int emplace_back_unsafe(Ts &&...args) {
        auto previousSize = m_size;
        m_size++;
        if (previousSize < maxSize) {
          (new (&m_data[previousSize]) T(std::forward<Ts>(args)...));
          return previousSize;
        } else {
          --m_size;
          return -1;
        }
      }

/**
 * Returns a reference to the last element in the container.
 *
 * @return A reference to the last element if the container is not empty,
 *         otherwise returns a default constructed T object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline constexpr T &back() const {
        if (m_size > 0) {
          return m_data[m_size - 1];
        } else
          return T();  //undefined behaviour
      }

      // thread-safe version of the vector, when used in a CUDA kernel
      int push_back(const T &element) {
        std::atomic_ref<int> s(m_size);
        auto previousSize = s++;
        if (previousSize < maxSize) {
          m_data[previousSize] = element;
          return previousSize;
        } else {
          --s;
          return -1;
        }
      }

      template <class... Ts>
/**
 * Emplaces element at the end of the container.
 *
 * @param args  variable number of arguments to forward to constructor of T
 * @return index of newly constructed element if successful, -1 otherwise
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      int emplace_back(Ts &&...args) {
        std::atomic_ref<int> s(m_size);
        auto previousSize = s++;
        if (previousSize < maxSize) {
          (new (&m_data[previousSize]) T(std::forward<Ts>(args)...));
          return previousSize;
        } else {
          --s;
          return -1;
        }
      }

/**
 * Removes and returns the last element from the container.
 *
 * @return The last element removed from the container.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline constexpr T pop_back() {
        if (m_size > 0) {
          auto previousSize = m_size--;
          return m_data[previousSize - 1];
        } else
          return T();
      }

      inline constexpr T const *begin() const { return m_data; }
      inline constexpr T const *end() const { return m_data + m_size; }
      inline constexpr T *begin() { return m_data; }
      inline constexpr T *end() { return m_data + m_size; }
      inline constexpr int size() const { return m_size; }
      inline constexpr T &operator[](int i) { return m_data[i]; }
      inline constexpr const T &operator[](int i) const { return m_data[i]; }
      inline constexpr void reset() { m_size = 0; }
      inline static constexpr int capacity() { return maxSize; }
      inline constexpr T const *data() const { return m_data; }
      inline constexpr void resize(int size) { m_size = size; }
      inline constexpr bool empty() const { return 0 == m_size; }
      inline constexpr bool full() const { return maxSize == m_size; }

    private:
      T m_data[maxSize];

      int m_size;
    };

  }  // namespace cuda
}  // namespace cms

#endif  // HeterogeneousCore_CUDAUtilities_interface_VecArray_h
