#ifndef RecoLocalTracker_SiPixelRecHits_PixelCPEFast_h
#define RecoLocalTracker_SiPixelRecHits_PixelCPEFast_h

#include <memory>

#include "CondFormats/pixelCPEforGPU.h"

/**
 * @brief Class representing a fast pixel cluster parameter estimator.
 *
 * This class provides an interface to estimate pixel cluster parameters quickly.
 * It manages the memory and data necessary for the estimation process.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
class PixelCPEFast {
public:
  PixelCPEFast(std::string const& path);

  ~PixelCPEFast();

  pixelCPEforGPU::ParamsOnGPU const* get() const { return m_params.get(); }

private:
  std::unique_ptr<pixelCPEforGPU::ParamsOnGPU> m_params;
  std::unique_ptr<pixelCPEforGPU::CommonParams> m_commonParams;
  std::unique_ptr<pixelCPEforGPU::DetParams[]> m_detParams;
  std::unique_ptr<pixelCPEforGPU::LayerGeometry> m_layerGeometry;
  std::unique_ptr<pixelCPEforGPU::AverageGeometry> m_averageGeometry;
};

#endif  // RecoLocalTracker_SiPixelRecHits_PixelCPEFast_h
