#include <algorithm>
#include <memory>
#include <vector>

#include "CondFormats/SiPixelGainCalibrationForHLTGPU.h"
#include "CondFormats/SiPixelGainForHLTonGPU.h"


// The following comment is generated by an LLM. 
/**
 * Constructor initializing SiPixelGainCalibrationForHLTGPU object with gain and gain data.
 * @param gain SiPixelGainForHLTonGPU object containing gain calibration data
 * @param gainData vector of DecodingStructure objects containing gain data
 */ 
SiPixelGainCalibrationForHLTGPU::SiPixelGainCalibrationForHLTGPU(SiPixelGainForHLTonGPU const& gain,
                                                                 std::vector<DecodingStructure> const& gainData)
    : gainForHLT_{std::make_unique<SiPixelGainForHLTonGPU>(gain)},
      gainData_{std::make_unique<DecodingStructure[]>(gainData.size())} {
  gainForHLT_->v_pedestals = gainData_.get();
  std::copy(gainData.cbegin(), gainData.cend(), gainData_.get());
}
