#ifndef RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h
#define RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h

#include <memory>

#include "CondFormats/SiPixelFedCablingMapGPU.h"

/**
 * @brief Wrapper class for SiPixelFedCablingMapGPU providing additional functionality
 *
 * @details Manages SiPixelFedCablingMapGPU object and provides access to its data
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
class SiPixelFedCablingMapGPUWrapper {
public:
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const& cablingMap,
                                          std::vector<unsigned char> const& modToUnp);

  bool hasQuality() const { return hasQuality_; }

  // returns pointer to GPU memory
  const SiPixelFedCablingMapGPU* cablingMap() const { return cablingMap_.get(); }

  // returns pointer to GPU memory
  const unsigned char* modToUnpAll() const { return modToUnpDefault_.get(); }

private:
  bool hasQuality_;

  std::unique_ptr<SiPixelFedCablingMapGPU> cablingMap_;
  std::unique_ptr<unsigned char[]> modToUnpDefault_;
};

#endif
