#ifndef HeterogeneousCore_CUDAUtilities_cudastdAlgorithm_h
#define HeterogeneousCore_CUDAUtilities_cudastdAlgorithm_h

#include <utility>

#include "CUDACore/cudaCompat.h"

// reimplementation of std algorithms able to compile with CUDA and run on GPUs,
// mostly by declaringthem constexpr

namespace cuda_std {

  template <typename T = void>
  struct less {
    constexpr bool operator()(const T &lhs, const T &rhs) const { return lhs < rhs; }
  };

  template <>
  struct less<void> {
    template <typename T, typename U>
    constexpr bool operator()(const T &lhs, const U &rhs) const {
      return lhs < rhs;
    }
  };

  template <typename RandomIt, typename T, typename Compare = less<T>>
/**
 * Searches for the first element in the range that is not less than the given value.
 *
 * @param first   beginning of the range
 * @param last    end of the range
 * @param value   value to search for
 * @param comp    comparison function object
 * @return       iterator pointing to the first element not less than the given value
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  constexpr RandomIt lower_bound(RandomIt first, RandomIt last, const T &value, Compare comp = {}) {
    auto count = last - first;

    while (count > 0) {
      auto it = first;
      auto step = count / 2;
      it += step;
      if (comp(*it, value)) {
        first = ++it;
        count -= step + 1;
      } else {
        count = step;
      }
    }
    return first;
  }

  template <typename RandomIt, typename T, typename Compare = less<T>>
/**
 * Searches for the upper bound of a value within a range defined by two random access iterators.
 *
 * @param first   beginning of the range
 * @param last    end of the range
 * @param value   value to search for
 * @param comp    comparison function object
 * @return       an iterator pointing to the upper bound of the value
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  constexpr RandomIt upper_bound(RandomIt first, RandomIt last, const T &value, Compare comp = {}) {
    auto count = last - first;

    while (count > 0) {
      auto it = first;
      auto step = count / 2;
      it += step;
      if (!comp(value, *it)) {
        first = ++it;
        count -= step + 1;
      } else {
        count = step;
      }
    }
    return first;
  }

  template <typename RandomIt, typename T, typename Compare = cuda_std::less<T>>
/**
 * Searches for an element in a sorted range using a custom comparison function.
 *
 * @param first Beginning of the search range.
 * @param last End of the search range.
 * @param value Value to be searched for.
 * @param comp Custom comparison function.
 * @return An iterator pointing to the found element if it exists, otherwise last.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  constexpr RandomIt binary_find(RandomIt first, RandomIt last, const T &value, Compare comp = {}) {
    first = cuda_std::lower_bound(first, last, value, comp);
    return first != last && !comp(value, *first) ? first : last;
  }

}  // namespace cuda_std

#endif  // HeterogeneousCore_CUDAUtilities_cudastdAlgorithm_h
