#ifndef HeterogeneousCore_CUDAUtilities_interface_HistoContainer_h
#define HeterogeneousCore_CUDAUtilities_interface_HistoContainer_h

#include <algorithm>
#include <atomic>
#include <cstddef>
#include <cstdint>
#include <type_traits>

#include "CUDACore/AtomicPairCounter.h"
#include "CUDACore/cuda_assert.h"
#include "CUDACore/cudastdAlgorithm.h"
#include "CUDACore/prefixScan.h"

namespace cms {
  namespace cuda {

    template <typename Histo, typename T>
/**
 * Counts elements from a vector and stores them in a histogram object.
 *
 * @param h          Histogram object to store the counts
 * @param nh         Number of histograms
 * @param v          Vector of elements to count
 * @param offsets    Offsets array for indexing
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    void countFromVector(Histo *__restrict__ h,
                         uint32_t nh,
                         T const *__restrict__ v,
                         uint32_t const *__restrict__ offsets) {
      int first = 0;
      for (int i = first, nt = offsets[nh]; i < nt; i++) {
        auto off = cuda_std::upper_bound(offsets, offsets + nh + 1, i);
        assert((*off) > 0);
        int32_t ih = off - offsets - 1;
        assert(ih >= 0);
        assert(ih < int(nh));
        (*h).count(v[i], ih);
      }
    }

    template <typename Histo, typename T>
/**
 * Fills histogram object from vector data.
 *
 * @param h         Histogram object to fill
 * @param nh        Number of histograms
 * @param v         Vector data to fill from
 * @param offsets   Offsets into vector data
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    void fillFromVector(Histo *__restrict__ h,
                        uint32_t nh,
                        T const *__restrict__ v,
                        uint32_t const *__restrict__ offsets) {
      int first = 0;
      for (int i = first, nt = offsets[nh]; i < nt; i++) {
        auto off = cuda_std::upper_bound(offsets, offsets + nh + 1, i);
        assert((*off) > 0);
        int32_t ih = off - offsets - 1;
        assert(ih >= 0);
        assert(ih < int(nh));
        (*h).fill(v[i], i, ih);
      }
    }

    template <typename Histo>
/**
 * Launches zero initialization of histogram data structure
 *
 * Initializes all offset values of the histogram to zero
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void launchZero(Histo *__restrict__ h) {
      uint32_t *poff = (uint32_t *)((char *)(h) + offsetof(Histo, off));
      int32_t size = offsetof(Histo, bins) - offsetof(Histo, off);
      assert(size >= int(sizeof(uint32_t) * Histo::totbins()));
      ::memset(poff, 0, size);
    }

    template <typename Histo>
    inline void launchFinalize(Histo *__restrict__ h) {
      h->finalize();
    }

    template <typename Histo, typename T>
/**
 * Brief description of function fillManyFromVector
 *
 * Detailed description of function fillManyFromVector which fills many histograms from a vector
 *
 * @param h histogram to be filled
 * @param nh number of histograms
 * @param v input vector
 * @param offsets offset values
 * @param totSize total size
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void fillManyFromVector(Histo *__restrict__ h,
                                   uint32_t nh,
                                   T const *__restrict__ v,
                                   uint32_t const *__restrict__ offsets,
                                   uint32_t totSize) {
      launchZero(h);
      countFromVector(h, nh, v, offsets);
      h->finalize();
      fillFromVector(h, nh, v, offsets);
    }

    template <typename Assoc>
    void finalizeBulk(AtomicPairCounter const *apc, Assoc *__restrict__ assoc) {
      assoc->bulkFinalizeFill(*apc);
    }

    // iteratate over N bins left and right of the one containing "v"
    template <typename Hist, typename V, typename Func>
/**
 * Brief description: Iterates over bins in a histogram.
 *
 * Detailed description: This function iterates over a specified range of bins
 * in a histogram and applies a given function to each bin.
 *
 * Parameters:
 *   hist - The input histogram.
 *   value - The central value of the bin range.
 *   n - The number of bins to iterate over on either side of the central bin.
 *   func - The function to apply to each bin.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void forEachInBins(Hist const &hist, V value, int n, Func func) {
      int bs = Hist::bin(value);
      int be = std::min(int(Hist::nbins() - 1), bs + n);
      bs = std::max(0, bs - n);
      assert(be >= bs);
      for (auto pj = hist.begin(bs); pj < hist.end(be); ++pj) {
        func(*pj);
      }
    }

    // iteratate over bins containing all values in window wmin, wmax
    template <typename Hist, typename V, typename Func>
/**
 * Performs an operation on all elements within a specified window of a histogram.
 *
 * @param hist The input histogram.
 * @param wmin The minimum value of the window.
 * @param wmax The maximum value of the window.
 * @param func The function to apply to each element in the window.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void forEachInWindow(Hist const &hist, V wmin, V wmax, Func const &func) {
      auto bs = Hist::bin(wmin);
      auto be = Hist::bin(wmax);
      assert(be >= bs);
      for (auto pj = hist.begin(bs); pj < hist.end(be); ++pj) {
        func(*pj);
      }
    }

    template <typename T,                  // the type of the discretized input values
              uint32_t NBINS,              // number of bins
              uint32_t SIZE,               // max number of element
              uint32_t S = sizeof(T) * 8,  // number of significant bits in T
              typename I = uint32_t,  // type stored in the container (usually an index in a vector of the input values)
              uint32_t NHISTS = 1     // number of histos stored
              >
    class HistoContainer {
    public:
      using Counter = uint32_t;

      using CountersOnly = HistoContainer<T, NBINS, 0, S, I, NHISTS>;

      using index_type = I;
      using UT = typename std::make_unsigned<T>::type;

/**
 * Calculates the integer logarithm base 2 of a given unsigned 32-bit integer.
 *
 * @param v The input value.
 * @return The integer logarithm base 2 of the input value.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      static constexpr uint32_t ilog2(uint32_t v) {
        constexpr uint32_t b[] = {0x2, 0xC, 0xF0, 0xFF00, 0xFFFF0000};
        constexpr uint32_t s[] = {1, 2, 4, 8, 16};

        uint32_t r = 0;  // result of log2(v) will go here
        for (auto i = 4; i >= 0; i--)
          if (v & b[i]) {
            v >>= s[i];
            r |= s[i];
          }
        return r;
      }

      static constexpr uint32_t sizeT() { return S; }
      static constexpr uint32_t nbins() { return NBINS; }
      static constexpr uint32_t nhists() { return NHISTS; }
      static constexpr uint32_t totbins() { return NHISTS * NBINS + 1; }
      static constexpr uint32_t nbits() { return ilog2(NBINS - 1) + 1; }
      static constexpr uint32_t capacity() { return SIZE; }

      static constexpr auto histOff(uint32_t nh) { return NBINS * nh; }

/**
 * Returns the binary representation of the input value 
 * after applying bit manipulation operations.
 *
 * @param t Input value to be processed
 * @return Binary representation of the input value
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      static constexpr UT bin(T t) {
        constexpr uint32_t shift = sizeT() - nbits();
        constexpr uint32_t mask = (1 << nbits()) - 1;
        return (t >> shift) & mask;
      }

/**
 * Brief description of the function to set all elements to zero
 *
 * Detailed description of the function to initialize values
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      void zero() {
        for (auto &i : off)
          i = 0;
      }

/**
 * Adds another CountersOnly object to this object
 *
 * @param[in] co the CountersOnly object to add
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void add(CountersOnly const &co) {
        for (uint32_t i = 0; i < totbins(); ++i) {
          auto &a = (std::atomic<Counter> &)(off[i]);
          a += co.off[i];
        }
      }

/**
 * Returns the previous value of the counter after incrementing it atomically.
 *
 * @param x reference to the Counter object to be incremented
 * @return the previous value of the counter
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      static inline uint32_t atomicIncrement(Counter &x) {
        auto &a = (std::atomic<Counter> &)(x);
        return a++;
      }

/**
 * Decrements the value of an atomic counter variable.
 *
 * @param x Reference to the Counter object to decrement.
 * @return The previous value of the counter before decrementing.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      static inline uint32_t atomicDecrement(Counter &x) {
        auto &a = (std::atomic<Counter> &)(x);
        return a--;
      }

/**
 * Brief description: Increments the offset of a specific bin in an array.
 *
 * Detailed description: This function takes a bin number as input and increments its corresponding offset value atomically.
 *
 * Parameters:
 *   b - The bin number to be incremented.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void countDirect(T b) {
        assert(b < nbins());
        atomicIncrement(off[b]);
      }

/**
 * FillDirectFunction 
 * Brief description: Decrements offset and assigns bin index
 * Detailed description: This function takes a bin number b and an index j 
 *                     as input decrements the corresponding offset 
 *                     and assigns the index to the respective bin
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void fillDirect(T b, index_type j) {
        assert(b < nbins());
        auto w = atomicDecrement(off[b]);
        assert(w > 0);
        bins[w - 1] = j;
      }

/**
 * Brief description of the function bulkFill
 *
 * This function performs a bulk fill operation on an AtomicPairCounter object
 * It adds a specified number of elements to the counter and stores them in a bin array
 *
 * @param apc reference to an AtomicPairCounter object
 * @param v pointer to an array of index_type values to be added
 * @param n number of elements to add
 * @return the index where the first element was stored or a negative value if overflow occurred
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline int32_t bulkFill(AtomicPairCounter &apc, index_type const *v, uint32_t n) {
        auto c = apc.add(n);
        if (c.m >= nbins())
          return -int32_t(c.m);
        off[c.m] = c.n;
        for (uint32_t j = 0; j < n; ++j)
          bins[c.n + j] = v[j];
        return c.m;
      }

      inline void bulkFinalize(AtomicPairCounter const &apc) { off[apc.get().m] = apc.get().n; }

/**
 * Finalizes the filling process for the AtomicPairCounter object.
 *
 * This function takes into account potential overflows and updates the offset values accordingly.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void bulkFinalizeFill(AtomicPairCounter const &apc) {
        auto m = apc.get().m;
        auto n = apc.get().n;
        if (m >= nbins()) {  // overflow!
          off[nbins()] = uint32_t(off[nbins() - 1]);
          return;
        }
        auto first = m;
        for (auto i = first; i < totbins(); i++) {
          off[i] = n;
        }
      }

/**
 * Brief description: Increments the offset of a specific bin in an atomic manner.
 *
 * Detailed description: This function takes an object of type T as input, determines its corresponding bin,
 * and atomically increments the offset of that bin.
 *
 * Parameters:
 *  t - The input object of type T used to determine the bin.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void count(T t) {
        uint32_t b = bin(t);
        assert(b < nbins());
        atomicIncrement(off[b]);
      }

/**
 * Brief description: Fills a bin with an index value
 *
 * Detailed description: This function takes an object of type T and an index value,
 * determines the corresponding bin using the bin function, decrements the offset
 * for that bin atomically, and stores the index value at the resulting position
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void fill(T t, index_type j) {
        uint32_t b = bin(t);
        assert(b < nbins());
        auto w = atomicDecrement(off[b]);
        assert(w > 0);
        bins[w - 1] = j;
      }

/**
 * Brief description: Increment histogram bin corresponding to given value
 * Detailed description: Increments the histogram bin associated with the input value t,
               taking into account the offset for the specified histogram number nh
 * Parameters:
   t - Input value to be binned
   nh - Histogram number
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void count(T t, uint32_t nh) {
        uint32_t b = bin(t);
        assert(b < nbins());
        b += histOff(nh);
        assert(b < totbins());
        atomicIncrement(off[b]);
      }

/**
 * Brief description: Fills a histogram bin with an index value.
 *
 * Detailed description: This function fills a specific histogram bin with an index value.
 * It first determines the bin number based on the input value t, then calculates the offset within that bin,
 * decrements the count at that offset atomically, and finally stores the index value at the calculated position.
 *
 * Parameters:
 *   t     - Input value to determine the bin number
 *   j     - Index value to store in the histogram bin
 *   nh    - Histogram number to calculate the offset
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void fill(T t, index_type j, uint32_t nh) {
        uint32_t b = bin(t);
        assert(b < nbins());
        b += histOff(nh);
        assert(b < totbins());
        auto w = atomicDecrement(off[b]);
        assert(w > 0);
        bins[w - 1] = j;
      }

/**
 * Finalizes the data structure by performing a prefix scan on the offset array.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline void finalize() {
        assert(off[totbins() - 1] == 0);
        blockPrefixScan(off, totbins());
        assert(off[totbins() - 1] == off[totbins() - 2]);
      }

      constexpr auto size() const { return uint32_t(off[totbins() - 1]); }
      constexpr auto size(uint32_t b) const { return off[b + 1] - off[b]; }

      constexpr index_type const *begin() const { return bins; }
      constexpr index_type const *end() const { return begin() + size(); }

      constexpr index_type const *begin(uint32_t b) const { return bins + off[b]; }
      constexpr index_type const *end(uint32_t b) const { return bins + off[b + 1]; }

      Counter off[totbins()];
      int32_t psws;  // prefix-scan working space
      index_type bins[capacity()];
    };

    template <typename I,        // type stored in the container (usually an index in a vector of the input values)
              uint32_t MAXONES,  // max number of "ones"
              uint32_t MAXMANYS  // max number of "manys"
              >
    using OneToManyAssoc = HistoContainer<uint32_t, MAXONES, MAXMANYS, sizeof(uint32_t) * 8, I, 1>;

  }  // namespace cuda
}  // namespace cms

#endif  // HeterogeneousCore_CUDAUtilities_interface_HistoContainer_h
