#ifndef HeterogeneousCore_CUDAUtilities_interface_HistoContainer_h
#define HeterogeneousCore_CUDAUtilities_interface_HistoContainer_h

#include <algorithm>
#include <atomic>
#include <cstddef>
#include <cstdint>
#include <type_traits>

#include "CUDACore/AtomicPairCounter.h"
#include "CUDACore/cuda_assert.h"
#include "CUDACore/cudastdAlgorithm.h"
#include "CUDACore/prefixScan.h"

namespace cms {
  namespace cuda {

    template <typename Histo, typename T>
/**
 * Counts elements from a vector and updates the histogram accordingly
 * @param h pointer to the histogram object
 * @param nh number of histograms
 * @param v constant array of values to be counted
 * @param offsets array of offsets for the histograms
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    void countFromVector(Histo *__restrict__ h,
                         uint32_t nh,
                         T const *__restrict__ v,
                         uint32_t const *__restrict__ offsets) {
      int first = 0;
      for (int i = first, nt = offsets[nh]; i < nt; i++) {
        auto off = cuda_std::upper_bound(offsets, offsets + nh + 1, i);
        assert((*off) > 0);
        int32_t ih = off - offsets - 1;
        assert(ih >= 0);
        assert(ih < int(nh));
        (*h).count(v[i], ih);
      }
    }

    template <typename Histo, typename T>
/**
 * Fills histogram from vector data
 *
 * @param h         Histogram object to fill
 * @param nh        Number of histograms
 * @param v         Vector data to fill from
 * @param offsets   Offsets into vector data
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    void fillFromVector(Histo *__restrict__ h,
                        uint32_t nh,
                        T const *__restrict__ v,
                        uint32_t const *__restrict__ offsets) {
      int first = 0;
      for (int i = first, nt = offsets[nh]; i < nt; i++) {
        auto off = cuda_std::upper_bound(offsets, offsets + nh + 1, i);
        assert((*off) > 0);
        int32_t ih = off - offsets - 1;
        assert(ih >= 0);
        assert(ih < int(nh));
        (*h).fill(v[i], i, ih);
      }
    }

    template <typename Histo>
/**
 * Launches zero initialization of histogram data structure.
 *
 * Initializes all offset values of the histogram to zero.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    inline void launchZero(Histo *__restrict__ h) {
      uint32_t *poff = (uint32_t *)((char *)(h) + offsetof(Histo, off));
      int32_t size = offsetof(Histo, bins) - offsetof(Histo, off);
      assert(size >= int(sizeof(uint32_t) * Histo::totbins()));
      ::memset(poff, 0, size);
    }

    template <typename Histo>
    inline void launchFinalize(Histo *__restrict__ h) {
      h->finalize();
    }

    template <typename Histo, typename T>
/**
 * Fill many histograms from a vector.
 *
 * @param h         Histogram to fill
 * @param nh        Number of histograms
 * @param v         Vector of values
 * @param offsets   Offsets into the vector
 * @param totSize   Total size of the vector
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    inline void fillManyFromVector(Histo *__restrict__ h,
                                   uint32_t nh,
                                   T const *__restrict__ v,
                                   uint32_t const *__restrict__ offsets,
                                   uint32_t totSize) {
      launchZero(h);
      countFromVector(h, nh, v, offsets);
      h->finalize();
      fillFromVector(h, nh, v, offsets);
    }

    template <typename Assoc>
    void finalizeBulk(AtomicPairCounter const *apc, Assoc *__restrict__ assoc) {
      assoc->bulkFinalizeFill(*apc);
    }

    // iteratate over N bins left and right of the one containing "v"
    template <typename Hist, typename V, typename Func>
/**
 * Brief description of forEachInBins function
 *
 * Detailed description of forEachInBins function
 * 
 * @param hist input histogram object
 * @param value input value
 * @param n number of bins to consider
 * @param func callback function to apply to each bin
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    inline void forEachInBins(Hist const &hist, V value, int n, Func func) {
      int bs = Hist::bin(value);
      int be = std::min(int(Hist::nbins() - 1), bs + n);
      bs = std::max(0, bs - n);
      assert(be >= bs);
      for (auto pj = hist.begin(bs); pj < hist.end(be); ++pj) {
        func(*pj);
      }
    }

    // iteratate over bins containing all values in window wmin, wmax
    template <typename Hist, typename V, typename Func>
/**
 * Brief description: Applies a function to all elements within a specified window of a histogram.
 *
 * Detailed description: This function iterates over a subset of bins in a histogram,
 * starting from the bin that corresponds to the minimum value of the window and ending at
 * the bin that corresponds to the maximum value of the window. For each bin in this range,
 * it applies a user-provided function.
 *
 * Parameters:
 *   hist - The input histogram.
 *   wmin - The minimum value of the window.
 *   wmax - The maximum value of the window.
 *   func - The function to apply to each element in the window.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    inline void forEachInWindow(Hist const &hist, V wmin, V wmax, Func const &func) {
      auto bs = Hist::bin(wmin);
      auto be = Hist::bin(wmax);
      assert(be >= bs);
      for (auto pj = hist.begin(bs); pj < hist.end(be); ++pj) {
        func(*pj);
      }
    }

    template <typename T,                  // the type of the discretized input values
              uint32_t NBINS,              // number of bins
              uint32_t SIZE,               // max number of element
              uint32_t S = sizeof(T) * 8,  // number of significant bits in T
              typename I = uint32_t,  // type stored in the container (usually an index in a vector of the input values)
              uint32_t NHISTS = 1     // number of histos stored
              >
    class HistoContainer {
    public:
      using Counter = uint32_t;

      using CountersOnly = HistoContainer<T, NBINS, 0, S, I, NHISTS>;

      using index_type = I;
      using UT = typename std::make_unsigned<T>::type;

/**
 * Calculates the integer logarithm base 2 of a given unsigned 32-bit integer.
 *
 * @param v The input value.
 * @return The integer logarithm base 2 of the input value.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      static constexpr uint32_t ilog2(uint32_t v) {
        constexpr uint32_t b[] = {0x2, 0xC, 0xF0, 0xFF00, 0xFFFF0000};
        constexpr uint32_t s[] = {1, 2, 4, 8, 16};

        uint32_t r = 0;  // result of log2(v) will go here
        for (auto i = 4; i >= 0; i--)
          if (v & b[i]) {
            v >>= s[i];
            r |= s[i];
          }
        return r;
      }

      static constexpr uint32_t sizeT() { return S; }
      static constexpr uint32_t nbins() { return NBINS; }
      static constexpr uint32_t nhists() { return NHISTS; }
      static constexpr uint32_t totbins() { return NHISTS * NBINS + 1; }
      static constexpr uint32_t nbits() { return ilog2(NBINS - 1) + 1; }
      static constexpr uint32_t capacity() { return SIZE; }

      static constexpr auto histOff(uint32_t nh) { return NBINS * nh; }

/**
 * Returns the binary representation of the input value 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      static constexpr UT bin(T t) {
        constexpr uint32_t shift = sizeT() - nbits();
        constexpr uint32_t mask = (1 << nbits()) - 1;
        return (t >> shift) & mask;
      }

/**
 * Brief description of the function to set all elements to zero
 *
 * Detailed description of the function to initialize all elements of a container to zero
 *
 * @brief Sets all elements to zero
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      void zero() {
        for (auto &i : off)
          i = 0;
      }

/**
 * Adds another CountersOnly object to this object
 *
 * @param co the CountersOnly object to add
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      inline void add(CountersOnly const &co) {
        for (uint32_t i = 0; i < totbins(); ++i) {
          auto &a = (std::atomic<Counter> &)(off[i]);
          a += co.off[i];
        }
      }

/**
 * Increments the value of a Counter object atomically and returns the previous value.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      static inline uint32_t atomicIncrement(Counter &x) {
        auto &a = (std::atomic<Counter> &)(x);
        return a++;
      }

/**
 * Decrements the value of a Counter object atomically.
 *
 * @param x Reference to the Counter object to decrement.
 * @return The decremented value of the Counter object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      static inline uint32_t atomicDecrement(Counter &x) {
        auto &a = (std::atomic<Counter> &)(x);
        return a--;
      }

/**
 * Increment the offset of a specific bin in an atomic manner.
 *
 * @param b the bin number to increment
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      inline void countDirect(T b) {
        assert(b < nbins());
        atomicIncrement(off[b]);
      }

/**
 * Brief description: Decrements the offset of a bin and stores an index.
 *
 * Detailed description: This function takes a bin number b and an index j as input,
 * decrements the offset of the specified bin atomically, and stores the index at the
 * resulting position in the bins array.
 *
 * Parameters:
 *   b - The bin number.
 *   j - The index to store.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      inline void fillDirect(T b, index_type j) {
        assert(b < nbins());
        auto w = atomicDecrement(off[b]);
        assert(w > 0);
        bins[w - 1] = j;
      }

/**
 * Calculates the bulk fill value for an AtomicPairCounter object.
 *
 * @param apc Reference to an AtomicPairCounter object.
 * @param v Array of indices to be filled.
 * @param n Number of elements in the array.
 * @return Index where the filling started or negative value if overflow occurred.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      inline int32_t bulkFill(AtomicPairCounter &apc, index_type const *v, uint32_t n) {
        auto c = apc.add(n);
        if (c.m >= nbins())
          return -int32_t(c.m);
        off[c.m] = c.n;
        for (uint32_t j = 0; j < n; ++j)
          bins[c.n + j] = v[j];
        return c.m;
      }

      inline void bulkFinalize(AtomicPairCounter const &apc) { off[apc.get().m] = apc.get().n; }

/**
 * Brief description of bulkFinalizeFill function
 *
 * This function finalizes the filling process for an AtomicPairCounter object.
 * It checks for potential overflows and updates the offset values accordingly.
 *
 * @param apc the AtomicPairCounter object to be finalized
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      inline void bulkFinalizeFill(AtomicPairCounter const &apc) {
        auto m = apc.get().m;
        auto n = apc.get().n;
        if (m >= nbins()) {  // overflow!
          off[nbins()] = uint32_t(off[nbins() - 1]);
          return;
        }
        auto first = m;
        for (auto i = first; i < totbins(); i++) {
          off[i] = n;
        }
      }

/**
 * Increment the offset of a specific bin in an atomic manner.
 *
 * @param t The value to be counted.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      inline void count(T t) {
        uint32_t b = bin(t);
        assert(b < nbins());
        atomicIncrement(off[b]);
      }

/**
 * Fill function to store index in corresponding bin
 * @param t input value
 * @param j index to be stored
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      inline void fill(T t, index_type j) {
        uint32_t b = bin(t);
        assert(b < nbins());
        auto w = atomicDecrement(off[b]);
        assert(w > 0);
        bins[w - 1] = j;
      }

/**
 * Brief description: Increments the histogram bin corresponding to the given value.
 *
 * Detailed description: This function takes a value and a histogram number as input,
 * determines the bin where the value belongs, calculates the offset within the total bins,
 * and atomically increments the counter at that position.
 *
 * Parameters:
 *   t - The value to be counted.
 *   nh - The histogram number.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      inline void count(T t, uint32_t nh) {
        uint32_t b = bin(t);
        assert(b < nbins());
        b += histOff(nh);
        assert(b < totbins());
        atomicIncrement(off[b]);
      }

/**
 * Fill function to store an index in a histogram bin
 *
 * @param t input value to determine the bin
 * @param j index to store in the bin
 * @param nh histogram number
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      inline void fill(T t, index_type j, uint32_t nh) {
        uint32_t b = bin(t);
        assert(b < nbins());
        b += histOff(nh);
        assert(b < totbins());
        auto w = atomicDecrement(off[b]);
        assert(w > 0);
        bins[w - 1] = j;
      }

/**
 * Finalize function to ensure correct offset values after prefix scan operation
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
      inline void finalize() {
        assert(off[totbins() - 1] == 0);
        blockPrefixScan(off, totbins());
        assert(off[totbins() - 1] == off[totbins() - 2]);
      }

      constexpr auto size() const { return uint32_t(off[totbins() - 1]); }
      constexpr auto size(uint32_t b) const { return off[b + 1] - off[b]; }

      constexpr index_type const *begin() const { return bins; }
      constexpr index_type const *end() const { return begin() + size(); }

      constexpr index_type const *begin(uint32_t b) const { return bins + off[b]; }
      constexpr index_type const *end(uint32_t b) const { return bins + off[b + 1]; }

      Counter off[totbins()];
      int32_t psws;  // prefix-scan working space
      index_type bins[capacity()];
    };

    template <typename I,        // type stored in the container (usually an index in a vector of the input values)
              uint32_t MAXONES,  // max number of "ones"
              uint32_t MAXMANYS  // max number of "manys"
              >
    using OneToManyAssoc = HistoContainer<uint32_t, MAXONES, MAXMANYS, sizeof(uint32_t) * 8, I, 1>;

  }  // namespace cuda
}  // namespace cms

#endif  // HeterogeneousCore_CUDAUtilities_interface_HistoContainer_h
