#ifndef CUDADataFormats_SiPixelDigi_interface_SiPixelDigiErrorsSoA_h
#define CUDADataFormats_SiPixelDigi_interface_SiPixelDigiErrorsSoA_h

#include <memory>

#include "CUDACore/SimpleVector.h"
#include "DataFormats/PixelErrors.h"

/**
 * Brief description of SiPixelDigiErrorsSoA class 
   * Detailed description of SiPixelDigiErrorsSoA class 
 * This class represents a collection of digital errors in the silicon pixel detector
 * It provides methods for accessing and manipulating the error data
 * The class follows the rule of five and has deleted copy constructor and assignment operator
 * to prevent copying of the object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
class SiPixelDigiErrorsSoA {
public:
  SiPixelDigiErrorsSoA() = default;
  explicit SiPixelDigiErrorsSoA(size_t maxFedWords, PixelFormatterErrors errors);
  ~SiPixelDigiErrorsSoA() = default;

  SiPixelDigiErrorsSoA(const SiPixelDigiErrorsSoA&) = delete;
  SiPixelDigiErrorsSoA& operator=(const SiPixelDigiErrorsSoA&) = delete;
  SiPixelDigiErrorsSoA(SiPixelDigiErrorsSoA&&) = default;
  SiPixelDigiErrorsSoA& operator=(SiPixelDigiErrorsSoA&&) = default;

  const PixelFormatterErrors& formatterErrors() const { return formatterErrors_h; }

  cms::cuda::SimpleVector<PixelErrorCompact>* error() { return error_d.get(); }
  cms::cuda::SimpleVector<PixelErrorCompact> const* error() const { return error_d.get(); }
  cms::cuda::SimpleVector<PixelErrorCompact> const* c_error() const { return error_d.get(); }

private:
  std::unique_ptr<PixelErrorCompact[]> data_d;
  std::unique_ptr<cms::cuda::SimpleVector<PixelErrorCompact>> error_d;
  PixelFormatterErrors formatterErrors_h;
};

#endif
