#ifndef CUDADataFormats_SiPixelCluster_interface_SiPixelClustersSoA_h
#define CUDADataFormats_SiPixelCluster_interface_SiPixelClustersSoA_h

#include "CUDACore/cudaCompat.h"
#include "CUDADataFormats/SiPixelClustersCUDA.h"

#include <memory>

/**
 * @brief Class representing a collection of silicon pixel clusters in Structure of Arrays format.
 *
 * This class provides methods for managing and accessing the cluster data,
 * including setting the number of clusters, retrieving module start indices,
 * cluster counts, and module IDs.
 *
 * It also offers const accessors for these values, ensuring data integrity.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
class SiPixelClustersSoA {
public:
  SiPixelClustersSoA() = default;
  explicit SiPixelClustersSoA(size_t maxClusters);
  ~SiPixelClustersSoA() = default;

  SiPixelClustersSoA(const SiPixelClustersSoA &) = delete;
  SiPixelClustersSoA &operator=(const SiPixelClustersSoA &) = delete;
  SiPixelClustersSoA(SiPixelClustersSoA &&) = default;
  SiPixelClustersSoA &operator=(SiPixelClustersSoA &&) = default;

  void setNClusters(uint32_t nClusters) { nClusters_h = nClusters; }

  uint32_t nClusters() const { return nClusters_h; }

  uint32_t *moduleStart() { return moduleStart_d.get(); }
  uint32_t *clusInModule() { return clusInModule_d.get(); }
  uint32_t *moduleId() { return moduleId_d.get(); }
  uint32_t *clusModuleStart() { return clusModuleStart_d.get(); }

  uint32_t const *moduleStart() const { return moduleStart_d.get(); }
  uint32_t const *clusInModule() const { return clusInModule_d.get(); }
  uint32_t const *moduleId() const { return moduleId_d.get(); }
  uint32_t const *clusModuleStart() const { return clusModuleStart_d.get(); }

  uint32_t const *c_moduleStart() const { return moduleStart_d.get(); }
  uint32_t const *c_clusInModule() const { return clusInModule_d.get(); }
  uint32_t const *c_moduleId() const { return moduleId_d.get(); }
  uint32_t const *c_clusModuleStart() const { return clusModuleStart_d.get(); }

  using DeviceConstView = SiPixelClustersCUDA::DeviceConstView;

  DeviceConstView *view() const { return view_d.get(); }

private:
  std::unique_ptr<uint32_t[]> moduleStart_d;   // index of the first pixel of each module
  std::unique_ptr<uint32_t[]> clusInModule_d;  // number of clusters found in each module
  std::unique_ptr<uint32_t[]> moduleId_d;      // module id of each module

  // originally from rechits
  std::unique_ptr<uint32_t[]> clusModuleStart_d;  // index of the first cluster of each module

  std::unique_ptr<DeviceConstView> view_d;  // "me" pointer

  uint32_t nClusters_h;
};

#endif
