#include <cassert>
#include <limits>

#include <cuda_runtime.h>

#include "CUDACore/allocate_device.h"
#include "CUDACore/cudaCheck.h"
#include "CUDACore/ScopedSetDevice.h"

#include "getCachingDeviceAllocator.h"

namespace {
  const size_t maxAllocationSize = allocator::intPow(cms::cuda::allocator::binGrowth, cms::cuda::allocator::maxBin);
}

namespace cms::cuda {

// The following comment is generated by an LLM. 
/**
 * Allocates device memory of specified size and returns a pointer to it.
 *
 * @param nbytes The number of bytes to allocate.
 * @param stream The CUDA stream associated with the allocation.
 * @return A pointer to the allocated device memory.
 */ 
  void *allocate_device(size_t nbytes, cudaStream_t stream) {
    void *ptr = nullptr;
    if constexpr (allocator::policy == allocator::Policy::Caching) {
      if (nbytes > maxAllocationSize) {
        throw std::runtime_error("Tried to allocate " + std::to_string(nbytes) +
                                 " bytes, but the allocator maximum is " + std::to_string(maxAllocationSize));
      }
      ptr = allocator::getCachingDeviceAllocator().allocate(nbytes, stream);
#if CUDA_VERSION >= 11020
    } else if constexpr (allocator::policy == allocator::Policy::Asynchronous) {
      cudaCheck(cudaMallocAsync(&ptr, nbytes, stream));
#endif
    } else {
      cudaCheck(cudaMalloc(&ptr, nbytes));
    }
    return ptr;
  }


// The following comment is generated by an LLM. 
/**
 * Allocates device memory for a specified number of bytes on a given device and stream.
 *
 * @param device The ID of the device to allocate memory on.
 * @param nbytes The number of bytes to allocate.
 * @param stream The CUDA stream to associate with the allocation.
 *
 * @return A pointer to the allocated device memory.
 *
 * @throws stdruntimeerror If the requested allocation exceeds the maximum allowed size when using the caching policy.
 */ 
  void *allocate_device(int device, size_t nbytes, cudaStream_t stream) {
    void *ptr = nullptr;
    ScopedSetDevice setDevice(device);
    if constexpr (allocator::policy == allocator::Policy::Caching) {
      if (nbytes > maxAllocationSize) {
        throw std::runtime_error("Tried to allocate " + std::to_string(nbytes) +
                                 " bytes, but the allocator maximum is " + std::to_string(maxAllocationSize));
      }
      ptr = allocator::getCachingDeviceAllocator().allocate(nbytes, stream);
#if CUDA_VERSION >= 11020
    } else if constexpr (allocator::policy == allocator::Policy::Asynchronous) {
      cudaCheck(cudaMallocAsync(&ptr, nbytes, stream));
#endif
    } else {
      cudaCheck(cudaMalloc(&ptr, nbytes));
    }
    return ptr;
  }


// The following comment is generated by an LLM. 
/**
 * Frees the device memory allocated at the specified pointer.
 *
 * @param ptr   Pointer to the device memory to be freed
 * @param stream  CUDA stream associated with the memory deallocation
 */ 
  void free_device(void *ptr, cudaStream_t stream) {
    if constexpr (allocator::policy == allocator::Policy::Caching) {
      allocator::getCachingDeviceAllocator().free(ptr);
#if CUDA_VERSION >= 11020
    } else if constexpr (allocator::policy == allocator::Policy::Asynchronous) {
      cudaCheck(cudaFreeAsync(ptr, stream));
#endif
    } else {
      cudaCheck(cudaFree(ptr));
    }
  }

}  // namespace cms::cuda
