#ifndef HeterogeneousCore_CUDAUtilities_deviceAllocatorStatus_h
#define HeterogeneousCore_CUDAUtilities_deviceAllocatorStatus_h

#include <map>

namespace cms {
  namespace cuda {
    namespace allocator {
/**
 * Struct representing total bytes information.
 * Contains members to track free, live and requested live byte counts.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
      struct TotalBytes {
        size_t free = 0;
        size_t live = 0;
        size_t liveRequested = 0;
      };
      /// Map type of device ordinals to the number of cached bytes cached by each device
      using GpuCachedBytes = std::map<int, TotalBytes>;
    }  // namespace allocator

    allocator::GpuCachedBytes deviceAllocatorStatus();
  }  // namespace cuda
}  // namespace cms

#endif
