#ifndef HeterogeneousCore_CUDACore_src_getCachingHostAllocator
#define HeterogeneousCore_CUDACore_src_getCachingHostAllocator

#include <iomanip>
#include <iostream>

#include "CUDACore/cudaCheck.h"

#include "getCachingDeviceAllocator.h"

namespace cms::cuda::allocator {
  struct HostTraits {
    using DeviceType = int;
    using QueueType = cudaStream_t;
    using EventType = cudaEvent_t;

    static constexpr DeviceType kInvalidDevice = -1;
    static constexpr DeviceType kHostDevice = 0;

    static DeviceType currentDevice() { return cms::cuda::currentDevice(); }

/**
 * Returns the device type for memory allocation.
 *
 * @param deviceEvent The device associated with the event.
 * @return The device type for memory allocation.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static DeviceType memoryDevice(DeviceType deviceEvent) {
      // For host allocator the "current device" refers to the GPU for
      // which the event has been recorded. The "device" where the
      // memory is allocated on is always 0.
      return kHostDevice;
    }

/**
 * Checks if two devices can reuse memory 
 * @param a first device type
 * @param b second device type
 * @return true if devices can reuse memory false otherwise
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static bool canReuseInDevice(DeviceType a, DeviceType b) {
      // Pinned host memory can be reused in any device, but in case of
      // changes the event must be re-created
      return true;
    }

/**
 * Checks if two queue types can reuse memory blocks in a queue.
 *
 * @param a first QueueType to compare
 * @param b second QueueType to compare
 * @return true if memory blocks can be reused, false otherwise
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static bool canReuseInQueue(QueueType a, QueueType b) {
      // For pinned host memory a freed block without completed event
      // can not be re-used even for operations in the same queue
      return false;
    }

    template <typename C>
    static bool deviceCompare(DeviceType a_dev, DeviceType b_dev, C&& compare) {
      return compare();
    }

    static bool eventWorkHasCompleted(EventType e) { return cms::cuda::eventWorkHasCompleted(e); }

/**
 * Creates an event with timing disabled
 *
 * @return created event
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static EventType createEvent() {
      EventType e;
      cudaCheck(cudaEventCreateWithFlags(&e, cudaEventDisableTiming));
      return e;
    }

    static void destroyEvent(EventType e) { cudaCheck(cudaEventDestroy(e)); }

/**
 * Recreates an event on a different device.
 *
 * @param e The event type to recreate.
 * @param prev The previous device where the event was created.
 * @param next The new device where the event will be recreated.
 * @return The recreated event.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static EventType recreateEvent(EventType e, DeviceType prev, DeviceType next) {
      cudaCheck(cudaSetDevice(prev));
      destroyEvent(e);
      cudaCheck(cudaSetDevice(next));
      return createEvent();
    }

/**
 * Records an event of specified type on a given queue and returns the recorded event.
 *
 * @param e The type of event to be recorded
 * @param queue The queue on which the event is to be recorded
 * @return The recorded event
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static EventType recordEvent(EventType e, QueueType queue) {
      cudaCheck(cudaEventRecord(e, queue));
      return e;
    }

    struct DevicePrinter {
      static void write(std::ostream& os) { os << "Host"; }
    };

    static DevicePrinter printDevice(DeviceType dev) { return DevicePrinter(); }

/**
 * Allocates host memory of specified size using CUDA.
 *
 * @param bytes number of bytes to allocate
 * @return pointer to allocated memory
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static void* allocate(size_t bytes) {
      void* ptr;
      cudaCheck(cudaHostAlloc(&ptr, bytes, cudaHostAllocDefault));
      return ptr;
    }

/**
 * Attempts to allocate host memory using CUDA.
 *
 * @param bytes The number of bytes to allocate.
 * @return A pointer to the allocated memory or nullptr if allocation failed.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    static void* tryAllocate(size_t bytes) {
      void* ptr;
      auto error = cudaHostAlloc(&ptr, bytes, cudaHostAllocDefault);
      if (error == cudaErrorMemoryAllocation) {
        return nullptr;
      }
      cudaCheck(error);
      return ptr;
    }

    static void free(void* ptr) { cudaCheck(cudaFreeHost(ptr)); }
  };

/**
 * Operator to output DevicePrinter object to ostream 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  inline std::ostream& operator<<(std::ostream& os, HostTraits::DevicePrinter const& pr) {
    pr.write(os);
    return os;
  }

  using CachingHostAllocator = GenericCachingAllocator<HostTraits>;

/**
 * Returns a caching host allocator instance with predefined settings.
 *
 * @return A reference to the caching host allocator instance.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  inline CachingHostAllocator& getCachingHostAllocator() {
    if (debug) {
      std::cout << "cub::CachingHostAllocator settings\n"
                << "  bin growth " << binGrowth << "\n"
                << "  min bin    " << minBin << "\n"
                << "  max bin    " << maxBin << "\n"
                << "  resulting bins:\n";
      for (auto bin = minBin; bin <= maxBin; ++bin) {
        auto binSize = ::allocator::intPow(binGrowth, bin);
        if (binSize >= (1 << 30) and binSize % (1 << 30) == 0) {
          std::cout << "    " << std::setw(8) << (binSize >> 30) << " GB\n";
        } else if (binSize >= (1 << 20) and binSize % (1 << 20) == 0) {
          std::cout << "    " << std::setw(8) << (binSize >> 20) << " MB\n";
        } else if (binSize >= (1 << 10) and binSize % (1 << 10) == 0) {
          std::cout << "    " << std::setw(8) << (binSize >> 10) << " kB\n";
        } else {
          std::cout << "    " << std::setw(9) << binSize << " B\n";
        }
      }
      std::cout << "  maximum amount of cached memory: " << (minCachedBytes() >> 20) << " MB\n";
    }

    // the public interface is thread safe
    static CachingHostAllocator allocator{binGrowth, minBin, maxBin, minCachedBytes(), debug};
    return allocator;
  }
}  // namespace cms::cuda::allocator

#endif
