//
// Original Author: Felice Pantaleo, CERN
//

// #define NTUPLE_DEBUG

#include <cmath>
#include <cstdint>

#include "CUDACore/cudaCompat.h"

#include "CUDACore/cuda_assert.h"
#include "CondFormats/pixelCPEforGPU.h"

#include "CAConstants.h"
#include "CAHitNtupletGeneratorKernels.h"
#include "GPUCACell.h"
#include "gpuFishbone.h"
#include "gpuPixelDoublets.h"

using HitToTuple = CAConstants::HitToTuple;
using TupleMultiplicity = CAConstants::TupleMultiplicity;

using Quality = pixelTrack::Quality;
using TkSoA = pixelTrack::TrackSoA;
using HitContainer = pixelTrack::HitContainer;

/**
 * @brief Checks for overflows in various data structures during the CA process.
 *
 * This function checks for potential overflows in several data structures used in the
 * combinatorial algorithm (CA) process, including the number of cells, tracks, and doublets.
 * It also updates counters for events, hits, cells, tuples, fit tracks, killed cells, empty cells,
 * and zero track cells.
 *
 * @param foundNtuplets Container of found N-tuplets
 * @param tupleMultiplicity Tuple multiplicity constants
 * @param apc Atomic pair counter
 * @param cells Array of GPU CA cells
 * @param nCells Number of cells
 * @param cellNeighbors Cell neighbors vector
 * @param cellTracks Cell tracks vector
 * @param isOuterHitOfCell Outer hit of cell array
 * @param nHits Total number of hits
 * @param maxNumberOfDoublets Maximum number of doublets
 * @param counters Counters for CA statistics
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_checkOverflows(HitContainer const *foundNtuplets,
                           CAConstants::TupleMultiplicity *tupleMultiplicity,
                           cms::cuda::AtomicPairCounter *apc,
                           GPUCACell const *__restrict__ cells,
                           uint32_t const *__restrict__ nCells,
                           gpuPixelDoublets::CellNeighborsVector const *cellNeighbors,
                           gpuPixelDoublets::CellTracksVector const *cellTracks,
                           GPUCACell::OuterHitOfCell const *__restrict__ isOuterHitOfCell,
                           uint32_t nHits,
                           uint32_t maxNumberOfDoublets,
                           CAHitNtupletGeneratorKernelsCPU::Counters *counters) {
  uint32_t first = 0;

  auto &c = *counters;
  // counters once per event
  if (0 == first) {
    atomicAdd(&c.nEvents, 1);
    atomicAdd(&c.nHits, nHits);
    atomicAdd(&c.nCells, *nCells);
    atomicAdd(&c.nTuples, apc->get().m);
    atomicAdd(&c.nFitTracks, tupleMultiplicity->size());
  }

#ifdef NTUPLE_DEBUG
  if (0 == first) {
    printf("number of found cells %d, found tuples %d with total hits %d out of %d\n",
           *nCells,
           apc->get().m,
           apc->get().n,
           nHits);
    if (apc->get().m < CAConstants::maxNumberOfQuadruplets()) {
      assert(foundNtuplets->size(apc->get().m) == 0);
      assert(foundNtuplets->size() == apc->get().n);
    }
  }

  for (int idx = first, nt = foundNtuplets->nbins(); idx < nt; idx++) {
    if (foundNtuplets->size(idx) > 5)
      printf("ERROR %d, %d\n", idx, foundNtuplets->size(idx));
    assert(foundNtuplets->size(idx) < 6);
    for (auto ih = foundNtuplets->begin(idx); ih != foundNtuplets->end(idx); ++ih)
      assert(*ih < nHits);
  }
#endif

  if (0 == first) {
    if (apc->get().m >= CAConstants::maxNumberOfQuadruplets())
      printf("Tuples overflow\n");
    if (*nCells >= maxNumberOfDoublets)
      printf("Cells overflow\n");
    if (cellNeighbors && cellNeighbors->full())
      printf("cellNeighbors overflow\n");
    if (cellTracks && cellTracks->full())
      printf("cellTracks overflow\n");
  }

  for (int idx = first, nt = (*nCells); idx < nt; idx++) {
    auto const &thisCell = cells[idx];
    if (thisCell.outerNeighbors().full())  //++tooManyNeighbors[thisCell.theLayerPairId];
      printf("OuterNeighbors overflow %d in %d\n", idx, thisCell.theLayerPairId);
    if (thisCell.tracks().full())  //++tooManyTracks[thisCell.theLayerPairId];
      printf("Tracks overflow %d in %d\n", idx, thisCell.theLayerPairId);
    if (thisCell.theDoubletId < 0)
      atomicAdd(&c.nKilledCells, 1);
    if (0 == thisCell.theUsed)
      atomicAdd(&c.nEmptyCells, 1);
    if (thisCell.tracks().empty())
      atomicAdd(&c.nZeroTrackCells, 1);
  }

  for (int idx = first, nt = nHits; idx < nt; idx++) {
    if (isOuterHitOfCell[idx].full())  // ++tooManyOuterHitOfCell;
      printf("OuterHitOfCell overflow %d\n", idx);
  }
}

/**
 * @brief Function to clean fishbone tracks in GPU CA cells
 * 
 * This function takes an array of GPUCACell objects, the number of cells,
 * and an array of Quality objects as input. It iterates over the cells,
 * checks if a cell has a negative doublet ID, and if so, marks all its
 * associated tracks as bad quality.
 *
 * @param cells Array of GPUCACell objects
 * @param nCells Number of cells in the array
 * @param quality Array of Quality objects to be updated
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_fishboneCleaner(GPUCACell const *cells, uint32_t const *__restrict__ nCells, Quality *quality) {
  constexpr auto bad = trackQuality::bad;

  uint32_t first = 0;
  for (int idx = first, nt = (*nCells); idx < nt; idx++) {
    auto const &thisCell = cells[idx];
    if (thisCell.theDoubletId >= 0)
      continue;

    for (auto it : thisCell.tracks())
      quality[it] = bad;
  }
}

/**
 * @brief Removes early duplicates from the tracking data.
 *
 * This function processes the input cells and marks tracks as duplicates
 * if they appear less frequently than the maximum number of hits in a cell.
 *
 * @param cells Array of GPUCACell objects containing tracking data.
 * @param nCells Number of cells in the input array.
 * @param foundNtuplets Container of hit counts for each track.
 * @param quality Output array to store the quality of each track.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_earlyDuplicateRemover(GPUCACell const *cells,
                                  uint32_t const *__restrict__ nCells,
                                  HitContainer *foundNtuplets,
                                  Quality *quality) {
  // constexpr auto bad = trackQuality::bad;
  constexpr auto dup = trackQuality::dup;
  // constexpr auto loose = trackQuality::loose;

  assert(nCells);
  uint32_t first = 0;
  for (int idx = first, nt = (*nCells); idx < nt; idx++) {
    auto const &thisCell = cells[idx];

    if (thisCell.tracks().size() < 2)
      continue;
    //if (0==thisCell.theUsed) continue;
    // if (thisCell.theDoubletId < 0) continue;

    uint32_t maxNh = 0;

    // find maxNh
    for (auto it : thisCell.tracks()) {
      auto nh = foundNtuplets->size(it);
      maxNh = std::max(nh, maxNh);
    }

    for (auto it : thisCell.tracks()) {
      if (foundNtuplets->size(it) != maxNh)
        quality[it] = dup;  //no race:  simple assignment of the same constant
    }
  }
}

/**
 * @brief Removes duplicate tracks from a collection of cells.
 *
 * This function iterates over a list of cells, identifies duplicate tracks within each cell,
 * and marks them as such. It uses a scoring system to determine which track to keep.
 *
 * @param cells A pointer to an array of GPUCACell objects.
 * @param nCells A pointer to the number of cells in the array.
 * @param foundNtuplets Not used in this implementation.
 * @param tracks A pointer to a TkSoA object containing track data.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_fastDuplicateRemover(GPUCACell const *__restrict__ cells,
                                 uint32_t const *__restrict__ nCells,
                                 HitContainer const *__restrict__ foundNtuplets,
                                 TkSoA *__restrict__ tracks) {
  constexpr auto bad = trackQuality::bad;
  constexpr auto dup = trackQuality::dup;
  constexpr auto loose = trackQuality::loose;

  assert(nCells);

  uint32_t first = 0;
  for (int idx = first, nt = (*nCells); idx < nt; idx++) {
    auto const &thisCell = cells[idx];
    if (thisCell.tracks().size() < 2)
      continue;
    // if (thisCell.theDoubletId < 0) continue;

    float mc = 10000.f;
    uint16_t im = 60000;

    auto score = [&](auto it) {
      return std::abs(tracks->tip(it));  // tip
      // return tracks->chi2(it);  //chi2
    };

    // find min socre
    for (auto it : thisCell.tracks()) {
      if (tracks->quality(it) == loose && score(it) < mc) {
        mc = score(it);
        im = it;
      }
    }
    // mark all other duplicates
    for (auto it : thisCell.tracks()) {
      if (tracks->quality(it) != bad && it != im)
        tracks->quality(it) = dup;  //no race:  simple assignment of the same constant
    }
  }
}

/**
 * Connects two cells based on their spatial alignment and distance.
 
 
  * Class representing an atomic pair counter.
 
  * Class representing a GPU CA cell.
 
  * Class representing a vector of cell neighbors.
 
  * Class representing the outer hit of a cell.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_connect(cms::cuda::AtomicPairCounter *apc1,
                    cms::cuda::AtomicPairCounter *apc2,  // just to zero them,
                    GPUCACell::Hits const *__restrict__ hhp,
                    GPUCACell *cells,
                    uint32_t const *__restrict__ nCells,
                    gpuPixelDoublets::CellNeighborsVector *cellNeighbors,
                    GPUCACell::OuterHitOfCell const *__restrict__ isOuterHitOfCell,
                    float hardCurvCut,
                    float ptmin,
                    float CAThetaCutBarrel,
                    float CAThetaCutForward,
                    float dcaCutInnerTriplet,
                    float dcaCutOuterTriplet) {
  auto const &hh = *hhp;

  auto firstCellIndex = 0 + 0 * 1;
  uint32_t first = 0;
  auto stride = 1;

  if (0 == (firstCellIndex + first)) {
    (*apc1) = 0;
    (*apc2) = 0;
  }  // ready for next kernel

  for (int idx = firstCellIndex, nt = (*nCells); idx < nt; idx += 1) {
    auto cellIndex = idx;
    auto &thisCell = cells[idx];
    //if (thisCell.theDoubletId < 0 || thisCell.theUsed>1)
    //  continue;
    auto innerHitId = thisCell.get_inner_hit_id();
    int numberOfPossibleNeighbors = isOuterHitOfCell[innerHitId].size();
    auto vi = isOuterHitOfCell[innerHitId].data();

    constexpr uint32_t last_bpix1_detIndex = 96;
    constexpr uint32_t last_barrel_detIndex = 1184;
    auto ri = thisCell.get_inner_r(hh);
    auto zi = thisCell.get_inner_z(hh);

    auto ro = thisCell.get_outer_r(hh);
    auto zo = thisCell.get_outer_z(hh);
    auto isBarrel = thisCell.get_inner_detIndex(hh) < last_barrel_detIndex;

    for (int j = first; j < numberOfPossibleNeighbors; j += stride) {
      auto otherCell = vi[j];
      auto &oc = cells[otherCell];
      // if (cells[otherCell].theDoubletId < 0 ||
      //    cells[otherCell].theUsed>1 )
      //  continue;
      auto r1 = oc.get_inner_r(hh);
      auto z1 = oc.get_inner_z(hh);
      // auto isBarrel = oc.get_outer_detIndex(hh) < last_barrel_detIndex;
      bool aligned = GPUCACell::areAlignedRZ(
          r1,
          z1,
          ri,
          zi,
          ro,
          zo,
          ptmin,
          isBarrel ? CAThetaCutBarrel : CAThetaCutForward);  // 2.f*thetaCut); // FIXME tune cuts
      if (aligned &&
          thisCell.dcaCut(hh,
                          oc,
                          oc.get_inner_detIndex(hh) < last_bpix1_detIndex ? dcaCutInnerTriplet : dcaCutOuterTriplet,
                          hardCurvCut)) {  // FIXME tune cuts
        oc.addOuterNeighbor(cellIndex, *cellNeighbors);
        thisCell.theUsed |= 1;
        oc.theUsed |= 1;
      }
    }  // loop on inner cells
  }    // loop on outer cells
}

/**
 * Brief description of the function kernel_find_ntuplets
 *
 * This function finds n-tuplets within GPU cells based on certain conditions
 *
 * @param hhp pointer to Hits object
 * @param cells array of GPUCACell objects
 * @param nCells number of cells
 * @param cellTracks vector of CellTracks
 * @param foundNtuplets container for storing found n-tuplets
 * @param apc AtomicPairCounter object
 * @param quality array of quality values
 * @param minHitsPerNtuplet minimum hits required per n-tuplet
  
 * Class representing a GPUCACell
 *
 * This class encapsulates data and methods related to a GPU cell
 
   * Class representing a HitContainer
 *
 * This class stores and manages hit data
 
 * Class representing an AtomicPairCounter
 *
 * This class provides atomic counter functionality for pairs
 
 * Class representing a Quality evaluator
 *
 * This class assesses the quality of certain conditions
 
 * Struct representing a gpuPixelDoublets CellTracksVector
 *
 * This struct holds a collection of cell tracks
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_find_ntuplets(GPUCACell::Hits const *__restrict__ hhp,
                          GPUCACell *__restrict__ cells,
                          uint32_t const *nCells,
                          gpuPixelDoublets::CellTracksVector *cellTracks,
                          HitContainer *foundNtuplets,
                          cms::cuda::AtomicPairCounter *apc,
                          Quality *__restrict__ quality,
                          unsigned int minHitsPerNtuplet) {
  // recursive: not obvious to widen
  auto const &hh = *hhp;

  uint32_t first = 0;
  for (int idx = first, nt = (*nCells); idx < nt; idx++) {
    auto const &thisCell = cells[idx];
    if (thisCell.theDoubletId < 0)
      continue;  // cut by earlyFishbone

    auto pid = thisCell.theLayerPairId;
    auto doit = minHitsPerNtuplet > 3 ? pid < 3 : pid < 8 || pid > 12;
    if (doit) {
      GPUCACell::TmpTuple stack;
      stack.reset();
      thisCell.find_ntuplets<6>(
          hh, cells, *cellTracks, *foundNtuplets, *apc, quality, stack, minHitsPerNtuplet, pid < 3);
      assert(stack.empty());
      // printf("in %d found quadruplets: %d\n", cellIndex, apc->get());
    }
  }
}

/**
 * Brief description of the function kernel_mark_used
 *
 * Detailed description of the function kernel_mark_used
 * This function marks used cells in a list of cells based on their tracks
 *
 * @param hhp pointer to the hits data structure
 * @param cells array of cell objects
 * @param nCells number of cells in the array
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_mark_used(GPUCACell::Hits const *__restrict__ hhp, GPUCACell *__restrict__ cells, uint32_t const *nCells) {
  // auto const &hh = *hhp;
  uint32_t first = 0;
  for (int idx = first, nt = (*nCells); idx < nt; idx++) {
    auto &thisCell = cells[idx];
    if (!thisCell.tracks().empty())
      thisCell.theUsed |= 2;
  }
}

/**
 * Brief description of the function kernel_countMultiplicity
 *
 * Detailed description of the function kernel_countMultiplicity
 * This function takes three parameters: foundNtuplets, quality, and tupleMultiplicity
 * It iterates over the foundNtuplets and checks their size and quality
 * If the size is less than 3 or the quality is duplicate, it skips to the next iteration
 * Otherwise, it asserts that the quality is bad and counts the direct multiplicity
 * If the number of hits is greater than 5, it prints an error message
 * Finally, it asserts that the number of hits is less than 8
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_countMultiplicity(HitContainer const *__restrict__ foundNtuplets,
                              Quality const *__restrict__ quality,
                              CAConstants::TupleMultiplicity *tupleMultiplicity) {
  auto first = 0;
  for (int it = first, nt = foundNtuplets->nbins(); it < nt; it++) {
    auto nhits = foundNtuplets->size(it);
    if (nhits < 3)
      continue;
    if (quality[it] == trackQuality::dup)
      continue;
    assert(quality[it] == trackQuality::bad);
    if (nhits > 5)
      printf("wrong mult %d %d\n", it, nhits);
    assert(nhits < 8);
    tupleMultiplicity->countDirect(nhits);
  }
}

/**
 * @brief Fills the multiplicity of tuples based on hit container data
 * @param foundNtuplets Container holding the hits
 * @param quality Array of qualities associated with the hits
 * @param tupleMultiplicity Object to store the calculated multiplicities
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_fillMultiplicity(HitContainer const *__restrict__ foundNtuplets,
                             Quality const *__restrict__ quality,
                             CAConstants::TupleMultiplicity *tupleMultiplicity) {
  auto first = 0;
  for (int it = first, nt = foundNtuplets->nbins(); it < nt; it++) {
    auto nhits = foundNtuplets->size(it);
    if (nhits < 3)
      continue;
    if (quality[it] == trackQuality::dup)
      continue;
    assert(quality[it] == trackQuality::bad);
    if (nhits > 5)
      printf("wrong mult %d %d\n", it, nhits);
    assert(nhits < 8);
    tupleMultiplicity->fillDirect(nhits, it);
  }
}

/**
 * Class representing a function to classify tracks based on their quality.
  
 * Class representing a container for hits.
  
 * Class representing a collection of tracks in SoA format.
  
 * Class representing quality cuts for track classification.
  
 * Class representing the quality of a track.
  
 * Class representing a generator of kernels for CPU-based hit n-tuplet generation.
  

Note: Some classes like HitContainer, TkSoA, CAHitNtupletGeneratorKernelsCPU, and Quality are not defined in the provided code snippet but seem to be part of a larger system, hence comments are written assuming their existence.* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_classifyTracks(HitContainer const *__restrict__ tuples,
                           TkSoA const *__restrict__ tracks,
                           CAHitNtupletGeneratorKernelsCPU::QualityCuts cuts,
                           Quality *__restrict__ quality) {
  int first = 0;
  for (int it = first, nt = tuples->nbins(); it < nt; it++) {
    auto nhits = tuples->size(it);
    if (nhits == 0)
      break;  // guard

    // if duplicate: not even fit
    if (quality[it] == trackQuality::dup)
      continue;

    assert(quality[it] == trackQuality::bad);

    // mark doublets as bad
    if (nhits < 3)
      continue;

    // if the fit has any invalid parameters, mark it as bad
    bool isNaN = false;
    for (int i = 0; i < 5; ++i) {
      isNaN |= std::isnan(tracks->stateAtBS.state(it)(i));
    }
    if (isNaN) {
#ifdef NTUPLE_DEBUG
      printf("NaN in fit %d size %d chi2 %f\n", it, tuples->size(it), tracks->chi2(it));
#endif
      continue;
    }

    // compute a pT-dependent chi2 cut
    // default parameters:
    //   - chi2MaxPt = 10 GeV
    //   - chi2Coeff = { 0.68177776, 0.74609577, -0.08035491, 0.00315399 }
    //   - chi2Scale = 30 for broken line fit, 45 for Riemann fit
    // (see CAHitNtupletGeneratorGPU.cc)
    float pt = std::min<float>(tracks->pt(it), cuts.chi2MaxPt);
    float chi2Cut = cuts.chi2Scale *
                    (cuts.chi2Coeff[0] + pt * (cuts.chi2Coeff[1] + pt * (cuts.chi2Coeff[2] + pt * cuts.chi2Coeff[3])));
    // above number were for Quads not normalized so for the time being just multiple by ndof for Quads  (triplets to be understood)
    if (3.f * tracks->chi2(it) >= chi2Cut) {
#ifdef NTUPLE_DEBUG
      printf("Bad fit %d size %d pt %f eta %f chi2 %f\n",
             it,
             tuples->size(it),
             tracks->pt(it),
             tracks->eta(it),
             3.f * tracks->chi2(it));
#endif
      continue;
    }

    // impose "region cuts" based on the fit results (phi, Tip, pt, cotan(theta)), Zip)
    // default cuts:
    //   - for triplets:    |Tip| < 0.3 cm, pT > 0.5 GeV, |Zip| < 12.0 cm
    //   - for quadruplets: |Tip| < 0.5 cm, pT > 0.3 GeV, |Zip| < 12.0 cm
    // (see CAHitNtupletGeneratorGPU.cc)
    auto const &region = (nhits > 3) ? cuts.quadruplet : cuts.triplet;
    bool isOk = (std::abs(tracks->tip(it)) < region.maxTip) and (tracks->pt(it) > region.minPt) and
                (std::abs(tracks->zip(it)) < region.maxZip);

    if (isOk)
      quality[it] = trackQuality::loose;
  }
}

/**
 * Performs statistical analysis on tracks based on hit container data and quality information.
 *
 * @param[in] tuples Hit container object containing track data
 * @param[in] quality Array of track qualities
 * @param[out] counters Object to store statistical results
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_doStatsForTracks(HitContainer const *__restrict__ tuples,
                             Quality const *__restrict__ quality,
                             CAHitNtupletGeneratorKernelsCPU::Counters *counters) {
  int first = 0;
  for (int idx = first, ntot = tuples->nbins(); idx < ntot; idx++) {
    if (tuples->size(idx) == 0)
      break;  //guard
    if (quality[idx] != trackQuality::loose)
      continue;
    atomicAdd(&(counters->nGoodTracks), 1);
  }
}

/**
 * Brief description of function kernel_countHitInTracks 
 * Detailed description of function kernel_countHitInTracks 
 * @param[in] tuples 
 * @param[in] quality 
 * @param[out] hitToTuple 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_countHitInTracks(HitContainer const *__restrict__ tuples,
                             Quality const *__restrict__ quality,
                             CAHitNtupletGeneratorKernelsCPU::HitToTuple *hitToTuple) {
  int first = 0;
  for (int idx = first, ntot = tuples->nbins(); idx < ntot; idx++) {
    if (tuples->size(idx) == 0)
      break;  // guard
    if (quality[idx] != trackQuality::loose)
      continue;
    for (auto h = tuples->begin(idx); h != tuples->end(idx); ++h)
      hitToTuple->countDirect(*h);
  }
}

/**
 * @brief Fills hit container with tracks based on quality
 * @param tuples HitContainer containing tuples
 * @param quality array of qualities
 * @param hitToTuple generator for hit ntuplets
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_fillHitInTracks(HitContainer const *__restrict__ tuples,
                            Quality const *__restrict__ quality,
                            CAHitNtupletGeneratorKernelsCPU::HitToTuple *hitToTuple) {
  int first = 0;
  for (int idx = first, ntot = tuples->nbins(); idx < ntot; idx++) {
    if (tuples->size(idx) == 0)
      break;  // guard
    if (quality[idx] != trackQuality::loose)
      continue;
    for (auto h = tuples->begin(idx); h != tuples->end(idx); ++h)
      hitToTuple->fillDirect(*h, idx);
  }
}

/**
 * @brief Fills hit detector indices container with data from tracking rec hits and hit container.
 *
 * This function copies offsets from the input hit container and fills hit indices
 * based on the tracking rec hits data.
 *
 * @param[in] tuples Input hit container with bin information.
 * @param[in] hhp View of tracking rec hits data.
 * @param[out] hitDetIndices Output container to store hit detector indices.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_fillHitDetIndices(HitContainer const *__restrict__ tuples,
                              TrackingRecHit2DSOAView const *__restrict__ hhp,
                              HitContainer *__restrict__ hitDetIndices) {
  int first = 0;
  // copy offsets
  for (int idx = first, ntot = tuples->totbins(); idx < ntot; idx++) {
    hitDetIndices->off[idx] = tuples->off[idx];
  }
  // fill hit indices
  auto const &hh = *hhp;
  auto nhits = hh.nHits();
  for (int idx = first, ntot = tuples->size(); idx < ntot; idx++) {
    assert(tuples->bins[idx] < nhits);
    hitDetIndices->bins[idx] = hh.detectorIndex(tuples->bins[idx]);
  }
}

/**
 * Performs statistical analysis for hits in tracks.
 *
 * @param hitToTuple HitToTuple object containing data for processing
 * @param counters Counters object to store results
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_doStatsForHitInTracks(CAHitNtupletGeneratorKernelsCPU::HitToTuple const *__restrict__ hitToTuple,
                                  CAHitNtupletGeneratorKernelsCPU::Counters *counters) {
  auto &c = *counters;
  int first = 0;
  for (int idx = first, ntot = hitToTuple->nbins(); idx < ntot; idx++) {
    if (hitToTuple->size(idx) == 0)
      continue;  // SHALL NOT BE break
    atomicAdd(&c.nUsedHits, 1);
    if (hitToTuple->size(idx) > 1)
      atomicAdd(&c.nDupHits, 1);
  }
}

/**
 * @brief Kernel function for cleaning triplets
 *
 * This function cleans triplets by removing duplicate tracks and selecting the best tip.
 *
 * @param hhp TrackingRecHit2DSOAView object containing hit data
 * @param ptuples HitContainer object containing tuple data
 * @param ptracks TkSoA object containing track data
 * @param quality array of quality values for each hit
 * @param phitToTuple CAHitNtupletGeneratorKernelsCPU object containing hit-to-tuple mapping
  
 * @class TrackingRecHit2DSOAView
 * @brief View class for tracking rec hits in 2D SOA format
 
 * @class HitContainer
 * @brief Container class for storing hit data
 
 * @class TkSoA
 * @brief Class representing track data in SOA format
 
 * @class CAHitNtupletGeneratorKernelsCPU
 * @brief Class generating hit-to-tuple mappings for CPU kernels
 
 * @enum trackQuality
 * @brief Enumerated type for track qualities
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_tripletCleaner(TrackingRecHit2DSOAView const *__restrict__ hhp,
                           HitContainer const *__restrict__ ptuples,
                           TkSoA const *__restrict__ ptracks,
                           Quality *__restrict__ quality,
                           CAHitNtupletGeneratorKernelsCPU::HitToTuple const *__restrict__ phitToTuple) {
  constexpr auto bad = trackQuality::bad;
  constexpr auto dup = trackQuality::dup;
  // constexpr auto loose = trackQuality::loose;

  auto &hitToTuple = *phitToTuple;
  auto const &foundNtuplets = *ptuples;
  auto const &tracks = *ptracks;

  //  auto const & hh = *hhp;
  // auto l1end = hh.hitsLayerStart_d[1];

  int first = 0;
  for (int idx = first, ntot = hitToTuple.nbins(); idx < ntot; idx++) {
    if (hitToTuple.size(idx) < 2)
      continue;

    float mc = 10000.f;
    uint16_t im = 60000;
    uint32_t maxNh = 0;

    // find maxNh
    for (auto it = hitToTuple.begin(idx); it != hitToTuple.end(idx); ++it) {
      uint32_t nh = foundNtuplets.size(*it);
      maxNh = std::max(nh, maxNh);
    }
    // kill all tracks shorter than maxHn (only triplets???)
    for (auto it = hitToTuple.begin(idx); it != hitToTuple.end(idx); ++it) {
      uint32_t nh = foundNtuplets.size(*it);
      if (maxNh != nh)
        quality[*it] = dup;
    }

    if (maxNh > 3)
      continue;
    // if (idx>=l1end) continue;  // only for layer 1
    // for triplets choose best tip!
    for (auto ip = hitToTuple.begin(idx); ip != hitToTuple.end(idx); ++ip) {
      auto const it = *ip;
      if (quality[it] != bad && std::abs(tracks.tip(it)) < mc) {
        mc = std::abs(tracks.tip(it));
        im = it;
      }
    }
    // mark duplicates
    for (auto ip = hitToTuple.begin(idx); ip != hitToTuple.end(idx); ++ip) {
      auto const it = *ip;
      if (quality[it] != bad && it != im)
        quality[it] = dup;  //no race:  simple assignment of the same constant
    }
  }  // loop over hits
}

/**
 * Brief description of the function kernel_print_found_ntuplets
 *
 * Detailed description of the function kernel_print_found_ntuplets
 * This function prints the found n-tuplets for a given event
 * It takes several parameters including the tracking rec hit, 
 * hit container, tracks, quality, hit to tuple generator and more
 * It iterates over the found n-tuplets and prints their details
 *
 * @param hhp TrackingRecHit2DSOAView object
 * @param ptuples HitContainer object
 * @param ptracks TkSoA object
 * @param quality Quality object
 * @param phitToTuple CAHitNtupletGeneratorKernelsCPUHitToTuple object
 * @param maxPrint maximum number of n-tuplets to print
 * @param iev event number
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_print_found_ntuplets(TrackingRecHit2DSOAView const *__restrict__ hhp,
                                 HitContainer const *__restrict__ ptuples,
                                 TkSoA const *__restrict__ ptracks,
                                 Quality const *__restrict__ quality,
                                 CAHitNtupletGeneratorKernelsCPU::HitToTuple const *__restrict__ phitToTuple,
                                 uint32_t maxPrint,
                                 int iev) {
  auto const &foundNtuplets = *ptuples;
  auto const &tracks = *ptracks;
  int first = 0;
  for (int i = first, np = std::min(maxPrint, foundNtuplets.nbins()); i < np; i += 1) {
    auto nh = foundNtuplets.size(i);
    if (nh < 3)
      continue;
    printf("TK: %d %d %d %f %f %f %f %f %f %f %d %d %d %d %d\n",
           10000 * iev + i,
           int(quality[i]),
           nh,
           tracks.charge(i),
           tracks.pt(i),
           tracks.eta(i),
           tracks.phi(i),
           tracks.tip(i),
           tracks.zip(i),
           //           asinhf(fit_results[i].par(3)),
           tracks.chi2(i),
           *foundNtuplets.begin(i),
           *(foundNtuplets.begin(i) + 1),
           *(foundNtuplets.begin(i) + 2),
           nh > 3 ? int(*(foundNtuplets.begin(i) + 3)) : -1,
           nh > 4 ? int(*(foundNtuplets.begin(i) + 4)) : -1);
  }
}

/**
 * Brief description of the function kernel_printCounters
 *
 * Detailed description of the function kernel_printCounters
 * Prints the counters from the cAHitNtupletGenerator Counters object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernel_printCounters(cAHitNtupletGenerator::Counters const *counters) {
  auto const &c = *counters;
  printf(
      "||Counters | nEvents | nHits | nCells | nTuples | nFitTacks  |  nGoodTracks | nUsedHits | nDupHits | "
      "nKilledCells | "
      "nEmptyCells | nZeroTrackCells ||\n");
  printf("Counters Raw %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n",
         c.nEvents,
         c.nHits,
         c.nCells,
         c.nTuples,
         c.nGoodTracks,
         c.nFitTracks,
         c.nUsedHits,
         c.nDupHits,
         c.nKilledCells,
         c.nEmptyCells,
         c.nZeroTrackCells);
  printf("Counters Norm %lld ||  %.1f|  %.1f|  %.1f|  %.1f|  %.1f|  %.1f|  %.1f|  %.1f|  %.3f|  %.3f||\n",
         c.nEvents,
         c.nHits / double(c.nEvents),
         c.nCells / double(c.nEvents),
         c.nTuples / double(c.nEvents),
         c.nFitTracks / double(c.nEvents),
         c.nGoodTracks / double(c.nEvents),
         c.nUsedHits / double(c.nEvents),
         c.nDupHits / double(c.nEvents),
         c.nKilledCells / double(c.nEvents),
         c.nEmptyCells / double(c.nCells),
         c.nZeroTrackCells / double(c.nCells));
}
