//
// Author: Felice Pantaleo, CERN
//

#include <cstdint>

#include "CUDACore/cudaCompat.h"

#include "CUDADataFormats/TrackingRecHit2DCUDA.h"
#include "CUDACore/cuda_assert.h"
#include "CondFormats/pixelCPEforGPU.h"

#include "RiemannFit.h"
#include "HelixFitOnGPU.h"

using HitsOnGPU = TrackingRecHit2DSOAView;
using Tuples = pixelTrack::HitContainer;
using OutputSoA = pixelTrack::TrackSoA;

template <int N>
/**
 * @brief Function to perform a fast fit on a set of hits
 * 
 * This function takes in several parameters including the found N-tuplets, 
 * tuple multiplicities, number of hits, hits on GPU, and pointers to store 
 * the results of the fit. It performs a fast fit on the hits and stores 
 * the result in the provided pointer.
 * 
 * @param foundNtuplets Pointer to the found N-tuplets
 * @param tupleMultiplicity Pointer to the tuple multiplicities
 * @param nHits Number of hits
 * @param hhp Pointer to the hits on GPU
 * @param phits Pointer to store the hits
 * @param phits_ge Pointer to store the geometric errors
 * @param pfast_fit Pointer to store the result of the fast fit
 * @param offset Offset value
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernelFastFit(Tuples const *__restrict__ foundNtuplets,
                   CAConstants::TupleMultiplicity const *__restrict__ tupleMultiplicity,
                   uint32_t nHits,
                   HitsOnGPU const *__restrict__ hhp,
                   double *__restrict__ phits,
                   float *__restrict__ phits_ge,
                   double *__restrict__ pfast_fit,
                   uint32_t offset) {
  constexpr uint32_t hitsInFit = N;

  assert(hitsInFit <= nHits);

  assert(pfast_fit);
  assert(foundNtuplets);
  assert(tupleMultiplicity);

  // look in bin for this hit multiplicity
  auto local_start = 0;

#ifdef RIEMANN_DEBUG
  if (0 == local_start)
    printf("%d Ntuple of size %d for %d hits to fit\n", tupleMultiplicity->size(nHits), nHits, hitsInFit);
#endif

  for (int local_idx = local_start, nt = Rfit::maxNumberOfConcurrentFits(); local_idx < nt; local_idx++) {
    auto tuple_idx = local_idx + offset;
    if (tuple_idx >= tupleMultiplicity->size(nHits))
      break;

    // get it from the ntuple container (one to one to helix)
    auto tkid = *(tupleMultiplicity->begin(nHits) + tuple_idx);
    assert(tkid < foundNtuplets->nbins());

    assert(foundNtuplets->size(tkid) == nHits);

    Rfit::Map3xNd<N> hits(phits + local_idx);
    Rfit::Map4d fast_fit(pfast_fit + local_idx);
    Rfit::Map6xNf<N> hits_ge(phits_ge + local_idx);

    // Prepare data structure
    auto const *hitId = foundNtuplets->begin(tkid);
    for (unsigned int i = 0; i < hitsInFit; ++i) {
      auto hit = hitId[i];
      // printf("Hit global: %f,%f,%f\n", hhp->xg_d[hit],hhp->yg_d[hit],hhp->zg_d[hit]);
      float ge[6];
      hhp->cpeParams()
          .detParams(hhp->detectorIndex(hit))
          .frame.toGlobal(hhp->xerrLocal(hit), 0, hhp->yerrLocal(hit), ge);
      // printf("Error: %d: %f,%f,%f,%f,%f,%f\n",hhp->detInd_d[hit],ge[0],ge[1],ge[2],ge[3],ge[4],ge[5]);

      hits.col(i) << hhp->xGlobal(hit), hhp->yGlobal(hit), hhp->zGlobal(hit);
      hits_ge.col(i) << ge[0], ge[1], ge[2], ge[3], ge[4], ge[5];
    }
    Rfit::Fast_fit(hits, fast_fit);

    // no NaN here....
    assert(fast_fit(0) == fast_fit(0));
    assert(fast_fit(1) == fast_fit(1));
    assert(fast_fit(2) == fast_fit(2));
    assert(fast_fit(3) == fast_fit(3));
  }
}

template <int N>
/**
 * @brief Function to perform circle fit on a set of points
 * 
 * @param tupleMultiplicity Tuple multiplicity data
 * @param nHits Number of hits
 * @param B Magnetic field strength
 * @param phits Array of hit coordinates
 * @param phits_ge Array of geometric error estimates
 * @param pfast_fit_input Input data for fast fit
 * @param circle_fit Output circle fit results
 * @param offset Offset into the tuple multiplicity array
  
 * @class CAConstants
 * @brief Constants used throughout the application
 
 * @class Rfit
 * @brief Class containing functions for fitting circles to sets of points
 
 * @struct Map3xNd
 * @brief Mapping of 3xN dimensional data
 *
 * @tparam N Dimensionality of the mapping
 
 * @struct Map4d
 * @brief Mapping of 4-dimensional data
 
 * @struct Map6xNf
 * @brief Mapping of 6xN floating-point data
 *
 * @tparam N Dimensionality of the mapping
 
 * @class VectorNd
 * @brief N-dimensional vector class
 *
 * @tparam N Dimensionality of the vector
 
 * @class Matrix2Nd
 * @brief 2xN dimensional matrix class
 *
 * @tparam N Dimensionality of the matrix
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernelCircleFit(CAConstants::TupleMultiplicity const *__restrict__ tupleMultiplicity,
                     uint32_t nHits,
                     double B,
                     double *__restrict__ phits,
                     float *__restrict__ phits_ge,
                     double *__restrict__ pfast_fit_input,
                     Rfit::circle_fit *circle_fit,
                     uint32_t offset) {
  assert(circle_fit);
  assert(N <= nHits);

  // same as above...

  // look in bin for this hit multiplicity
  auto local_start = 0;
  for (int local_idx = local_start, nt = Rfit::maxNumberOfConcurrentFits(); local_idx < nt; local_idx++) {
    auto tuple_idx = local_idx + offset;
    if (tuple_idx >= tupleMultiplicity->size(nHits))
      break;

    Rfit::Map3xNd<N> hits(phits + local_idx);
    Rfit::Map4d fast_fit(pfast_fit_input + local_idx);
    Rfit::Map6xNf<N> hits_ge(phits_ge + local_idx);

    Rfit::VectorNd<N> rad = (hits.block(0, 0, 2, N).colwise().norm());

    Rfit::Matrix2Nd<N> hits_cov = Rfit::Matrix2Nd<N>::Zero();
    Rfit::loadCovariance2D(hits_ge, hits_cov);

    circle_fit[local_idx] = Rfit::Circle_fit(hits.block(0, 0, 2, N), hits_cov, fast_fit, rad, B, true);

#ifdef RIEMANN_DEBUG
//    auto tkid = *(tupleMultiplicity->begin(nHits) + tuple_idx);
//  printf("kernelCircleFit circle.par(0,1,2): %d %f,%f,%f\n", tkid,
//         circle_fit[local_idx].par(0), circle_fit[local_idx].par(1), circle_fit[local_idx].par(2));
#endif
  }
}

template <int N>
/**
 * Brief description of the function kernelLineFit
 *
 * Detailed description of the function kernelLineFit
 * This function performs line fitting for a set of hits in a detector
 * It takes several parameters including tuple multiplicity, number of hits, magnetic field strength, output SoA, and various pointers to data arrays
 * The function iterates over the hits, performing fits and storing the results in the output SoA
 *
 * @param tupleMultiplicity pointer to an array of tuple multiplicities
 * @param nHits number of hits to process
 * @param B magnetic field strength
 * @param results pointer to the output SoA
 * @param phits pointer to an array of hit data
 * @param phits_ge pointer to an array of geometric hit data
 * @param pfast_fit_input pointer to an array of fast fit input data
 * @param circle_fit pointer to an array of circle fit objects
 * @param offset starting index for the iteration
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void kernelLineFit(CAConstants::TupleMultiplicity const *__restrict__ tupleMultiplicity,
                   uint32_t nHits,
                   double B,
                   OutputSoA *results,
                   double *__restrict__ phits,
                   float *__restrict__ phits_ge,
                   double *__restrict__ pfast_fit_input,
                   Rfit::circle_fit *__restrict__ circle_fit,
                   uint32_t offset) {
  assert(results);
  assert(circle_fit);
  assert(N <= nHits);

  // same as above...

  // look in bin for this hit multiplicity
  auto local_start = (0);
  for (int local_idx = local_start, nt = Rfit::maxNumberOfConcurrentFits(); local_idx < nt; local_idx++) {
    auto tuple_idx = local_idx + offset;
    if (tuple_idx >= tupleMultiplicity->size(nHits))
      break;

    // get it for the ntuple container (one to one to helix)
    auto tkid = *(tupleMultiplicity->begin(nHits) + tuple_idx);

    Rfit::Map3xNd<N> hits(phits + local_idx);
    Rfit::Map4d fast_fit(pfast_fit_input + local_idx);
    Rfit::Map6xNf<N> hits_ge(phits_ge + local_idx);

    auto const &line_fit = Rfit::Line_fit(hits, hits_ge, circle_fit[local_idx], fast_fit, B, true);

    Rfit::fromCircleToPerigee(circle_fit[local_idx]);

    results->stateAtBS.copyFromCircle(
        circle_fit[local_idx].par, circle_fit[local_idx].cov, line_fit.par, line_fit.cov, 1.f / float(B), tkid);
    results->pt(tkid) = B / std::abs(circle_fit[local_idx].par(2));
    results->eta(tkid) = asinhf(line_fit.par(0));
    results->chi2(tkid) = (circle_fit[local_idx].chi2 + line_fit.chi2) / (2 * N - 5);

#ifdef RIEMANN_DEBUG
    printf("kernelLineFit size %d for %d hits circle.par(0,1,2): %d %f,%f,%f\n",
           N,
           nHits,
           tkid,
           circle_fit[local_idx].par(0),
           circle_fit[local_idx].par(1),
           circle_fit[local_idx].par(2));
    printf("kernelLineFit line.par(0,1): %d %f,%f\n", tkid, line_fit.par(0), line_fit.par(1));
    printf("kernelLineFit chi2 cov %f/%f %e,%e,%e,%e,%e\n",
           circle_fit[local_idx].chi2,
           line_fit.chi2,
           circle_fit[local_idx].cov(0, 0),
           circle_fit[local_idx].cov(1, 1),
           circle_fit[local_idx].cov(2, 2),
           line_fit.cov(0, 0),
           line_fit.cov(1, 1));
#endif
  }
}
