#include "gpuClusterTracksByDensity.h"
#include "gpuClusterTracksDBSCAN.h"
#include "gpuClusterTracksIterative.h"
#include "gpuFitVertices.h"
#include "gpuSortByPt2.h"
#include "gpuSplitVertices.h"

namespace gpuVertexFinder {

/**
 * Brief description of function loadTracks 
 * Loads tracks into a vertex SoA data structure.
 *
 * Detailed description of function loadTracks 
 * This function takes four parameters: a pointer to an array of tracks,
 * a pointer to a vertex SoA data structure, a workspace pointer, and a minimum pt value.
 * It iterates over the tracks, filters out those with insufficient hits or poor quality,
 * and loads the remaining tracks into the SoA data structure.
 *
 * Parameters:
 *   ptracks  Pointer to an array of tracks
 *   soa      Pointer to a vertex SoA data structure
 *   pws      Workspace pointer
 *   ptMin    Minimum pt value
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  void loadTracks(TkSoA const* ptracks, ZVertexSoA* soa, WorkSpace* pws, float ptMin) {
    assert(ptracks);
    assert(soa);
    auto const& tracks = *ptracks;
    auto const& fit = tracks.stateAtBS;
    auto const* quality = tracks.qualityData();

    auto first = 0;
    for (int idx = first, nt = TkSoA::stride(); idx < nt; idx++) {
      auto nHits = tracks.nHits(idx);
      if (nHits == 0)
        break;  // this is a guard: maybe we need to move to nTracks...

      // initialize soa...
      soa->idv[idx] = -1;

      if (nHits < 4)
        continue;  // no triplets
      if (quality[idx] != trackQuality::loose)
        continue;

      auto pt = tracks.pt(idx);

      if (pt < ptMin)
        continue;

      auto& data = *pws;
      auto it = atomicAdd(&data.ntrks, 1);
      data.itrk[it] = idx;
      data.zt[it] = tracks.zip(idx);
      data.ezt2[it] = fit.covariance(idx)(14);
      data.ptt2[it] = pt * pt;
    }
  }

// #define THREE_KERNELS
#ifndef THREE_KERNELS
/**
 * Brief description of the function vertexFinderOneKernel
 *
 * Detailed description of the function vertexFinderOneKernel which finds vertices
 * using one kernel with parameters pdata, pws, minT, eps, errmax and chi2max
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  void vertexFinderOneKernel(gpuVertexFinder::ZVertices* pdata,
                             gpuVertexFinder::WorkSpace* pws,
                             int minT,      // min number of neighbours to be "seed"
                             float eps,     // max absolute distance to cluster
                             float errmax,  // max error to be "seed"
                             float chi2max  // max normalized distance to cluster,
  ) {
    clusterTracksByDensity(pdata, pws, minT, eps, errmax, chi2max);

    fitVertices(pdata, pws, 50.);

    splitVertices(pdata, pws, 9.f);

    fitVertices(pdata, pws, 5000.);

    sortByPt2(pdata, pws);
  }
#else
/**
 * Brief description of the function
 *
 * This function implements the first stage of the vertex finding process
 * It clusters tracks by density and fits vertices
 *
 * Parameters:
 *   pdata - pointer to ZVertices data structure
 *   pws - pointer to WorkSpace data structure
 *   minT - minimum number of neighbors required to be considered a seed
 *   eps - maximum absolute distance to cluster
 *   errmax - maximum error allowed to be considered a seed
 *   chi2max - maximum normalized distance to cluster
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  void vertexFinderKernel1(gpuVertexFinder::ZVertices* pdata,
                           gpuVertexFinder::WorkSpace* pws,
                           int minT,      // min number of neighbours to be "seed"
                           float eps,     // max absolute distance to cluster
                           float errmax,  // max error to be "seed"
                           float chi2max  // max normalized distance to cluster,
  ) {
    clusterTracksByDensity(pdata, pws, minT, eps, errmax, chi2max);

    fitVertices(pdata, pws, 50.);
  }

/**
 * Brief description of the function
 *
 * Detailed description of the function
 * Parameters:
 *   pdata pointer to ZVertices data
 *   pws pointer to WorkSpace data
 * Returns:
 *   None
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  void vertexFinderKernel2(gpuVertexFinder::ZVertices* pdata, gpuVertexFinder::WorkSpace* pws) {
    fitVertices(pdata, pws, 5000.);

    sortByPt2(pdata, pws);
  }
#endif

/**
 * Brief description of the class 
   * Detailed description of the class 
 * This class appears to be responsible for producing heterogeneous vertices from track information.
 * It utilizes various clustering algorithms such as density-based, DBSCAN, and iterative methods.
 * The produced vertices are then fitted and sorted according to their transverse momentum.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  ZVertexHeterogeneous Producer::make(TkSoA const* tksoa, float ptMin) const {
    // std::cout << "producing Vertices on  CPU" <<    std::endl;
    ZVertexHeterogeneous vertices(std::make_unique<ZVertexSoA>());
    assert(tksoa);
    auto* soa = vertices.get();
    assert(soa);

    auto ws_d = std::make_unique<WorkSpace>();

    init(soa, ws_d.get());
    loadTracks(tksoa, soa, ws_d.get(), ptMin);

    if (useDensity_) {
      clusterTracksByDensity(soa, ws_d.get(), minT, eps, errmax, chi2max);
    } else if (useDBSCAN_) {
      clusterTracksDBSCAN(soa, ws_d.get(), minT, eps, errmax, chi2max);
    } else if (useIterative_) {
      clusterTracksIterative(soa, ws_d.get(), minT, eps, errmax, chi2max);
    }
    // std::cout << "found " << (*ws_d).nvIntermediate << " vertices " << std::endl;
    fitVertices(soa, ws_d.get(), 50.);
    // one block per vertex!
    splitVertices(soa, ws_d.get(), 9.f);
    fitVertices(soa, ws_d.get(), 5000.);
    sortByPt2(soa, ws_d.get());

    return vertices;
  }

}  // namespace gpuVertexFinder

#undef FROM
