#include "gpuClusterTracksByDensity.h"
#include "gpuClusterTracksDBSCAN.h"
#include "gpuClusterTracksIterative.h"
#include "gpuFitVertices.h"
#include "gpuSortByPt2.h"
#include "gpuSplitVertices.h"

namespace gpuVertexFinder {

/**
 * Brief description of function loadTracks 
   * Detailed description of function loadTracks 
 * This function loads tracks into an SoA data structure 
 * It takes four parameters 
 * ptracks a pointer to TkSoA 
 * soa a pointer to ZVertexSoA 
 * pws a pointer to WorkSpace 
 * ptMin minimum transverse momentum 
 * The function iterates over all tracks 
 * For each track it checks the number of hits and quality 
 * If the track has at least 4 hits and passes quality check 
 * It calculates various track properties and stores them in soa 
 * The function uses atomic addition to update track count 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  void loadTracks(TkSoA const* ptracks, ZVertexSoA* soa, WorkSpace* pws, float ptMin) {
    assert(ptracks);
    assert(soa);
    auto const& tracks = *ptracks;
    auto const& fit = tracks.stateAtBS;
    auto const* quality = tracks.qualityData();

    auto first = 0;
    for (int idx = first, nt = TkSoA::stride(); idx < nt; idx++) {
      auto nHits = tracks.nHits(idx);
      if (nHits == 0)
        break;  // this is a guard: maybe we need to move to nTracks...

      // initialize soa...
      soa->idv[idx] = -1;

      if (nHits < 4)
        continue;  // no triplets
      if (quality[idx] != trackQuality::loose)
        continue;

      auto pt = tracks.pt(idx);

      if (pt < ptMin)
        continue;

      auto& data = *pws;
      auto it = atomicAdd(&data.ntrks, 1);
      data.itrk[it] = idx;
      data.zt[it] = tracks.zip(idx);
      data.ezt2[it] = fit.covariance(idx)(14);
      data.ptt2[it] = pt * pt;
    }
  }

// #define THREE_KERNELS
#ifndef THREE_KERNELS
/**
 * Brief description of the function vertexFinderOneKernel 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  void vertexFinderOneKernel(gpuVertexFinder::ZVertices* pdata,
                             gpuVertexFinder::WorkSpace* pws,
                             int minT,      // min number of neighbours to be "seed"
                             float eps,     // max absolute distance to cluster
                             float errmax,  // max error to be "seed"
                             float chi2max  // max normalized distance to cluster,
  ) {
    clusterTracksByDensity(pdata, pws, minT, eps, errmax, chi2max);

    fitVertices(pdata, pws, 50.);

    splitVertices(pdata, pws, 9.f);

    fitVertices(pdata, pws, 5000.);

    sortByPt2(pdata, pws);
  }
#else
/**
 * Brief description of the function
 *
 * This function implements the first stage of the vertex finding process
 * It takes in various parameters including vertex data and workspace
 * and performs clustering and fitting operations to identify vertices
 *
 * Parameters:
 *   pdata - pointer to vertex data
 *   pws - pointer to workspace data
 *   minT - minimum number of neighbors required to be considered a seed
 *   eps - maximum absolute distance to cluster
 *   errmax - maximum error allowed to be considered a seed
 *   chi2max - maximum normalized distance to cluster
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  void vertexFinderKernel1(gpuVertexFinder::ZVertices* pdata,
                           gpuVertexFinder::WorkSpace* pws,
                           int minT,      // min number of neighbours to be "seed"
                           float eps,     // max absolute distance to cluster
                           float errmax,  // max error to be "seed"
                           float chi2max  // max normalized distance to cluster,
  ) {
    clusterTracksByDensity(pdata, pws, minT, eps, errmax, chi2max);

    fitVertices(pdata, pws, 50.);
  }

/**
 * Brief description of the function
 *
 * Detailed description of the function
 * Parameters:
 *   pdata pointer to ZVertices data
 *   pws pointer to WorkSpace data
 * Returns:
 *   None
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  void vertexFinderKernel2(gpuVertexFinder::ZVertices* pdata, gpuVertexFinder::WorkSpace* pws) {
    fitVertices(pdata, pws, 5000.);

    sortByPt2(pdata, pws);
  }
#endif

/**
 * Brief description of the function make
 *
 * Detailed description of the function make which produces 
 * heterogeneous vertices from input tracks on the CPU
 *
 * @param tksoa input track information
 * @param ptMin minimum transverse momentum requirement
 * @return unique pointer to produced heterogeneous vertices
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
  ZVertexHeterogeneous Producer::make(TkSoA const* tksoa, float ptMin) const {
    // std::cout << "producing Vertices on  CPU" <<    std::endl;
    ZVertexHeterogeneous vertices(std::make_unique<ZVertexSoA>());
    assert(tksoa);
    auto* soa = vertices.get();
    assert(soa);

    auto ws_d = std::make_unique<WorkSpace>();

    init(soa, ws_d.get());
    loadTracks(tksoa, soa, ws_d.get(), ptMin);

    if (useDensity_) {
      clusterTracksByDensity(soa, ws_d.get(), minT, eps, errmax, chi2max);
    } else if (useDBSCAN_) {
      clusterTracksDBSCAN(soa, ws_d.get(), minT, eps, errmax, chi2max);
    } else if (useIterative_) {
      clusterTracksIterative(soa, ws_d.get(), minT, eps, errmax, chi2max);
    }
    // std::cout << "found " << (*ws_d).nvIntermediate << " vertices " << std::endl;
    fitVertices(soa, ws_d.get(), 50.);
    // one block per vertex!
    splitVertices(soa, ws_d.get(), 9.f);
    fitVertices(soa, ws_d.get(), 5000.);
    sortByPt2(soa, ws_d.get());

    return vertices;
  }

}  // namespace gpuVertexFinder

#undef FROM
