#ifndef RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h
#define RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h

#include "CUDACore/ESProduct.h"
#include "CUDACore/HostAllocator.h"
#include "CUDACore/device_unique_ptr.h"
#include "CondFormats/SiPixelFedCablingMapGPU.h"

#include <cuda_runtime.h>

#include <set>

/**
 * @brief Wrapper class for managing SiPixelFedCablingMapGPU data on both CPU and GPU.
 *
 * This class provides methods for accessing the data on both the host and device,
 * as well as handling quality checks and module unpacking information.
 
class SiPixelFedCablingMapGPUWrapper {
     * @brief Constructor for initializing the wrapper with a cabling map and module unpacking data.
   *
   * @param cablingMap The input cabling map data structure.
   * @param modToUnp Module unpacking data.
   
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap,
                                        std::vector<unsigned char> modToUnp);
   * @brief Destructor for releasing resources allocated by the wrapper.
   
  ~SiPixelFedCablingMapGPUWrapper();
   * @brief Checks if the wrapped data has quality.
   *
   * @return True if the data has quality, false otherwise.
   
  bool hasQuality() const { return hasQuality_; }
   * @brief Retrieves a pointer to the GPU product asynchronously.
   *
   * @param cudaStream The CUDA stream handle.
   * @return A pointer to the GPU product.
   
  const SiPixelFedCablingMapGPU *getGPUProductAsync(cudaStream_t cudaStream) const;
   * @brief Retrieves a pointer to the CPU product.
   *
   * @return A pointer to the CPU product.
   
  const SiPixelFedCablingMapGPU *getCPUProduct() const { return cablingMapHost; }
   * @brief Retrieves a pointer to the module unpacking data for all modules asynchronously.
   *
   * @param cudaStream The CUDA stream handle.
   * @return A pointer to the module unpacking data.
   
  const unsigned char *getModToUnpAllAsync(cudaStream_t cudaStream) const;
   * @brief Retrieves a pointer to the default module unpacking data.
   *
   * @return A pointer to the default module unpacking data.
   
  const unsigned char *getModToUnpAll() const { return modToUnpDefault.data(); }

private:   * @brief Default module unpacking data stored on the host.
   
  std::vector<unsigned char, cms::cuda::HostAllocator<unsigned char>> modToUnpDefault;
   * @brief Flag indicating whether the data has quality.
   
  bool hasQuality_;
   * @brief Pointer to the cabling map data structure on the host.
   
  SiPixelFedCablingMapGPU *cablingMapHost;
   * @brief Structure representing data on the GPU.
   
  struct GPUData {
         * @brief Destructor for releasing GPU resources.
     
    ~GPUData();
     * @brief Pointer to the cabling map data structure on the GPU.
     
    SiPixelFedCablingMapGPU *cablingMapDevice;
  };
   * @brief Product storing GPU data for all devices.
   
  cms::cuda::ESProduct<GPUData> gpuData_;
   * @brief Structure representing module unpacking data on the GPU.
   
  struct ModulesToUnpack {
         * @brief Destructor for releasing GPU resources.
     
    ~ModulesToUnpack();
     * @brief Pointer to the module unpacking data on the GPU.
     
    unsigned char *modToUnpDefault;
  };
   * @brief Product storing module unpacking data for all devices.
   
  cms::cuda::ESProduct<ModulesToUnpack> modToUnp_;
}* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
class SiPixelFedCablingMapGPUWrapper {
public:
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap,
                                          std::vector<unsigned char> modToUnp);
  ~SiPixelFedCablingMapGPUWrapper();

  bool hasQuality() const { return hasQuality_; }

  // returns pointer to GPU memory
  const SiPixelFedCablingMapGPU *getGPUProductAsync(cudaStream_t cudaStream) const;
  const SiPixelFedCablingMapGPU *getCPUProduct() const { return cablingMapHost; }

  // returns pointer to GPU memory
  const unsigned char *getModToUnpAllAsync(cudaStream_t cudaStream) const;
  const unsigned char *getModToUnpAll() const { return modToUnpDefault.data(); }

private:
  std::vector<unsigned char, cms::cuda::HostAllocator<unsigned char>> modToUnpDefault;
  bool hasQuality_;

  SiPixelFedCablingMapGPU *cablingMapHost = nullptr;  // pointer to struct in CPU

  struct GPUData {
    ~GPUData();
    SiPixelFedCablingMapGPU *cablingMapDevice = nullptr;  // pointer to struct in GPU
  };
  cms::cuda::ESProduct<GPUData> gpuData_;

  struct ModulesToUnpack {
    ~ModulesToUnpack();
    unsigned char *modToUnpDefault = nullptr;  // pointer to GPU
  };
  cms::cuda::ESProduct<ModulesToUnpack> modToUnp_;
};

#endif
