#ifndef RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h
#define RecoLocalTracker_SiPixelClusterizer_SiPixelFedCablingMapGPUWrapper_h

#include "CUDACore/ESProduct.h"
#include "CUDACore/HostAllocator.h"
#include "CUDACore/device_unique_ptr.h"
#include "CondFormats/SiPixelFedCablingMapGPU.h"

#include <cuda_runtime.h>

#include <set>

/**
 * @brief Wrapper class for managing SiPixelFedCablingMapGPU data on both CPU and GPU.
 *
 * This class provides functionality for handling SiPixelFedCablingMapGPU objects,
 * including asynchronous access to GPU memory and caching of CUDA streams.
 
class SiPixelFedCablingMapGPUWrapper {
     * @brief Constructor for initializing the wrapper with a SiPixelFedCablingMapGPU object and module unpacking data.
   *
   * @param cablingMap The input SiPixelFedCablingMapGPU object.
   * @param modToUnp Module unpacking data.
   
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap, std::vector<unsigned char> modToUnp);
   * @brief Destructor for releasing allocated resources.
   
  ~SiPixelFedCablingMapGPUWrapper();
   * @brief Checks if quality data is available.
   *
   * @return True if quality data exists, false otherwise.
   
  bool hasQuality() const;
   * @brief Returns a pointer to the SiPixelFedCablingMapGPU object in GPU memory asynchronously.
   *
   * @param cudaStream The CUDA stream for asynchronous operation.
   * @return Pointer to the SiPixelFedCablingMapGPU object in GPU memory.
   
  const SiPixelFedCablingMapGPU *getGPUProductAsync(cudaStream_t cudaStream) const;
   * @brief Returns a pointer to the SiPixelFedCablingMapGPU object in CPU memory.
   *
   * @return Pointer to the SiPixelFedCablingMapGPU object in CPU memory.
   
  const SiPixelFedCablingMapGPU *getCPUProduct() const;
   * @brief Returns a pointer to module unpacking data in GPU memory asynchronously.
   *
   * @param cudaStream The CUDA stream for asynchronous operation.
   * @return Pointer to module unpacking data in GPU memory.
   
  const unsigned char *getModToUnpAllAsync(cudaStream_t cudaStream) const;
   * @brief Returns a pointer to module unpacking data in CPU memory.
   *
   * @return Pointer to module unpacking data in CPU memory.
   
  const unsigned char *getModToUnpAll() const;

 private:   * @brief Default module unpacking data stored in CPU memory.
   
  std::vector<unsigned char, cms::cuda::HostAllocator<unsigned char>> modToUnpDefault;
   * @brief Flag indicating availability of quality data.
   
  bool hasQuality_;
   * @brief Pointer to the SiPixelFedCablingMapGPU object in CPU memory.
   
  SiPixelFedCablingMapGPU *cablingMapHost;
   * @brief Struct representing GPU data, including a pointer to the SiPixelFedCablingMapGPU object in GPU memory.
   
  struct GPUData {
         * @brief Destructor for releasing GPU memory.
     
    ~GPUData();
     * @brief Pointer to the SiPixelFedCablingMapGPU object in GPU memory.
     
    SiPixelFedCablingMapGPU *cablingMapDevice;
  };
   * @brief Cached product for distributing GPUData across devices.
   
  cms::cuda::ESProduct<GPUData> gpuData_;
   * @brief Struct representing module unpacking data in GPU memory.
   
  struct ModulesToUnpack {
         * @brief Destructor for releasing GPU memory.
     
    ~ModulesToUnpack();
     * @brief Pointer to module unpacking data in GPU memory.
     
    unsigned char *modToUnpDefault;
  };
   * @brief Cached product for distributing module unpacking data across devices.
   
  cms::cuda::ESProduct<ModulesToUnpack> modToUnp_;
}* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
class SiPixelFedCablingMapGPUWrapper {
public:
  explicit SiPixelFedCablingMapGPUWrapper(SiPixelFedCablingMapGPU const &cablingMap,
                                          std::vector<unsigned char> modToUnp);
  ~SiPixelFedCablingMapGPUWrapper();

  bool hasQuality() const { return hasQuality_; }

  // returns pointer to GPU memory
  const SiPixelFedCablingMapGPU *getGPUProductAsync(cudaStream_t cudaStream) const;
  const SiPixelFedCablingMapGPU *getCPUProduct() const { return cablingMapHost; }

  // returns pointer to GPU memory
  const unsigned char *getModToUnpAllAsync(cudaStream_t cudaStream) const;
  const unsigned char *getModToUnpAll() const { return modToUnpDefault.data(); }

private:
  std::vector<unsigned char, cms::cuda::HostAllocator<unsigned char>> modToUnpDefault;
  bool hasQuality_;

  SiPixelFedCablingMapGPU *cablingMapHost = nullptr;  // pointer to struct in CPU

  struct GPUData {
    ~GPUData();
    SiPixelFedCablingMapGPU *cablingMapDevice = nullptr;  // pointer to struct in GPU
  };
  cms::cuda::ESProduct<GPUData> gpuData_;

  struct ModulesToUnpack {
    ~ModulesToUnpack();
    unsigned char *modToUnpDefault = nullptr;  // pointer to GPU
  };
  cms::cuda::ESProduct<ModulesToUnpack> modToUnp_;
};

#endif
