#ifndef KokkosCore_hintLightWeight_h
#define KokkosCore_hintLightWeight_h

#include <Kokkos_Core.hpp>

// shorthand because this will be used a lot
template <typename T>
/**
 * Returns a new policy with the HintLightWeight property set.
 *
 * @param policy The input policy to modify.
 * @return A new policy with the HintLightWeight property applied.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
auto hintLightWeight(T&& policy) {
  return Kokkos::Experimental::require(std::forward<T>(policy),
                                       Kokkos::Experimental::WorkItemProperty::HintLightWeight);
}

#endif  // KokkosCore_hintLightWeight_h
