#ifndef KokkosCore_hintLightWeight_h
#define KokkosCore_hintLightWeight_h

#include <Kokkos_Core.hpp>

// shorthand because this will be used a lot
template <typename T>
/**
 * @brief Returns a new policy with the HintLightWeight property set.
 *
 * @tparam T Type of the input policy.
 * @param policy Input policy to modify.
 * @return New policy with HintLightWeight property.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
auto hintLightWeight(T&& policy) {
  return Kokkos::Experimental::require(std::forward<T>(policy),
                                       Kokkos::Experimental::WorkItemProperty::HintLightWeight);
}

#endif  // KokkosCore_hintLightWeight_h
