#ifndef HeterogeneousCore_CUDAUtilities_interface_HistoContainer_h
#define HeterogeneousCore_CUDAUtilities_interface_HistoContainer_h

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <type_traits>

#include <Kokkos_Core.hpp>

#include "KokkosCore/AtomicPairCounter.h"
#include "KokkosCore/hintLightWeight.h"
#include "KokkosCore/memoryTraits.h"
#include "KokkosCore/atomic.h"
#include "KokkosCore/kokkos_assert.h"

namespace cms {
  namespace kokkos {
    template <typename T, typename MemSpace>
/**
 * Finds the upper bound of a given value within a view of offsets.
 *
 * @param offsets View of offsets to search through
 * @param upper_index Upper limit of the search range
 * @param value Value to find the upper bound for
 * @return Index of the first offset greater than the given value, or 0 if not found
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    KOKKOS_INLINE_FUNCTION uint32_t
    upper_bound(const Kokkos::View<uint32_t const*, MemSpace, RestrictUnmanaged>& offsets,
                const uint32_t& upper_index,
                const T& value) {
      for (uint32_t j = 0; j < upper_index; ++j) {
        if (offsets(j) > value) {
          return j;
        }
      }
      return 0;
    }

    template <typename Histo, typename MemSpace, typename ExecSpace, typename T>
/**
 * Counts elements from a vector using a team of threads.
 *
 * @param h histogram to update
 * @param nh number of histograms
 * @param v input vector
 * @param offsets offset array
 * @param teamMember team member information
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    KOKKOS_INLINE_FUNCTION void countFromVector(
        const Kokkos::View<Histo, MemSpace, RestrictUnmanaged>& h,
        const uint32_t nh,
        const Kokkos::View<T const*, MemSpace, RestrictUnmanaged>& v,
        const Kokkos::View<uint32_t const*, MemSpace, RestrictUnmanaged>& offsets,
        const typename Kokkos::TeamPolicy<ExecSpace>::member_type& teamMember) {
      uint32_t first = teamMember.league_rank() * teamMember.team_size() + teamMember.team_rank();
      uint32_t total_threads = teamMember.league_size() * teamMember.team_size();
      for (uint32_t i = first, nt = offsets(nh); i < nt; i += total_threads) {
        uint32_t index = upper_bound(offsets, nh + 1, i);
        assert(offsets(index) > 0);
        int32_t ih = &offsets(index) - &offsets() - 1;
        assert(ih >= 0);
        assert(ih < int(nh));
        h().count(v(i), ih);
      }
    }

    template <typename Histo, typename MemSpace, typename ExecSpace, typename T>
/**
 * Fills histogram from vector using parallel execution
 * @param h histogram to fill
 * @param nh number of histograms
 * @param v input vector
 * @param offsets offset array
 * @param teamMember team policy member
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    KOKKOS_INLINE_FUNCTION void fillFromVector(const Kokkos::View<Histo, MemSpace, RestrictUnmanaged>& h,
                                               const uint32_t nh,
                                               const Kokkos::View<T const*, MemSpace, RestrictUnmanaged>& v,
                                               const Kokkos::View<uint32_t const*, MemSpace, RestrictUnmanaged>& offsets,
                                               const typename Kokkos::TeamPolicy<ExecSpace>::member_type& teamMember) {
      int first = teamMember.league_rank() * teamMember.team_size() + teamMember.team_rank();
      int total_threads = teamMember.league_size() * teamMember.team_size();

      for (uint32_t i = first, nt = offsets(nh); i < nt; i += total_threads) {
        uint32_t index = 0;
        for (uint32_t j = 0; j <= nh; ++j) {
          if (offsets(j) > i) {
            index = j;
            break;
          }
        }
        assert(offsets(index) > 0);
        int32_t ih = &offsets(index) - &offsets() - 1;
        assert(ih >= 0);
        assert(ih < int(nh));
        h().fill(v(i), i, ih);
      }
    }

    template <typename Histo, typename MemSpace, typename ExecSpace>
/**
 * Launches a kernel to zero out a histogram view.
 *
 * @param h        Histogram view to be zeroed
 * @param execSpace Execution space where the kernel will run
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void launchZero(const Kokkos::View<Histo, MemSpace, RestrictUnmanaged>& h, ExecSpace const& execSpace) {
      Kokkos::parallel_for(
          "launchZero_view",
          hintLightWeight(Kokkos::RangePolicy<ExecSpace>(execSpace, 0, Histo::totbins())),
          KOKKOS_LAMBDA(const size_t i) { h().off[i] = 0; });
    }

    template <typename Histo, typename ExecSpace>
/**
 * Launches a parallel operation to initialize an array to zero.
 *
 * @param h pointer to the histogram object
 * @param execSpace execution space for the parallel operation
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void launchZero(Histo* h, ExecSpace const& execSpace) {
      Kokkos::parallel_for(
          "launchZero_pointer",
          hintLightWeight(Kokkos::RangePolicy<ExecSpace>(execSpace, 0, Histo::totbins())),
          KOKKOS_LAMBDA(const size_t i) { h->off[i] = 0; });
    }

    template <typename Histo, typename MemSpace, typename ExecSpace>
/**
 * Launches finalize operation on histogram data in parallel.
 *
 * @param h input histogram view
 * @param execSpace execution space
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void launchFinalize(const Kokkos::View<Histo, MemSpace, RestrictUnmanaged>& h, ExecSpace const& execSpace) {
      Kokkos::parallel_scan(
          "launchFinalize",
          hintLightWeight(Kokkos::RangePolicy<ExecSpace>(execSpace, 0, Histo::totbins())),
          KOKKOS_LAMBDA(const int& i, float& upd, const bool& final) {
            upd += h().off[i];
            if (final)
              h().off[i] = upd;
          });
    }

    template <typename Histo, typename MemSpace, typename ExecSpace, typename T>
/**
 * Function to fill multiple histograms from a vector
 *
 * @param h histogram view to be filled
 * @param nh number of histograms
 * @param v input vector view
 * @param offsets offset view for the input vector
 * @param totSize total size of the data
 * @param nthreads number of threads to use
 * @param execSpace execution space
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline void fillManyFromVector(const Kokkos::View<Histo, MemSpace, RestrictUnmanaged>& h,
                                   const uint32_t nh,
                                   const Kokkos::View<T const*, MemSpace, RestrictUnmanaged>& v,
                                   const Kokkos::View<uint32_t const*, MemSpace, RestrictUnmanaged>& offsets,
                                   const uint32_t totSize,
                                   const int nthreads,
                                   ExecSpace const& execSpace) {
      launchZero(h, execSpace);
      using TeamPolicy = Kokkos::TeamPolicy<ExecSpace>;
      // TODO: spreadin the total amount of work (totSize) manually to
      // the teams in a way that depends on the number of threads per
      // team feels suboptimal.
      //
      // Kokkos::AUTO() for the number of threads does not really work
      // because the number of blocks depends on the number of threads.
      //
      // Maybe this would really be a case for RangePolicy?
#if defined KOKKOS_BACKEND_SERIAL || defined KOKKOS_BACKEND_PTHREAD
      const auto nblocks = (totSize + ExecSpace::impl_thread_pool_size()) / ExecSpace::impl_thread_pool_size();
      auto tp = hintLightWeight(TeamPolicy(execSpace, nblocks, ExecSpace::impl_thread_pool_size()));
#else
      const auto nblocks = (totSize + nthreads - 1) / nthreads;
      auto tp = hintLightWeight(TeamPolicy(execSpace, nblocks, nthreads));
#endif
      Kokkos::parallel_for(
          "countFromVector", tp, KOKKOS_LAMBDA(typename TeamPolicy::member_type const& teamMember) {
            // TODO: unclear why the argument type deduction fails here
            countFromVector<Histo, MemSpace, ExecSpace, T>(h, nh, v, offsets, teamMember);
          });
      launchFinalize(h, execSpace);
      Kokkos::parallel_for(
          "fillFromVector", tp, KOKKOS_LAMBDA(typename TeamPolicy::member_type const& teamMember) {
            // TODO: unclear why the argument type deduction fails here
            fillFromVector<Histo, MemSpace, ExecSpace, T>(h, nh, v, offsets, teamMember);
          });
    }

    template <typename Assoc, typename MemSpace, typename ExecSpace>
/**
 * Finalizes bulk data structures.
 *
 * @param[in] apc Atomic pair counter view
 * @param[in] assoc Association view
 * @param[in] execSpace Execution space
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    void finalizeBulk(Kokkos::View<AtomicPairCounter, MemSpace, RestrictUnmanaged> const& apc,
                      Kokkos::View<Assoc, MemSpace, RestrictUnmanaged> const& assoc,
                      ExecSpace const& execSpace) {
      Kokkos::parallel_for(
          "finalizeBulk",
          hintLightWeight(Kokkos::RangePolicy<ExecSpace>(execSpace, 0, Assoc::totbins())),
          KOKKOS_LAMBDA(const int& i) { assoc().bulkFinalizeFill(apc, i); });
    }

    template <typename Assoc, typename MemSpace, typename ExecSpace>
/**
 * Finalizes bulk data structures.
 *
 * @param[in] apc Atomic pair counter view
 * @param[out] assoc Association pointer
 * @param[in] execSpace Execution space
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    void finalizeBulk(Kokkos::View<AtomicPairCounter, MemSpace, RestrictUnmanaged> const& apc,
                      Assoc* __restrict__ assoc,
                      ExecSpace const& execSpace) {
      Kokkos::parallel_for(
          "finalizeBulk",
          hintLightWeight(Kokkos::RangePolicy<ExecSpace>(execSpace, 0, Assoc::totbins())),
          KOKKOS_LAMBDA(const int& i) { assoc->bulkFinalizeFill(apc, i); });
    }

    // iteratate over N bins left and right of the one containing "v"
    template <typename Hist, typename V, typename Func>
/**
 * Performs an operation on each element within a specified range of bins in a histogram.
 *
 * @param hist   The input histogram.
 * @param value  The central value around which the range of bins is determined.
 * @param n      The number of bins to consider on either side of the central bin.
 * @param func   The function to apply to each element in the specified range of bins.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    KOKKOS_FORCEINLINE_FUNCTION void forEachInBins(Hist const* hist, V value, int n, Func func) {
      int bs = Hist::bin(value);
      int be = std::min(int(Hist::nbins() - 1), bs + n);
      bs = std::max(0, bs - n);
      assert(be >= bs);
      for (auto pj = hist->begin(bs); pj < hist->end(be); ++pj) {
        func(*pj);
      }
    }

    // iteratate over bins containing all values in window wmin, wmax
    template <typename Histo, typename V, typename Func, typename MemSpace>
/**
 * Brief description: Applies a function to each element within a specified window of a histogram.
 *
 * Detailed description: This function iterates over a subset of bins in a histogram, 
 * starting from the bin that corresponds to the minimum value wmin and ending at the bin 
 * that corresponds to the maximum value wmax, and applies the provided function func to each element.
 *
 * Parameters:
 *   hist - The input histogram viewed as a collection of pointers to Histo objects.
 *   wmin - The minimum value that defines the start of the window.
 *   wmax - The maximum value that defines the end of the window.
 *   func - The function object to be applied to each element within the window.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    KOKKOS_FORCEINLINE_FUNCTION void forEachInWindow(const Kokkos::View<Histo*, MemSpace, RestrictUnmanaged>& hist,
                                                     V wmin,
                                                     V wmax,
                                                     Func const& func) {
      auto bs = Histo::bin(wmin);
      auto be = Histo::bin(wmax);
      assert(be >= bs);
      for (auto pj = hist(0).begin(bs); pj < hist(0).end(be); ++pj) {
        func(*pj);
      }
    }

    template <typename T,                  // the type of the discretized input values
              uint32_t NBINS,              // number of bins
              uint32_t SIZE,               // max number of element
              uint32_t S = sizeof(T) * 8,  // number of significant bits in T
              typename I = uint32_t,  // type stored in the container (usually an index in a vector of the input values)
              uint32_t NHISTS = 1     // number of histos stored
              >
    class HistoContainer {
    public:
      using Counter = uint32_t;

      using CountersOnly = HistoContainer<T, NBINS, 0, S, I, NHISTS>;

      using index_type = I;
      using UT = typename std::make_unsigned<T>::type;

/**
 * Calculates the integer base 2 logarithm of a given 32 bit unsigned integer.
 *
 * @param v input value
 * @return integer base 2 logarithm of v
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      static constexpr uint32_t ilog2(uint32_t v) {
        constexpr uint32_t b[] = {0x2, 0xC, 0xF0, 0xFF00, 0xFFFF0000};
        constexpr uint32_t s[] = {1, 2, 4, 8, 16};

        uint32_t r = 0;  // result of log2(v) will go here
        for (auto i = 4; i >= 0; i--)
          if (v & b[i]) {
            v >>= s[i];
            r |= s[i];
          }
        return r;
      }

      static constexpr uint32_t sizeT() { return S; }
      static constexpr uint32_t nbins() { return NBINS; }
      static constexpr uint32_t nhists() { return NHISTS; }
      static constexpr uint32_t totbins() { return NHISTS * NBINS + 1; }
      static constexpr uint32_t nbits() { return ilog2(NBINS - 1) + 1; }
      static constexpr uint32_t capacity() { return SIZE; }

      static constexpr auto histOff(uint32_t nh) { return NBINS * nh; }

/**
 * Returns the temporary storage size required for the inclusive sum operation.
 *
 * @return The size of the temporary storage in bytes.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_INLINE_FUNCTION static size_t wsSize() {
#ifdef TODO  //__CUDACC__
        uint32_t* v = nullptr;
        void* d_temp_storage = nullptr;
        size_t temp_storage_bytes = 0;
        cub::DeviceScan::InclusiveSum(d_temp_storage, temp_storage_bytes, v, v, totbins());
        return temp_storage_bytes;
#else
        return 0;
#endif
      }

/**
 * Returns the binary representation of the input value
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      static constexpr UT bin(T t) {
        constexpr uint32_t shift = sizeT() - nbits();
        constexpr uint32_t mask = (1 << nbits()) - 1;
        return (t >> shift) & mask;
      }

/**
 * Brief description: Resets all elements to zero.
 *
 * Detailed description: This function iterates over all elements in the offset range and sets their values to zero.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_INLINE_FUNCTION void zero() {
        for (auto& i : off)
          i = 0;
      }

/**
 * Adds another CountersOnly object to this object
 * @param co the CountersOnly object to add
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_FORCEINLINE_FUNCTION void add(const CountersOnly& co) {
        for (uint32_t i = 0; i < totbins(); ++i) {
          cms::kokkos::atomic_add(off + i, co.off[i]);
        }
      }

      static KOKKOS_FORCEINLINE_FUNCTION uint32_t atomicIncrement(Counter& x) {
        return cms::kokkos::atomic_fetch_add(&x, 1U);
      }

      static KOKKOS_FORCEINLINE_FUNCTION uint32_t atomicDecrement(Counter& x) {
        return cms::kokkos::atomic_fetch_sub(&x, 1U);
      }

/**
 * Increments the offset counter at the specified bin index.
 *
 * @param b Bin index to increment the offset counter for.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_FORCEINLINE_FUNCTION void countDirect(T b) {
        assert(b < nbins());
        atomicIncrement(off[b]);
      }

/**
 * Fills the direct bin with the specified value.
 *
 * @param b   the bin number
 * @param j   the value to store in the bin
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_FORCEINLINE_FUNCTION void fillDirect(T b, index_type j) {
        assert(b < nbins());
        auto w = atomicDecrement(off[b]);
        assert(w > 0);
        bins[w - 1] = j;
      }

      template <typename MemSpace>
/**
 * Performs a bulk fill operation on an AtomicPairCounter view.
 *
 * @param apc the AtomicPairCounter view to operate on
 * @param v the array of values to fill
 * @param n the number of values to fill
 * @return the updated bin index or a negative value indicating overflow
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_FORCEINLINE_FUNCTION int32_t bulkFill(
          Kokkos::View<AtomicPairCounter, MemSpace, RestrictUnmanaged> const& apc, index_type const* v, uint32_t n) {
        auto c = apc().add(n);
        if (c.m >= nbins())
          return -int32_t(c.m);
        off[c.m] = c.n;
        for (uint32_t j = 0; j < n; ++j)
          bins[c.n + j] = v[j];
        return c.m;
      }

/**
 * Brief description of function bulkFill
 *
 * Detailed description of function bulkFill which fills the bins with input data
 *
 * @param apc reference to AtomicPairCounter object
 * @param v pointer to array of indices
 * @param n number of elements to fill
 * @return index where filling started or negative value if full
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_INLINE_FUNCTION int32_t bulkFill(AtomicPairCounter& apc, index_type const* v, uint32_t n) {
        auto c = apc.add(n);
        if (c.m >= nbins())
          return -int32_t(c.m);
        off[c.m] = c.n;
        for (uint32_t j = 0; j < n; ++j)
          bins[c.n + j] = v[j];
        return c.m;
      }

      template <typename MemSpace>
/**
 * Brief description of function bulkFinalize 
 * Finalizes the atomic pair counter by updating offset values.
 *
 * Details of function bulkFinalize 
 * This function takes a constant reference to an AtomicPairCounter view as input and updates 
 * the offset value at the specified memory location.
 *
 * @param[in] apc Constant reference to an AtomicPairCounter view
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_FORCEINLINE_FUNCTION void bulkFinalize(
          Kokkos::View<AtomicPairCounter, MemSpace, RestrictUnmanaged> const& apc) {
        off[apc().get().m] = apc().get().n;
      }

      template <typename MemSpace>
/**
 * Finalizes the filling process for a given thread.
 *
 * @param[in] apc Atomic pair counter view.
 * @param[in] threadId Thread identifier.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_FORCEINLINE_FUNCTION void bulkFinalizeFill(
          Kokkos::View<AtomicPairCounter, MemSpace, RestrictUnmanaged> const& apc, const int threadId) {
        auto m = apc().get().m;
        auto n = apc().get().n;
        if (m >= nbins()) {  // overflow!
          off[nbins()] = uint32_t(off[nbins() - 1]);
          return;
        }
        auto i = m + threadId;
        if (i < totbins()) {
          off[i] = n;
        }
      }

/**
 * Brief description: Counts an element of type T and updates the offset accordingly.
 *
 * Detailed description: This function takes an object of type T as input, determines its bin using the bin function,
 * asserts that the calculated bin is within the valid range, and then atomically increments the offset at the calculated bin.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_FORCEINLINE_FUNCTION void count(T t) {
        uint32_t b = bin(t);
        assert(b < nbins());
        atomicIncrement(off[b]);
      }

/**
 * Fills a bin with a given value at a specific index.
 *
 * @param t value to be filled
 * @param j index where the value is to be filled
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_FORCEINLINE_FUNCTION void fill(T t, index_type j) {
        uint32_t b = bin(t);
        assert(b < nbins());
        auto w = atomicDecrement(off[b]);
        assert(w > 0);
        bins[w - 1] = j;
      }

/**
 * Counts the occurrences of a specific type T within a histogram.
 *
 * @param t The type to be counted.
 * @param nh The index of the histogram.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_FORCEINLINE_FUNCTION void count(T t, uint32_t nh) {
        uint32_t b = bin(t);
        assert(b < nbins());
        b += histOff(nh);
        assert(b < totbins());
        atomicIncrement(off[b]);
      }

/**
 * Brief description of function to decrement offset and store index
 *
 * Detailed description of function to handle histogram updates
 *
 * @param t input type variable
 * @param j index type variable
 * @param nh unsigned integer variable
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_FORCEINLINE_FUNCTION void fill(T t, index_type j, uint32_t nh) {
        uint32_t b = bin(t);
        assert(b < nbins());
        b += histOff(nh);
        assert(b < totbins());
        auto w = atomicDecrement(off[b]);
        assert(w > 0);
        bins[w - 1] = j;
      }

#pragma hd_warning_disable
      // The team size must be power-of-two
      template <typename TeamMemberType>
/**
 * Finalizes the computation by performing a parallel scan operation
 * across the team members and updates the offset values accordingly
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_FORCEINLINE_FUNCTION void finalize(const TeamMemberType& teamMember) {
        Kokkos::parallel_scan(Kokkos::TeamThreadRange(teamMember, totbins()),
                              [=](int i, uint32_t& update, const bool final) {
                                update += this->off[i];
                                if (final)
                                  this->off[i] = update;
                              });
      }

      constexpr auto size() const { return uint32_t(off[totbins() - 1]); }
      constexpr auto size(uint32_t b) const { return off[b + 1] - off[b]; }

      constexpr index_type const* begin() const { return bins; }
      constexpr index_type const* end() const { return begin() + size(); }

      constexpr index_type const* begin(uint32_t b) const { return bins + off[b]; }
      constexpr index_type const* end(uint32_t b) const { return bins + off[b + 1]; }

      Counter off[totbins()];
      index_type bins[capacity()];
    };

    template <typename I,        // type stored in the container (usually an index in a vector of the input values)
              uint32_t MAXONES,  // max number of "ones"
              uint32_t MAXMANYS  // max number of "manys"
              >
    using OneToManyAssoc = HistoContainer<uint32_t, MAXONES, MAXMANYS, sizeof(uint32_t) * 8, I, 1>;
  }  // namespace kokkos
}  // namespace cms

#endif  // HeterogeneousCore_CUDAUtilities_interface_HistoContainer_h
