#ifndef KokkosCore_kokkosConfigCommon_h
#define KokkosCore_kokkosConfigCommon_h

#include <vector>
#include <memory>

// This header needs to be #included in a file that may not be
// compiled with nvcc.
namespace kokkos_common {
/**
 * @brief Class to manage initialization scope guard for different backends.
 *
 * This class provides a way to initialize and cleanup resources for various backends such as serial, pthread, CUDA, and HIP.
 * It ensures proper setup and teardown of the environment for the specified backends.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  class InitializeScopeGuard {
  public:
    enum class Backend { SERIAL, PTHREAD, CUDA, HIP };

    explicit InitializeScopeGuard(std::vector<Backend> const& backends, int numberOfInnerThreads = 1);
    ~InitializeScopeGuard();

  private:
    class Impl;
    std::unique_ptr<Impl> pimpl_;
  };
}  // namespace kokkos_common

#endif
