#ifndef HeterogeneousCore_CUDAUtilities_interface_SimpleVector_h
#define HeterogeneousCore_CUDAUtilities_interface_SimpleVector_h

//  author: Felice Pantaleo, CERN, 2018

#include <type_traits>
#include <utility>

#include "KokkosCore/kokkosConfig.h"
#include "KokkosCore/atomic.h"

namespace cms {
  namespace kokkos {
    template <class T>
    struct SimpleVector {
      constexpr SimpleVector() = default;

      // ownership of m_data stays within the caller
      constexpr void construct(int capacity, T *data) {
        m_size = 0;
        m_capacity = capacity;
        m_data = data;
      }

/**
 * Pushes an element onto the end of the container without checking for capacity.
 *
 * @param element The element to be added to the container.
 * @return The index of the newly added element if successful, -1 otherwise.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline constexpr int push_back_unsafe(const T &element) {
        auto previousSize = m_size;
        m_size++;
        if (previousSize < m_capacity) {
          m_data[previousSize] = element;
          return previousSize;
        } else {
          --m_size;
          return -1;
        }
      }

      template <class... Ts>
/**
 * Emplaces an element at the end of the container without checking for capacity.
 *
 * @param args  variable number of arguments to forward to the constructor of T
 * @return the index where the new element was inserted, or -1 if insertion failed due to lack of capacity
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      constexpr int emplace_back_unsafe(Ts &&...args) {
        auto previousSize = m_size;
        m_size++;
        if (previousSize < m_capacity) {
          (new (&m_data[previousSize]) T(std::forward<Ts>(args)...));
          return previousSize;
        } else {
          --m_size;
          return -1;
        }
      }

      inline constexpr T &back() { return m_data[m_size - 1]; }

/**
 * Returns a constant reference to the last element in the container.
 *
 * @return A constant reference to the last element if the container is not empty,
 *         otherwise returns a default constructed T object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      inline constexpr const T &back() const {
        if (m_size > 0) {
          return m_data[m_size - 1];
        } else
          return T();  //undefined behaviour
      }

      // thread-safe version of the vector, when used in a CUDA kernel
      KOKKOS_INLINE_FUNCTION int push_back(const T &element) {
        auto previousSize = cms::kokkos::atomic_fetch_add(&m_size, 1);
        if (previousSize < m_capacity) {
          m_data[previousSize] = element;
          return previousSize;
        } else {
          cms::kokkos::atomic_sub(&m_size, 1);
          return -1;
        }
      }

      template <class... Ts>
/**
 * Emplaces element at the end of the container.
 *
 * @param args  variable number of arguments to forward to constructor
 * @return index of newly added element if successful, -1 otherwise
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_INLINE_FUNCTION int emplace_back(Ts &&...args) {
        auto previousSize = cms::kokkos::atomic_fetch_add(&m_size, 1);
        if (previousSize < m_capacity) {
          (new (&m_data[previousSize]) T(std::forward<Ts>(args)...));
          return previousSize;
        } else {
          cms::kokkos::atomic_sub(&m_size, 1);
          return -1;
        }
      }

      // thread safe version of resize
      KOKKOS_INLINE_FUNCTION int extend(int size = 1) {
        auto previousSize = cms::kokkos::atomic_fetch_add(&m_size, size);
        if (previousSize < m_capacity) {
          return previousSize;
        } else {
          cms::kokkos::atomic_sub(&m_size, size);
          return -1;
        }
      }

/**
 * Decreases the size by a specified amount atomically.
 *
 * @param size the amount to decrease the size by
 * @return the new size if successful, -1 otherwise
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
      KOKKOS_INLINE_FUNCTION int shrink(int size = 1) {
        auto previousSize = cms::kokkos::atomic_fetch_sub(&m_size, size);
        if (previousSize >= size) {
          return previousSize - size;
        } else {
          cms::kokkos::atomic_add(&m_size, size);
          return -1;
        }
      }

      inline constexpr bool empty() const { return m_size <= 0; }
      inline constexpr bool full() const { return m_size >= m_capacity; }
      inline constexpr T &operator[](int i) { return m_data[i]; }
      inline constexpr const T &operator[](int i) const { return m_data[i]; }
      inline constexpr void reset() { m_size = 0; }
      inline constexpr int size() const { return m_size; }
      inline constexpr int capacity() const { return m_capacity; }
      inline constexpr T const *data() const { return m_data; }
      inline constexpr void resize(int size) { m_size = size; }
      inline constexpr void set_data(T *data) { m_data = data; }

    private:
      int m_size;
      int m_capacity;

      T *m_data;
    };

    // ownership of m_data stays within the caller
    template <class T>
/**
 * Constructs a vector with specified capacity and data
 *
 * @param capacity initial capacity of the vector
 * @param data array of elements to initialize the vector
 * @return constructed SimpleVector instance
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    SimpleVector<T> make_SimpleVector(int capacity, T *data) {
      SimpleVector<T> ret;
      ret.construct(capacity, data);
      return ret;
    }

    // ownership of m_data stays within the caller
    template <class T>
/**
 * Creates a new instance of SimpleVector at the specified memory location
 * @param mem Memory address where the vector will be constructed
 * @param capacity Initial capacity of the vector
 * @param data Array of elements to initialize the vector with
 * @return Pointer to the newly created SimpleVector instance
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    SimpleVector<T> *make_SimpleVector(SimpleVector<T> *mem, int capacity, T *data) {
      auto ret = new (mem) SimpleVector<T>();
      ret->construct(capacity, data);
      return ret;
    }
  }  // namespace kokkos
}  // namespace cms

#endif  // HeterogeneousCore_CUDAUtilities_interface_GPUSimpleVector_h
