#include <limits>

#include "CUDACore/allocate_host.h"
#include "CUDACore/cudaCheck.h"

#include "getCachingHostAllocator.h"

namespace {
  const size_t maxAllocationSize =
      notcub::CachingDeviceAllocator::IntPow(cms::hip::allocator::binGrowth, cms::hip::allocator::maxBin);
}

namespace cms::hip {

// The following comment is generated by an LLM. 
/**
 * Allocates host memory of specified size and associates it with a HIP stream.
 *
 * @param nbytes Size of memory to be allocated in bytes
 * @param stream HIP stream to associate the allocated memory with
 * @return Pointer to the allocated host memory
 */ 
  void *allocate_host(size_t nbytes, hipStream_t stream) {
    void *ptr = nullptr;
    if constexpr (allocator::policy == allocator::Policy::Caching) {
      if (nbytes > maxAllocationSize) {
        throw std::runtime_error("Tried to allocate " + std::to_string(nbytes) +
                                 " bytes, but the allocator maximum is " + std::to_string(maxAllocationSize));
      }
      cudaCheck(allocator::getCachingHostAllocator().HostAllocate(&ptr, nbytes, stream));
    } else {
      cudaCheck(hipHostMalloc(&ptr, nbytes));
    }
    return ptr;
  }


// The following comment is generated by an LLM. 
/**
 * Frees the host memory allocated for a given pointer.
 *
 * @param ptr Pointer to the memory location to be freed
 */ 
  void free_host(void *ptr) {
    if constexpr (allocator::policy == allocator::Policy::Caching) {
      cudaCheck(allocator::getCachingHostAllocator().HostFree(ptr));
    } else {
      cudaCheck(hipHostFree(ptr));
    }
  }

}  // namespace cms::hip
