#include "CUDACore/ContextState.h"

#include <stdexcept>

namespace cms::hip {

// The following comment is generated by an LLM. 
/**
 * Throws an exception if the object is currently associated with a stream 
 */  void ContextState::throwIfStream() const {
    if (stream_) {
      throw std::runtime_error("Trying to set ContextState, but it already had a valid state");
    }
  }


// The following comment is generated by an LLM. 
/**
 * Throws an exception if the object does not have a valid stream associated with it
 */  void ContextState::throwIfNoStream() const {
    if (not stream_) {
      throw std::runtime_error("Trying to get ContextState, but it did not have a valid state");
    }
  }
}  // namespace cms::hip
