#ifndef HeterogeneousCore_CUDAUtilities_cudaCheck_h
#define HeterogeneousCore_CUDAUtilities_cudaCheck_h

// C++ standard headers
#include <iostream>
#include <sstream>
#include <stdexcept>

// Boost headers
#define BOOST_STACKTRACE_USE_BACKTRACE
#include <boost/stacktrace.hpp>

// CUDA headers
#include <hip/hip_runtime.h>

namespace cms {
  namespace hip {

/**
 * Brief description: Aborts program execution due to a CUDA error.
 *
 * Detailed description: This function generates an error message including 
 * the filename, line number, CUDA command, error message, and optional description.
 * It also provides the current stack trace before throwing a runtime error exception.
 *
 * Parameters:
 *   file - The filename where the error occurred
 *   line - The line number in the file where the error occurred
 *   cmd - The CUDA command that caused the error
 *   error - The error message returned by CUDA
 *   message - A custom error message
 *   description - An optional detailed description of the error
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    [[noreturn]] inline void abortOnCudaError(const char* file,
                                              int line,
                                              const char* cmd,
                                              const char* error,
                                              const char* message,
                                              const char* description = nullptr) {
      std::ostringstream out;
      out << "\n";
      out << file << ", line " << line << ":\n";
      out << "cudaCheck(" << cmd << ");\n";
      out << error << ": " << message << "\n";
      if (description)
        out << description << "\n";

      out << "\nCurrent stack trace:\n";
      out << boost::stacktrace::stacktrace();
      out << "\n";

      throw std::runtime_error(out.str());
    }

/**
 * Checks the result of a HIP operation and aborts with an error message if it fails.
 *
 * @param file The source file where the check is performed
 * @param line The line number in the source file where the check is performed
 * @param cmd The command that was executed
 * @param result The result of the HIP operation
 * @param description An optional description of the error
 * @return True if the result is hipSuccess, false otherwise
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    inline bool cudaCheck_(
        const char* file, int line, const char* cmd, hipError_t result, const char* description = nullptr) {
      if (result == hipSuccess)
        return true;

      const char* error = hipGetErrorName(result);
      const char* message = hipGetErrorString(result);
      abortOnCudaError(file, line, cmd, error, message, description);
      return false;
    }

  }  // namespace hip
}  // namespace cms

#define cudaCheck(ARG, ...) (cms::hip::cudaCheck_(__FILE__, __LINE__, #ARG, (ARG), ##__VA_ARGS__))

#endif  // HeterogeneousCore_CUDAUtilities_cudaCheck_h
