#ifndef HeterogenousCore_CUDAUtilities_currentDevice_h
#define HeterogenousCore_CUDAUtilities_currentDevice_h

#include "CUDACore/cudaCheck.h"

#include <hip/hip_runtime.h>

namespace cms {
  namespace hip {
/**
 * Returns the index of the current CUDA device
 *
 * @return The index of the current CUDA device
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    inline int currentDevice() {
      int dev;
      cudaCheck(hipGetDevice(&dev));
      return dev;
    }
  }  // namespace hip
}  // namespace cms

#endif
