#ifndef HeterogeneousCore_CUDAUtilities_interface_device_unique_ptr_h
#define HeterogeneousCore_CUDAUtilities_interface_device_unique_ptr_h

#include <functional>
#include <memory>

#include <hip/hip_runtime.h>

#include "CUDACore/allocate_device.h"
#include "CUDACore/currentDevice.h"

namespace cms {
  namespace hip {
    namespace device {
      namespace impl {
        // Additional layer of types to distinguish from host::unique_ptr
        class DeviceDeleter {
        public:
          DeviceDeleter() = default;  // for edm::Wrapper
          DeviceDeleter(int device, hipStream_t stream) : device_{device}, stream_{stream} {}

/**
 * @brief Functor for freeing device memory
 *
 * This functor is used to free device memory allocated on a specific device
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
          void operator()(void *ptr) {
            if (device_ >= 0) {
              free_device(device_, ptr, stream_);
            }
          }

        private:
          int device_ = -1;
          hipStream_t stream_ = hipStreamDefault;
        };
      }  // namespace impl

      template <typename T>
      using unique_ptr = std::unique_ptr<T, impl::DeviceDeleter>;

      namespace impl {
        template <typename T>
        struct make_device_unique_selector {
          using non_array = cms::hip::device::unique_ptr<T>;
        };
        template <typename T>
        struct make_device_unique_selector<T[]> {
          using unbounded_array = cms::hip::device::unique_ptr<T[]>;
        };
        template <typename T, size_t N>
        struct make_device_unique_selector<T[N]> {
          struct bounded_array {};
        };
      }  // namespace impl
    }    // namespace device

    template <typename T>
/**
 * @brief Creates a unique device selector for a given type T.
 *
 * This function allocates memory on the device and constructs an object of type T.
 * It returns a unique selector that manages the lifetime of the allocated memory.
 *
 * @tparam T The type of the object to be constructed on the device.
 * @param stream The HIP stream used for allocation and deallocation.
 * @return A unique device selector managing the lifetime of the allocated memory.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    typename device::impl::make_device_unique_selector<T>::non_array make_device_unique(hipStream_t stream) {
      static_assert(std::is_trivially_constructible<T>::value,
                    "Allocating with non-trivial constructor on the device memory is not supported");
      int dev = currentDevice();
      void *mem = allocate_device(dev, sizeof(T), stream);
      return typename device::impl::make_device_unique_selector<T>::non_array{reinterpret_cast<T *>(mem),
                                                                              device::impl::DeviceDeleter{dev, stream}};
    }

    template <typename T>
/**
 * @brief Creates an unbounded array of unique pointers to device memory.
 *
 * @tparam T Type of elements in the array.
 * @param n Size of the array.
 * @param stream HIP stream used for allocation.
 * @return Unbounded array of unique pointers to device memory.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    typename device::impl::make_device_unique_selector<T>::unbounded_array make_device_unique(size_t n,
                                                                                              hipStream_t stream) {
      using element_type = typename std::remove_extent<T>::type;
      static_assert(std::is_trivially_constructible<element_type>::value,
                    "Allocating with non-trivial constructor on the device memory is not supported");
      int dev = currentDevice();
      void *mem = allocate_device(dev, n * sizeof(element_type), stream);
      return typename device::impl::make_device_unique_selector<T>::unbounded_array{
          reinterpret_cast<element_type *>(mem), device::impl::DeviceDeleter{dev, stream}};
    }

    template <typename T, typename... Args>
    typename device::impl::make_device_unique_selector<T>::bounded_array make_device_unique(Args &&...) = delete;

    // No check for the trivial constructor, make it clear in the interface
    template <typename T>
/**
 * @brief Creates a unique selector for a device object
 *
 * @tparam T Type of the device object
 * @param stream HIP stream handle
 * @return A non-array device unique selector
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    typename device::impl::make_device_unique_selector<T>::non_array make_device_unique_uninitialized(
        hipStream_t stream) {
      int dev = currentDevice();
      void *mem = allocate_device(dev, sizeof(T), stream);
      return typename device::impl::make_device_unique_selector<T>::non_array{reinterpret_cast<T *>(mem),
                                                                              device::impl::DeviceDeleter{dev, stream}};
    }

    template <typename T>
/**
 * @brief Creates an unbounded array of uninitialized elements on a device.
 *
 * @tparam T Type of elements in the array.
 * @param n Number of elements in the array.
 * @param stream HIP stream associated with the allocation.
 * @return An unbounded array of uninitialized elements on a device.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
    typename device::impl::make_device_unique_selector<T>::unbounded_array make_device_unique_uninitialized(
        size_t n, hipStream_t stream) {
      using element_type = typename std::remove_extent<T>::type;
      int dev = currentDevice();
      void *mem = allocate_device(dev, n * sizeof(element_type), stream);
      return typename device::impl::make_device_unique_selector<T>::unbounded_array{
          reinterpret_cast<element_type *>(mem), device::impl::DeviceDeleter{dev, stream}};
    }

    template <typename T, typename... Args>
    typename device::impl::make_device_unique_selector<T>::bounded_array make_device_unique_uninitialized(Args &&...) =
        delete;
  }  // namespace hip
}  // namespace cms

#endif
