#ifndef HeterogeneousCore_CUDAUtilities_interface_host_unique_ptr_h
#define HeterogeneousCore_CUDAUtilities_interface_host_unique_ptr_h

#include <memory>
#include <functional>

#include "CUDACore/allocate_host.h"

namespace cms {
  namespace hip {
    namespace host {
      namespace impl {
        // Additional layer of types to distinguish from host::unique_ptr
        class HostDeleter {
        public:
          void operator()(void *ptr) { cms::hip::free_host(ptr); }
        };
      }  // namespace impl

      template <typename T>
      using unique_ptr = std::unique_ptr<T, impl::HostDeleter>;

      namespace impl {
        template <typename T>
        struct make_host_unique_selector {
          using non_array = cms::hip::host::unique_ptr<T>;
        };
        template <typename T>
        struct make_host_unique_selector<T[]> {
          using unbounded_array = cms::hip::host::unique_ptr<T[]>;
        };
        template <typename T, size_t N>
        struct make_host_unique_selector<T[N]> {
          struct bounded_array {};
        };
      }  // namespace impl
    }    // namespace host

    // Allocate pinned host memory
    template <typename T>
/**
 * @brief Creates a unique selector for host memory allocation
 *
 * This function allocates memory on the host and returns a unique selector
 * for accessing the allocated memory. It checks if the type T is trivially
 * constructible to ensure compatibility with pinned host memory allocation.
 *
 * @tparam T Type of the object being allocated
 * @param stream Hip stream used for memory allocation
 * @return Unique selector for the allocated host memory
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    typename host::impl::make_host_unique_selector<T>::non_array make_host_unique(hipStream_t stream) {
      static_assert(std::is_trivially_constructible<T>::value,
                    "Allocating with non-trivial constructor on the pinned host memory is not supported");
      void *mem = allocate_host(sizeof(T), stream);
      return typename host::impl::make_host_unique_selector<T>::non_array{reinterpret_cast<T *>(mem)};
    }

    template <typename T>
/**
 * Allocates an unbounded array of trivially constructible elements on the pinned host memory.
 *
 * @param n The number of elements to allocate.
 * @param stream The HIP stream associated with the allocation.
 *
 * @return An unbounded array of allocated elements.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    typename host::impl::make_host_unique_selector<T>::unbounded_array make_host_unique(size_t n, hipStream_t stream) {
      using element_type = typename std::remove_extent<T>::type;
      static_assert(std::is_trivially_constructible<element_type>::value,
                    "Allocating with non-trivial constructor on the pinned host memory is not supported");
      void *mem = allocate_host(n * sizeof(element_type), stream);
      return typename host::impl::make_host_unique_selector<T>::unbounded_array{reinterpret_cast<element_type *>(mem)};
    }

    template <typename T, typename... Args>
    typename host::impl::make_host_unique_selector<T>::bounded_array make_host_unique(Args &&...) = delete;

    // No check for the trivial constructor, make it clear in the interface
    template <typename T>
/**
 * @brief Creates a unique selector for a non-array type on the host
 * @tparam T Type of the object being selected
 * @param stream Hip stream used for allocation
 * @return Unique selector for the allocated object
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    typename host::impl::make_host_unique_selector<T>::non_array make_host_unique_uninitialized(hipStream_t stream) {
      void *mem = allocate_host(sizeof(T), stream);
      return typename host::impl::make_host_unique_selector<T>::non_array{reinterpret_cast<T *>(mem)};
    }

    template <typename T>
/**
 * @brief Creates an unbounded array of unique elements on the host.
 *
 * @tparam T Type of elements in the array.
 * @param n Number of elements in the array.
 * @param stream Hip stream used for memory allocation.
 * @return Unbounded array of unique elements on the host.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    typename host::impl::make_host_unique_selector<T>::unbounded_array make_host_unique_uninitialized(
        size_t n, hipStream_t stream) {
      using element_type = typename std::remove_extent<T>::type;
      void *mem = allocate_host(n * sizeof(element_type), stream);
      return typename host::impl::make_host_unique_selector<T>::unbounded_array{reinterpret_cast<element_type *>(mem)};
    }

    template <typename T, typename... Args>
    typename host::impl::make_host_unique_selector<T>::bounded_array make_host_unique_uninitialized(Args &&...) = delete;
  }  // namespace hip
}  // namespace cms

#endif
